- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/collection_job_driver.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/problem_details.rs
- aggregator/src/binary_utils/job_driver.rs
- aggregator/src/metrics.rs
- aggregator_core/src/datastore.rs
This backports #1788 to the 0.5 branch.
> Metrics name/unit fixes, 0.5 backport

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/collection_job_driver.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/problem_details.rs
- aggregator/src/binary_utils/job_driver.rs
- aggregator/src/metrics.rs
- aggregator_core/src/datastore.rs
This backports #1788 to the subscriber-01 branch.
> Metrics name/unit fixes, subscriber-01

- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/collection_job_tests.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/taskprov_tests.rs
Follow up to https://github.com/divviup/janus/pull/1765#discussion_r1300693529.
Also noticed some places where we could use `assert_headers!` instead of manually checking headers.
> More aggregator test cleanup 

- collector/src/lib.rs
- integration_tests/tests/common/mod.rs
This refactors `janus_collector::CollectionJob` to store a collection job ID instead of a collection job URL. Since draft-ietf-ppm-dap-04, it is no longer necessary to store an entire URL, so this cuts out some redundant data. We can also remove a test-util function for collecting while rewriting URLs -- all URLs are constructed from the leader endpoint base URL in the collector's parameters, so this is no longer necessary. This cleanup is related to #1796.
> janus_collector: Store collection job ID instead of URL

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/collection_job_tests.rs
- aggregator/src/aggregator/query_type.rs
- aggregator_core/src/datastore/models.rs
- db/00000000000001_initial_schema.down.sql
- db/00000000000001_initial_schema.up.sql
Before, the Leader would account for `max_batch_query_count` over all requests, so multiple identical requests would count as multiple queries.
If this is acceptable for Janus, we should consider a change to DAP to clarify that `max_batch_query_count` is accounted for by distinct aggregation parameters; currently, the text is ambiguous and permits both the preexisting behavior & the behavior in this PR.
Likely obviates the need for #1655. Inspired by & hopefully simplifies #1796.
> Account max_batch_query_count against distinct requests.

- db/00000000000001_initial_schema.up.sql
This also adds an index over collection job ID, which will make `get_collection_job` more efficient (i.e. an index lookup rather than a table scan).
Closes #1798.
> Require collection job IDs to be unique.

- .github/workflows/ci-migrations.yml
Allows the ci-migrations check to be overridden by the label `allow-changed-migrations`. Note that it the job will still check the validity of migrations, but it will ignore if there were changes to existing migrations.
Using this label asserts that we know what we're doing and that changing an existing migration is actually safe, and signals to reviewers to scrutinize the safety of the operation.
For the best experience, you should open a PR with this label already applied. If you retroactively apply this label, you'll need to make another push to the repository, because retrying a failed job submits the job with the same parameters as its original attempt.
Note that we will still have to use the `force` flag when deploying migrations to GCS.
> Allow skipping migrations validity check

- aggregator_core/src/datastore.rs
- db/00000000000016_trace_context.down.sql
- db/00000000000016_trace_context.up.sql
This adds `jsonb` database columns to aggregation jobs and collection jobs to propagate distributed tracing metadata through our job queue system. This is a backport of #1800, and part of #1628.
> Add database columns to jobs for W3C trace context, 0.5 backport

- db/00000000000001_initial_schema.up.sql
This adds `jsonb` database columns to aggregation jobs and collection jobs to propagate distributed tracing metadata through our job queue system. This is part of #1628.
> Add database columns to jobs for W3C trace context

- collector/src/lib.rs
- integration_tests/tests/common/mod.rs
This re-applies #1797, which was partially rolled back by #1805, likely due to conflict resolution issues.
> janus_collector: Store collection job ID, not URL

- aggregator/src/bin/janus_cli.rs
- aggregator/src/binary_utils.rs
- aggregator/src/metrics.rs
This implements #1842, moving build-time version information from a custom `janus_build_info` gauge into `target_info`, which is produced by the `opentelemetry-prometheus` exporter. I tried to follow the spirit of the semantic conventions for resource attributes, relating to [`service.version`](https://opentelemetry.io/docs/specs/otel/resource/semantic_conventions/#service-experimental) and [`process.runtime.name` and `process.runtime.version`](https://opentelemetry.io/docs/specs/otel/resource/semantic_conventions/process/#process-runtimes).
Note that there's only one `service.version` attribute defined, while we previously recorded both a semantic version and a git hash separately. The conventions for [version attributes](https://opentelemetry.io/docs/specs/otel/resource/semantic_conventi …
> Move version information to OTel resource

- Cargo.lock
- core/Cargo.toml
- core/src/hpke.rs
- messages/src/lib.rs
- tools/Cargo.toml
- tools/src/bin/collect.rs
- tools/tests/cmd/collect.trycmd
Adds a new option to `collect` so that an HPKE keypair encoded in JSON by `divviup hpke-config generate` may be used instead of providing the Base64URL unpadded private key plus the RFC 8446 encoding of the HPKE config.
Resolves #1810
> `collect` tool: accept HPKE keypair from `divviup`

- aggregator/src/bin/janus_cli.rs
- aggregator/src/binary_utils.rs
- aggregator/src/metrics.rs
This backports #1845, moving version information to a different, stickier Prometheus metric.
> Move version information to OTel resource, subscriber-01 backport

- .github/workflows/ci-build.yml
- Cargo.toml
- README.md
- aggregator/src/aggregator.rs
This backports #1848 to the subscriber-01 release branch, implementing the new MSRV policy in #1730.
> Update MSRV and document MSRV policy, subscriber-01 backport

- .github/workflows/ci-build.yml
- Cargo.toml
- README.md
- aggregator/src/aggregator.rs
This backports #1848 to the 0.5 release branch, implementing the new MSRV policy in #1730.
> Update MSRV and document MSRV policy, 0.5 backport

- aggregator_api/src/tests.rs
This backports #1729 to the release/0.5 branch, to fix up a test.
> Fix flaky test that occasionally collides on random(), 0.5 backport

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/collection_job_tests.rs
- aggregator/src/aggregator/query_type.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/models.rs
- db/00000000000018_nonunique_collection_jobs.down.sql
- db/00000000000018_nonunique_collection_jobs.up.sql
Before, the Leader would account for max_batch_query_count over all requests, so multiple identical requests would count as multiple queries.
> Account max_batch_query_count against distinct requests. [0.5 backport]

- Cargo.lock
- Cargo.toml
We don't imminently plan to release, but we don't want to suggest that the tip of `main` is equivalent to tag `0.5.14`.
> Bump crate versions to 0.6.0

- .github/dependabot.yml
This sets up several groups in our Dependabot configuration for related crates
> Set up Dependabot groups

- aggregator/src/bin/aggregator.rs
- docs/samples/advanced_config/aggregator.yaml
From discussion in https://isrg.slack.com/archives/C0167LT4C73/p1692908321449989, we noticed that providing both `listen_address` and `path_prefix` results in `listen_address` being prioritized, which is misleading. It should be an error to provide both fields.
The quick and easy solution to this is to add `#[serde(deny_unknown_fields)]` to the `AggregatorApi` enum. However, this results in an unfriendly error message: `data did not match any variant of untagged enum AggregatorApi`, which IMO is essentially meaningless to an operator without knowledge of Janus internals. Instead, we implement a custom deserializer that performs additional validation and lets us have a nicer error message.
> Add validation to enforce listen_address and path_prefix mutual exclusion

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/collection_job_driver.rs
- aggregator/src/aggregator/collection_job_tests.rs
- aggregator/src/aggregator/garbage_collector.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/models.rs
- aggregator_core/src/datastore/tests.rs
- db/00000000000001_initial_schema.up.sql
This allows current-batch requests to be reissued in fixed-size tasks, simplifying implementation of a Collector & avoiding the potential for loss of a collection job due to an inopportunely-timed task failure.
While I'm at it, I also update `get_collection_job` to take a task ID in addition to a collection job ID. This provides isolation between different tasks, which is especially imporant now that the Collector generates the collection job IDs -- otherwise, it would be trivial for Collectors to generate the same collection job ID for two tasks, which would cause some very strange behavior in Janus.
Resolves #1877. Part of #1860.
> Check collection job equivalence by query, not batch ID.

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/models.rs
- aggregator_core/src/datastore/tests.rs
- db/00000000000001_initial_schema.up.sql
This required a few updates to non-test code:
* The aggregation job creator used equality checks to determine if a given report aggregation was in state `START`. These are easily replaced by a call to `matches!`, which does not require `PartialEq + Eq`.
* Checking if a repeated aggregation job `PUT` matched the preexisting aggregation job checked if the report aggregations were equal. This is replaced by populating the last request hash for initialization requests (as well as continuation requests) and checking if the aggregation job is equal; since the aggregation job carries both the round number as well as the request hash, this should suffice to check that the requests are equal. As a bonus, we no longer need to read the preexisting report aggregations.
> Do not compare preparation states in non-test code.

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/collection_job_tests.rs
Following #1878, we now perform idempotency checks for creation of a collection job based on the query in the request, not what batch we resolve that query to at different times. However, due to the order of checks, we still required that the query be able to be resolved to a batch, even if we would later discard it and return an already-existing collection job with a different batch. This could lead to the following problem: (which I have captured in a new test) if a forgetful collector creates a collection job using the current-batch query, polls it once, and then tries creating it with the same ID again, the response it gets to the final request would depend on the state of other outstanding batches, and it could either get a 201 or a 400. This PR fixes that by reordering the code in …
> Check existing collection jobs before resolving query

- integration_tests/src/client.rs
- integration_tests/src/daphne.rs
- integration_tests/src/janus.rs
- integration_tests/tests/daphne.rs
- interop_binaries/src/lib.rs
- interop_binaries/tests/end_to_end.rs
Minor cleanup: use [`ContainerLogsDropGuard`](https://github.com/divviup/janus/blob/main/interop_binaries/src/lib.rs#L391) instead of these custom Drop impls. It's already used for the [client container](https://github.com/divviup/janus/blob/main/integration_tests/src/client.rs#L189), not sure why it's not used for the other containers.
> Use ContainerLogsDropGuard instead of custom Drop impls

- Cargo.lock
- collector/src/lib.rs
Same as https://github.com/divviup/janus/pull/1907, but with code changes to remove use of deprecated function `DateTime::from_utc`. Need peer review.
> build(deps): Bump chrono from 0.4.26 to 0.4.30 and remove use of deprecated function

- Cargo.lock
- collector/src/lib.rs
Backport https://github.com/divviup/janus/pull/1917.
> build(deps): Bump chrono from 0.4.26 to 0.4.30 and remove use of deprecated function (0.5 backport)

- Cargo.lock
- Cargo.toml
- aggregator/Cargo.toml
- aggregator/src/aggregator.rs
- aggregator/src/aggregator/accumulator.rs
- aggregator/src/aggregator/aggregate_init_tests.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/aggregation_job_writer.rs
- aggregator/src/aggregator/error.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/taskprov_tests.rs
- aggregator_api/Cargo.toml
- aggregator_core/Cargo.toml
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/models.rs
- aggregator_core/src/datastore/tests.rs
- collector/src/lib.rs
- core/Cargo.toml
- core/src/test_util/mod.rs
- db/00000000000001_initial_schema.up.sql
- integration_tests/Cargo.toml
- interop_binaries/Cargo.toml
- messages/Cargo.toml
- messages/src/lib.rs
- tools/Cargo.toml
This change implements the DAP-05 ping-pong topology in which aggregators take turns preprocessing prepare shares into prepare messages. While this topology first appeared in DAP-05, this implementation follows the changes in [1], which should appear in DAP-06.
This change depends on the implementation of the VDAF ping-pong topology added to crate `prio` in [2], which in turn conforms to the specification added after VDAF-06 and further tweaked in [3] (we expect this to be published soon as VDAF-07).
This commit makes some changes to what intermediate values are stored by aggregators. In the case where an aggregator is continuing, it will have computed a prepare state, a prepare message for the current round and a
prepare share for the next round. The existing implementation would store …
> DAP-05 ping-pong

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregate_init_tests.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/error.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/problem_details.rs
- aggregator/src/aggregator/taskprov_tests.rs
- client/src/lib.rs
- collector/src/lib.rs
- messages/src/lib.rs
- messages/src/problem_type.rs
DAP-05 changes a few error types.
- `unrecongizedMessage -> invalidMessage`
- `queryMismatch` is gone (now we use `invalidMessage` in that case)
- `roundMismatch -> stepMismatch`
We still use the word "round" in several places where "step" would be more appropriate given DAP-05 text. Renaming those variables, etc., will arrive in a later commit to avoid adding unnecessary noise here.
Part of #1669
> Adopt DAP-05 error types

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregate_init_tests.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/batch_creator.rs
- aggregator/src/aggregator/collection_job_driver.rs
- aggregator/src/aggregator/collection_job_tests.rs
- aggregator/src/aggregator/error.rs
- aggregator/src/aggregator/garbage_collector.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/taskprov_tests.rs
- aggregator_api/src/tests.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/models.rs
- aggregator_core/src/datastore/tests.rs
- core/src/test_util/mod.rs
- db/00000000000001_initial_schema.up.sql
- messages/src/lib.rs
When DAP-05 introduced the ping-pong topology, it also started talking about aggregation protocol "steps" instead of "rounds". This commit corrects the word usage across Janus to line up with the specification.
This change is pretty pedantic, but I think it's worth it for readers trying to resolve Janus against the DAP specification.
Relevant to #1669
> Replace "round" with "step"

- Cargo.lock
- Cargo.toml
This release is being cut for integration testing, but tagged as a pre-release because we anticipate making more disruptive changes (especially SQL schema changes) before deploying it anywhere.
The Janus maintainers DO NOT recommend deploying this version as it will be incompatible with eventual 0.6.x releases and no migration path will be provided.
> Release Janus `0.6.0-prerelease-1`

- aggregator_api/src/lib.rs
- aggregator_api/src/routes.rs
- aggregator_api/src/tests.rs
- aggregator_core/src/task.rs
- collector/src/lib.rs
- core/src/hpke.rs
- interop_binaries/src/lib.rs
- messages/src/lib.rs
- tools/src/bin/hpke_keygen.rs
Mainly targeting the ExtensionType, but I noticed other enums that could expand in the future in this crate are missing it.
Adding it to the HPKE types comes with unfortunate propagation of an error and unwraps. I'm open to whether this change is worth it. We could also alternatively have a panic here https://github.com/divviup/janus/pull/1957/files#diff-9c7b948f33912f9d1847860795daa701030c35ed114ba5d7e1fcd9674f234ba2R219.
> Add missing non_exhaustive to enums

- db/00000000000001_initial_schema.up.sql
I don't think this makes a real difference, because all the code paths that write auth tokens into the database should be setting the token type explicitly anyway, and we switched the default type in the aggregator API to `BEARER` a while ago. But this at least is consistent with the other token tables and will be less confusing to readers.
> Change default auth token type to `BEARER`

- .github/workflows/dependabot-automerge.yml
The important change is GITHUB_TOKEN -> GH_TOKEN. Despite the gh CLI allowing either, apparently in the context of Github Actions GITHUB_TOKEN is not allowed. (I couldn't find documentation to this effect, but the error I was receiving earlier suggested setting GH_TOKEN, and switching from GITHUB_TOKEN to GH_TOKEN does indeed cause the action to work as expected.)
> Fix dependabot automerge.

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/taskprov_tests.rs
Minor test cleanup.
Some bad formatting since rustfmt chokes on macros :sob:.
It's not necessary for us to tweak the global HPKE cache refresh interval in tests, since we manually `refresh()` them now.
> Fix bad formatting, remove unnecessary config

- aggregator_api/src/lib.rs
It's not necessary to compare in constant time here, because our implementation of AuthenticationToken has a [PartialEq implementation that works in constant time](https://github.com/divviup/janus/blob/main/core/src/task.rs#L745).
> Remove unnecessary constant time compare

- aggregator/src/aggregator/aggregate_init_tests.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/collection_job_driver.rs
- aggregator/src/aggregator/collection_job_tests.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/bin/janus_cli.rs
- aggregator_api/src/models.rs
- aggregator_api/src/routes.rs
- aggregator_api/src/tests.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/tests.rs
- aggregator_core/src/task.rs
- aggregator_core/src/taskprov.rs
- db/00000000000001_initial_schema.down.sql
- db/00000000000001_initial_schema.up.sql
- docs/samples/tasks.yaml
- integration_tests/tests/common/mod.rs
- interop_binaries/src/bin/janus_interop_aggregator.rs
- interop_binaries/src/lib.rs
We've decided that each task has exactly one aggregator and collector auth token, and rotating those means rotating the task. This commit updates the representations of auth tokens in the database and in memory (`aggregator_core::task::Task`) accordingly.
Several tests relied upon tasks constructed in tests having two aggregator auth tokens, one of each supported type. Those tests are fixed to explicitly construct tasks using `DAP-Auth-Token` tokens where necessary.
Given that there is now a single aggregator or collector auth token per task, we could remove the `task_aggregator_auth_tokens` and `task_collector_auth_tokens` tables and instead add columns `aggregator_auth_token`, `aggregator_auth_token_type`, `collector_auth_token` and `collector_auth_token_type` to `tasks`.
I chose not to …
> Tasks have only one aggregator, collector token

- Cargo.lock
- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/bin/janus_cli.rs
- aggregator_api/src/tests.rs
- aggregator_core/src/datastore/tests.rs
- aggregator_core/src/task.rs
- core/src/task.rs
- integration_tests/Cargo.toml
- integration_tests/src/client.rs
- integration_tests/tests/common/mod.rs
- integration_tests/tests/divviup_ts.rs
- integration_tests/tests/in_cluster.rs
- integration_tests/tests/janus.rs
- interop_binaries/src/bin/janus_interop_client.rs
- interop_binaries/src/bin/janus_interop_collector.rs
- interop_binaries/src/lib.rs
- interop_binaries/tests/end_to_end.rs
- messages/src/taskprov.rs
- tools/src/bin/collect.rs
This adds chunk_length parameters to `VdafInstance` and updates to the latest editor's copy of draft-wang-ppm-dap-taskprov. This will require some additional changes in divviup-api to handle aggregator API changes.
Closes #1900.
> Handle chunk_length VDAF parameter

- .github/actions/validate-migrations/action.yml
e.g. `00000000000001_taskprov_sub01.up.sql` should pass.
> Migration filenames containing numbers are valid

- core/src/task.rs
- tools/src/bin/collect.rs
This relaxes the requirements we place on authentication tokens. The last time we changed this, we required that all `DAP-Auth-Token` and `Authorization: Bearer` values were in unpadded base64url. This causes problems when using the interop test API outside of Janus's integration tests, because it's more restrictive than it used to be. In one case, I was using structured values for these, consisting of a word describing the token's role, a hyphen, and then some random hexadecimal bytes. This failed the base64url check in one case because it had an impossible length. (base64 cannot produce an output with length one more than a multiple of four, ignoring padding)
This PR places different, looser, validation requirements on each kind of authentication token. For `DAP-Auth-Token`, we require …
> Relax format restrictions on authentication tokens

- .github/dependabot.yml
This makes three changes to our Dependabot configuration:
- Ignore all updates to the library "postgres" container image. Putting this in the configuration will avoid some back-and-forth with each new release branch.
- Group all GHA reusable actions related to Docker together.
- Ignore all semver-minor updates to libprio-rs. Since these are often wire-breaking changes, these tend to be just noise. We can handle updates in other cases manually.
> Dependabot tweaks

- aggregator/src/aggregator.rs
- aggregator_core/src/task.rs
- core/src/auth_tokens.rs
When acting as an HTTP server, Janus only needs a hash of the aggregator authentication token to validate incoming requests, and can avoid storing the actual token. This commit adds
`janus_core::auth_tokens::AuthenticationTokenHash` which will be used to implement that.
Part of #1509
> Add `AuthenticationTokenHash`

- .github/dependabot.yml
This adds a Dependabot group covering deadpool and deadpool-postgres. The new version of deadpool-postgres is now released, so this should create PRs updating the two in tandem.
> Add Dependabot group for deadpool

- Cargo.lock
- core/Cargo.toml
- core/src/auth_tokens.rs
This implements the suggestion in https://github.com/divviup/janus/pull/1985/files#r1336411760.
> Use regex for bearer token validation

- interop_binaries/setup.sh
This waits for the Postgres database to come up before starting `janus_interop_aggregator` etc. This is for #1977. I tried this out locally, and saw the following on stdout from the `setup` job. (the first two lines are from `pg_isready`)
```
/var/run/postgresql:5432 - no response
/var/run/postgresql:5432 - accepting connections
janus_interop_aggregator: started
aggregation_job_creator: started
aggregation_job_driver: started
collection_job_driver: started
```
> Interop binaries: wait for database to be up

- interop_binaries/setup.sh
This backports #2006 to the release/0.5 branch.
> Interop binaries: wait for database to be up, 0.5 backport

- Cargo.lock
- Cargo.toml
This prepares us for cutting a new prerelease, in order to include full `chunk_length` support.
> Bump version to 0.6.0-prerelease-2

- integration_tests/src/client.rs
- integration_tests/src/daphne.rs
- integration_tests/src/janus.rs
- integration_tests/tests/common/mod.rs
- integration_tests/tests/daphne.rs
- integration_tests/tests/divviup_ts.rs
- integration_tests/tests/in_cluster.rs
- integration_tests/tests/janus.rs
- interop_binaries/config/supervisord.conf
- interop_binaries/src/lib.rs
- interop_binaries/tests/end_to_end.rs
Some improvements that came out of me debugging https://github.com/divviup/janus/issues/1977.
- Pass through the RUST_LOG environment variable to test containers, so we can directly control log level at the CLI. We still default to `info` logging level.
- Have each test deposit logs to a folder whose name is the test name, so that logs from a run that invoked multiple tests can be differentiated.
- Always output logs if JANUS_E2E_LOGS_PATH is set, in case we need help debugging a test that should fail, but doesn't.
> Integration/E2E test logging improvements 

- Dockerfile.interop_aggregator
This is a follow-up to #2011 to set the default `RUST_LOG` level in a Dockerfile environment variable. Docker allows environment variables declared in a container image to be overridden when creating a container, so the new code in #2011 will still be able to pass through `RUST_LOG` from integration test processes. This change just affects other use cases of the images (such as in the divviup-ts test suite), so that they still get a good default amount of logging.
> Set a default log level in Dockerfile.interop_aggregator

- aggregator_core/src/task.rs
We want to enable aggregators to only store authentication token hashes if they don't need the actual token (e.g., a helper only receives aggregation sub-protocol messages). With the existing `janus_aggregator_core::task::Task` structure, this is awkward, because that struct was used both as a view into all of a task's parameters and secrets, useful for test code that orchestrates the provisioning and execution of a task, as well as a specific DAP participant's view of the task, which is useful in Janus itself.
To resolve that tension, this commit introduces distinct structures for those distinct views. `janus_aggregator_core::task::test_util::Task` contains all of a task's parameters and secrets, regardless of any protocol role. `janus_aggregatore_core::task::test_util::NewTaskBuilder` …
> Task rewrite: introduce new task types

- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/taskprov_tests.rs
- aggregator/src/bin/janus_cli.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/tests.rs
- aggregator_core/src/task.rs
- db/00000000000001_initial_schema.up.sql
Adopts `janus_aggregator_core::task::test_util::NewTaskBuilder` and `janus_aggregator_core::task::AggregatorTask` in the `janus_aggregator_core::datastore` module. Much as the previous change provides two kinds of `Task` structure, we now provide two sets of methods for reading and writing tasks: one that deals in the new `AggregatorTask` and the other which deals in the old `Task`.
We add routines for converting between `task::Task` and `task::AggregatorTask` to make it easier for these two paths through the datastore to co-exist. This conversion is lossy because `AggregatorTask` only retains one of the aggregator endpoints, but this doesn't cause substantial problems in Janus, and we can live it transitionally.
Part of #1524
> Task rewrite: adopt `AggregatorTask` in datastore

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/accumulator.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/aggregation_job_writer.rs
- aggregator/src/aggregator/collection_job_driver.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/query_type.rs
- aggregator_core/src/datastore/tests.rs
- aggregator_core/src/query_type.rs
Adopts `janus_aggregator_core::task::AggregatorTask` in the `janus_aggregator_core::query_type` and `janus_aggregator::query_type` modules, making use of the routines for converting between `janus_aggregator_core::Task` and
`janus_aggregator_core::AggregatorTask` to make this minimally intrusive.
Part of #1524
> Task rewrite: use `AggregatorTask` in `query_type`

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/taskprov_tests.rs
- aggregator_core/src/taskprov.rs
Adopts `janus_aggregator_core::task::AggregatorTask` in the `taskprov` module and code that uses it in `janus_aggregator`.
Of particular interest is that we do away with
`janus_aggregator_core::taskprov::Task` and instead represent taskprov tasks as a `janus_aggregator_core::task::Task` with `AggregatorTaskParameters::TaskProvHelper`. Hopefully we'll be able to further unify handling of taskprov and regular tasks in the future.
Part of #1524
> Task rewrite: adopt `AggregatorTask` in taskprov

- aggregator_api/src/models.rs
- aggregator_api/src/routes.rs
- aggregator_api/src/tests.rs
Adopt `janus_aggregator_core::task::AggregatorTask` throughout `janus_aggregator_api`. Gratifyingly, this removes some hacks that resolved impedance mismatches between the `PostTaskReq` and `janus_aggregator_core::task::Task`, which are no longer needed because `AggregatorTask` only has the peer aggregator's endpoint in it.
Part of #1524
> Task rewrite: Aggregator API

- aggregator/src/aggregator/aggregate_init_tests.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/collection_job_tests.rs
- aggregator/src/aggregator/http_handlers.rs
Adopts `NewTaskBuilder` and `AggregatorTask` across portions of the test utilities and tests in the `janus_aggregator` module.
Part of #1524
> Task rewrite: `TaskBuilder` in `aggregator` pt. 1

- Cargo.lock
- client/Cargo.toml
- client/src/lib.rs
- core/src/hpke.rs
- integration_tests/src/client.rs
- integration_tests/tests/in_cluster.rs
- interop_binaries/src/bin/janus_interop_client.rs
- messages/src/lib.rs
This closes #857. The message enums for algorithm IDs are expanded to include catch-all variants, so that we can parse an `HpkeConfigList` even if it contains unsupported or unrecognized algorithms. I added a function to `janus_core` that probes whether `hpke_dispatch` supports a given config's suite of algorithms. Then, I used that in `janus_client` to filter through the received `HpkeConfigList` and select a `HpkeConfig` with supported algorithms.
This includes some Rust-level breaking changes: The message enums now have a value carrying variant, so they can't be cast to a primitive anymore. The associated types `<HpkeKemId as TryFrom<u16>>::Error` etc. changed from `num_enum::TryFromPrimitiveError` to `std::convert::Infallible`. I removed a now-unused variant from …
> Gracefully handle unrecognized HPKE algorithms

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregate_share.rs
- aggregator/src/aggregator/collection_job_driver.rs
Adopts `AggregatorTask` and `NewTaskBuilder` across the helper's aggregate share handlers and the leader's collection job driver.
Part of #1524
> Task rewrite: aggregate shares

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/accumulator.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/aggregation_job_writer.rs
Adopts `AggregatorTask` and `NewTaskBuilder` across the aggregation job handling components.
Part of #1524
> Task rewrite: aggregation job handling

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/tests/graceful_shutdown.rs
Adopts `AggregatorTask` and `NewTaskBuilder` across remainder of test and non-test portions of `janus_aggregator::aggregator`, and the graceful shutdown test.
Part of #1524
> Task rewrite: remainder of `aggregator` module

- aggregator/src/bin/janus_cli.rs
- aggregator_core/src/task.rs
- docs/samples/tasks.yaml
Adopts `AggregatorTask` in `janus_cli`. There's a functional change here: the YAML task accepted by `janus_cli` is now an `AggregatorTask` (via `SerializedAggregatorTask`), containing an aggregator's specific view of a task, meaning it contains just the peer aggregator's endpoint URL. In the near future, there will be more changes to the task YAML format so that for instance leader tasks only get the collector auth token _hash_ and helper tasks only get the aggregator auth token _hash_.
Part of #1524
> Task rewrite: `janus_cli`

- integration_tests/src/daphne.rs
- integration_tests/src/interop_api.rs
- integration_tests/src/janus.rs
- integration_tests/src/lib.rs
- integration_tests/tests/common/mod.rs
- integration_tests/tests/daphne.rs
- integration_tests/tests/divviup_ts.rs
- integration_tests/tests/in_cluster.rs
- integration_tests/tests/janus.rs
- interop_binaries/Cargo.toml
- interop_binaries/src/bin/janus_interop_aggregator.rs
- interop_binaries/src/lib.rs
Adopts `AggregatorTask`, `test_util::Task` and `NewTaskBuilder` across the integration test and interop binaries modules.
Part of #1524
> Task rewrite: integration tests

- Cargo.lock
- Cargo.toml
- aggregator/Cargo.toml
- aggregator/src/aggregator.rs
- aggregator/src/bin/janus_cli.rs
- aggregator_api/Cargo.toml
- aggregator_api/src/models.rs
- aggregator_api/src/routes.rs
- aggregator_api/src/tests.rs
- aggregator_core/Cargo.toml
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/models.rs
- aggregator_core/src/task.rs
- client/Cargo.toml
- collector/Cargo.toml
- db/00000000000001_initial_schema.up.sql
- docs/samples/tasks.yaml
- interop_binaries/src/bin/janus_interop_aggregator.rs
- messages/Cargo.toml
- tools/Cargo.toml
When acting as the helper, Janus only needs the aggregator auth token hash to validate requests. It never makes aggregation sub-protocol requests and thus doesn't need the actual token.
In this commit we change the schema of the `tasks` table so that helpers may store an auth token hash instead of an auth token. These changes are reflected in `janus_aggregator_core::task::AggregatorTask`. Finally we make changes to the aggregator API to accommodate this: the helper reports the aggregator auth token it generates during task provisioning, but doesn't store that token and cannot subsequently provide it when responding to `GET /tasks/:task_id` requests. Fortunately that field in `TaskResp` was already optional, and divviup-api already ignored it except in the creation case.
Part of #1509, …
> Only store aggregator auth token hash in helper

- client/src/lib.rs
- integration_tests/src/client.rs
- interop_binaries/src/bin/janus_interop_client.rs
This hides the `ClientParameters` struct from the public API, and introduces a new builder for clients. This removes an artificial separation between a task's VDAF and all other task parameters, allows omission of a reqwest client when the default one works, and allows automatically fetching HPKE configs when using the simpler constructors.
> Add builder API for clients

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/collection_job_tests.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/taskprov_tests.rs
- collector/src/lib.rs
- core/src/hpke.rs
- integration_tests/tests/common/mod.rs
- interop_binaries/src/bin/janus_interop_collector.rs
- tools/src/bin/collect.rs
This changes `janus_core::hpke::open()` and `janus_collector::CollectorParameters::new()` to take a single `HpkeKeypair` instead of separate `HpkeConfig` and `HpkePrivateKey` arguments. This addresses part of #230.
> Use HpkeKeypair instead of config and private key

- aggregator/src/bin/janus_cli.rs
- aggregator_api/src/models.rs
- aggregator_api/src/routes.rs
- aggregator_api/src/tests.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/tests.rs
- aggregator_core/src/task.rs
- db/00000000000001_initial_schema.up.sql
- docs/samples/tasks.yaml
- interop_binaries/src/bin/janus_interop_aggregator.rs
The leader only needs the hash of the collector auth token in order to authenticate collection sub-protocol requests and thus we can avoid the risk of storing the unhashed token.
This commit changes the `tasks` table to store a hash instead of the token, and makes the corresponding change to
`janus_aggregator_core::task::AggregatorTask`. There are corresponding changes to the aggregator API: the leader must now be provided the collector auth token hash during task creation, and `TaskResp` now only contains a collector auth token hash.
Part of #1509, #1524
> only store collector auth token hash in leader

- aggregator_core/src/datastore.rs
Should have been bumped in https://github.com/divviup/janus/pull/1976.
Integration tests in janus-ops would have kept this from moving to a live system. Arguable whether a check for this should be made earlier in the CI/CD process, to prevent from cutting a faulty release.
> subscriber-01: Bump supported schema version

- Cargo.lock
- Cargo.toml
Making the next release early since .9 was faulty due to missing https://github.com/divviup/janus/pull/2075, and so that https://github.com/divviup/janus-ops/pull/1083 can have passing CI on a new version.
> Release Janus 0.5.12-subscriber-01.10

- aggregator_core/src/datastore.rs
- db/00000000000001_initial_schema.up.sql
This adds a task_id column to the report_aggregations table, adds it to the existing unique index over the table, and updates relevant queries to filter on it. This is intended to lay the groundwork for future partitioning (see #647), as this was the last table of per-task objects without a direct foreign key to the tasks table. While I haven't tested it, this may also help the performance of some of our more complex queries by improving the locality of index accesses when looking at multiple aggregation jobs in the same task, and giving the query planner another condition with good selectivity to move around.
> Add task_id column to report_aggregations

- aggregator/src/bin/janus_cli.rs
- aggregator/src/binary_utils.rs
- aggregator/tests/cmd/aggregation_job_creator.trycmd
- aggregator/tests/cmd/aggregation_job_driver.trycmd
- aggregator/tests/cmd/aggregator.trycmd
- aggregator/tests/graceful_shutdown.rs
Closes https://github.com/divviup/janus/issues/1997.
This eliminates all usage of non-URL_SAFE_NO_PAD in Janus :tada:
> Datastore keys should be unpadded url-safe base64

- Cargo.toml
- aggregator/src/aggregator/batch_creator.rs
- aggregator_api/src/routes.rs
This fixes two Clippy lints (`clippy::redundant_locals` and `clippy::incorrect_partial_ord_impl_on_ord_type`) and bumps the MSRV following our stable-plus-two-releases policy.
> Updates for Rust 1.73.0

- Cargo.lock
- Cargo.toml
- aggregator/Cargo.toml
- aggregator_core/Cargo.toml
- aggregator_core/src/datastore/test_util.rs
- core/Cargo.toml
- core/src/test_util/testcontainers.rs
- integration_tests/Cargo.toml
- integration_tests/src/daphne.rs
- interop_binaries/Cargo.toml
This updates to the just-released version 0.15.0 of testcontainers. This version removed all pre-defined container images to reduce maintenance burden, so I vendored the `Postgres` image into `janus_core` and simplified it.
> Update to testcontainers-rs 0.15

- Cargo.lock
- Cargo.toml
- aggregator/Cargo.toml
- aggregator_core/Cargo.toml
- aggregator_core/src/datastore/test_util.rs
- core/Cargo.toml
- core/src/test_util/testcontainers.rs
- integration_tests/Cargo.toml
- integration_tests/src/daphne.rs
- interop_binaries/Cargo.toml
> Update to testcontainers-rs 0.15, 0.5 backport

- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/test_util.rs
- aggregator_core/src/datastore/tests.rs
- db/00000000000001_initial_schema.up.sql
Adds rows `updated_by` and `created_at` to all database tables. `updated_by` is set to the transaction name passed to `Datastore::run_tx_with_name` and `created_at` is automatically set to the current time.
For those tables whose rows are mutable, we also add an `updated_at` column, whose value is the time at which the row was mutated.
These values aren't used for anything in Janus and so do not appear in any Janus data structure. They are intended to aid operators debugging or otherwise examining activity in Janus.
Resolves #1858
> database: record who modified rows and when

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregate_init_tests.rs
- aggregator/src/aggregator/taskprov_tests.rs
Calls to /aggregate subsequent to taskprov task provisioning would fail for the same task, because /aggregate was not using the right authorization tokens (that is, it was attempting to use non-existent authorization tokens and failing).
The first commit is just a refactoring PR to make the test implementation cleaner. The second commit is the operative one.
> Taskprov: fix authorization bug in aggregate init call

- collector/src/lib.rs
- core/src/test_util/dummy_vdaf.rs
- integration_tests/tests/common/mod.rs
- interop_binaries/src/bin/janus_interop_collector.rs
- tools/src/bin/collect.rs
This overhauls the public API of janus_collector. `CollectorParameters` is removed, and functionally replaced with the new `CollectorBuilder`. `CollectionJob` and `PollResult` are made public, along with methods for starting and polling a job. A new method is added to delete a job.
`CollectionJob` has a public constructor and `into_fields()` method, so that it can be serialized and reconstructed in stateful collectors, but I chose not to define serde implementations (or `prio::codec` implementations) in this PR, since the struct has two generic parameters, mixing VDAF-level and DAP-level concepts. Implementing serialization in an opinionated way may require additional trait bounds. The constructor and access to fields at least makes it possible for applications to do their own …
> Collector API redesign

- db/00000000000001_initial_schema.up.sql
This updates the `aggregation_jobs` & `collection_jobs` tables; previously, only the direct ID (`aggregation_job_id` or `collection_job_id`) was treated as the effective primary key. For both tables, this will allow an indexed lookup where previously a scan was required (in `get_aggregation_job`/`get_collection_job`, respectively).
Closes #1550.
> Include `task_id` in effective primary keys for all tables.

- tools/tests/cmd/collect_fpvec_bounded_l2.trycmd
It seems that the `collect.trycmd` file was updated, while the `collect_fpvec_bounded_l2.trycmd` file was not. The result was that the relevant test didn't pass when running `cargo test --features fpvec_bounded_l2`. This commit fixes it.
> Fix cli test for `fpvec_bounded_l2` feature flag.

- aggregator/src/aggregator/garbage_collector.rs
This sets transaction names in the two database transactions used by the garbage collector. Previously they were showing up under "default" in metrics.
> Set transaction names in garbage collector

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/collection_job_driver.rs
- aggregator/src/aggregator/collection_job_tests.rs
- aggregator/src/aggregator/garbage_collector.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/report_writer.rs
- aggregator/src/aggregator/taskprov_tests.rs
- aggregator/src/bin/janus_cli.rs
- aggregator/src/cache.rs
- aggregator_api/src/routes.rs
- aggregator_api/src/tests.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/tests.rs
- interop_binaries/src/bin/janus_interop_aggregator.rs
From remark in https://github.com/divviup/janus/pull/2079#pullrequestreview-1660025763, and related to https://github.com/divviup/janus/pull/2113.
Move `run_tx_with_name -> run_tx` and move `(old) run_tx -> run_unnamed_tx` and lock it behind `test-util`.
> Ensure all production code provides transaction names

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregate_init_tests.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/taskprov_tests.rs
- core/src/lib.rs
- integration_tests/tests/divviup_ts.rs
- integration_tests/tests/in_cluster.rs
- integration_tests/tests/janus.rs
- interop_binaries/tests/end_to_end.rs
- messages/src/lib.rs
Adopts draft-wang-ppm-dap-taskprov-02 for the subscriber-01 branch.
The primary difference between this revision and the latest is that the taskprov configuration is expressed in the extension field of each report share. A helper must parse the extension in each AggregateInitRequest and use it to provision the task.
The implementation of this is unclean. Due to how AggregateInitRequest is structured, we need to know the query type ahead of time. We can't decode it unless we know the query type, but we won't know the query type until we decode it. To work around this, decode by trial.
To simplify implementation I made all helper requests use the main aggregator auth token established in https://github.com/divviup/janus/pull/1976. Leader requests are unmodified, but are effectively …
> subscriber-01: Implement draft-wang-ppm-dap-taskprov-02

- aggregator/Cargo.toml
- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregate_share.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/collection_job_driver.rs
- aggregator/src/aggregator/error.rs
- aggregator/src/aggregator/http_handlers.rs
- core/Cargo.toml
- core/src/dp.rs
- core/src/lib.rs
- core/src/test_util/dummy_vdaf.rs
- core/src/vdaf.rs
- interop_binaries/src/bin/janus_interop_client.rs
- interop_binaries/src/bin/janus_interop_collector.rs
- interop_binaries/src/lib.rs
- interop_binaries/tests/end_to_end.rs
We have integrated differential privacy into janus as proposed here #1865.
Highlights:
- The differential privacy strategy for a vdaf is carried directly in its enum variant in `VdafInstance` and `VdafOps`. This means that every vdaf is responsible to carry the data required for each of its supported strategies. No changes to database schema or task definition are required. For already existing types which do not need differential privacy the change is conservative - no updates to the enum variant have to occur. For a vdaf which supports multiple strategies, a dedicated enum containing *only* the supported dp strategies has to be created. An example for our type is [here](https://github.com/divviup/janus/blob/c22282e4777c01841350627662f3d51b2e62b050/core/src/task.rs#L25-L37).
- We updated …
> Differential privacy in janus

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregate_share.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/collection_job_driver.rs
- core/src/vdaf.rs
- interop_binaries/src/bin/janus_interop_client.rs
- interop_binaries/src/bin/janus_interop_collector.rs
- interop_binaries/tests/end_to_end.rs
- tools/src/bin/collect.rs
This cleans up a couple items as a follow-up to #1892. First, we close #1658 by removing the 64-bit variant of Prio3FixedPointBoundedL2VecSum. Due to length constraints, this could only be used on vectors with maximum dimension of three. Lower-precision variants will be more practically useful. Second, I removed the DP strategy generic type parameter from `compute_aggregate_share()`, and relaxed the bound on the VDAF type parameter from `AggregatorWithNoise` to `Aggregator`. This simplifies callsites and gets rid of some extra monomorphizations.
> Differential Privacy Cleanups

- core/src/test_util/kubernetes.rs
I noticed a couple CI failures where `kind create cluster` returned an error status code. This captures the output from those invocations, and displays it upon failure.
> Print output when `kind create cluster` fails

- aggregator/src/bin/janus_cli.rs
- aggregator/src/binaries/aggregation_job_creator.rs
- aggregator/src/binaries/aggregation_job_driver.rs
- aggregator/src/binaries/aggregator.rs
- aggregator/src/binaries/collection_job_driver.rs
- aggregator/src/binary_utils.rs
- integration_tests/src/client.rs
- integration_tests/src/janus.rs
- integration_tests/src/lib.rs
- integration_tests/tests/common/mod.rs
- integration_tests/tests/daphne.rs
- integration_tests/tests/divviup_ts.rs
- integration_tests/tests/janus.rs
This is part of #2081. This PR adds new integration tests that run both Janus aggregator instances in-process, relying on the existing ephemeral database support for Postgres. This also includes one test with an in-process Janus leader and a Daphne helper running in a container.
Note that the divviup-ts integration tests, or tests with Daphne as the leader, are not supported with in-process aggregators yet. That will require making connections from inside a container to TCP servers on the host, which may be doable using `host.docker.internal` on Windows/Mac and `--add-host` with `host-gateway` on Linux, FWIW.
> Add single process integration tests

- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/tests.rs
An infinite retry could be triggered if a report with the same ID as an expired report was submitted.
Supports https://github.com/divviup/janus/issues/2124.
I didn't add a separate method for `get_client_reports_including_expired_ones` because naming things is hard, and I think this is the only situation where we care about expired reports.
I altered the error message to provide more detail as to what's happening in this branch of code. The error here does matter because it is logged by `tracing`.
> Fix infinite retry bug

- Cargo.lock
- aggregator_api/src/routes.rs
- integration_tests/Cargo.toml
- integration_tests/tests/in_cluster.rs
The PRs related to https://github.com/divviup/divviup-api/issues/542 implement the new concept of "collector credential". This entails changes to the API for provisioning tasks via divviup-api that we use in e2e integration tests. In this commit we adopt the new `divviup-client` and fix up its usage.
Part of #2071
> adopt new `divviup-client`

- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/bin/janus_cli.rs
- aggregator/src/binary_utils.rs
- aggregator/src/trace.rs
- docs/DEPLOYING.md
- docs/samples/advanced_config/aggregation_job_creator.yaml
- docs/samples/advanced_config/aggregation_job_driver.yaml
- docs/samples/advanced_config/aggregator.yaml
- docs/samples/advanced_config/collection_job_driver.yaml
- docs/samples/basic_config/aggregation_job_creator.yaml
- docs/samples/basic_config/aggregation_job_driver.yaml
- docs/samples/basic_config/aggregator.yaml
- docs/samples/basic_config/collection_job_driver.yaml
Supports https://github.com/divviup/janus/issues/2124, and may be necessary for helping us debug issues without blowing up our cloud logging bill.
I chose to add this endpoint to the same `/healthz` handler we use for k8s status checks. I didn't think it fit on the aggregator API since we support deployments where the aggregator API is disabled, and the control plane will never be able to make full use of it since it only operates on a single replica of Janus.
> Add endpoint for configuring tracing filter at runtime

- aggregator/src/aggregator/aggregation_job_continue.rs
The time-interval check was correct. The fixed-size check was effectively a no-op since `aggregate_share_jobs.batch_interval` is not populated for fixed-size tasks. Instead, we replace it with a check that the relevant batch has not yet started collection by ID.
Closes #2174.
> Use correct batch-collected check for aggregation job continuation.

- .github/workflows/ci-build.yml
- .github/workflows/push-docker-images-release.yml
- Dockerfile.sqlx
- README.md
- docker-bake.hcl
- docs/DEPLOYING.md
Janus now builds and ships a container image that bundles `sqlx` and the current Janus version's SQL migration scripts. This makes it easier for deployments to apply SQL migrations, as they no longer need to build a `sqlx` image themselves and (more importantly) figure out how to provide the appropriate set of migration scripts to whatever is applying the migrations.
While updating the READMEs, I also fixed a few Markdown hyperlinks to make some long lines less long.
> Add `janus_db_migrator` container

- Cargo.lock
- Cargo.toml
- core/Cargo.toml
see:
* [trillium-http@0.3.4](https://github.com/trillium-rs/trillium/releases/tag/trillium-http-v0.3.4)
* [trillium@0.2.10](https://github.com/trillium-rs/trillium/releases/tag/trillium-v0.2.10)
* [trillium-server-common@0.4.5](https://github.com/trillium-rs/trillium/releases/tag/trillium-server-common-v0.4.5)
> upgrade trillium

- docker-bake.hcl
This is a follow-up to #2177 to tweak the docker buildx cache configuration. Currently, the layers aren't being cached, and sqlx is rebuilt (with the release profile) on each commit. This PR changes the `cache-from` lines to read from a different cache key (distinct from that used for Janus) and adds a `cache-to` line that writes back layers under that new cache key.
> Update cache configuration for sqlx container

- aggregator/src/binary_utils.rs
- docs/DEPLOYING.md
From brief discussion in https://github.com/divviup/divviup-api/pull/607#discussion_r1378180279, the trace config endpoint can be made simpler.
(From discussion in https://isrg.slack.com/archives/C0167LT4C73/p1698787638814279, the previous code is subtly wrong or otherwise cumbersome to properly use, because of how trillium intends to do content negotiation).
> Use simpler body for trace config endpoint

- tools/src/bin/collect.rs
- tools/tests/cmd/collect.trycmd
- tools/tests/cmd/collect_fpvec_bounded_l2.trycmd
Don't print the values of these variables when using `--help`, to avoid exposing secrets.
> collect: hide sensitive environment variable values

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/report_writer.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/models.rs
- aggregator_core/src/datastore/tests.rs
Specifically, we scrub report data once aggregation has been started, at the end of the first aggregation step. This will considerably reduce the amount of data we store, at the cost of additional writes to the datastore. We also change the semantics of report-upload idempotency; see below.
Implementing this required changing the semantics of report-upload idempotency. Specifically, we can no longer detect when an uploaded report matches an already-stored report if the already-stored report has been scrubbed, since the data required to perform this check has been deleted. The new semantics are to do idempotency-checking on (task_id, report_id) only; any task that sees a duplicate report ID will treat it as a duplicated upload & return OK. I think these semantics are acceptable: in real …
> Scrub report data once it is no longer required.

- client/src/lib.rs
In case, e.g., a client needs to be used inside a `move` closure.
> client: derive clone

- aggregator/src/binary_utils.rs
- docs/DEPLOYING.md
- docs/samples/advanced_config/aggregation_job_creator.yaml
- docs/samples/advanced_config/aggregation_job_driver.yaml
- docs/samples/advanced_config/aggregator.yaml
- docs/samples/advanced_config/collection_job_driver.yaml
- docs/samples/advanced_config/janus_cli.yaml
This closes #2226. #2179 introduced optional support for TLS in database connections. For database servers that don't support TLS, this resulted in no change to default behavior, but for database servers that do support TLS, our client would always try to use TLS, which fails without having a trust store. This PR fixes the default behavior without a trust store by conditionally using `tokio_postgres::NoTls` in that situation. This struct has a special implementation of a trait, with an override of a `#[doc(hidden)]` method that can't be overridden from third-party crates, that changes the client's default behavior to skip attempting TLS connections.
> Don't use rustls if no trust store is provided

- collector/src/lib.rs
- tools/src/bin/collect.rs
A few things happening here, I can break this up if we want to evaluate them separately.
The main goal is to choose exponential backoff parameters that are better suited to my impatience. IMO at the CLI, more polling aggressiveness is justified since the tool is more likely being used interactively. The previous parameters yielded backoff timings of:
```
>>> [15*(1.2**t) for t in range(100) if 15*(1.2**t) < 300]
[15.0, 18.0, 21.599999999999998, 25.919999999999995, 31.104, 37.32479999999999, 44.78975999999999, 53.747711999999986, 64.49725439999997, 77.39670527999998, 92.87604633599996, 111.45125560319995, 133.74150672383993, 160.4898080686079, 192.58776968232948, 231.10532361879538, 277.3263883425545]
```
The new parameters yield: 
```
>>> [3*(1.2**t) for t in range(100) if 3*(1.2**t) < …
```
> collect: improve polling feedback and timing; re-export ExponentialBackoff

- aggregator_core/src/datastore.rs
- integration_tests/tests/integration/common.rs
This was caused by the batch_aggregations soft-delete condition not respecting batches.batch_interval, which is used in time-interval tasks to allow coherent GC semantics even for batches including 0 reports (which time-interval must allow). This bug could specifically be triggered only if a collection request was made for a time interval including a minimal time interval with 0 reports, and then repeated. In that case, the empty batch aggregations would not be read due to the GC condition, which would then cause us to try writing them again, leading to a MutationTargetAlreadyExists error which would fail the collection job step until the collection job was abandoned.
This bug could only occur in time-interval: fixed-size tasks will always have more than 0 reports per batch.
I also …
> Fix repeated collection for time-interval.

- tools/src/bin/collect.rs
Closes #1861--incorporates all suggestions present.
Example output:
```
Batch: Z38FaJX_134j3alqLvuhWH7BkafhyGYNzQlQs2_CLYc
Number of reports: 100
Interval start: 2023-11-13 21:46:00 UTC
Interval end: 2023-11-13 21:47:00 UTC
Interval length: 60s
Aggregation result: 100
```
> collect: More user-friendly description of a collection's interval

- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/aggregation_job_writer.rs
- aggregator/src/aggregator/batch_creator.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/models.rs
- aggregator_core/src/datastore/tests.rs
We can only eagerly delete Leader aggregation jobs: Helper aggregation jobs need to stick around to allow the possibility of a replayed request.  (I think we could delete them too once an aggregate share request arrives, but I leave that for later improvement.)
I had to update a few other places that were reading this data:
* Report count per batch used report_aggregations. Now, it reads the number of reports that have successfully completed aggregation -- this is a stronger requirement than before, but I think it's more correct. Notably this is the same condition used to determine which batches can be selected for a current-batch request; I don't see a good reason to let folks collect a batch by ID that would not be selected for current-batch.
* Outstanding batch size used …
> Eagerly delete aggregation jobs.

- core/src/test_util/testcontainers.rs
This fixes a future compatibility warning with the 1.74 toolchain.
> Fix future compatibility warning

- aggregator_core/src/datastore.rs
I tried adding a shim around `tokio_postgres::Row` to see if any selected columns were going unused, and found two bigints and a TaskId. There were enough false positives due to early returns and other conditionals that this wouldn't be worth adding in a test, but we can at least make these cleanups now.
> Remove unused columns from SELECT

- aggregator/src/aggregator/garbage_collector.rs
- aggregator/src/binaries/aggregator.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/tests.rs
This adds a tracing span around the `gc_task()` method (which will be helpful in the event we see events fired from the datastore methods) and counter metrics that add up the total number of deleted rows from three of the tables.
> Garbage collector observability improvements

- .github/dependabot.yml
- Cargo.lock
- aggregator/Cargo.toml
- aggregator/src/binaries/aggregator.rs
- aggregator/src/binary_utils.rs
- aggregator/src/config.rs
- aggregator/src/metrics.rs
- aggregator/src/trace.rs
- aggregator/tests/cmd/aggregation_job_creator.trycmd
- aggregator/tests/cmd/aggregation_job_driver.trycmd
- aggregator/tests/cmd/aggregator.trycmd
- docs/CONFIGURING_METRICS.md
- docs/CONFIGURING_TRACING.md
This takes advantage of support in the latest version of `opentelemetry-otlp` for reading additional metadata/headers from [standard environment variables](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.25.0/specification/protocol/exporter.md#specifying-headers-via-environment-variables). Support for setting these is removed from our configuration files and from our command-line interface, and documentation is updated with an example of how to pass them in via the environment. This is mainly relevant when using Honeycomb.
> Remove direct configuration of OTLP gRPC metadata

- .github/workflows/ci-build.yml
This enables logging when running `cargo test`. This is particularly helpful for the in-process integration tests.
> Enable logging when running tests in CI

- aggregator_core/src/datastore.rs
- docs/DEVELOPMENT.md
This replaces most `try_get()` calls with `get()`, to follow our convention in this file. I left the ones of type `Json<T>` alone for now: in addition to mismatched column names and unsupported Postgres data types, those can also error/panic if the serde deserialization fails, which is a less clear signal of a source code-level mistake. We could leave them be, or do `row::get<_, serde_json::Value>("...")` and `serde_json::from_value(...).map_err(|e| Error::DbState(...))?`, at the expense of some allocations, in order to more tightly follow our conventions.
> Replace most Row::try_get() calls with Row::get()

- aggregator/Cargo.toml
This rolls back a change that was inadvertently included in #2239.
> Undo change to default features

- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/collection_job_driver.rs
- aggregator/src/binaries/aggregation_job_driver.rs
- aggregator/src/binaries/collection_job_driver.rs
- aggregator/src/binary_utils/job_driver.rs
- aggregator/src/config.rs
- aggregator/tests/integration/graceful_shutdown.rs
- docs/samples/advanced_config/aggregation_job_driver.yaml
- docs/samples/advanced_config/collection_job_driver.yaml
- docs/samples/basic_config/aggregation_job_driver.yaml
- docs/samples/basic_config/collection_job_driver.yaml
- integration_tests/src/janus.rs
- interop_binaries/config/aggregation_job_driver.yaml
- interop_binaries/config/collection_job_driver.yaml
Replaces the exponential backoff strategy used in job drivers with the fixed interval with random jitter strategy used by the job creator.
The configuration parameters min_job_discovery_delay_secs and max_job_discovery_delay_secs are deprecated and replaced with the parameter job_discovery_interval_secs. The configuration changes are backwards compatible--if job_discovery_interval_secs is not present we use the value max_job_discovery_delay_secs in its place.
Closes https://github.com/divviup/janus/issues/2252
> Do not use exponential backoff when acquiring jobs

- tools/src/bin/collect.rs
- tools/tests/cmd/collect.trycmd
- tools/tests/cmd/collect_fpvec_bounded_l2.trycmd
Stacked on #2302.
Allows specifying the `HPKE_CONFIG_JSON_CONTENTS` environment variable, which is the contents of the file generated by `divviup collector-credential generate`. Suitable for integration with systems that don't have neat support for files.
Also removes needless use of `Derivative`--all our structs already use `Derivative` to hide their sensitive contents.
> collect: allow specifying HPKE JSON config via environment variable

- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/collection_job_driver.rs
- aggregator/src/bin/aggregation_job_driver.rs
- aggregator/src/bin/collection_job_driver.rs
- aggregator/src/binary_utils/job_driver.rs
- aggregator/src/config.rs
- docs/samples/advanced_config/aggregation_job_driver.yaml
- docs/samples/advanced_config/collection_job_driver.yaml
- docs/samples/basic_config/aggregation_job_driver.yaml
- docs/samples/basic_config/collection_job_driver.yaml
- integration_tests/src/janus.rs
- interop_binaries/config/aggregation_job_driver.yaml
- interop_binaries/config/collection_job_driver.yaml
Backports #2253.
Largely backporting this so we can phase out the old configuration from our infrastructure repo.
> Do not use exponential backoff when acquiring jobs (#2253 release/0.5 backport)

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/error.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/problem_details.rs
- aggregator/src/aggregator/query_type.rs
From discussion in Slack and somewhat alluded to in https://github.com/divviup/janus/issues/2293.
Client upload errors are opaque at the moment. They don't provide much detail as to went wrong, and some classes of errors don't return errors at all. This makes troubleshooting a misconfigured client cumbersome.
First, introduce usage of the `detail` field in HTTP problem documents as defined in [RFC 7807](https://www.rfc-editor.org/rfc/rfc7807.html#page-5). 
The plumbing is relatively straightforward. `aggregator::Error`'s variants can contain an additional `Reason` enum which is provided to `ProblemDetailsConnExt::with_problem_details()`. This pattern will be useful for taskprov as well, where opt-out rationale is opaque because of the lack of a `detail` field.
Then, expose all errors …
> Add additional context to report upload rejection errors

- tools/src/bin/collect.rs
- tools/tests/cmd/collect.trycmd
- tools/tests/cmd/collect_fpvec_bounded_l2.trycmd
Stacked on https://github.com/divviup/janus/pull/2324. Uses the collector credential nomenclature.
Note that this collides slightly with https://github.com/divviup/janus/pull/2307, in that we change the environment variable name. Since this PR hasn't made it into a release yet, this is not a breaking change. This PR also addresses the confusing naming of `--hpke-config-json` vs `--hpke-config-json-contents`.
We support the alias `--hpke-config-json` as `--collector-credential-file` for backwards compatibility.
> collect: Use collector credential nomenclature

- Cargo.lock
- Cargo.toml
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/binaries/aggregator.rs
- aggregator_api/src/lib.rs
- aggregator_api/src/tests.rs
This PR upgrades trillium-opentelemetry and enlists the type system in making sure that it is using the correct MeterProvider, by passing a Meter directly. We currently are depending on two versions of opentelemetry transitively, which results in duplicate globals, and ultimately results in lost metrics. I also made use of the new `.with_error_type()` feature to use our error codes in labels on the built-in histogram metrics, in addition to our custom counter metric elsewhere.
> Fix global mismatch with trillium-opentelemetry

- Cargo.lock
- Cargo.toml
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/bin/aggregator.rs
- aggregator_api/src/lib.rs
- aggregator_api/src/tests.rs
> Fix global mismatch with trillium-opentelemetry, 0.5 backport

- .github/workflows/ci-build.yml
- Cargo.lock
- deny.toml
This sets up cargo-deny to prevent multiple dependencies on different versions of `tracing` or `opentelemetry`, either of which could lead to lost observability data.
Closes #2332.
> Add cargo-deny configuration, run in CI

- Cargo.lock
- integration_tests/Cargo.toml
- integration_tests/src/lib.rs
- integration_tests/tests/integration/in_cluster.rs
Adds tests to exercise Divvi Up's rate limiting to the existing `in_cluster` test module. The test setup reads in rate limit configuration from a file whose path is specified via environment variable, akin to the existing `JANUS_E2E_*` variables.
These tests don't actually exercise any part of Janus itself, but they rely on the test support for forwarding ports and otherwise working with a pair of Januses in a Kubernetes cluster, so this is a convenient place to define them.
> Integration test for rate limits

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator_core/src/lib.rs
Janus was emitting traces at `info` every time it successfully handled a request (which yields one log statement per successful upload) as well as for a variety of client errors (e.g., undecodable input share). Downgrade those to `debug` to keep a lid of logging and log storage costs.
> Downgrade some `tracing::info!` calls to `debug!`

- tools/src/bin/collect.rs
https://github.com/divviup/janus/pull/2330 broke providing the `--hpke-config` and `--hpke-private-key` flags.
```
thread 'main' panicked at tools/src/bin/collect.rs:463:18:
internal error: entered unreachable code: collector credential arguments are mutually exclusive
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This was due to a missing match arm handling the case where no `--collector-credential*` argument was provided.
This made it past unit testing since #2330 change some aspects of credential evaluation to be done after clap parsing. I have updated the unit tests to catch this case, and other possible cases.
> collect: fix crash when supplying --hpke-config and --hpke-private-key

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/accumulator.rs
- aggregator/src/aggregator/http_handlers.rs
- docs/DEVELOPMENT.md
Calls to the helper's `/aggregate` endpoint were not actually idempotent.
This is because we invoked `accumulator.flush_to_datastore(tx, &vdaf)`, before checking whether the request was replayed. This function makes changes, and we would `Ok` on replayed requests, causing the changes to be committed. 
The overall effect was repeated `/aggregate` requests would count again against the underlying batch aggregations. This would render the batch uncollectable, since the checksums between helper and leader wouldn't match.
This was particularly noticeable when the helper was under heavy load. If the upstream LB times out the request, the request isn't cancelled and the changes are committed. Since the leader sees `502 Bad Gateway`, it retries the request.
`flush_to_datastore()` was at that spot …
> Fix idempotency bug in `handle_aggregate_init_generic`

- aggregator/src/aggregator/accumulator.rs
- messages/src/lib.rs
A deadlock is possible in `Accumulator::flush_to_datastore()` because there is no deterministic order to shard updates. Fix this by sorting the batch aggregations by shard ID before calling `update_batch_aggregation()`.
The effect on the helper's `aggregate_init` is quite nice! Deadlocks turn out to be extremely costly.
I installed some metrics to categorize database retries by reason (i.e. serialization error or deadlock)[^1]. I then issued 31680 Prio3Count time interval reports at about 500 QPS. Here's the helper's retry metrics:
After this change:
Note there's still a few deadlocks in the aggregate_init's usage of `Transaction::update_batch()`, but the change has removed all deadlocks in `flush_to_datastore()`. I will investigate `update_batch()` in another PR.
The transaction duration …
> Fix deadlock in `Accumulator::flush_to_datastore()`

- Cargo.lock
- aggregator/Cargo.toml
- aggregator_core/Cargo.toml
`janus_aggregator` and `janus_aggregator_core` have been carrying around a dependency on `uuid` for a while, but neither crate actually uses them.
> Remove `uuid` dependency

- aggregator/src/metrics.rs
- aggregator_core/src/datastore.rs
This metric will help us identify transactions that excessively retry due to serialization errors or deadlock. Transactions that retry too much are candidates for optimization, e.g. by sharding or fixing the underlying deadlock.
Here's an example of how this looks:
```promql
label_replace(histogram_quantile(0.5, sum without(job, node, instance, service) (rate(janus_database_retries_bucket[10m]))), "quantile", "0.50", "", "") or label_replace(histogram_quantile(0.95, sum without(job, node, instance, service) (rate(janus_database_retries_bucket[10m]))), "quantile", "0.95", "", "") or label_replace(histogram_quantile(0.99, sum without(job, node, instance, service) (rate(janus_database_retries_bucket[10m]))), "quantile", "0.99", "", "")
```
> Metric for transaction retries

- .github/workflows/ci-build.yml
- integration_tests/src/client.rs
- integration_tests/tests/integration/divviup_ts.rs
divviup-ts long since has support for draft-ietf-ppm-dap-07. Update the referenced container image and turn that test back on (just in time for us to go do draft 9).
> Re-enable divviup-ts integration test

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/error.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/problem_details.rs
- messages/src/problem_type.rs
Fixes #248.
I opted not to embed an abandonment reason into the DB. There is no action that a user can take for this error except to contact the operators, so we're going to have to go log crawling anyway. The current cases that cause this also do not have straightforward fixes (why is the collection job retrying so many times? why is there a batch mismatch?). Thus I don't think it's worth the additional complexity.
~Note that this PR is insufficient to stop collectors from infinite looping, [because our retry logic in `core.rs` retries on all server errors](https://github.com/divviup/janus/blob/main/core/src/retries.rs#L89). I will address this in a future PR. I think we need to not retry on 500 errors, but also give a pass through `aggregator/src/aggregator/http_handlers.rs` to provide …
> Return server error for abandoned collection jobs

- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/taskprov_tests.rs
- collector/src/credential.rs
- core/src/hpke.rs
- core/src/test_util/kubernetes.rs
- integration_tests/tests/integration/in_cluster.rs
- tools/src/bin/collect.rs
This fixes some Clippy lints that surfaced with the latest Rust toolchain. Notably, this pointed out that `janus_collector::credential::PrivateCollectorCredential::hpke_keypair()` and `impl TryFrom<DivviUpHpkeConfig> for HpkeKeypair` have unnecessary error handling, ever since we made `janus_core::hpke::HpkeConfig` able to deserialize unsupported algorithms. (I didn't change the method's return value or the trait implemented since they are part of the public API)
> Fix Clippy lints

- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/taskprov_tests.rs
- client/src/lib.rs
- core/src/test_util/kubernetes.rs
This fixes Clippy lints that show up with the latest stable Rust toolchain. This was more straightforward than #2419 for 0.6.
> Fix Clippy lints, 0.5 branch

- Cargo.toml
- aggregator_core/src/datastore/test_util.rs
- core/src/test_util/testcontainers.rs
This bumps `rust-version` to 1.73, and uses `Weak::new()` in two static variable initializers, now that it's stable in const contexts.
> Make use of Weak::new() in constant contexts

- .github/workflows/dependabot-automerge.yml
This backports #2352 to the release/0.5 branch.
> dependabot-automerge: only run on opened/reopened

- aggregator/src/bin/janus_cli.rs
- aggregator/src/binaries/aggregator.rs
- aggregator/src/binary_utils.rs
- aggregator/tests/cmd/aggregation_job_creator.trycmd
- aggregator/tests/cmd/aggregation_job_driver.trycmd
- aggregator/tests/cmd/aggregator.trycmd
- docs/DEVELOPMENT.md
- tools/src/bin/dap_decode.rs
- tools/src/bin/hpke_keygen.rs
- tools/tests/cmd/dap_decode.trycmd
As alluded to in https://github.com/divviup/janus/pull/2234#discussion_r1397689826. Makes our CLI help texts consistent, and adds coding style guidelines to our documentation.
Some texts also were in need of minor content touch-ups. I removed usage of `help` as clap's derive macro does a good job of filling that out for us.
> Clean up all CLI help texts

- .github/workflows/unused-dependencies.yml
- Cargo.lock
- aggregator/Cargo.toml
- aggregator_api/Cargo.toml
- aggregator_core/Cargo.toml
- collector/Cargo.toml
- integration_tests/Cargo.toml
- interop_binaries/Cargo.toml
This implements #2392.  We had a variety of small issues to clean up before `cargo-udeps` would run cleanly. I think we'll have to merge this PR before we can test the GHA workflow, but I added a workflow_dispatch trigger to speed that up.
I had the workflow create an issue because by default, only the last person to touch a scheduled workflow gets alerted when it fails.
> Fix unused dependencies, add periodic workflow to monitor

- .github/workflows/unused-dependencies.yml
This is a follow-up to #2433, after testing the workflow. I needed to explicitly set `shell: bash` to get `-o pipefail` behavior. This PR additionally includes the cargo-udeps output in the body of issues created by the workflow.
> Unused dependencies: followup

- Cargo.lock
- Cargo.toml
- aggregator/Cargo.toml
- aggregator_api/Cargo.toml
- aggregator_core/Cargo.toml
- integration_tests/Cargo.toml
- integration_tests/src/lib.rs
- integration_tests/tests/integration/common.rs
- integration_tests/tests/integration/daphne.rs
- integration_tests/tests/integration/divviup_ts.rs
- integration_tests/tests/integration/in_cluster.rs
- integration_tests/tests/integration/janus.rs
- interop_binaries/Cargo.toml
- tools/Cargo.toml
- xtask/Cargo.toml
Extends the test harness in
`janus_integration_tests::integration::in_cluster` so that it can run
tests against remote instances of divviup-api, a Janus leader and a
Janus helper.
Concretely, this means connecting to those services at some remote URL
rather than over a `kubectl port-forward` to a local Kind cluster. Past
that, we also exercise less of the `divviup-api` surface.
In Kind, we do everything from creating an account through provisioning
a task. This works because the `divviup-api` used in that context has
authentication disabled and also because that entire environment is
understood to be ephemeral -- we can litter it with tasks and paired
aggregators and anything else we want and not clean up, because our
expectation is that the entire Kubernetes cluster and all its storage …
> Run E2E integration tests against cloud env

- aggregator/src/aggregator/aggregation_job_driver.rs
Before this PR, this would happen if every report in the job was filtered (for example, because the report was GC'ed before the aggregation job was sent). DAP did not proscribe how to handle this; a Helper Janus would return an error, causing the aggregation job to become stuck.
Now, instead of sending an empty aggregation initialization request, the Leader sends no request at all and continues processing as if it received an empty response. This will cause the aggregation job to be finished; the Helper will not know about this aggregation job, but that's OK since the aggregation job will not contribute anything to the eventual aggregate.
> Leader: do not send empty aggregation initialization requests.

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/binaries/aggregator.rs
- aggregator/src/binary_utils.rs
- aggregator_core/src/datastore.rs
- client/src/lib.rs
- core/src/auth_tokens.rs
- integration_tests/tests/integration/divviup_ts.rs
- messages/src/lib.rs
This cleans up some comments across the codebase.
- Update old references to draft-gpew-priv-ppm.
- Update references to pre-resource HTTP routes.
- Review TODOs, and delete them if completed or reference a more-specific issue if available.
- Add a missing divviup-ts integration test for Prio3SumVec.
- Fix rustdoc warnings in private items.
> Comment cleanup

- aggregator/src/config.rs
Credit to @jbr for the discovery and suggested fix.
> Redact database URL password

- aggregator/src/aggregator.rs
This adds a label with the HTTP method to the `janus_http_request_duration` histogram. This is important now that we have PUTs and POSTs to the same paths.
> Add method label to janus_http_request_duration

- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/aggregation_job_writer.rs
- aggregator_core/src/datastore.rs
This issue should only exist in the time-interval query type, as fixed-size is arranged such that aggregation jobs touching a given batch must be GC'ed before the batch. I include a guard to ensure that the new codepath is only taken in the expected case of an already-GC'ed batch for a time-interval query, as otherwise we might drop batch writes if we fell into it unexpectedly.
> Fix writing aggregation jobs touching GC'ed batches.

- Cargo.lock
- Cargo.toml
This release contains a number of nice bugfixes & performance improvements. See the eventual release notes for details.
> Bump Janus to 0.6.9.

- .github/dependabot.yml
- README.md
The `main` branch will soon start implementing `draft-ietf-ppm-dap-09` (#2389).
- Update dependabot config
- Update draft version table in README
- Mention errata in DAP-07 implementation
> Prepare to branch for `release/0.6`

- messages/src/lib.rs
Include the 4 byte length prefix when encoding ping-pong messages into a `PrepareRespResult`.
Closes #2466
> Fix `PrepareRespResult` wire encoding

- aggregator/Cargo.toml
- aggregator/src/bin/janus_cli.rs
- aggregator/src/binary_utils.rs
- aggregator/src/lib.rs
- aggregator/src/metrics.rs
#2474 was merged after we branched `release/0.6` from main so it needs to be backported.
> Log version information on startup

- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/collection_job_driver.rs
- client/src/lib.rs
- collector/src/lib.rs
- core/src/http.rs
- core/src/retries.rs
This sets a collection job to immediately abandon on failure, except in a narrow set of retryable errors.
The `is_retryable_error()` function is relatively narrow. It basically only retries on particular HTTP status codes and database errors. It's tricky to enumerate all possible retryable rrors. I'm welcome to input if there are other errors that should be retried.
Note that it retries on 500 errors. I don't really want it to, but this is done to share the logic with the other HTTP retry logic we have. I will address whether we should generally retry on 500 errors in a future PR.
I will give the same treatment to aggregation jobs in another PR (see https://github.com/divviup/janus/issues/235)
> Abandon collection jobs early when a fatal error is encountered

- aggregator/src/aggregator.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/tests.rs
- aggregator_core/src/query_type.rs
Part of DAP-09 implementation (#2389). With this change, Collectors are expected to remember the collection job IDs they generate before sending the collection request. If the Collector encounters a transient failure, it can then resend the request (with the same collection job ID), and rely on request idempotency for things to work out.
The upside of this change is that Collectors no longer need to have logic to deduplicate multiple current-batch requests that are mapped to the same underlying batch, and they can generate current-batch requests at higher rates without risking more duplicated collections.
> Fixed-size: return each batch to at most one current-batch query.

- Cargo.lock
- aggregator/Cargo.toml
- aggregator/src/binary_utils.rs
This updates crates used for TLS database connections, and adapts to a couple API changes.
> Upgrade tokio-postgres-rustls and rustls

- Cargo.lock
- aggregator/Cargo.toml
- aggregator/src/binary_utils.rs
> Upgrade tokio-postgres-rustls and rustls, 0.6 backport

- Cargo.lock
This addresses https://rustsec.org/advisories/RUSTSEC-2024-0003.
> Update h2 to address DoS advisory

- Cargo.lock
> Update h2 to address DoS advisory, 0.5 backport

- Cargo.lock
> Update h2 to address DoS advisory, 0.6 backport

- aggregator/src/aggregator/accumulator.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/aggregation_job_writer.rs
- aggregator/src/aggregator/garbage_collector.rs
- aggregator/src/aggregator/report_writer.rs
- aggregator_core/src/datastore.rs
This annotates a new datastore method with `#[tracing::instrument]`, and selectively renames some `#[tracing::instrument]`-generated spans on methods, for clarity. This is particularly relevant for, i.e., `run`, `write`, and `write_batch`.
> Tracing span tweaks

- Cargo.lock
- aggregator/Cargo.toml
- aggregator/src/binary_utils.rs
This closes #2478. It adds three new metrics, `janus_database_pool_available_connections`, `janus_database_pool_total_connections`, and `janus_database_pool_waiting_tasks`, to report the status of the database connection pool. These gauges are updated on-demand from a callback. I included a unit test to confirm that the first two are operating as intended.
> Add gauge metrics for DB connection pool status

- aggregator_core/src/datastore/test_util.rs
PostgreSQL might not be immediately ready after the container is started. If postgres isn't ready, the first connection to the database will fail. Wrap it in a retry loop to accommodate for this.
> tests: Add retry to first database connection

- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/collection_job_driver.rs
Closes https://github.com/divviup/janus/issues/235. Similar to https://github.com/divviup/janus/pull/2476.
I've duplicated the `is_retryable_error()` function because I strongly suspect that the interesting errors are going to differ between the two jobs.
I've removed usage of `anyhow::Error` from the aggregation job driver. While we can `downcast()` an `anyhow::Error`, it seemed cleaner just to go ahead and use our fully fleshed out `aggregator::Error` instead.
> Abandon aggregation jobs early when a fatal error is encountered

- Cargo.lock
Should fix the security advisory [that is blocking the CI on release/0.6](https://github.com/divviup/janus/actions/runs/7615913510/job/20741488192?pr=2517). Not sure why dependabot didn't do this for us.
> Update shlex 1.3.0 (release/0.6)

- .github/workflows/ci-build.yml
This splits out `cargo deny check advisories` into a separate GitHub Actions job, with `continue-on-error: true`. This is recommended in the action's README. This way, we will still see notice of advisories here, in addition to GitHub's Dependabot security alerts, but won't be blocked from merging unrelated changes when there's a new advisory about one of our dependencies.
> Don't block CI upon announcement of new advisories

- .github/workflows/ci-build.yml
> Don't block CI upon announcement of new advisories, 0.6 backport

- Cargo.lock
- Cargo.toml
Bump crate versions for release. Use prerelease version tags so we can break the SQL schema a few times.
> Release Janus 0.7.0-prerelease-1

- aggregator/src/aggregator/http_handlers.rs
This should make investigation of a BatchMismatch error a bit easier, by propagating error information from the helper into the leader. This would be to mainly to spot trends in report counts or checksums.
This also comes with the happy extension of supporting arbitrary fields in a `ProblemDocument` and slightly more test coverage on the helper's checksum/report count calculation.
> Include batch details in batch mismatch error

- messages/src/lib.rs
This adds a missing error code to PrepareError. The DAP changelog says this was added in draft 03, so all maintained branches will need this fix backported. If we tried to aggregate with a different helper implementation that uses this error code, we would fail to parse responses that contained this error code, which would turn an entire aggregation job into a dead letter.
I also fleshed out the related serialization unit test, and added an unrelated unit test that we were missing.
> Add report_too_early to PrepareError

- messages/src/lib.rs
> Add report_too_early to PrepareError, 0.6 backport

- messages/src/lib.rs
This is a backport of #2538. (I left off the HpkeConfigList unit test, since there were conflicts)
> Add report_too_early to PrepareError, 0.5 backport

- .github/workflows/ci-build.yml
> Pin to last working version of cargo-deny-action, 0.6 backport

- aggregator/Cargo.toml
- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/collection_job_driver.rs
- aggregator/src/aggregator/error.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/problem_details.rs
- aggregator_core/src/datastore/models.rs
- db/00000000000001_initial_schema.up.sql
Per DAP-09, when the leader gives up on an aggregation job, it SHOULD delete that job in the helper. Our leader (specifically `aggregation_job_driver`) now does this, and we wire up a simple handler for deleting aggregation jobs on the helper side. This handler does nothing but mark the relevant row in the aggregations job as deleted. This could eventually be used by Janus garbage collection to more aggressively evict data before its expiry.
Part of #2389
> leader deletes abandoned aggregation job in helper

- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/batch_creator.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/tests.rs
Other than being the earliest point that we can scrub reports, this avoids (briefly) duplicating report data in both the `client_reports` and `report_aggregations` tables. I think placing this logic in the aggregation job creator also makes more sense for when we'll eventually expand it to handle VDAFs requiring multiple aggregations per report.
Part of #2442.
> Scrub reports during aggregation job creation, rather than the initial aggregation step.

- aggregator/src/aggregator.rs
- aggregator_api/src/lib.rs
- aggregator_api/src/models.rs
- aggregator_api/src/routes.rs
- aggregator_api/src/tests.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/models.rs
- aggregator_core/src/datastore/tests.rs
Stacked on https://github.com/divviup/janus/pull/2508.
I exposed these metrics through `tasks/{task_id}/metrics/uploads`, rather than directly superseding or extending the existing `/metrics` endpoint.
This is mostly for ease of backporting and compatibility with divviup-api. I also wanted to avoid coupling the queries that underly `/metrics` together, since currently it times out for large tasks. I also generally think multiple smaller APIs are better than a larger kitchen-sink one, since downstream can compose them any way it likes.
> Expose upload metrics through aggregator API

- aggregator_core/src/datastore/test_util.rs
https://github.com/divviup/janus/pull/2514
> tests: Add retry to first database connection (release/0.6 backport)

- aggregator_core/src/datastore.rs
- db/00000000000002_task_upload_counters.down.sql
- db/00000000000002_task_upload_counters.up.sql
Supports https://github.com/divviup/janus/issues/2293, partial backport of https://github.com/divviup/janus/pull/2508.
This is just the database schema, so we can roll this changeset out without having downtime or crashing replicas.
> Add schema for report upload counters (release/0.6 backport)

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator_core/src/datastore.rs
The Trillium handler for errors was unconditionally logging them at `WARN`, generating large volumes of logging for problems that aren't Janus' fault, like reports whose timestamps are in the future. Now, we check whether the respones indicates a server error before bothing to log it (keeping in mind that client errors will still appear in metrics).
Additionally, we've made liberal use of the [`tracing::instrument`][1] attribute macro to decorate various functions and methods with tracing spans, and in particular its `err` argument for logging anytime a function that returns `Result<T, E>` returns an `Err`. Mostly, logging those errors is handled at a higher level -- say, in a Trillium handler or in the top-level loop of `aggregation_job_driver` -- so logging them at level `ERROR` at the …
> Downgrade various logs to `DEBUG` level

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator_core/src/datastore.rs
The Trillium handler for errors was unconditionally logging them at `WARN`, generating large volumes of logging for problems that aren't Janus' fault, like reports whose timestamps are in the future. Now, we check whether the respones indicates a server error before bothing to log it (keeping in mind that client errors will still appear in metrics).
Additionally, we've made liberal use of the [`tracing::instrument`][1] attribute macro to decorate various functions and methods with tracing spans, and in particular its `err` argument for logging anytime a function that returns `Result<T, E>` returns an `Err`. Mostly, logging those errors is handled at a higher level -- say, in a Trillium handler or in the top-level loop of `aggregation_job_driver` -- so logging them at level `ERROR` at the …
> Downgrade various logs to `DEBUG` level (backport #2557)

- Cargo.lock
This bumps a transitive dependency to pull in a fix for a security advisory. See #2544 and #2574.
> Trillium security patches, 0.5 backport

- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/tests.rs
> Split delete_expired_client_reports() query, 0.6 backport

- Cargo.lock
This bumps two transitive deps to satisfy `cargo deny check advisories`. It appears that Dependabot only sends security updates for the main branch, and as these are transitive dependencies only, they don't get picked up by regular Dependabot updates either. See #2544.
> Trillium security patches, 0.6 backport

- aggregator/src/aggregator/aggregation_job_driver.rs
This makes a small fix to a couple tests to scrub client reports before running the aggregation job driver. In practice, the aggregation job creator does this when setting up a job, so we should mirror that in this fixture as well.
> Scrub report in setup_cancel_aggregation_job_test

- collector/src/credential.rs
- integration_tests/tests/integration/in_cluster.rs
- tools/src/bin/collect.rs
Supports https://github.com/divviup/janus/issues/2588. Cleans up the public API.
> Make `hpke_keypair()` infallible, remove `hpke_keypair_infallible()`

- aggregator/src/config.rs
Supports https://github.com/divviup/janus/issues/2588. Removes support for deprecated configuration.
> Remove support for field `max_job_discovery_delay_secs`

- .github/workflows/make-release.yml
Interpolating GitHub user-controlled variables directly into a shell script is unsafe, since they're interpolated verbatim, leading to the possibility of script injection. https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections
This change is just out of an abundance of caution. At the moment, only people with `write` access can trigger a workflow_dispatch, which should be a tightly controlled set of users who are exceedingly unlikely to execute injection attacks.
> Avoid script injection in make-release workflow

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/accumulator.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/collection_job_driver.rs
- aggregator/src/aggregator/collection_job_tests.rs
- aggregator/src/aggregator/garbage_collector.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/taskprov_tests.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/models.rs
- aggregator_core/src/datastore/tests.rs
- db/00000000000001_initial_schema.up.sql
These fields were unused.
Closes #2251.
> Remove batch_aggregations.{batch,client_timestamp}_interval.

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregate_init_tests.rs
- aggregator/src/aggregator/http_handlers.rs
Like with the Leader, this is based on the `tolerable_clock_skew` task parameter.
Closes #2539.
> Helper: disallow reports from too far in the future.

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregate_init_tests.rs
- aggregator/src/aggregator/http_handlers.rs
Like with the Leader, this is based on the `tolerable_clock_skew` task parameter.
> [0.6] Helper: disallow reports from too far in the future.

- messages/src/lib.rs
- tools/src/bin/collect.rs
Closes https://github.com/divviup/janus/issues/2236
Cleanup: replace `&'static str` and `Box<dyn Debug>` error types with the existing `messages::Error` type. This mostly affects `FromStr` and `TryFrom` impls.
`thiserror::Error` derived types implement `Into<std::error::Error>`. This leads to simplification of clap argument parsing in collect.rs, because clap able to transparently deal with types where `<T as FromStr>::Err: Into<std::error::Error>`.
> Replace &str and Box error types with messages::Error

- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/batch_creator.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/tests.rs
- core/src/time.rs
The implementation strategy is to consider only a given batch at a time, generating as many aggregation jobs as possible. Only once there are too few reports from the batch remaining to generate any more aggregation jobs do we move on to the next batch, rolling in the leftovers from the current batch (effectively smearing across batches when necessary).
Note that this will not necessarily avoid multi-batch aggregation jobs in all cases. For example, if aggregation jobs are generated with sizes in [5, 10], and there are 11 reports available for aggregation in the current batch, this logic will generate a single batch of size 10, rolling the leftover report into the next batch. It is instead possible to generate two aggregation jbos of (say) 5 and 6, with no leftovers to be rolled into the …
> Time-interval: create aggregation jobs touching fewer batches.

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator_core/src/task.rs
- core/src/dp.rs
- core/src/vdaf.rs
- integration_tests/src/client.rs
- integration_tests/tests/integration/common.rs
- integration_tests/tests/integration/janus.rs
- interop_binaries/src/bin/janus_interop_client.rs
- interop_binaries/src/bin/janus_interop_collector.rs
- interop_binaries/src/lib.rs
This adds support for a customized variant of Prio3. It uses a smaller field and more FLP proofs, and uses a different XOF. I chose the same algorithm ID that Daphne uses, from the private use range, so we can interoperate. This VDAF needs a different verify key length, but fortunately this required just a bit more plumbing to support. Unlike in Daphne, I hardcoded the number of proofs to 3 (the minimum allowed number when using Field64) to avoid misuse with choices that could compromise robustness.
I also noticed that the `vdaf_dispatch!()` macro no longer gets called in the mode that doesn't construct the VDAF, so I dropped a bunch of code before adding this VDAF to it.
> Add customized Prio3SumVec VDAF

- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/batch_creator.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/tests.rs
- core/src/time.rs
The implementation strategy is to consider only a given batch at a time, generating as many aggregation jobs as possible. Only once there are too few reports from the batch remaining to generate any more aggregation jobs do we move on to the next batch, rolling in the leftovers from the current batch (effectively smearing across batches when necessary).
Note that this will not necessarily avoid multi-batch aggregation jobs in all cases. For example, if aggregation jobs are generated with sizes in [5, 10], and there are 11 reports available for aggregation in the current batch, this logic will generate a single batch of size 10, rolling the leftover report into the next batch. It is instead possible to generate two aggregation jobs of (say) 5 and 6, with no leftovers to be rolled into the …
> [0.6] Time-interval: create aggregation jobs touching fewer batches.

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/bin/janus_cli.rs
- aggregator_api/src/models.rs
- aggregator_api/src/routes.rs
- aggregator_api/src/tests.rs
- aggregator_core/src/datastore/tests.rs
- aggregator_core/src/task.rs
- core/src/vdaf.rs
- integration_tests/tests/integration/common.rs
- integration_tests/tests/integration/in_cluster.rs
- interop_binaries/src/bin/janus_interop_collector.rs
- tools/src/bin/collect.rs
- tools/tests/cmd/collect.trycmd
- tools/tests/cmd/collect_fpvec_bounded_l2.trycmd
This removes Prio3CountVec throughout. It was formerly polyfilled using Prio3SumVec inside the aggregator. Prio3CountVec is removed from the list of supported VDAFs exposed via the aggregator API, so the control plane should handle this change gracefully. I replaced Prio3CountVec with Prio3SumVec when it was incidentally used in tests.
Closes #2608. Stacked on #2633.
> Remove Prio3CountVec

- Cargo.lock
- Cargo.toml
This prepares for cutting a new prerelease, which will include support for Prio3SumVecField64MultiproofHmacSha256Aes128.
> Bump version to 0.7.0-prerelease-2

- aggregator/src/binaries/aggregation_job_driver.rs
- aggregator/src/binaries/collection_job_driver.rs
- aggregator/src/config.rs
- aggregator/tests/integration/graceful_shutdown.rs
- client/src/lib.rs
- collector/src/lib.rs
- docs/samples/advanced_config/aggregation_job_driver.yaml
- docs/samples/advanced_config/collection_job_driver.yaml
- integration_tests/src/janus.rs
Applies HTTP client timeouts in the `janus_client` and `janus_collector` crates, as well as in leader->helper HTTP requests.
Closes #426
> Set HTTP client timeouts

- aggregator/src/binaries/aggregation_job_driver.rs
- aggregator/src/binaries/collection_job_driver.rs
- aggregator/src/config.rs
- aggregator/tests/integration/graceful_shutdown.rs
- client/src/lib.rs
- collector/src/lib.rs
- docs/samples/advanced_config/aggregation_job_driver.yaml
- docs/samples/advanced_config/collection_job_driver.yaml
- integration_tests/src/janus.rs
* client, collector: default timeouts for requests
Apply default timeouts (10 s to connect, 30 s overall) to HTTP requests made by the client and collector crates. Additionally, we remove `ClientParameters::new_with_backoff`: since that struct was private to the crate anyway, we can just write directly to its `http_request_retry_parameters` field, and `ClientBuilder::with_backoff` provides a public API affordance for achieving this.
Resolves #426
* Apply timeouts to leader->helper HTTP requests
Set default timeouts for HTTP requests made from leader to helper, and wire up config options for them.
> Set HTTP client timeouts (backport #2632)

- core/src/vdaf.rs
- messages/src/taskprov.rs
This plumbs the new VDAF through the taskprov module. Note that Prio3SumVec was previously missing from the VdafInstance conversion as well.
> Add Taskprov support for Prio3SumVecField64MultiproofHmacSha256Aes128

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/report_writer.rs
Stop updating per task upload metrics as this was causing a performance regression in Divvi Up production.
See #2654
> Hotfix: disable task counter updates

- Cargo.lock
- aggregator/src/aggregator/error.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator_core/src/datastore/test_util.rs
This fixes #2655. Transaction-level errors in ReportWriteBatcher were resulting in panics during response handling. I think that database connection pool timeouts were the most likely cause of such errors, during periods of high load. This PR adds a unit test simulating this condition, and fixes the panic in two ways, by upgrading trillium, and by using a newtype around `Arc<Error>` as a `Handler`, allowing us to specify our own (no-op) init method.
Reviewer note: I recommend flipping "ignore whitespace" on, because I turned an existing method into a function, and an existing function into a method.
> Fix fanning out transaction error from ReportWriteBatcher

- aggregator/src/aggregator/http_handlers.rs
I noticed some flakiness in CI from the new test introduced by #2657. This PR attempts to fix it by waiting for the database connection pool to be both maxed out and not have any connections available.
> Fix test flakiness

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- core/src/vdaf.rs
- integration_tests/src/client.rs
- integration_tests/tests/integration/common.rs
- integration_tests/tests/integration/janus.rs
- interop_binaries/src/bin/janus_interop_client.rs
- interop_binaries/src/bin/janus_interop_collector.rs
- interop_binaries/src/lib.rs
- messages/src/taskprov.rs
This makes the number of proofs a VDAF parameter, whereas previously it was hardcoded to 3. I added a check in the constructor function to disallow using only one proof with Field64. I wrote the Taskprov VdafConfig serialization/deserialization to be compatible with Daphne, with the number of proofs occurring last.
> Parameterize number of proofs in multiproof Prio3

- Cargo.lock
- Cargo.toml
This bumps the version so we can cut a new prerelease that includes #2685 and other improvements.
> Bump version to 0.7.0-prerelease-3

- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/binaries/aggregation_job_creator.rs
- aggregator/tests/integration/graceful_shutdown.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/tests.rs
- docs/samples/advanced_config/aggregation_job_creator.yaml
- integration_tests/src/janus.rs
This adds a configuration option to set how many reports the unaggregated reports query may return. Until we implement #2689, this query could potentially return enough to OOM a process, with large enough VDAF parameters. In the future, we may also want to experiment with this parameter to improve throughput.
> Configurable LIMIT in unaggregated reports query

- docker-bake.hcl
This changes our use of the GitHub Actions cache backend for Docker BuildKit so that errors writing to the cache are ignored. This should improve our Monday flakiness significantly, at the expense of skipping some cache writes.
> Ignore Docker cache export errors

- aggregator_api/src/routes.rs
- aggregator_api/src/tests.rs
Supports #2293.
See https://github.com/divviup/divviup-api/pull/809#issuecomment-1954906298. It's necessary to communicate this feature to divviup-api so it can change its behavior for versions of Janus that don't contain this feature (i.e. Janus 0.5).
I will overload issue https://github.com/divviup/janus/issues/2066 to phase out this feature flag once Janus 0.5 (and any older versions) aren't in production use anymore.
> Add UploadMetrics feature to aggregator API

- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/aggregation_job_writer.rs
- aggregator/src/aggregator/batch_creator.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/models.rs
- aggregator_core/src/datastore/tests.rs
This refactors the aggregation job writer, providing separate APIs for creating versus updating aggregation jobs, and changes aggregation job creation so that it does not read entire reports into memory, or write them back out from meory, but instead copies directly between the two database tables. This should improve the performance of the aggregation job creator, which we haven't yet scaled horizontally, and will mainly benefit tasks with very large VDAF messages.
Behavior differences between new aggregation jobs and updated aggregation jobs are controlled through a combination of static dispatch with traits and conditionals. There's one trait for updating a batch to reflect aggregation job changes, and another that abstracts over `ReportAggregation` and the new …
> Copy report shares within database when creating aggregation jobs

- aggregator/src/aggregator/aggregation_job_writer.rs
This is a follow-up to #2727, adding `#[tracing::instrument]` to the two new `write()` methods. `AggregationJobWriter::write()` used to be instrumented.
> Re-instrument aggregation job writers with spans

- aggregator_api/src/tests.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/tests.rs
Fresh tasks, or tasks that otherwise don't have any counters, would return 404 when `/{task_id}/metrics/uploads` was called. This is not correct behavior. Fix the underlying database query.
Here's some query plans, doesn't appear to be regressive:
Before:
```
postgres=> EXPLAIN SELECT
SUM(interval_collected)::BIGINT AS interval_collected,
SUM(report_decode_failure)::BIGINT AS report_decode_failure,
SUM(report_decrypt_failure)::BIGINT AS report_decrypt_failure,
SUM(report_expired)::BIGINT AS report_expired,
SUM(report_outdated_key)::BIGINT AS report_outdated_key,
SUM(report_success)::BIGINT AS report_success,
SUM(report_too_early)::BIGINT AS report_too_early,
SUM(task_expired)::BIGINT AS task_expired
FROM task_upload_counters
WHERE task_id = (SELECT id FROM tasks WHERE task_id = …
```
> Aggregator API: return 200 with zero counters for fresh task

- aggregator_core/src/task.rs
- integration_tests/tests/integration/common.rs
- integration_tests/tests/integration/daphne.rs
- integration_tests/tests/integration/divviup_ts.rs
- integration_tests/tests/integration/in_cluster.rs
- integration_tests/tests/integration/janus.rs
Refactors integration test harness so that the top-level test functions can instantiate and manipulate a `TaskBuilder` value instead of having it constructed several calls deep in `test_task_builder_inner`.
This is useful because soon, we will want to run tests using VDAFs with non-trivial aggregation parameters. That means collecting a single batch multiple times, which means we want to set `max_batch_query_count` higher than 1. Exposing the `TaskBuilder` is an easier way to do that (or set other values) than to plumb more arguments into the `task_builder_*` functions.
> expose `TaskBuilder` to integration tests

- Cargo.lock
This resolves a security advisory only relevant to less-common Unixes.
> Upgrade whoami to 1.5.0

- Cargo.lock
This upgrades two dependencies to address security advisories relevant to less-common Unixes and Windows, respectively.
See #2774 and #2775.
> Upgrade whoami to 1.5.0 and mio to 0.8.11

- Cargo.lock
> Upgrade dependencies to address security advisories, 0.6 backport

- messages/src/taskprov.rs
We currently encode and decode two parameter fields for Prio3SumVec in the wrong order. See [this figure](https://wangshan.github.io/draft-wang-ppm-dap-taskprov/draft-wang-ppm-dap-taskprov.html#section-3-11). The length must come first, followed by the number of bits. I also changed the multiproof variant in the same manner, and with this fix, it now matches Daphne.
> Fix Taskprov struct field order for Prio3SumVec

- messages/src/taskprov.rs
This backports #2777. I'm backporting this mainly to avoid possible confusion.
> Fix Taskprov struct field order for Prio3SumVec, 0.6 backport

- core/src/auth_tokens.rs
Smol API nit: If we have a DapAuthToken, such as in situations where we deserialized an explicit DapAuthToken:
```rust
#[derive(Deserialize)]
struct DeserializeMe {
dap_auth_token: DapAuthToken,
}
```
we may wish to `.into()` it when giving it to other functions that take a `AuthenticationToken`.
```rust
let auth_token: AuthenticationToken = dap_auth_token.into();
```
This is a little bit bit nicer to do than `AuthenticationToken::DapAuth(dap_auth_token)`. In other situations, we get the bonus of being able to do `AuthenticationToken::from(dap_auth_token)` without having to actually care about the token type.
> Implement From<{BearerToken,DapAuthToken}> for AuthenticationToken

- core/src/hpke.rs
- messages/src/lib.rs
Makes FromStr implementations consistent with what we have in the `janus_messages` crate.
> Use base64 encoding for HpkePrivateKey's FromStr; implement FromStr for HpkePublicKey

- aggregator/src/aggregator/taskprov_tests.rs
- aggregator_core/src/task.rs
- core/src/vdaf.rs
This fixes an issue when using Taskprov in combination with a custom VDAF using an XOF that has a different seed length. We previously had two functions that provided the VDAF verify key length for a given VdafInstance, and only one of them was updated for `Prio3SumVecField64MultiproofHmacSha256Aes128`. This PR removes that duplication, and fixes Taskprov verify key derivation.
> Taskprov: fix verify key length for HMAC XOF

- aggregator_core/src/datastore.rs
This applies the same strategy from #2560 to the query in `get_unaggregated_client_reports_for_task()`. I'm currently seeing bad average performance and worse outlier performance in production from this query. Typical query plans include a sort node after an index scan, but before the limit node. This means we're having to sort the entire backlog of unaggregated reports for each task. Removing the join on the `tasks` table eliminates the sort node. Eliminating this join should also improve the accuracy of row count estimates, which may help address the outlier queries that are taking two hours to execute.
> Split database query for unaggregated reports

- aggregator/src/bin/janus_cli.rs
- aggregator/src/binaries/aggregation_job_creator.rs
- aggregator/src/binaries/aggregation_job_driver.rs
- aggregator/src/binaries/aggregator.rs
- aggregator/src/binaries/collection_job_driver.rs
- aggregator/src/binary_utils.rs
- aggregator/src/config.rs
- aggregator/tests/integration/graceful_shutdown.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/test_util.rs
- aggregator_core/src/datastore/tests.rs
- integration_tests/src/janus.rs
Closes https://github.com/divviup/janus/issues/2124.
Breaks out of the transaction loop if it's tried too many times. This is governed by the config option `max_transaction_retries`. We could hard code this limit, but it's not a big deal to plumb it through to configuration in the off chance we need to raise it.
> Add limit to transaction retries

- aggregator/src/aggregator/http_handlers.rs
This removes an extra extension member from our `urn:ietf:params:ppm:dap:error:unrecognizedAggregationJob` problem details documents. Closes #2593.
I decided to just remove the aggregation job ID and not template it into the `detail` string. Doing that would require a broader refactor -- I think we'd want to start using a value-carrying enum instead of a C-style enum and multiple optional fields provided via builder methods, and then build the entire document in one place, removing the detail method that currently returns a `&'static str`.
> Remove extra extension member from problem details

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/taskprov_tests.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/task.rs
- db/00000000000001_initial_schema.up.sql
This closes #2720. I chose to not plumb this field to the YAML or JSON representations of tasks.
> Save Taskprov task_info field in database

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregate_init_tests.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/aggregation_job_writer.rs
- aggregator/src/aggregator/garbage_collector.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/taskprov_tests.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/tests.rs
- db/00000000000001_initial_schema.up.sql
Previously, such writes would lead to a MutationTargetAlreadyExists error. However, the same error would happen if two transactions concurrently wrote the same entity (regardless of GC), which would have to be manually retried (by `tx.retry()`) by application code if it was sure the row shouldn't exist. This could lead to infinitely-repeated retries if the MutationTargetAlreadyExists error was due to the row being GC'ed rather than a concurrent write.
Now, we perform an upsert if the existing row is logically GC'ed. This allows overwriting logically-nonexistent rows with a put, but more importantly, this should allow concurrent writes to receive a serialization failure, rather than a
MutationTargetAlreadyExists error. This removes the need for application-level retries entirely, which …
> Datastore: treat writes to logically GC'ed rows as new writes.

- Cargo.lock
- Cargo.toml
- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregate_init_tests.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/collection_job_driver.rs
- aggregator/src/aggregator/collection_job_tests.rs
- aggregator/src/aggregator/garbage_collector.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/binary_utils/job_driver.rs
- aggregator_api/src/tests.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/models.rs
- aggregator_core/src/datastore/tests.rs
- aggregator_core/src/query_type.rs
- core/src/vdaf.rs
- integration_tests/Cargo.toml
- integration_tests/src/client.rs
- integration_tests/tests/integration/common.rs
- integration_tests/tests/integration/janus.rs
- messages/Cargo.toml
Enable Janus to run the dummy VDAF from crate `prio` with arbitrary rounds
(by extending the representation of `VdafInstance::Fake`) and with multiple
aggregation parameters chosen by the test.
To that end, this resurrects some functionality previously deleted in #1508.
At the time, we had that code gated on `#[cfg(test)]`, with some cautions
about its likely performance problems. I'm bringing it back in the release
configuration of Janus. I don't think we need a feature flag for this: the
various `VdafInstance::Fake` variants that would use these codepaths are not
currently compiled into release Janus builds. Even if they were, deployments
can avoid this risky code by simply not using those VDAFs.
This wires up some tests for both time interval and fixed size tasks, running
multiple …
> Integration test using dummy VDAF with agg param

- aggregator/src/aggregator/aggregate_init_tests.rs
- aggregator/src/aggregator/http_handlers/tests/aggregate_share.rs
- aggregator/src/aggregator/http_handlers/tests/helper_e2e.rs
- aggregator/src/aggregator/http_handlers/tests/mod.rs
This adds a test to check that replayed reports are correctly handled by helpers. There's currently one test that checks for `PrepareError::ReportReplayed`, this test differs because it sets up the report via DAP requests instead of datastore fixtures, and it checks the aggregate share report count/checksum matches expected values as well.
> Add negative test for helper handling of replayed reports

- aggregator_api/src/lib.rs
- aggregator_api/src/models.rs
- aggregator_api/src/routes.rs
- aggregator_api/src/tests.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/tests.rs
Lets us issue `PATCH /tasks/:task_id` with the following bodies and results
- `{}` -> no changes, returns the task as-is.
- `{"task_expiration": null}` -> unsets the task expiration. There currently isn't a use case for this, but I did it for consistency with how PUT of a task works, i.e. you can make a task with no expiration.
- `{"task_expiration": 1000}` -> works as you'd expect, content is seconds since epoch.
Supports https://github.com/divviup/divviup-api/issues/862
> aggregator api: Allow patching a task's expiration time

- aggregator_core/src/datastore.rs
- db/00000000000001_initial_schema.up.sql
Supports https://github.com/divviup/janus/issues/2819, follow up to https://github.com/divviup/janus/pull/2824 since task rows are no longer immutable.
> datastore: Add updated_at to tasks table

- aggregator_core/src/datastore.rs
I thought I took this suggestion https://github.com/divviup/janus/pull/2824#discussion_r1529437708 but it didn't stick.
> Downgrade log level for update_task_expiration

- aggregator_core/src/datastore.rs
This is a follow-up to #2857 to add conditions on `aggregation_jobs.task_id` back to some queries. The importance of these predicates varies: some are in `test-util` methods, some may be fine as it is if other joined tables can be searched over first, and some don't have any such compensating factors. These conditions will help when looking up aggregation jobs by their `aggregation_job_id` column, because there is only one index covering this column, and its first column is `task_id`. We know that all `report_aggregations` rows linked to an aggregation job will share the same `task_id` as the `aggregation_jobs` row, but the database doesn't, so supplying this redundant constraint when joining across both opens up new opportunities for efficient index scans. Without this, my concern is …
> Add conditions on aggregation_jobs.task_id back to queries

- Cargo.lock
- Dockerfile
- Dockerfile.interop
- Dockerfile.interop_aggregator
- interop_binaries/Cargo.toml
- interop_binaries/config/aggregator.yaml
- interop_binaries/config/supervisord.conf
- interop_binaries/setup.sh
- interop_binaries/src/bin/janus_interop_aggregator.rs
This closes #446. The aggregator interop container is changed so that it runs the aggregator component as a separate process, managed by supervisord, and the `janus_interop_aggregator` binary reverse proxies DAP requests it receives to the aggregator. I also moved schema migration out of `janus_interop_aggregator`, so we can sequence it before starting other processes. This was necessary because the aggregator component doesn't tolerate missing tables well when it loads global HPKE keys at startup. With this change, the `janus_interop_aggregator` binary is much smaller, since it doesn't include the entire aggregator.
I also cleaned up old `ENV CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse` lines, because this option is now the default, and has been for a while.
> Reverse proxy inside `janus_interop_aggregator`

- Cargo.lock
`divviup-client` 0.1.16 isn't aware of DAP-09 and so can't drive integration tests against a DAP-09 aggregator.
> bump divviup-client to 0.1.17

- Dockerfile.interop
- Dockerfile.interop_aggregator
- aggregator/src/bin/aggregation_job_creator.rs
- aggregator/src/bin/aggregation_job_driver.rs
- aggregator/src/bin/aggregator.rs
- aggregator/src/bin/collection_job_driver.rs
- aggregator/src/binary_utils.rs
- interop_binaries/src/bin/janus_interop.rs
- interop_binaries/src/commands/janus_interop_aggregator.rs
- interop_binaries/src/commands/janus_interop_client.rs
- interop_binaries/src/commands/janus_interop_collector.rs
- interop_binaries/src/commands/mod.rs
- interop_binaries/src/lib.rs
- interop_binaries/src/main.rs
This combines the three binary targets under `janus_interop_binaries` into one. It can either be used via symlinks with the original names of the three binaries, dispatching on argv[0], or with its default name and a subcommand. Dockerfiles are updated so that they work the same way as before. Moreover, we can now share builder layers between all three interop test containers. Overall, this should slightly improve build time and total image size. This is a warm-up for #2312. Note that I had to move `Options::parse()` out of `janus_main()` here; this will be doubly necessary when implementing #2312.
> Unify interop test binary targets

- Cargo.lock
- interop_binaries/Cargo.toml
This disables the default features of the new trillium-proxy dependency. We only have one upstream, so we don't need either `upstream-random` or `upstream-connection-counting`.
> Disable default features on trillium-proxy

- aggregator/src/aggregator.rs
- tools/src/bin/collect.rs
Already fixed on main with https://github.com/divviup/janus/pull/2659/files.
I went with the `let` approach rather than `#[allow(...)]` approach since the former is what we already have on main.
> Fix unused braces lint for clippy 1.77

- .github/workflows/ci-build.yml
- .github/workflows/push-docker-images-release.yml
- Dockerfile.sqlx
- README.md
- docker-bake.hcl
- docs/DEPLOYING.md
Supports https://github.com/divviup/janus-ops/issues/1122, backports https://github.com/divviup/janus/pull/2177.
---
Original message by timg:
Janus now builds and ships a container image that bundles `sqlx` and the current Janus version's SQL migration scripts. This makes it easier for deployments to apply SQL migrations, as they no longer need to build a `sqlx` image themselves and (more importantly) figure out how to provide the appropriate set of migration scripts to whatever is applying the migrations.
While updating the READMEs, I also fixed a few Markdown hyperlinks to make some long lines less long.
> Add `janus_db_migrator` container (release/0.5 backport)

- .github/workflows/ci-build.yml
- Cargo.toml
- Dockerfile
- Dockerfile.interop
- Dockerfile.interop_aggregator
- Dockerfile.sqlx
This includes loosely related CI optimizations, primarily about reducing the volume of data we cache.
- Incremental compilation is disabled in all Dockerfiles with an environment variable, since there won't be a subsequent compilation in which to use the files. This only has an impact when we compile with the `small` profile; the `release` built-in profile already disables this. Our `docker-bake.hcl` file only applies `PROFILE=small` to the interop containers, but I added the environment variables throughout to avoid blocking layer reuse between Dockerfiles, and as insurance for future builds with other profiles. When I tested this, it reduced total layer size of builder stages for the interop test containers by 1.4GiB, but I hadn't pulled in #2873 yet, so this will ultimately be a lesser …
> CI optimizations

- Cargo.lock
- Cargo.toml
- aggregator/Cargo.toml
- aggregator_core/Cargo.toml
- client/Cargo.toml
- collector/Cargo.toml
- core/Cargo.toml
- integration_tests/Cargo.toml
- interop_binaries/Cargo.toml
- tools/Cargo.toml
This updates all crates in the `http` ecosystem. Closes #2295.
> Update http ecosystem crates

- Cargo.lock
Many of our dependencies are out-of-date in terms of minor version. I noticed this because some of Janus' dependents failed to take an update to the Janus crates due to using a too-old version of the chrono crate which was missing a function introduced in a later minor version.
> Run `cargo update`.

- aggregator/tests/cmd/aggregation_job_creator.trycmd
- aggregator/tests/cmd/aggregation_job_driver.trycmd
- aggregator/tests/cmd/aggregator.trycmd
This fixes the trycmd tests, which were ignored since #2879.
There's not currently any way to opt out of this ignoring behavior, though there is an upstream open issue on the topic.
`trycmd` doesn't have any support for changing argv[0] -- trying to use `register_bins()` just results in invoking the binary with its filename in argv[0]. Thus, I changed the commands to use the non-multicall subcommands, which are functionally equivalent. (The other way to address this would be creating temporary symbolic links with the right names, and registering those)
> Fix trycmd tests

- Cargo.lock
- Cargo.toml
This sets the minimum version of chrono to 0.4.33, which is when `Duration::try_seconds()` was introduced.
> Update minimum version of chrono

- Cargo.toml
> Update minimum version of chrono, 0.6 backport

- aggregator/src/binaries/aggregator.rs
This applies a late suggestion I made on #2880.
While trying to propagate this to the trycmd tests, I discovered that #2879 made trycmd ignore relevant tests, since binary names changed. I'll fix that separately.
> Rephrase description of signing key option

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/aggregation_job_writer.rs
- aggregator/src/metrics.rs
The new "janus_aggregation_success_counter" tracks the number of successfully-aggregated reports. This metric is not keyed by task ID or anything else, so it will be most useful (a) in single-teneant deployments or (b) as an overall metric of aggregation throughput.
> Add metric for aggregation success.

- Cargo.toml
- aggregator/Cargo.toml
- aggregator_api/Cargo.toml
- aggregator_core/Cargo.toml
- client/Cargo.toml
- collector/Cargo.toml
- core/Cargo.toml
- integration_tests/Cargo.toml
- interop_binaries/Cargo.toml
- messages/Cargo.toml
- tools/Cargo.toml
- xtask/Cargo.toml
Use `cargo-autoinherit` to rewrite all the workspace `Cargo.toml`s to pull in dependencies from the top-level using `workspace = true`. I then hand-sorted the top-level `Cargo.toml` because I couldn't get `cargo-sort` to work.
> Hoist all dependencies up to top-level Cargo.toml

- aggregator/Cargo.toml
- client/Cargo.toml
- collector/Cargo.toml
- core/Cargo.toml
This sorts dependencies in remaining Cargo.toml files.
I have a hacked-up version of `cargo-sort` sitting around that compiles, but adds extra spaces when pretty-printing, so I used that as an oracle to fix alphabetization.
> Sort dependencies in Cargo.toml files

- interop_binaries/Cargo.toml
- interop_binaries/config/janus_interop_aggregator.yaml
- interop_binaries/src/commands/janus_interop_aggregator.rs
See https://github.com/divviup/divviup-android/issues/101#issuecomment-2032813271, if the subprocesses aren't ready, we shouldn't report that the interop API is ready.
> interop: Wait for subprocesses to be ready before reporting ready

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/collection_job_driver.rs
- aggregator/src/aggregator/http_handlers/tests/aggregate_share.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_continue.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/models.rs
- aggregator_core/src/datastore/tests.rs
- aggregator_core/src/query_type.rs
Specifically, we now check if there are unaggregated reports, or unfinished aggregation jobs, in the same pipelined round-trip as reading the task and collection job. The outstanding aggregation job count is determined without reading the set of batch aggregations, which can be quite large in some cases as they include partial aggregate shares.
We also now check for a matching, already-completed collection job before reading the batch aggregations.
> Collection job driver: reduce work required to detect step readiness.

- .github/workflows/ci-build.yml
- deny.toml
This addresses some warnings from `cargo-deny` about deprecations in the config file format, and enables some new checks. I enabled the `sources` check, which will exclude any non-crates.io registries, and codified our practice of occasionally using pinned git commits from our other repositories. I enabled the `licenses` check, and allowed all licenses of software we currently use, primarily to raise a flag if we add a dependency on a crate lacking clear license terms.
> Update cargo-deny config

- Cargo.lock
- Cargo.toml
- aggregator/Cargo.toml
- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/binary_utils.rs
- aggregator/src/cache.rs
- aggregator/src/main.rs
- aggregator_core/src/task.rs
- integration_tests/src/janus.rs
- interop_binaries/src/commands/janus_interop_aggregator.rs
This should address #2955. I'm going to open this as a draft now before doing performance testing on it.
This moves VDAF preparation in three places to a `rayon` threadpool. Various inputs are moved into a closure, the closure is sent into a new threadpool task, and the task sends the result back to the initiating future via a Tokio oneshot channel. I created a new tracing span at the beginning of the threadpool task, and linked it to a parent span.
I hemmed and hawed between `rayon::spawn()` and `rayon::spawn_fifo()`, but ultimately went with the former. This means tasks will be handled in LIFO order when picked up by the same thread, or FIFO order when other threads do work stealing. I figure having some LIFO behavior is preferable, because when overloaded, we'd rather successfully …
> Run VDAF preparation on a threadpool

- aggregator/src/binaries/aggregator.rs
- aggregator/src/binary_utils.rs
- aggregator/tests/integration/graceful_shutdown.rs
- integration_tests/src/janus.rs
This removes the `response_headers` configuration option, leaving behind just enough to raise an error if it is specified in a configuration file. This was originally added as a workaround for limitations in ingress-gce, but we no longer need it, and haven't used it in a while. We did not mention this in the sample configuration files under the `docs` directory.
Part of the reason I'd like to get rid of this is that we used to have different config file sections that accepted HTTP headers as lists of name-value pairs (as done here) and as a YAML map (in the case of the now-removed OTLP metadata configuration option, which we dropped in favor of the exporter reading the `OTEL_EXPORTER_OTLP_HEADERS` environment variable). Dropping this configuration option will give us a fresh start when it …
> Remove response_headers configuration option

- Cargo.lock
- Cargo.toml
This bumps the version on the main branch. I plan to cut a release manually, in order to include a note about #2971.
> Bump version to 0.7.3

- aggregator/src/aggregator/collection_job_driver.rs
- aggregator/src/binaries/collection_job_driver.rs
- aggregator/tests/integration/graceful_shutdown.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/models.rs
- aggregator_core/src/datastore/tests.rs
- core/src/test_util/mod.rs
- docs/samples/advanced_config/collection_job_driver.yaml
- docs/samples/basic_config/collection_job_driver.yaml
- integration_tests/src/janus.rs
- interop_binaries/config/collection_job_driver.yaml
This is controlled by a couple of new collection job driver config knobs, which determine the maximum delay between polling attempts & the exponential factor to use. No randomization factor is included as these delays are the _minimum_ delays possible before retry; thundering herd is not a risk because the collection job driver already controls how many collection jobs it tries to step at once.
Also, make min_collection_job_retry_delay optional (along with the new collection job driver configuration options).
> Exponential backoff for collection job polling.

- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/batch_creator.rs
- aggregator/src/aggregator/garbage_collector.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/tests.rs
- aggregator_core/src/query_type.rs
These marked batches will no longer be considered when generating aggregation jobs in the future; this is a performance optimization which will be especially impactful when there are many outstanding_batches, which might occur if the collector falls behind in collection.
> aggregation_job_creator: mark filled outstanding batches.

- collector/src/lib.rs
Some HTTP servers (*cough* GCP Load Balancer) require Content-Length for POST requests, even if the body is empty.
This became apparent because reqwest no longer sends this header https://github.com/seanmonstar/reqwest/commit/68a3f5803b03393938c39a3794a5a9e5f5264796.
> collector: Set Content-Length when polling collection jobs

- integration_tests/tests/integration/daphne.rs
- integration_tests/tests/integration/divviup_ts.rs
- integration_tests/tests/integration/in_cluster.rs
- integration_tests/tests/integration/janus.rs
- integration_tests/tests/integration/main.rs
The in-cluster integration tests failed with Janus 0.7.2, because kube-client 0.90.0 both uses rustls 0.23, and enables the `aws-lc-rs` and `ring` features together. Thus, we need to set a default crypto provider before calling into `kube`. I went ahead and did so in all tests in `janus_integration_tests`.
> Initialize rustls provider in integration tests

- Cargo.lock
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/tests.rs
`Transaction::get_unaggregated_client_reports_for_task` took a `vdaf: &A` parameter that isn't actually used. Deleting that lets us remove some generics and trait bounds from the method, which probably emits less code. Curiously, this didn't trip any unused parameter warnings. I think this is because we put a `tracing::instrument` annotation on the method, which must generate code that uses that parameter.
> Remove unused parameter from `Transaction` method

- integration_tests/src/daphne.rs
This adds a fallback to use the `latest` tag when a container image is specified without a tag in the Daphne integration test module. The two other places where we parse image names already do the same thing.
> Add ":latest" tag fallback in Daphne module

- Cargo.lock
- integration_tests/tests/integration/in_cluster.rs
Supports https://github.com/divviup/divviup-api/issues/291.
Also updates divviup-client to 0.2.1 to get client support.
This is more or less a smoke test, since the actual time bucketing is not really exercised. I will leave that for a continuous load test.
> Add integration test for time-bucketed fixed size

- aggregator/src/aggregator.rs
Previously, if multiple requestors concurrently retrieved the same task from the task aggregator cache, we would query the DB for the task for each requestor.
Now, we use an additional layer of per-task locking so that, in the concurrent-requestor scenario, one requestor will read the task from the DB, and the remaining requestors will wait on that requestor's value.
> Task aggregator cache: remove redundant reads on concurrent requests.

- .github/workflows/ci-build.yml
- .github/workflows/push-docker-images-release.yml
- Dockerfile
- README.md
- aggregator/src/binaries.rs
- aggregator/src/binaries/aggregator.rs
- aggregator/src/binaries/garbage_collector.rs
- aggregator/src/main.rs
- aggregator/tests/integration/graceful_shutdown.rs
- docker-bake.hcl
- docs/DEPLOYING.md
- docs/samples/advanced_config/garbage_collector.yaml
- docs/samples/basic_config/garbage_collector.yaml
This adds a new subcommand that just does garbage collection, as an alternative to enabling garbage collection in the aggregator subcommand. Since we are now building one multicall-enabled binary, this is effectively free. This new subcommand and Docker image is intended to make our deployment simpler by removing the need for providing aggregator configuration to a deployment that is only responsible for garbage collection. However, I figure we'll likely wait on making that change until we decommission all older versions of Janus. I updated the deployment documentation to mention that both the aggregator and garbage collector components can do garbage collection.
I also noticed that our garbage collector task does not shut down upon SIGTERM, so I updated the aggregator graceful …
> Add GC subcommand

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
This adds a couple more tracing spans around VDAF preparation in the leader case of multi-round preparation, and renames all such spans so they have unique names.
> Update VDAF preparation tracing spans

- Cargo.toml
- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/taskprov_tests.rs
- collector/src/lib.rs
- core/Cargo.toml
- core/src/dp.rs
- core/src/vdaf.rs
- integration_tests/src/client.rs
- integration_tests/tests/integration/common.rs
- interop_binaries/Cargo.toml
- interop_binaries/src/commands/janus_interop_client.rs
- interop_binaries/src/commands/janus_interop_collector.rs
- messages/Cargo.toml
- tools/src/bin/collect.rs
This closes #2956. I changed the aggregator and collector to use `ParallelSum` throughout, because it doesn't matter there. (The multithreading feature only affects the gadget's `call_poly()` method, which is only used during proof generation when sharding) I changed some client callers in integration tests and the interop containers to use `ParallelSumMultithreaded`, because those can be sped up. I also made a few impl blocks generic over `ParallelSumGadget`.
> Use rayon VDAF in client, not aggregator/collector

- aggregator/src/binaries/janus_cli.rs
- aggregator/src/binary_utils.rs
- aggregator/src/config.rs
- aggregator/src/main.rs
- aggregator/src/metrics.rs
- aggregator/src/metrics/tests.rs
- aggregator/src/metrics/tokio_runtime.rs
- docs/samples/advanced_config/aggregation_job_creator.yaml
- docs/samples/advanced_config/aggregation_job_driver.yaml
- docs/samples/advanced_config/aggregator.yaml
- docs/samples/advanced_config/collection_job_driver.yaml
- docs/samples/advanced_config/garbage_collector.yaml
- docs/samples/advanced_config/janus_cli.yaml
- integration_tests/src/janus.rs
- interop_binaries/src/bin/janus_interop.rs
- interop_binaries/src/commands/janus_interop_aggregator.rs
- interop_binaries/src/commands/janus_interop_client.rs
- interop_binaries/src/commands/janus_interop_collector.rs
This implements #2968. I've held off on changing the build configuration of our Dockerfiles yet, pending review and discussion. Here's sample output from the new metrics.
```
tokio_io_fd_count{otel_scope_name="tokio-runtime-metrics"} 7
tokio_io_fd_deregistered_total{otel_scope_name="tokio-runtime-metrics"} 0
tokio_io_fd_registered_total{otel_scope_name="tokio-runtime-metrics"} 7
tokio_io_ready_events_total{otel_scope_name="tokio-runtime-metrics"} 30
tokio_noop_total{otel_scope_name="tokio-runtime-metrics"} 37
tokio_park_total{otel_scope_name="tokio-runtime-metrics"} 89
tokio_queue_depth{queue="blocking",otel_scope_name="tokio-runtime-metrics"} 0
tokio_queue_depth{queue="injection",otel_scope_name="tokio-runtime-metrics"} 0
tokio_queue_depth{queue="local",worker="0",otel_scope_name="tokio-r …
```
> Add Tokio runtime metrics

- Cargo.lock
- Cargo.toml
> Update trillium-opentelemetry to 0.7.0, 0.6 backport

- Cargo.lock
- Cargo.toml
> Update trillium-opentelemetry to 0.7.0, 0.5 backport

- Cargo.lock
- Cargo.toml
Dependabot is failing to update this and reporting `update_not_possible`. The main change in 0.7.0 for our purposes is that the server.address and server.port metric attributes are now opt-in. We should keep them off because these attributes are populated from request headers, and Janus is expected to be a public-facing HTTP server. (currently we get a lot of junk values for server.address)
> Update trillium-opentelemetry to 0.7.0

- README.md
As far as I can tell cargo build does not call docker and I am able to build on macOS without issue.
> README: remove docker requirement

- Cargo.lock
- Cargo.toml
- aggregator/Cargo.toml
- aggregator/src/aggregator.rs
- aggregator/src/aggregator/report_writer.rs
- aggregator/src/binaries/aggregator.rs
- aggregator/src/cache.rs
- aggregator/tests/integration/graceful_shutdown.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/task.rs
- core/src/time.rs
- integration_tests/src/janus.rs
Supports https://github.com/divviup/divviup-api/issues/862. Closes https://github.com/divviup/janus/issues/238.
This attaches a lifetime to entries in a TaskAggregatorCache, and uses that lifetime to evaluate whether to use the entry or not. I've also added an optimization for the non-taskprov use-case where we are allowed to cache None results for some time. Please review this code and its tests carefully, since it's somewhat complex.
> Task cache invalidation

- .github/workflows/ci-build.yml
- integration_tests/src/client.rs
- integration_tests/tests/integration/divviup_ts.rs
The integration tests need a small fix in how they handle Prio3Count. Due to how the generics work out, we are currently relying on `<bool As Display>`, when we should be sending `"0"` or `"1"`. See https://divergentdave.github.io/draft-dcook-ppm-dap-interop-test-design/draft-dcook-ppm-dap-interop-test-design.html#table-3.
> Error: measurement is not a valid base 10 integer (was 'true')
> Re-enable divviup-ts integration tests

- aggregator/src/binaries/janus_cli.rs
This initializes the default rustls provider in another unit test. I ran into one such issue in #3063 when running one unit test in isolation. To find this missing initialization, I exhaustively ran all tests each in their own process, with the following Python script. (I pivoted from Bash once I realized I needed a directory from each JSON object as well as a compiled executable)
```python
#!/usr/bin/env python3
import json
import os.path
import subprocess
cargo_output = subprocess.check_output([
"cargo",
"test",
"--all-targets",
"--no-run",
"--message-format=json",
])
for cargo_line in cargo_output.decode("utf-8").splitlines():
message = json.loads(cargo_line)
if message["reason"] != "compiler-artifact":
continue
if not message["profile"]:
continue
if not message["profile"]["test"]: …
```
> Initialize default rustls provider in another test

- .github/workflows/ci-build.yml
- Cargo.toml
- docker-bake.hcl
- xtask/src/main.rs
This changes the profile we use to compile interop containers in tests, from `small` to `ci`. This results in an increase in layer sizes, and thus cache usage, and a huge speedup in compile time. I think this effect is primarily attributable to changing `opt-level` from `"z"` to `0`.
The total size of all Docker stages increased from 5397MiB to 5724MiB. The two chief contributors are the `builder-aggregator` and `final` stages from `Dockerfile.interop_aggregator`, which grew by 158MiB and 136MiB. The relative increase in the `final` stages of both Dockerfiles is large, at 41% and 141%, but note that the size of the final stage doesn't have a big impact anymore, since we are no longer embedding it in later compilations.
Locally, compilation time for the various layers improved by 2x to 6x, …
> Use ci profile in interop containers

- Cargo.lock
- core/Cargo.toml
- core/src/http.rs
Closes https://github.com/divviup/janus/issues/3107. The `bearer` part is now case insensitive. Add some basic tests.
I also allow whitespace between `bearer` and the token. The `1*SP` part of the grammar, IIUC, indices one or more whitespace:
```
Authorization = credentials
credentials = auth-scheme [ 1*SP ( token68 / #auth-param ) ]
```
> Relax constraints on bearer token format

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/error.rs
- aggregator/src/aggregator/http_handlers.rs
This will be very helpful when we have requests which timeout, which is presented to Janus as a client disconnect. Otherwise, we would continue processing the request until it is complete.
Update Helper aggregation methods, which use rayon to parallelize processing, to respect cancellation. Specifically, the `receiver` will be dropped, causing the producer's `sender` to return a SendError, which will cause `try_for_each_with` to stop processing.
> Implement cancellation on disconnect.

- Cargo.lock
- README.md
- aggregator/Cargo.toml
- aggregator/src/aggregator.rs
- aggregator/src/binaries/aggregator.rs
- aggregator/src/diagnostic.rs
- aggregator/src/lib.rs
- aggregator/tests/integration/graceful_shutdown.rs
- docs/samples/advanced_config/aggregator.yaml
- integration_tests/src/janus.rs
When we detect that an aggregation job ID is being re-used, we check that the incoming request matches whatever request we previously saw, and reject it with `Error::ForbiddenMutation`, which is rendered as HTTP 409 Conflict.
We now record an event when this occurs for aggregation job initialization. The event contains the expected request hash, the incoming request's hash and the list of `ReportMetadata`s for both.
Because the resulting event object is quite large, it gets written to a file, created under the directory specified in the `log_forbidden_mutations` option.
~The event is logged in a new span `aggregation_job_init_forbidden_mutation_span` at the DEBUG level. This event will be logged if a suitable filter is set up. For example, running Janus with `RUST_LOG=debug` or a …
> Log agg job init forbidden mutations.

- aggregator/src/aggregator.rs
This was left as a placeholder during testing, instead of plumbing through the config. Fixes an issue where the task cache refreshes too often.
> Fully plumb through cache TTL config

- aggregator/src/aggregator.rs
This will considerably reduce the computational cost of repeated requests, at the cost of an additional (read-only) DB transaction per aggregation initialization.
> Helper agg init: check for repeated request before VDAF computations.

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/aggregation_job_writer.rs
- aggregator/src/aggregator/error.rs
- aggregator/src/aggregator/http_handlers.rs
This will be very helpful when we have requests which timeout, which is presented to Janus as a client disconnect. Otherwise, we would continue processing the request until it is complete.
Previously, we used a rayon threadpool for aggregation computations, but the computations within the handling of a single aggregation job were still serialized. Now, we use a parallel iterator for handling each report share in turn, allowing the VDAF evaluations to be performed in parallel. The Helper methods are also updated such that the parallel computations respect cancellation. Specifically, the `receiver` will be dropped on cancellation, causing the producer threads' `sender` to return a `SendError` when they attempt to send, which will cause `try_for_each_with` to stop processing, which will …
> Implement cancellation on disconnect, & parallelize Helper aggregation computations.

- aggregator/src/metrics.rs
This changes the histogram boundaries we use on request and response size histograms. I chopped off 64MiB at the top end, and changed the spacing to be uniformly logarithmic, instead of quadrupling on the low end and doubling on the high end. The net change is five more buckets, from 12 to 17. Inspired by https://github.com/divviup/janus-ops/pull/1754#issuecomment-2116397960.
> Adjust histogram buckets for request/response size

- aggregator/build.rs
This adds a directive to build.rs telling the compiler to expect the `tokio_unstable` config flag. This prevents a warning in nightly currently.
> Add check-cfg directive to build script

- aggregator_core/src/datastore.rs
Previously, a datastore::Error::User would have been added to our metrics as an "error_other". But returning a user error from a database transaction is, from the POV of the database code, a perfectly successful way to terminate a transaction. So we treat these errors as a success.
> Do not treat user errors as DB errors.

- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/tests.rs
This metric is currently increasing too fast, because it is counting the number of `batch_aggregations` rows deleted. I made the relevant test more robust by adding more `batch_aggregations` rows, and then changed the query to return the cardinality of the `batches_to_delete` CTE. Here's what the plan looks like, FWIW.
`postgres=> EXPLAIN WITH batches_to_delete AS (SELECT batch_identifier, aggregation_param FROM batch_aggregations WHERE task_id = 14 GROUP BY batch_identifier, aggregation_param HAVING MAX(UPPER(COALESCE(batch_interval, client_timestamp_interval))) < '2024-05-08 21:01:18.631912+00'::timestamp LIMIT 50), deleted_outstanding_batches AS (DELETE FROM outstanding_batches USING batches_to_delete WHERE task_id = 14 AND outstanding_batches.batch_id = …
> Fix `janus_gc_deleted_batches_total`

- aggregator/src/aggregator/aggregate_init_tests.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_init.rs
- core/src/http.rs
This is not to the RFC, but we are observing this behavior in a deployment.
> Accept repeated, duplicate Authorization headers as one.

- aggregator/src/aggregator/aggregate_init_tests.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_init.rs
- aggregator/src/aggregator/http_handlers/tests/collection_job.rs
- aggregator/src/aggregator/problem_details.rs
- aggregator/src/aggregator/taskprov_tests.rs
Previously, we were returning 400 Bad Request, likely based on the following text from the DAP specification:
> This document uses the verbs "abort" and "alert with [some error message]" to describe how protocol participants react to various error conditions. This implies HTTP status code 400 Bad Request unless explicitly specified otherwise.
...but the authorization section of the spec does not list an authorization error as an "abort", and 401 Unauthorized is a much more common response code for authorization errors.
> Return HTTP 401 Unauthorized for authorization errors.

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/aggregation_job_writer.rs
- aggregator/src/metrics.rs
This is the first part of #3165. It adds a new histogram metric to supersede `janus_report_aggregation_success_counter`, but with additional labels for VDAF type and size buckets. I set the "dimension" to 1 for Prio3Count, "bits" for Prio3Sum, "length" for Prio3Histogram, "length * bits" for Prio3SumVec, etc. Here's some sample output.
```
janus_aggregated_report_share_vdaf_dimension_bucket{type="Prio3SumVecField64MultiproofHmacSha256Aes128",otel_scope_name="janus_aggregator",le="1"} 0
janus_aggregated_report_share_vdaf_dimension_bucket{type="Prio3SumVecField64MultiproofHmacSha256Aes128",otel_scope_name="janus_aggregator",le="4"} 0
janus_aggregated_report_share_vdaf_dimension_bucket{type="Prio3SumVecField64MultiproofHmacSha256Aes128",otel_scope_name="janus_aggregator",le="16"} 0 …
```
> Add histogram of report shares by VDAF parameters

- integration_tests/tests/integration/in_cluster.rs
We changed the return code to 403 in https://github.com/divviup/janus/pull/3162, but this test was hard-coded to look for 400.
> Fix rate limit integration test to accept any client error

- .github/workflows/ci-build.yml
- Cargo.lock
- Cargo.toml
- client/Cargo.toml
- client/src/lib.rs
- client/src/tests/mod.rs
- client/src/tests/ohttp.rs
Adds support for uploading reports to the Leader via OHTTP.
> `janus_client`: Uploads over OHTTP

- integration_tests/Cargo.toml
- integration_tests/src/client.rs
- integration_tests/src/lib.rs
- integration_tests/tests/integration/common.rs
- integration_tests/tests/integration/in_cluster.rs
Add an integration test which configures its `janus_client::Client`s to upload over OHTTP. The OHTTP key configs and gateway are assumed to be adjacent to the leader's DAP API. The test only runs if feature `ohttp` is enabled.
> `integration_tests`: OHTTP report uploads

- aggregator/Cargo.toml
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/http_handlers/tests/report.rs
- aggregator/src/binary_utils.rs
- aggregator/src/metrics.rs
- aggregator/src/metrics/test_util.rs
This PR changes the status code we use for `Error::ClientDisconnected`, for the purposes of our metrics labels, and catches errors when reading request bodies, turning them into `Error::ClientDisconnected` or `Error::BadRequest`. A unit test is included, to send crafted incomplete requests, and check the resulting metrics.
Closes #2515.
> Improve client disconnect handling

- client/src/lib.rs
`janus_client` 0.7.16 failed to build in docs.rs ([1]), because I forgot to add the appropriate `cfg_attr` to that crate, as we do in `janus_core` and `janus_collector`.
[1]: https://docs.rs/crate/janus_client/0.7.16/builds/1234824
> Fix `janus_client` build in docs.rs

- aggregator/src/aggregator/http_handlers/tests/aggregation_job_continue.rs
- aggregator_core/src/datastore.rs
- db/00000000000004_batch_aggregation_gc.down.sql
- db/00000000000004_batch_aggregation_gc.up.sql
Previously, we would need to scan the batch_aggregations table to fulfill batches_to_delete, which was especially painful if there were not enough batches to delete because we would have to scan the entire table to determine that.
Now, we do a quick first pass to determine candidate batches to delete, with the aid of a new index.
> Improve efficiency of collection-artifact GC.

- Cargo.lock
- Cargo.toml
This upgrades all OTel crates. Dependabot did not propose this for the main branch for some reason, it reports `update_not_possible` many times.
> Upgrade to opentelemetry-rust 0.23

- integration_tests/tests/integration/in_cluster.rs
- integration_tests/tests/integration/janus.rs
This changes some string literals so that each integration test gets its own directory when logs are saved.
> Change integration test name arguments

- aggregator_core/src/datastore.rs
- db/00000000000005_global_hpke_keys_last_state_change_at.down.sql
- db/00000000000005_global_hpke_keys_last_state_change_at.up.sql
Supports https://github.com/divviup/janus/issues/2147.
It's generally risky to directly add a NOT NULL column with our usual migration workflow, because older versions of Janus missing application code won't know about the new column.
Work around this by using an intermediate `-infinity` default for the column. This works because `global_hpke_keys` is not frequently used at the moment, so the window of time where someone can insert or modify rows on the old Janus version is low. Even if they do, the worst case is that the key rotator induces an early rotation of the key.
This migration blocks readers while it's applied. However, readers run in a background task to refresh their cache of this table, so it's not a big deal if they're blocked for longer.
> DB migration for key rotator

- Cargo.lock
- Cargo.toml
- aggregator/Cargo.toml
Closes #3209. We stopped using this directly almost a year ago, when we stopped setting the `service.name` resource attribute explicitly in the code, and instead let an SDK resource provider read it from an environment variable. Since then, this crate has been pulled in transitively by `opentelemetry-otlp`, but that stopped depending on it in `opentelemetry-otlp 0.16.0`.
> Fix unused opentelemetry-semantic-conventions dep

- aggregator_core/src/datastore/test_util.rs
On my machine I get intermittent errors like
```
---- binaries::janus_cli::tests::set_global_hpke_key_state stdout ----
thread 'binaries::janus_cli::tests::set_global_hpke_key_state' panicked at /home/inahga/Projects/janus/aggregator_core/src/datastore/test_util.rs:269:78:
called `Result::unwrap()` on an `Err` value: Database(PgDatabaseError { severity: Fatal, code: "53300", message: "sorry, too many clients already", detail: None, hint: None, position: None, where: None, schema: None, table: None, column: None, data_type: None, constraint: None, file: Some("proc.c"), line: Some(357), routine: Some("InitProcess") })
```
when running tests. Bump the number of connections allowed in the test DB.
> tests: allow more client connections in test DB

- deny.toml
ISRG counsel has reviewed the license
(https://opensource.org/license/unicode-license-v3) and deemed it "harmless", so allow it in our `cargo deny` config. This will unblock `url` updates (#3214, #3223).
> Add Unicode license V3 to allow-list

- .github/workflows/ci-build.yml
- integration_tests/src/client.rs
- integration_tests/tests/integration/common.rs
This changes the integration tests to use the same timestamp in all uploaded reports. This removes one potential source of flakiness in the time-bucketed fixed size test, by keeping the reports from getting split into two time buckets.
> Integration test: use same time in all reports

- interop_binaries/src/lib.rs
This lint does us no good, since `INTEROP_CLIENT_IMAGE_BYTES` et. al. are defined as
```rust
const INTEROP_AGGREGATOR_IMAGE_BYTES: &[u8] =
include_bytes!(concat!(env!("OUT_DIR"), "/interop_aggregator.tar.zst"));
```
so if that file is absent at linting time, it will flag.
> Ignore const_is_empty lint

- aggregator/src/bin/janus_cli.rs
- aggregator/src/binary_utils.rs
- integration_tests/tests/integration/daphne.rs
- integration_tests/tests/integration/divviup_ts.rs
- integration_tests/tests/integration/in_cluster.rs
- integration_tests/tests/integration/janus.rs
- integration_tests/tests/integration/main.rs
This PR sets the default rustls crypto provider at various entry points. This is a backport of parts of #2973, #3063, and #3082. This should unblock #3241.
> Set default rustls crypto provider, 0.6 backport

- aggregator/src/aggregator/aggregate_init_tests.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_init.rs
- core/src/http.rs
The issue that led to us accepting this behavior has been fixed. Given that this behavior is not RFC-compliant, we remove it from Janus.
> Stop accepting repeated, duplicate Authorization headers.

- Cargo.lock
- Cargo.toml
- aggregator/Cargo.toml
- aggregator/src/aggregator.rs
- aggregator/src/aggregator/key_rotator.rs
- aggregator/src/binaries.rs
- aggregator/src/binaries/key_rotator.rs
- aggregator/src/lib.rs
- aggregator/src/main.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/models.rs
- aggregator_core/src/datastore/tests.rs
- core/Cargo.toml
- core/src/hpke.rs
- core/src/time.rs
- db/00000000000006_global_hpke_keys_last_state_change_at_drop_default.down.sql
- db/00000000000006_global_hpke_keys_last_state_change_at_drop_default.up.sql
- docs/samples/advanced_config/key_rotator.yaml
- docs/samples/basic_config/key_rotator.yaml
- messages/src/lib.rs
Supports https://github.com/divviup/janus/issues/2147.
Introduces the `key_rotator`, which is a utility for managing the lifecycle of global HPKE keys. It will bootstrap keys, and rotate them according to the rotation policy in the config.
Keys are unique by their HPKE ciphersuite. For each ciphersuite, a key is run through the pending->active->expired->deleted lifecycle. It is permissive of some manual operator changes, e.g. if a manual key rotation needs to be executed through janus_cli or the aggregator API.
In this iteration, it runs as a standalone binary for use in a cronjob. It is suitable for deployment in our environments, including taskprov ones. A future PR will add support for BYOH deployments by letting the `aggregator` process run the key rotator.
> Key rotator

- aggregator/src/binaries/aggregator.rs
- aggregator/tests/integration/graceful_shutdown.rs
- docs/samples/advanced_config/aggregator.yaml
- integration_tests/src/janus.rs
Stacked on https://github.com/divviup/janus/pull/3136. Supports https://github.com/divviup/janus/issues/2147.
Lets the key rotator be run as part of a BYOH all-in-one aggregator deployment, like we support for the garbage collector.
This is not ideal for high-scale deployments, i.e. ours, because this effectively serializes the startup of Janus due to the exclusive lock taken by the key rotator.
> key rotator: allow running it as part of aggregator process

- integration_tests/tests/integration/in_cluster.rs
This fixes an unused import warning that's showing up in CI tests.
> Fix unused import warning

- aggregator/src/binaries/janus_cli.rs
- docs/samples/advanced_config/aggregation_job_creator.yaml
- docs/samples/advanced_config/aggregation_job_driver.yaml
- docs/samples/advanced_config/aggregator.yaml
- docs/samples/advanced_config/collection_job_driver.yaml
- docs/samples/advanced_config/garbage_collector.yaml
- docs/samples/advanced_config/janus_cli.yaml
- docs/samples/advanced_config/key_rotator.yaml
- docs/samples/tasks.yaml
This PR first adds documentation of more configuration parameters in our sample files. (I think `ignore_unknown_differential_privacy_mechanism` is the only one missing now) It also deletes two now-obsolete parameters (`input_share_aad_public_share_length_prefix` from a past spec compliance workaround and `metadata` under the OTLP exporters) and fixes parameters with incorrect names (either outdated or mistyped). I found the latter issues by hacking in `#[serde(deny_unknown_fields)]` everywhere.
> Document more configuration options and fix errors

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/http_handlers/tests/hpke_config.rs
- aggregator/src/aggregator/key_rotator.rs
- aggregator/src/aggregator/taskprov_tests.rs
- aggregator/src/binaries/aggregator.rs
- aggregator/src/binaries/key_rotator.rs
- aggregator/src/cache.rs
- aggregator/tests/integration/graceful_shutdown.rs
- integration_tests/src/janus.rs
- interop_binaries/config/janus_interop_aggregator.yaml
- interop_binaries/config/key_rotator.yaml
- interop_binaries/config/supervisord.conf
- interop_binaries/setup.sh
Supports https://github.com/divviup/janus/issues/2147.
Introduces a feature flag `require_global_hpke_keys`. When this is enabled:
- The `GlobalHpkeKeypairCache` blocks and retries fetching keys until it gets a list containing at least one active key. This is a bootstrapping case--it allows for the key rotator to do initialization, whether it's running in-process or separately.
- The `/hpke_configs` endpoint unconditionally returns global keys, regardless of the `?task_id` parameter.
Draft, as it needs refactoring and more testing. Looking for feedback on whether the overall approach is sane.
> Feature flag for requiring global HPKE keys

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/aggregation_job_driver/tests.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_init.rs
- aggregator/src/aggregator/http_handlers/tests/hpke_config.rs
- aggregator/src/aggregator/http_handlers/tests/report.rs
- aggregator/src/aggregator/key_rotator.rs
- aggregator/src/aggregator/taskprov_tests.rs
- aggregator/src/binaries/janus_cli.rs
- aggregator/src/cache.rs
- aggregator_api/src/routes.rs
- aggregator_api/src/tests.rs
- aggregator_core/src/datastore/tests.rs
- aggregator_core/src/task.rs
- aggregator_core/src/taskprov.rs
- client/src/tests/mod.rs
- client/src/tests/ohttp.rs
- collector/src/lib.rs
- core/src/hpke.rs
- interop_binaries/src/lib.rs
- tools/src/bin/collect.rs
- tools/src/bin/hpke_keygen.rs
Small refactor. `generate_test_hpke_config_and_private_key_with_id_and_ciphersuite()` is a pretty incredible name, so let's shorten that up by making these functions methods on `HpkeKeypair`.
A lot of ways this could be cleaned up, e.g. builder pattern, `impl Distribution`, but this seemed the most straightforward win to me.
> Replace generate_* functions with methods of HpkeKeypair

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/http_handlers/tests/aggregate_share.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_continue.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_init.rs
- aggregator/src/aggregator/http_handlers/tests/collection_job.rs
- aggregator/src/aggregator/http_handlers/tests/hpke_config.rs
Stacked on https://github.com/divviup/janus/pull/3284.
Changes remaining usage of `setup_http_handler_test()` to using `HttpHandlerTest`.
I think we could make this tighter by using rstest and destructuring the struct inside the function arguments, but that would just be syntactic sugar--not sure if it's worth the effort.
> tests: Use HttpHandlerTest struct instead of returning tuple

- aggregator/src/aggregator/http_handlers/tests/aggregation_job_init.rs
- aggregator/src/aggregator/http_handlers/tests/hpke_config.rs
- aggregator/src/aggregator/upload_tests.rs
- aggregator/src/cache.rs
This fixes some flaky tests I found. Common themes:
- Some more tests that assume an HPKE config ID is unused needed to be updated to take the initial global HPKE key into account.
- `put_global_hpke_keypair()` does not return `MutationTargetAlreadyExists`, so we can't try to insert a keypair and suppress errors, but we can compare config IDs up front in tests.
- Some of the checks in task cache tests are racy, and they are more likely to fail under high CPU load. I removed or changed these, so we no longer require that the cache reflect a stale value immediately after changing the database. (since sometimes "immediately" comes too late)
> Fix flaky tests

- docs/samples/advanced_config/key_rotator.yaml
These aren't actually the default algorithms. https://github.com/divviup/janus/blob/main/aggregator/src/aggregator/key_rotator.rs#L478
> docs: Incorrect defaults in sample

- Dockerfile.sqlx
This fixes the following warning I saw while building.
> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)
> Fix warning in Dockerfile.sqlx

- docs/samples/advanced_config/key_rotator.yaml
The default was changed to 12 weeks, but the actual value wasn't changed. https://github.com/divviup/janus/blob/main/aggregator/src/aggregator/key_rotator.rs#L470
> docs: Fix sample, again

- collector/src/lib.rs
Give a little bit of love to this doccomment. Suggest use of the `PrivateCollectorCredential` instead of bringing in the unstable `janus_core`. Also provide an example of using a fixed size query.
> collector: Refresh example in doccomment

- aggregator/src/aggregator/key_rotator.rs
- aggregator/src/binaries/aggregation_job_creator.rs
- aggregator/src/binaries/aggregation_job_driver.rs
- aggregator/src/binaries/aggregator.rs
- aggregator/src/binaries/collection_job_driver.rs
- aggregator/src/binaries/garbage_collector.rs
- aggregator/src/binaries/janus_cli.rs
- aggregator/src/binaries/key_rotator.rs
- aggregator/src/config.rs
- aggregator/src/metrics.rs
- aggregator/src/trace.rs
- core/src/hpke.rs
This changes all config-related deserialization routines to throw an error upon seeing unexpected fields, rather than ignoring them. This should be mentioned in the next release notes.
> Reject unknown fields in configuration files

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_writer.rs
Previously, we copied report share data into the transaction callback (re-copying it on transaction retry). Notably, this required us to keep two copies of the output shares in memory. This was done to allow modification of the report aggregations based on information retrieved from the datastore, i.e. if the report was replayed.
Now, we remove the copy by passing an Arc of the relevant data into the transaction callback. Modification of the report aggregation is implemented via a Cow, which will be borrowed from the data in the Arc in the common case of no modification. The aggregation job writer is augmented with the ability to accept report aggregations already stored in a Cow, and is taught to be smart enough not to double-wrap Cow around its already-Cow'ed internal state.
Closes …
> Helper agg init: remove copy of report share data.

- aggregator/src/binaries/aggregator.rs
Bug: the key rotator future was being spawned too late. When bootstrapping a new Janus instance, we need the key rotator future to be spawned before we invoke `aggregator_handler()`, as the latter function blocks awaiting a HPKE key to be present.
Supports https://github.com/divviup/janus/issues/2147
> key rotator: Fix bringup ordering when running in-process

- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/collection_job_driver.rs
- core/src/retries.rs
Transient HTTP Client errors were causing an aggregation/collection job to immediately be abandoned. Extend `is_retryable_error()` to cover client errors. See https://docs.rs/reqwest/latest/reqwest/struct.Error.html for the list of error kinds.
> Retry on leader -> helper client errors

- client/src/lib.rs
This removes a large byte slice from a tracing span's field.
> Skip logging request_body in upload_with_ohttp

- aggregator/src/aggregator/http_handlers/tests/collection_job.rs
- aggregator/src/aggregator/http_handlers/tests/hpke_config.rs
- aggregator_api/src/tests.rs
I updated my nightly toolchain recently and got a number of lints saying "the borrowed expression implements the required traits". This PR fixes them by eliminating unnecessary borrows in tests.
> Fix nightly Clippy warnings

- Dockerfile
- Dockerfile.sqlx
This fixes the following warning message.
>  - LegacyKeyValueFormat: "LABEL key=value" should be used instead of legacy "LABEL key value" format
> Fix warnings in Dockerfiles

- aggregator/src/metrics/tokio_runtime.rs
This updates the exporter for Tokio runtime metrics for various external changes. The latest version of Tokio renamed one method and added three, I added `spawned_tasks_count()` but skipped the thread ID and "park/unpark count".
> Update Tokio runtime metrics

- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/tests.rs
Fixes #3323.
Track the number of FINISHED report_aggregations from `batch_aggregations.report_count`. This allows us to account for GC, since `batch_aggregations` are not sensitive to GC.
I don't think this is racy. The only possible race I can think of: If an aggregation job is in flight, there must be an accompanying report_aggregations row, as generated by the job creator. That row will be captured in `max_size`. Anyone else have thoughts?
This passes the regression test in https://github.com/divviup/janus/pull/3324.
> fix: Count batch size via batch_aggregations rather than report_aggregations

- aggregator_core/README.md
- aggregator_core/src/datastore/test_util.rs
Makes it easier to inspect query plans while working locally. These query plans do have to be taken with a grain of salt, because they're always running against an empty database and with `enable_seqscan=false`, so they're not entirely representative.
We dump to stdout because the output from tracing is fairly incomprehensible, since each node of the query plan is on its own tracing event.
> aggregator_core: Allow dumping query plans to stdout

- aggregator/src/aggregator/aggregation_job_driver/tests.rs
- aggregator/src/aggregator/collection_job_tests.rs
- aggregator/src/aggregator/http_handlers/tests/collection_job.rs
- aggregator_core/src/task.rs
This adds a validation that `min_batch_size` is not zero. Without this, we can wind up taking this code path in the collection job driver: https://github.com/divviup/janus/blob/3258350fabbd6b1be8ad48637d7fbdd381893742/aggregator/src/aggregator/aggregate_share.rs#L98-L101
The following simulation test input reproduces this, based on an automatically-generated input.
```rust
Input {
is_fixed_size: true,
config: Config {
time_precision: Duration::from_seconds(3600),
min_batch_size: 0,
max_batch_size: Some(255),
batch_time_window_size: None,
report_expiry_age: None,
min_aggregation_job_size: 1,
max_aggregation_job_size: 76,
},
ops: Vec::from([
Op::Upload {
report_time: Time::from_seconds_since_epoch(1700000903),
count: 13,
},
Op::AggregationJobCreator,
Op::AggregationJobDriverResponseError, …
```
> Add validation that min_batch_size is nonzero

- aggregator_core/src/datastore/test_util.rs
This mounts a tmpfs volume into test database containers, over where the Postgres data directory will be. Closes #3359. I saw the following runtime improvements locally.
Tests | Before | After
-------|-----------|-----------
All | 2m57s | 2m25s
`-p janus_aggregator --lib` | 82s | 68s
`-p janus_integration_tests --test integration` | 29s | 24s
> Use tmpfs in database container

- aggregator_core/src/datastore/test_util.rs
This is a follow-up to #3358, which was not actually deleting databases. First, we need to fix the SQL statement. The database name is an identifier, not a string, so we can't template it in as a parameter. This was producing the following error, which was being intentionally swallowed to handle container deletion races.
```
2024-08-09 19:41:26.520 UTC [30587] ERROR:  syntax error at or near "$1" at character 15
2024-08-09 19:41:26.520 UTC [30587] STATEMENT:  DROP DATABASE $1
```
Beyond that, we can't drop the database that the connection is using, so we have to spin up a fresh connection to the `postgres` database.
```
2024-08-09 19:52:39.758 UTC [843] ERROR:  cannot drop the currently open database
2024-08-09 19:52:39.758 UTC [843] STATEMENT:  DROP DATABASE …
```
> Ephemeral database cleanup followup

- docs/DEVELOPMENT.md
This style preference has come up a few times, e.g. https://github.com/divviup/janus/pull/3029#discussion_r1572731209.
> docs: Prefer Arc::clone(&arc) instead of arc.clone()

- aggregator/src/aggregator/aggregate_init_tests.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/collection_job_tests.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_init.rs
- aggregator/src/aggregator/http_handlers/tests/hpke_config.rs
- aggregator/src/aggregator/http_handlers/tests/report.rs
- aggregator/src/aggregator/taskprov_tests.rs
- aggregator/src/binaries/aggregator.rs
- aggregator/src/metrics/tests/prometheus.rs
- aggregator/tests/integration/graceful_shutdown.rs
- docs/samples/advanced_config/aggregator.yaml
- integration_tests/src/janus.rs
- integration_tests/tests/integration/simulation/setup.rs
Stacked on https://github.com/divviup/janus/pull/3369. Supports https://github.com/divviup/janus/issues/3181.
I attached a shared queue to the aggregate init and continue handlers, and plumbed through configuration to a flag `helper_request_queue`. These are our most expensive handlers. Queuing them allows servicing of `/hpke_configs` even if the server is overloaded.
I refactored the `aggregator_handler*` functions into a rough builder pattern.
> Feature flag for queuing of expensive helper requests

- Cargo.lock
> Update bytemuck off of yanked version

- Cargo.lock
- aggregator/Cargo.toml
- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregate_init_tests.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/collection_job_tests.rs
- aggregator/src/aggregator/error.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_init.rs
- aggregator/src/aggregator/http_handlers/tests/hpke_config.rs
- aggregator/src/aggregator/http_handlers/tests/report.rs
- aggregator/src/aggregator/queue.rs
- aggregator/src/aggregator/taskprov_tests.rs
- aggregator/src/binaries/aggregator.rs
- aggregator/src/metrics/tests/prometheus.rs
- aggregator/tests/integration/graceful_shutdown.rs
- docs/samples/advanced_config/aggregator.yaml
- integration_tests/src/janus.rs
- integration_tests/tests/integration/simulation/bad_client.rs
- integration_tests/tests/integration/simulation/setup.rs
Supports https://github.com/divviup/janus/issues/3181.
Introduces functionality for LIFO queueing certain request handlers. This is done independently of the request handlers themselves, i.e. any handler could be queued by wrapping them in a `queued_lifo()` function.
This code is not plumbed through anything production, yet, to keep this PR small. I will do so in a future PR. See tests for the expected usage of the code.
> Backpressure by bounded request queueing

- .github/dependabot.yml
This preemptively ignores the most recent OTel release in Dependabot, since Prometheus isn't supported for now.
> Ignore opentelemetry-rust 0.25

- Cargo.lock
- Cargo.toml
This upgrades deadpool-postgres, which was stuck with "update not possible" in Dependabot.
> Upgrade deadpool-postgres

- Cargo.lock
- Cargo.toml
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator_core/src/datastore/models.rs
This upgrades itertools, which was stuck with "update not possible" in Dependabot. Note that `group_by()` has been deprecated, in favor of the renamed `chunk_by()`.
> Upgrade itertools

- Cargo.lock
- Cargo.toml
This upgrades three trillium crates that were stuck with "update not possible" in Dependabot.
> Upgrade trillium crates

- Cargo.lock
- Cargo.toml
This upgrades console-subscriber, which was stuck with "update not possible". This upgrade removes old versions of tonic and http from the dependency tree.
> Upgrade console-subscriber

- Cargo.lock
- Cargo.toml
This upgrades trillium-prometheus to the new version I just published. This cleans up a duplicate version of trillium-router.
> Upgrade trillium-prometheus

- integration_tests/tests/integration/simulation/run.rs
This adds a check to the simulation tests that the report count in collection results is consistent with the aggregate result. This leverages the "bad client" implementation to confirm that we correctly exclude invalid report shares from "report_count".
> Check report count in simulation tests

- .github/dependabot.yml
The OpenTelemetry Rust crates are releasing on a more frequent cadence on the road to 1.0. This PR ignores this week's release, and future pre-1.0 releases.
> Ignore range of opentelemetry-rust versions

- .github/workflows/ci-build.yml
This adds a workaround for #3178 to CI. The GitHub Actions workers are now using Ubuntu 24.04 as well. This workaround can be removed once the tests are rewritten to be part of `cargo xtask test-docker`.
> CI: Enable unprivileged user namespaces

- Dockerfile
> LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 40)
> Fix Dockerfile warning

- aggregator/src/aggregator/collection_job_tests.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/http_handlers/tests/collection_job.rs
- aggregator/src/aggregator/http_handlers/tests/report.rs
- client/src/lib.rs
- client/src/tests/mod.rs
- client/src/tests/ohttp.rs
- collector/src/lib.rs
- integration_tests/tests/integration/daphne.rs
- integration_tests/tests/integration/divviup_ts.rs
- integration_tests/tests/integration/simulation/bad_client.rs
Specifically:
* Use POST rather than PUT for report uploads.
* Use GET rather than POST for collection job polling.
> Update HTTP verbs for DAP-13.

- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/http_handlers/tests/report.rs
This is required by the spec since DAP-04, but was missed previously. I think it is likely that clients are effectively just looking for a "success" (i.e. 2xx) status code.
> Upload: switch success response from 200 OK to 201 Created.

- README.md
We don't plan to fix this (in the short term) because Mozilla looks specifically for a 200 OK response from the Leader.
> Add DAP-09 errata for upload response code issue.

- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/aggregation_job_driver/tests.rs
- aggregator/src/aggregator/batch_creator.rs
- aggregator/src/aggregator/collection_job_tests.rs
- aggregator/src/aggregator/garbage_collector.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_init.rs
- aggregator/src/aggregator/http_handlers/tests/helper_e2e.rs
- aggregator/src/aggregator/taskprov_tests.rs
- aggregator/src/binaries/janus_cli.rs
- aggregator_api/src/tests.rs
- aggregator_core/src/datastore/tests.rs
- aggregator_core/src/task.rs
- docs/samples/tasks.yaml
- integration_tests/tests/integration/in_cluster.rs
- integration_tests/tests/integration/janus.rs
- integration_tests/tests/integration/simulation/arbitrary.rs
- integration_tests/tests/integration/simulation/model.rs
- integration_tests/tests/integration/simulation/reproduction.rs
- integration_tests/tests/integration/simulation/setup.rs
- interop_binaries/src/commands/janus_interop_aggregator.rs
- interop_binaries/src/lib.rs
- interop_binaries/tests/end_to_end.rs
- messages/src/taskprov.rs
This parameter was removed in DAP-12, and we do not have any reason to keep it as functionality over-and-above what is specified in DAP, so we remove this parameter from Janus. The aggregation job creator will now always create batches which are exactly min_batch_size, matching previous functionality if max_batch_size was unspecified.
> Remove max_batch_size parameter from leader-selected tasks.

- messages/src/lib.rs
- messages/src/tests/aggregation.rs
- messages/src/tests/collection.rs
- messages/src/tests/query.rs
As before, we will (correctly) generate an invalidMessage error if we receive a message with an unknown batch mode, starting from an error generated at the point of parsing the batch mode discriminator byte.
> Update batch mode-specific messages to include a length prefix.

- Cargo.lock
- Cargo.toml
- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregate_init_tests.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/aggregation_job_driver/tests.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_continue.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_init.rs
- aggregator/src/aggregator/test_util.rs
- aggregator_core/src/datastore/tests.rs
- client/src/lib.rs
- collector/src/lib.rs
- core/Cargo.toml
- core/src/hpke.rs
- core/src/lib.rs
- core/src/test_util/mod.rs
- core/src/vdaf.rs
- integration_tests/tests/integration/simulation/bad_client.rs
I currently pin to a specific commit in libprio-rs tracking the VDAF-13 implementation, as the implementation is currently ongoing. I am fairly confident that the only breaking interface changes have already been implemented: there is a new "application context string", which is computed as the concatenation of hte current DAP draft in use & the task ID.
Also, bump the version tag while I'm at it, since I touched it anyway.
> Switch to VDAF-13.

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregate_init_tests.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/aggregation_job_driver/tests.rs
- aggregator/src/aggregator/batch_creator.rs
- aggregator/src/aggregator/garbage_collector.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_continue.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_init.rs
- aggregator/src/aggregator/http_handlers/tests/report.rs
- aggregator/src/aggregator/taskprov_tests.rs
- aggregator/src/aggregator/test_util.rs
- aggregator/src/diagnostic.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/models.rs
- aggregator_core/src/datastore/tests.rs
- client/src/lib.rs
- db/00000000000001_initial_schema.up.sql
- integration_tests/tests/integration/simulation/bad_client.rs
- messages/src/lib.rs
- messages/src/tests/aggregation.rs
- messages/src/tests/upload.rs
...and rename the existing (private) extensions to "private extensions". Per DAP, these extensions can conflict with one another.
> Add support for public extensions.

- Cargo.toml
- aggregator/src/binaries/janus_cli.rs
- aggregator_api/src/routes.rs
- aggregator_core/src/taskprov.rs
- core/src/auth_tokens.rs
- integration_tests/tests/integration/in_cluster.rs
- integration_tests/tests/integration/simulation/proxy.rs
This is, at time of writing, the "stable minus two releases" that Janus supports. Also, clean up a few uses of OnceLock -- mostly to replace with the simpler LazyLock stabilized in 1.80, in one place replacing it with an async mutex as neither OnceLock nor LazyLock were appropriate as the initializing function would be async.
> Bump MSRV to 1.80.

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregate_init_tests.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/aggregation_job_driver/tests.rs
- aggregator/src/aggregator/collection_job_tests.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_continue.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_init.rs
- aggregator/src/aggregator/http_handlers/tests/collection_job.rs
- aggregator/src/aggregator/http_handlers/tests/helper_e2e.rs
- aggregator/src/aggregator/taskprov_tests.rs
- collector/src/lib.rs
- messages/src/batch_mode.rs
- messages/src/lib.rs
- messages/src/tests/aggregation.rs
- messages/src/tests/collection.rs
- tools/src/bin/dap_decode.rs
- tools/tests/cmd/dap_decode.trycmd
Implementation of asynchronous aggregation is forthcoming. With this change, we use the Pending/Finished statuses for aggregation/collection as-specified, but both the Leader & Helper support only synchronous aggregation.
> Message & request changes for async aggregation/collection.

- Cargo.toml
See https://github.com/divviup/janus/pull/3519#issuecomment-2512804503, for the time being, we can only build on 1.81 or later.
> Bump MSRV to 1.81

- deny.toml
This is a backport of #3508 to the release/0.7 branch.
> cargo-deny: ignore instant and derivative unmaintained warnings - 0.7 backport

- Cargo.lock
- aggregator/Cargo.toml
- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/aggregation_job_driver/tests.rs
- aggregator/src/aggregator/batch_creator.rs
- aggregator/src/aggregator/collection_job_driver.rs
- aggregator/src/aggregator/garbage_collector.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_continue.rs
- aggregator/src/aggregator/taskprov_tests.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/models.rs
- aggregator_core/src/datastore/tests.rs
- aggregator_core/src/task.rs
- db/00000000000001_initial_schema.up.sql
This change includes unit tests, but no integration tests -- those will need to come with the Helper async aggregation implementation, as without it we do not have anything to integration test against.
A few implementation notes:
* I renamed the report aggregation states to better match their functionality (IMO).
* If the Helper does not provide a retry-after header, the Leader will poll each "processing" aggregation job (at most) once per minute.
* The retry-after header can specify either a number of seconds, or a specific date. Currently, we only support receiving a number of seconds.
> Implement Leader async aggregation.

- aggregator/src/aggregator/aggregation_job_driver/tests.rs
- aggregator/src/aggregator/test_util.rs
Fixes #3617. The `async_aggregation_job_init_poll_to_finished` test had an incorrect expected value for the task aggregation counter, expecting 0 instead of 1, and most of the time, the test's polling loop happened to run before a background async task incremented the counter. Only under higher CPU load would the counter be incremented first, and then the polling loop would never succeed. This PR fixes the expected counter value (since this unit test expects the aggregation job to be finished during this request) and adds an initial wait of 0.1s before polling the database. The additional wait should make it significantly more likely that counter increments happen before the first poll. I also ran the test suite with a longer initial wait to confirm there weren't any other similar bugs. …
> Fix aggregation job driver test

- Cargo.lock
- Cargo.toml
- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator_api/src/tests.rs
- core/src/dp.rs
- core/src/vdaf.rs
- integration_tests/tests/integration/common.rs
- integration_tests/tests/integration/simulation/bad_client.rs
- interop_binaries/src/commands/janus_interop_client.rs
- interop_binaries/src/commands/janus_interop_collector.rs
- tools/src/bin/collect.rs
This upgrades libprio, so we are now VDAF-interoperable. This includes a change to the field used by Prio3Sum and a change to the XofTurboShake128 seed size.
> Upgrade libprio to alpha prerelease

- Cargo.lock
- Cargo.toml
- aggregator/Cargo.toml
- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/collection_job_driver.rs
- aggregator/src/aggregator/garbage_collector.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/http_handlers/tests/report.rs
- aggregator/src/aggregator/problem_details.rs
- aggregator/src/aggregator/queue.rs
- aggregator/src/binary_utils.rs
- aggregator/src/binary_utils/job_driver.rs
- aggregator/src/config.rs
- aggregator/src/metrics.rs
- aggregator/src/metrics/test_util.rs
- aggregator/src/metrics/tests/prometheus.rs
- aggregator/src/metrics/tokio_runtime.rs
- aggregator/src/trace.rs
- aggregator_api/src/lib.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/lib.rs
- docs/samples/advanced_config/aggregation_job_creator.yaml
- docs/samples/advanced_config/aggregation_job_driver.yaml
- docs/samples/advanced_config/aggregator.yaml
- docs/samples/advanced_config/collection_job_driver.yaml
- docs/samples/advanced_config/garbage_collector.yaml
- docs/samples/advanced_config/janus_cli.yaml
This upgrades to the 0.27 release of opentelemetry-rust. This includes the following changes:
- Various OTel APIs were renamed.
- The `Meter` no longer allows supplying a multi-callback for several instruments. Instead, separate callbacks are registered on each instrument. Additionally, `observe()` can no longer be called on observable gauges, etc.; this method has moved to the argument provided to the instrument's callback.
- Support for the `MetricProducer` trait has been removed. As a result, the (unstable) Tokio poll time histogram has been removed, and the remaining Tokio runtime metrics have been reimplemented with SDK instruments.
- Histogram boundaries can now be set directly on instrument builders. Thus, I have done so and removed our custom `View`.
- `NoopMeterProvider` was …
> Upgrade to opentelemetry-rust 0.27

- aggregator/src/aggregator/taskprov_tests.rs
- aggregator/src/binaries/janus_cli.rs
- aggregator_api/src/routes.rs
- aggregator_api/src/tests.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/tests.rs
- aggregator_core/src/taskprov.rs
Closes #3666. This makes `PeerAggregator::new()` and `PeerAggregatorBuilder::build()` fallible, and adds a couple validation checks.
> Add verification of aggregation mode in PeerAggregator

- Cargo.lock
- deny.toml
> Update janus_messages, remove ignore in deny.toml, 0.7 backport

- Cargo.lock
- deny.toml
This updates a transitive dependency on `janus_messages`, in order to get rid of a dependency on `derivative`, and cleans up the relevant ignore in `deny.toml`. Dependabot cannot update this because it can only handle one version of a crate per workspace.
> Update janus_messages, remove ignore in deny.toml

- Cargo.lock
> Bump crossbeam-channel from 0.5.12 to 0.5.15

- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/aggregation_job_driver/tests.rs
- aggregator/src/aggregator/batch_mode.rs
- aggregator/src/aggregator/collection_job_driver.rs
- aggregator/src/aggregator/error.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/http_handlers/tests/aggregate_share.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_continue.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_init.rs
- aggregator/src/aggregator/http_handlers/tests/collection_job.rs
- aggregator/src/aggregator/problem_details.rs
- aggregator/src/aggregator/taskprov_tests.rs
- messages/src/problem_type.rs
draft-ietf-ppm-dap-15 (forthcoming) will make some changes to the fart problem types defined by DAP.
- `unauthorizedRequest` is gone. We still have `aggregator::Error::UnauthorizedRequest`, but now we construct a problem document with a URN pointing to Divvi Up docs (which will be updated in [133][1].
- `batchQueriedMultipleTimes` is gone, and now instead we are instructed to provide `invalidMessage` if someone tries to change a collection or aggregate share's aggregation parameter. Accordingly we remove `aggregator::Error::BatchQueriedMultipleTimes`.
- `aggregator::Error::MissingTaskId` was not used anywhere except tests.
- We no loner need `DapProblemTypeExt` because all DAP problem types can now be represented as HTTP 400 Bad Request, per DAP's guidance to use the most general possible …
> Harmonize errors with draft-ietf-ppm-dap-15

- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/models.rs
- aggregator_core/src/datastore/tests.rs
...and put_leader_report_aggregation. The condition here was reversed, only allowing a non-expired report aggregation row to be updated by the put operations. In practice, this wasn't a problem, as in application code put_report_aggregation was always paired with put_aggregation_job, and the condition on put_aggregation_job was correct.
> Fixup garbage-collection-check clause of put_report_aggregation.

- .github/workflows/ci-build.yml
- README.md
- core/src/test_util/kubernetes.rs
This upgrades the version of Kind and Kubernetes we test against.
> Upgrade Kind and Kubernetes

- collector/src/lib.rs
This test was taking too long to run for me when I ran it locally. It looks like it's taking around five minutes in CI. I noticed that `max_delay` was still very low, and thus determining `backoff_duration`. Since `backon` accounts for time spent sleeping instead of wall clock time, this increases the number of iterations, and thus the overhead and total time elapsed. I increased `max_delay` to match `min_delay`, and then similarly modified the HTTP request parameters as well.
> Fix collector poll_timing test

- core/src/test_util/kubernetes.rs
In my setup I get a lot of timing errors during runs of `cargo test --profile ci --locked --all-targets --features=prometheus`, and they are all around the automatic teardown of the `kind` cluster:
```
ERROR: failed to delete cluster "janus-ephemeral-bfc0838a": failed to delete nodes: command "docker rm -f -v janus-ephemeral-bfc0838a-control-plane" failed with error: exit status 1
Command Output: Error response from daemon: cannot remove container "/janus-ephemeral-bfc0838a-control-plane": could not kill: tried to kill container, but did not receive an exit event
```
This PR uses `backon` to retry that cluster delete, using the [default 3 tries, 1s between each](https://docs.rs/backon/latest/backon/struct.ConstantBuilder.html) Constant Backoff. 
Note this is our first use of the blocking …
> Use backoff/retry on Kubernetes test `kind cluster delete` operations

- Cargo.lock
- Cargo.toml
- aggregator/src/aggregator/aggregation_job_driver/tests.rs
- aggregator/src/aggregator/collection_job_driver.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/http_handlers/tests/report.rs
- aggregator/src/aggregator/problem_details.rs
- aggregator/src/aggregator/upload_tests.rs
- aggregator/src/binaries/janus_cli.rs
- aggregator/src/binary_utils.rs
- aggregator/tests/integration/graceful_shutdown.rs
- client/src/tests/mod.rs
- client/src/tests/ohttp.rs
- collector/src/lib.rs
- core/Cargo.toml
- core/src/lib.rs
- core/src/retries.rs
- integration_tests/tests/integration/simulation/bad_client.rs
- integration_tests/tests/integration/simulation/quicktest.rs
- integration_tests/tests/integration/simulation/reproduction.rs
- interop_binaries/src/bin/janus_interop.rs
- interop_binaries/tests/end_to_end.rs
- tools/src/bin/collect.rs
This upgrades the testcontainers dependency, and changes feature flags on it and reqwest to use aws-lc-rs more. We now only depend on ring for tokio-postgres-rustls and rustls-platform-verifier. I had to explicitly initialize the rustls crypto provider in more tests, because reqwest only has special handling for there being no installed default crypto provider when its ring feature is enabled.
> Upgrade testcontainers, use aws-lc-rs in more places

- Dockerfile.interop_aggregator
- interop_binaries/config/aggregator.yaml
- interop_binaries/config/supervisord.conf
While looking closely at the aggregator interop test container, I noticed that the key rotator program was failing and restarting repeatedly, because its configuration file was missing. This PR fixes that, reconfigures supervisord to expect the program to successfully exit soon after startup, and disables the key rotator component inside the aggregator program.
> Fix supervisord key rotator program

- core/src/time.rs
This adds tests to both `Interval::merge` and `Interval::merged_with` to ensure the semantics now match expectations.
> Add tests to Interval::merged_with and Interval:merge

- Cargo.lock
- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/error.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/queue.rs
- aggregator/src/cache.rs
- aggregator_api/src/lib.rs
- aggregator_api/src/routes.rs
- collector/Cargo.toml
- collector/src/lib.rs
Recent changes to guarantee aligned times, intervals and durations have prompted us to look closely at some nuanced error handling in Janus. Our error enums generally provide structured variants to represent specific failure modes, but inevitably, we end up with "catch-all" variants like `janus_aggregator::aggregator::Error`'s `Internal` or `BadRequest` which wrap a `String`, an opaque description of whatever went wrong.
Sometimes, that string is a flattened error of some type that occurs so infrequently that we don't think it's worth adding a variant to the error enum. But it's still unfortunate to lose the structure of the error chain. A compromise here is to replace variants like `Internal(String)` with `Internal(Box<dyn std::error::Error>)`. The standard `Error` trait is implemented …
> Use `Box<dyn Error>` as catch-all in error enums

- Cargo.toml
- aggregator/src/aggregator/aggregation_job_driver/tests.rs
- aggregator_core/src/datastore/models.rs
- collector/src/lib.rs
This fixes #3834, and fixes test breakages by moving off of `Interval::from_time()` (see #3827). It also changes various manual implementations so that they start by destructuring their arguments. This uncovered one more missing field in the collector crate.
> Add missing fields to manual PartialEq implementations

- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/batch_creator.rs
- aggregator/src/metrics.rs
This adds a new histogram metric to track the distribution of aggregation job sizes. I also hoisted initialization of existing metrics from `AggregationJobCreator::run()` to `AggregationJobCreator::new()`.
Closes #2730.
> Aggregation job size histogram

- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/batch_creator.rs
- aggregator/src/metrics.rs
This is a backport of #3832. Note that the histogram boundaries are set through different means, since this branch uses an older version of the OpenTelemetry SDK.
> Aggregation job size histogram, 0.7 backport

- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/tests.rs
The last `Interval`-dependent object that isn't doing full Interval time precision validation was `BatchAggregation`, as there were a lot of pieces that needed to be resolved first in https://github.com/divviup/janus/pull/3820 and https://github.com/divviup/janus/pull/3796.
One remaining thing I see to do -- which I could do in this PR -- is to change the `setup_collection_job_acquire_test_case` method in the datastore tests to use a global const `TIME_PRECISION` of 100s like roughly half the tests in this file do, instead of using the default of 8h. But that's another host of little test changes. Comments welcome.
> Enforce interval validation for BatchAggregation jobs

- aggregator/src/aggregator/aggregate_share.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/aggregation_job_init.rs
- aggregator/src/aggregator/aggregation_job_writer.rs
- aggregator/src/aggregator/batch_mode.rs
- aggregator/src/aggregator/report_writer.rs
- aggregator/src/aggregator/taskprov_tests.rs
- aggregator_core/src/batch_mode.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/models.rs
Adopt the supertrait in the remaining parts of the crate where it's appropriate. This one is rather noisier than previous PRs because the most egregious `where` blocks have been expunged already.
We still have some "bare" `prio::vdaf::Aggregator` in the client libraries, but I don't think it'd be appropriate to use `AsyncAggregator` there.
> Move remainder of project to `AsyncAggregator`

- aggregator_core/src/datastore.rs
This changes `Transaction::run_op()` so that it takes a pinned mutable reference to a future, instead of taking the future by value. This is a workaround for rust-lang/rust#62958. Here's the impact of this change according to `RUSTFLAGS=-Zprint-type-sizes`.
```
2368 {async fn body of janus_aggregator_core::datastore::Transaction<'_, janus_core::time::RealClock>::run_op<tokio_postgres::statement::Statement, {async fn body of deadpool_postgres::Transaction<'_>::prepare_cached()}>()} align=8
1 <discriminant>
2367 variant Suspend0
15 <padding>
1160 op (upvar) align=8
8 op_group
8 self (upvar)
2 <padding>
1 coroutine_field9 align=1 type=bool
5 <padding>
8 coroutine_field2 align=8 type=&AtomicBool
1160 __awaitee type={async fn body of deadpool_postgres::Transaction<'_>::prepare_cached()}
1399 …
```
> Pin futures passed to run_op()

- aggregator_core/src/datastore.rs
- db/00000000000008_aggregation_jobs_expresssion_index.down.sql
- db/00000000000008_aggregation_jobs_expresssion_index.up.sql
> Add btree index over aggregation_jobs to help GC, 0.7 backport

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
While investigating another issue, I noticed the following panic in the output of `janus_aggregator`:
```
thread 'tokio-runtime-worker' panicked at <snip>
tried to clone Id(274877906948), but no span exists with that ID
This may be caused by consuming a parent span (`parent: span`) rather
than borrowing it (`parent: &span`).
```
The backtrace pointed me to our usage of the `tracing::info_span` macro. The error message and documentation ([1]) make it clear enough you're meant to use a reference to the parent span and not the value. I audited our usage of `info_span!` and related macros and fixed them all.
[1]: https://docs.rs/tracing/0.1.41/tracing/index.html#using-the-macros
> Use reference to parent span where appropriate

- aggregator_api/src/routes.rs
This raises the tolerable clock skew for tasks newly created via the aggregator API. Five minutes should let us accept reports from most machines with normal clock drift. It is also still small enough that it doesn't raise concerns about long-term data storage trends.
This just targets the release branch. Note that on main, the tolerable clock skew is now set to exactly one time precision. I don't plan to make any change there for now.
> Raise tolerable clock skew set in aggregator API

- .github/dependabot.yml
This tells Dependabot to ignore rand 0.9 on the release/0.7 branch. This should clean up an error message in previous Dependabot logs. Dependabot can't handle the `min_const_gen` Cargo feature going away with the upgrade. We don't want to take this upgrade anyway, since it is not compatible with the libprio-rs version we're using.
> Ignore rand upgrades on 0.7 branch

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregate_share.rs
- aggregator/src/aggregator/collection_job_driver.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_continue.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_init.rs
- aggregator_core/src/batch_mode.rs
When handing a collection job or aggregate share, we want to write lots of batch aggregations rows. Often, the vast majority of these will be empty batch aggregations that exist only to force conflicts with other SQL transactions. Rather than allocating all these empty BAs at once, we now create a `BatchAggregationsIterator` which lazily constructs them. In order to decide whether an empty BA is needed for a given `(batch_identifier, ord)` tuple, the `BatchAggregationsIterator` needs to know what real batch aggregations exist, so it takes ownership of the `Vec<BatchAggregation<_>>` returned by
`CollectableBatchMode::get_batch_aggregations_for_collection_identifier` and yields a unified stream of both real and empty/synthetic BAs.
In order to avoid traversing this iterator multiple times …
> Lazily instantiate empty batch aggregations

- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/aggregation_job_driver/tests.rs
- aggregator/src/aggregator/aggregation_job_init.rs
- aggregator/src/aggregator/collection_job_driver.rs
- aggregator/src/aggregator/collection_job_tests.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/http_handlers/tests/aggregate_share.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_get.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_init.rs
- aggregator/src/aggregator/http_handlers/tests/collection_job.rs
- aggregator/src/aggregator/http_handlers/tests/hpke_config.rs
- aggregator/src/aggregator/http_handlers/tests/report.rs
- aggregator/src/aggregator/taskprov_tests.rs
- client/src/lib.rs
- client/src/tests/mod.rs
- client/src/tests/ohttp.rs
- collector/src/lib.rs
- integration_tests/tests/integration/simulation/bad_client.rs
- messages/src/lib.rs
The `MediaType` trait identifies messages that have an HTTP media type associated with them, intended for use in `content-type` HTTP headers. Various types defined in `janus_messages` already had an associated `MEDIA_TYPE` constant, which is now part of the trait. This means that elsewhere, we can use a trait bound like `prio::codec::Decode + MediaType` to generically check that an incoming message has the desired content-type and then decode it into the desired structure.
> `janus_messages`: introduce `MediaType` trait

- client/src/lib.rs
- client/src/tests/mod.rs
- core/Cargo.toml
- core/src/http.rs
- core/src/http/cached_resource.rs
- core/src/http/cached_resource_tests.rs
Adds a `janus_core::http::cached_resource` module which GETs an HTTP resource and then caches it, honoring the `no-cache` and `max-age` `cache-control` directives. We then use this in `janus_client` to cache HPKE configurations.
Part of #3159
> `janus_client`: cache HPKE configurations

- client/src/lib.rs
- client/src/tests/mod.rs
- client/src/tests/ohttp.rs
- core/Cargo.toml
- core/src/http.rs
- core/src/http/cached_resource.rs
- core/src/http/cached_resource_tests.rs
- messages/src/lib.rs
Adds a `janus_core::http::cached_resource` module which GETs an HTTP resource and then caches it, honoring the `no-cache` and `max-age` `cache-control` directives. We then use this in `janus_client` to cache HPKE configurations and OHTTP keys.
This is a forward-port of #3903, which went into `release/0.7`. The major differences:
- use the `janus_messages::MediaType` trait to figure out the desired media type instead of passing it around as an argument
- cache OHTTP keys as well as HPKE keys
- introduce a `FromBytes` trait and use that in `CachedResource` instead of `prio::codec::Decode` to gracefully handle `Vec<ohttp::KeyConfig`>
- avoid cloning values where possible
Part of #3159
> `janus_client`: cache HPKE and OHTTP keys

- db/00000000000001_initial_schema.up.sql
This updates some comments in the database schema. I noted that `verify_key_init` is encrypted, and fixed the comments of two `peer_aggregator_id` columns.
> Update schema comments

- aggregator/src/aggregator/collection_job_tests.rs
While looking over #3928, I was wondering why the `CollectionJobReq` in the test needs to be in an `Arc` and why the type annotation is needed. Sure enough, we can elide those in the new test as well as in an existing one and the compiler doesn't gripe. Probably left over from a refactor of a more complex test that previously used a database transaction to double check something.
> remove unneeded `Arc` in collection job tests

- aggregator/src/binaries/janus_cli.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/leases.rs
Adds new subcommands to `janus_cli` to enable easily getting information about aggregation and collection jobs and any leases on them.
> `janus_cli`: get aggregation and collection jobs

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/aggregation_job_continue.rs
- aggregator/src/aggregator/aggregation_job_creator.rs
- aggregator/src/aggregator/aggregation_job_driver.rs
- aggregator/src/aggregator/aggregation_job_driver/tests.rs
- aggregator/src/aggregator/aggregation_job_writer.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_continue.rs
- aggregator/src/aggregator/http_handlers/tests/aggregation_job_init.rs
- aggregator_api/src/routes.rs
- aggregator_api/src/tests.rs
- aggregator_core/src/datastore.rs
- aggregator_core/src/datastore/models.rs
- aggregator_core/src/datastore/tests.rs
- db/00000000000009_task_aggregation_counters_failures.down.sql
- db/00000000000009_task_aggregation_counters_failures.up.sql
Expands `TaskAggregationCounter` so that the leader can report the various `PrepareError`s that a helper might indicate during handling of an aggregation job.
Part of #3798
> Per-task counters for helper prep errors

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/collection_job_driver.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/http_handlers/tests/aggregate_share.rs
- aggregator_core/src/datastore.rs
Changes:
- Add DELETE request support at aggregate_shares endpoint for cleanup operations, to comply with DAP-15 section 4.7.4.
- Change the collection job driver to send DELETE to the helper on the next step after the collection job state transitions to Deleted.
> [!NOTE]
> I didn't bother doing the `vdaf_ops_dispatch` business for the DELETE calls, as all the generics were unused, so it saves a bunch of boilerplate (about 80 lines -- I started with them). 
Fixes #3962
> Support aggregate share job deletion

- .github/workflows/make-release.yml
- Dockerfile
- Dockerfile.interop
- Dockerfile.interop_aggregator
- Dockerfile.sqlx
This passes `--locked` to invocations of `cargo install` in Dockerfiles and CI scripts, so that we use the crate's lock file when building and installing binaries. This will avoid surprises from untested dependency versions, such as the now-yanked `cfg-if@1.0.2`, which we ran into earlier today.
> Use `cargo install --locked`

- aggregator/src/aggregator.rs
- aggregator/src/aggregator/error.rs
- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/http_handlers/tests/report.rs
- aggregator/src/aggregator/report_writer.rs
- aggregator/src/aggregator/test_util.rs
- aggregator/src/aggregator/upload_tests.rs
- aggregator_api/src/tests.rs
- aggregator_core/src/datastore/task_counters.rs
- aggregator_core/src/datastore/task_counters_tests.rs
- db/00000000000001_initial_schema.up.sql
Note there's an error response inconsistency between Helper and Leader -- Leader returns ReportRejectionReason::DuplicateExtension while Helper returns ReportError::InvalidMessage (line 235 in aggregation_job_init.rs).
Also note that this adds the telemetry to TaskUploadCounter, but we already have -- completely unused -- DuplicateExtension in TaskAggregationCounter.
Maybe this is putting the rejection in the wrong place for the Leader?
Fixes #3997
> Leader must reject reports with duplicate extensions

- Cargo.lock
- Cargo.toml
- README.md
- core/src/lib.rs
From the [DAP-15 changelog](https://datatracker.ietf.org/doc/html/draft-ietf-ppm-dap-15#name-change-log):
- Specify body of responses to aggregation job GET requests. (https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/651)
-  PR #3630
- Align with RFC 9205 recommendations. (*) (https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/673, https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/683) 
- The most significant changes are to HTTP status codes, which now should be treated as their most general class, and we shouldn't rely on specific codes. As part of #3878, an audit of `send_request_to_helper` shows that the Leader no longer relies on the returned status from the Helper.
- Define consistent semantics for long-running interactions: aggregation jobs, collection jobs and …
> Update wire version and readme to DAP-15

- aggregator/src/aggregator/http_handlers.rs
- aggregator/src/aggregator/taskprov_tests.rs
The problem documents served to the leader when a Janus helper opts out of a taskprov task will now include an unstructured description of the reason.
> Taskprov: Plumb opt-out reason into opt-out errors
