divviup/janus

janus_server/Cargo.toml, janus_server/src/lib.rs, janus_server/src/message.rs
This matches what is in the draft-interop-target branch of the PPM
specification at d8c6677, and was heavily inspired by the message
definitions throughout the ppm-prototype.
=> PPM protocol messages with serialization/deserialization support.

janus_server/src/message.rs
This fixes a copy-paste error.
=> Fix AggregationJobId docstring

janus_server/src/message.rs
This field is an HMAC-SHA256 of the remainder of the message, as with
other tag fields. This field was added in a recent commit against the
interop target PR.
=> Add AggregateShareReq.tag field.

janus_server/src/message.rs
These were added to the PPM specification by ppm-specification commit
29ce456.
=> Add AggregateShareReq.{report_count,checksum} fields.

db/schema.sql
I am fairly confident that this is shaped like a usable DB schema,
though of course we'll likely need to make changes as we move forward
through implementation. I am probably underspecifying the indexes: I
created a few that I am certain we'll use, but I think we should
otherwise create indexes as needed.
=> Initial Postgres DB schema.

janus_server/Cargo.toml, janus_server/src/bin/aggregator.rs, janus_server/src/config.rs, janus_server/src/hpke.rs, janus_server/src/lib.rs, janus_server/src/message.rs
This fixes a merge conflict in Cargo.toml and applies #38 to main.
=> Follow-up to #38

db/schema.sql, janus_server/Cargo.toml, janus_server/src/aggregator.rs, janus_server/src/bin/aggregator.rs, janus_server/src/client.rs, janus_server/src/datastore.rs, janus_server/src/message.rs, janus_server/tests/integration_test.rs
Apologies for the size of this PR; a review strategy that might work is:
1) Review the datastore/schema changes first.
2) Once you are happy with the datastore changes, review the aggregator changes.
I need to land https://github.com/divviup/libprio-rs/pull/202 before we can commit this, but it seems very likely that any changes required from review of that PR will be minimal. I want to send this for review ASAP since it has already taken quite a while & grown quite large.
=> Initial /aggregate implementation, for init requests.

janus_server/src/aggregator.rs
This adds a tracing event, at error level, to the `error_handler()` function, which is part of each of our routes. Sample JSON output: (reformatted, for shorter line lengths)
```json
{
"timestamp": "2022-04-11T20:49:20.938775Z",
"level": "ERROR",
"fields":{
"error": "datastore error: DB error: db error: ERROR: null value in column \"task_id\" of relation \"client_reports\" violates not-null constraint\nDETAIL: Failing row contains (1, null, 2021-09-17 19:38:20, \\x13f82ede89ce636e, \\x0000, \\x0cba0000205633dd721d57b0dd8387371d6dcde22f1b26a3a1c8cfeb148244...)."
},
"target": "janus_server::aggregator",
"filename": "janus_server/src/aggregator.rs",
"line_number": 729,
"threadId": "ThreadId(8)"
}
```
=> Emit a tracing event upon error responses

db/schema.sql, janus_server/src/bin/aggregator.rs, janus_server/src/datastore.rs
Right now, that means tasks.vdaf_verify_param, tasks.agg_auth_key, and
tasks.hpke_private_key.
=> datastore: use Crypter to encrypt secret values.

janus_server/src/hpke.rs
This leads to slightly simpler code than doing setup_{sender,receiver}
followed by {seal,open} ourselves.
=> hpke: use single_shot_{seal,open}.

Cargo.lock, db/schema.sql, janus_server/Cargo.toml, janus_server/src/aggregator.rs, janus_server/src/datastore.rs
Adds support for fetching collect job UUIDs from the database, and
creating collect jobs on demand.
=> Store collect jobs in the database

janus_server/src/message.rs
=> Fix typo in error message

janus_server/src/aggregator.rs, janus_server/src/datastore.rs, janus_server/src/hpke.rs, janus_server/src/message.rs, janus_server/src/task.rs
This is part of #18. I chose to go with into/from, as this is just a newtype over a primitive.
=> Add and use conversions for HpkeConfigId

janus_server/src/aggregator.rs, janus_server/src/datastore.rs
Refactors some existing code that supports the helper's
`max_batch_lifetime` enforcement so that it can be re-used in the
leader's `collect` endpoint. All the logic for that endpoint now moves
into methods on `VdafOps`.
part of #105
=> max batch lifetime enforcement in the leader

janus_server/src/aggregator.rs, janus_server/src/aggregator/accumulator.rs, janus_server/src/datastore.rs
A couple of follow up items from #166 / #170.
=> Cleanup: Error trait bounds and NonceChecksum

janus_server/src/datastore.rs
This adds a counter metric recording the number and status of database transactions. For starters, I'm categorizing by whether the transaction succeeded, hit a serialization failure, hit a non-serialization database error, or any other application-level error.
We could also assign names to each callsite, and add another label for the transaction name, but I decided to hold off on that for now.
=> Add a counter metric for database transactions

db/schema.sql, janus_server/src/datastore.rs
I merged #192 into the wrong place. This should have the same commits.
=> PR #192, take 2

Cargo.lock, janus_server/Cargo.toml, monolithic_integration_test/Cargo.toml, test_util/src/lib.rs
=> Upgrade testcontainers to 0.14.0

janus_server/src/aggregator.rs
This fixes #184, using Warp's built-in CORS filter. I confirmed that these settings are sufficient for sending requests and reading responses with `fetch()` in Firefox and Chromium.
One limitation to be aware of: HTTP error responses that arise from Warp rejections do not carry an Access-Control-Allow-Origin header, so browser clients will see a CORS error rather than the underlying 404, 400, etc. error. (This affects rejections from unrecognized paths, mismatched HTTP methods, and mismatched Content-Type headers.) HTTP error responses that originate in our `error_handler()` filter do get decorated with CORS headers, so browser clients can read them properly. This is because the CORS wrapping filter passes rejections on unmodified, whereas it wraps reply futures to add headers before …
=> Add CORS filters to client-facing endpoints

db/schema.sql, janus_server/src/aggregator.rs, janus_server/src/aggregator/aggregate_share.rs, janus_server/src/bin/aggregation_job_driver.rs, janus_server/src/bin/collect_job_driver.rs, janus_server/src/datastore.rs
=> Collect job driver: abandon collect jobs that fail repeatedly.

janus_server/src/aggregator/aggregate_share.rs, janus_server/src/bin/aggregation_job_driver.rs, janus_server/src/bin/collect_job_driver.rs
This moves the closures to acquire jobs and step them into separate methods. The closures for the aggregator job driver were defined separately in tests and the binary, and had begun to drift.
=> Extract job driver-related closures

janus_server/src/aggregator.rs
This is a somewhat nitpicky commit, following the principle that
requests that fail should not affect the externally-observable state of
the system.
Closes #307.
=> Don't consume batch lifetime for failing requests.

README.md
This adds a section to the README with advice on raising the inotify instance limit.
=> Document inotify issue and fix

janus_server/src/task.rs
Serialization is currently only used in the janus_cli's provision-tasks
command, so backwards-compatibility breaks are currently acceptable.
The major changes are:
* HPKE public keys are now serialized into unpadded base64url
encoding, rather than being encoded as a sequence of numeric values.
* The hpke_keys config-and-private-key structure is now encoded as a
structure with named fields, rather than being encoded as a list of
two anonymous elements.
Closes #329. (See that issue for an example of the previous serialization format.)
Example of the new format, serializing a vector containing a single task
into YAML (sensitive values not redacted as this is a randomly-generated
test task):
```
---
- id: H0-5NywUzXVZ_yHDB1YacR-uvKlyklo9xtRUgf90jEs
aggregator_endpoints:
- …
```
=> Improve Task serialization format.

Cargo.lock, janus_client/Cargo.toml, janus_core/Cargo.toml, janus_server/Cargo.toml
=> Increment versions to 0.1.5.

Cargo.lock, janus_client/Cargo.toml, janus_core/Cargo.toml, janus_server/Cargo.toml
DO NOT MERGE until #386 is merged.
=> Increment versions to 0.1.6.

janus_core/src/test_util/dummy_vdaf.rs, janus_server/src/aggregator.rs, janus_server/src/aggregator/aggregation_job_driver.rs
This fixes some new clippy lints that showed up with the latest stable toolchain.
=> Fix clippy lints

Cargo.lock, janus_collector/Cargo.toml, janus_collector/examples/collect.rs
This takes the new collector library and exposes it via a Clap CLI. Unit tests cover command-line argument handling, and I confirmed that it works end-to-end against interop-00. Here's the help text, for reference.
```
collect 0.1.11
Command-line DAP-PPM collector from ISRG's Divvi Up
USAGE:
collect [OPTIONS] --task-id <TASK_ID> --leader <LEADER> --auth-token <AUTH_TOKEN> --hpke-config <HPKE_CONFIG> --hpke-private-key <HPKE_PRIVATE_KEY> --vdaf <VDAF> --batch-interval-start <BATCH_INTERVAL_START> --batch-interval-duration <BATCH_INTERVAL_DURATION>
OPTIONS:
-h, --help       Print help information
-V, --version    Print version information
DAP TASK PARAMETERS:
--task-id <TASK_ID>
DAP task identifier, encoded with base64url
--leader <LEADER>
The leader aggregator's endpoint URL
--auth-token …
```
=> Add example binary to perform collection from CLI

janus_server/src/metrics.rs
This swaps in a coarser set of histogram buckets for `janus_job_acquire_time`. These buckets are each about half a decibel wide, instead of a third of a decibel. This is done to better capture times from slow database queries. The top bucket boundary is now at five minutes, instead of ten seconds.
=> Use coarser buckets for janus_job_acquire_time

janus_server/src/datastore.rs
Adds a test to prove that any collect jobs not in the `START` state (including ones in the new `DELETED` state) are not acquired by `collect_job_driver`. This commit also refactors some of the tests in `datastore.rs` to share some test setup code.
Part of #344
=> Only acquire collect jobs in `START` state

janus_server/src/aggregator/aggregate_share.rs
We now check whether the state of a collect job has changed while the lease is held. This is possible if a DELETE request is sent to the collect job URI while the collect job driver is working. We also check for unexpected state transitions. Along the way, we expand the metrics recorded by `collect_job_driver`.
Part of #344
Stacked on #579
=> `collect_job_driver`: check job state at finish

interop_binaries/src/lib.rs, janus_core/src/hpke.rs
This updates the version component of HPKE application info strings for DAP draft 02. This closes #474.
=> Update HPKE application info strings to "dap-02"

janus_server/src/aggregator.rs
Adds a `warp` route for `DELETE` request to collect job URIs and updates the `GET` handler to check for the deleted state.
Resolves #344
Stacked on #580
=> Support deleting collect jobs

janus_messages/src/lib.rs
This changes various length fields from 2-byte to 4-byte, in line with changes in DAP draft 02. This closes #471.
=> Change length field sizes for DAP draft 02

janus_server/src/aggregator.rs, janus_server/src/aggregator/aggregate_share.rs
DAP-02 updates the "Batch Validation" section [1] with several new error types. This commit updates `janus_server` with the new problem document types, returns them as appropriate, and adds tests to verify that correct errors are constructed.
The exception is `batchOverlap`: while the `collect_job_driver` does correctly check for that condition when stepping a collect job, DAP-02 requires that this error be presented to the collector while handling a `CollectReq`. Meeting that requirement will require more significant refactoring that will arrive in a later pull request.
Part of #470
[1]: https://www.ietf.org/archive/id/draft-ietf-ppm-dap-02.html#section-4.5.6
=> Correct errors for DAP-02 collect, agg share reqs

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregate_share.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/datastore.rs, db/schema.sql, messages/src/lib.rs
Update several datastore tests to test with the FixedSize query type. The remainder of the tests will be updated as functionality in their packages is updated.
=> Add batch_identifier to AggregationJob.

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregate_share.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/datastore.rs, aggregator/src/messages.rs, db/schema.sql
=> Fixed-size task: implement aggregation job creation.

aggregator/src/aggregator.rs
Sending a `CollectReq` with an aggregation parameter that isn't a valid encoding now yields an HTTP 400 Bad Request response with a problem document of type `unrecognizedMessage`, instead of the 500 Internal Server Error it previously provided.
=> `/collect`: handle invalid aggregation parameter

collector/examples/collect.rs
This fixes a clap argument handling test that was failing intermittently. Three different arguments have base64url-encoded values, and the first byte of all three is uniformly chosen at random in this test. When the encoded value starts with a dash, clap was interpreting it as the start of another flag, rather than the value for the preceding flag, as intended. There was a 4.6% chance of the test failing due to this issue. This PR rewrites the test to specify these three arguments with `--flag=value` syntax, (instead of using two separate argv elements) so that any leading hyphens are unambiguously part of the argument's value.
Closes #715.
=> Fix flakiness in clap argument handling test

aggregator/src/datastore.rs
This changes `run_tx_once` to explicitly roll back the transaction upon error, rather than rely on the `Drop` implementation scheduling the message for us. The benefit of this change is that we can now see any errors received in response to the rollback. I used the newly-added `Error::combine()` to propagate this error as needed, and I added a counter metric to record error codes seen in response to `ROLLBACK`. I'd like to see what kinds of errors can be produced here -- for example, is it possible for Postgres to return a serialization failure error? Will we only ever see connection-related errors?
=> Explicitly call Transaction::rollback(), and propagate its error

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregate_share.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/collect_job_driver.rs, aggregator/src/aggregator/query_type.rs, aggregator/src/datastore.rs, aggregator/src/task.rs, db/schema.sql, messages/src/lib.rs
=>  Fixed-size tasks: implement helper collection.

Cargo.lock, Cargo.toml, aggregator/Cargo.toml, client/Cargo.toml, collector/Cargo.toml, core/Cargo.toml, integration_tests/Cargo.toml, interop_binaries/Cargo.toml
Version 0.3 will implement the DAP-03 specification.
=> Bump Janus to version 0.3.

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/datastore.rs, client/src/lib.rs, collector/src/lib.rs, core/src/hpke.rs, messages/src/lib.rs
=> DAP-03: update AAD encoding to use explicit structs.

.github/workflows/ci-build.yml, .github/workflows/publish-crates.yml, .github/workflows/publish-sql-schema.yml, .github/workflows/push-docker-images-release.yml
This is a backport of #844, a CI fix.
=> Add OS version to cache key (0.2 backport)

.github/workflows/ci-build.yml
=> Run CI with MSRV and stable Rust toolchains

aggregator/src/aggregator.rs, client/src/lib.rs, messages/src/lib.rs
In DAP-03, aggregators may advertise multiple HPKE configs in order of preference, and clients may choose any of them for encrypting reports ([1]). In this change, we introduce the `HpkeConfigList` structure and handle it in `janus_client`, but `janus_aggregator` still only ever advertises a single HPKE configuration.
[1]: https://datatracker.ietf.org/doc/html/draft-ietf-ppm-dap-03#name-hpke-configuration-request
=> DAP-03: Aggregators must advertise `HpkeConfigList`

collector/examples/collect.rs, collector/src/lib.rs, integration_tests/tests/common/mod.rs
This makes the following changes, to better support current batch queries in `janus_collector`.
1. Add a `--current-batch` command line flag to the collect CLI.
2. Plumb the partial batch selector from the collect response through to the `Collection` struct returned by the library.
3. Add the batch ID to the collect CLI output for fixed size queries.
=> Collect CLI current batch enhancements

.github/workflows/ci-build.yml, integration_tests/src/client.rs, integration_tests/tests/divviup_ts.rs
=> Re-enable divviup-ts tests for DAP-03.

aggregator/src/aggregator.rs, aggregator/src/bin/janus_cli.rs, aggregator/src/datastore.rs, aggregator/src/task.rs, aggregator/tests/graceful_shutdown.rs, client/src/lib.rs, integration_tests/src/client.rs, integration_tests/src/janus.rs, interop_binaries/src/bin/janus_interop_aggregator.rs, interop_binaries/src/bin/janus_interop_client.rs, interop_binaries/src/bin/janus_interop_collector.rs, interop_binaries/src/lib.rs
This makes some mechanical changes to format strings, to fix clippy lints.
=> cargo clippy --fix, 1.67

aggregator/src/datastore.rs, aggregator/src/metrics.rs
This adds a new histogram metric for transaction durations, keyed off of transaction names. This is a follow-up to #937.
=> Add histogram for database transaction duration

aggregator/src/task.rs
This adds validation to serialized task handling to check that authentication tokens are valid HTTP header values. This is currently a sharp edge of `janus_cli`, since we take these in as base64url-encoded strings, and it's natural to come up with a random token by base64-encoding random bytes.
=> Validate authentication tokens loaded from YAML

aggregator/src/datastore.rs
We got a user report of the following database error message.
```
ERROR: deadlock detected
DETAIL: Process 184495 waits for ShareLock on transaction 2097298; blocked by process 185919.
Process 185919 waits for ShareLock on transaction 2097304; blocked by process 184495.
HINT: See server log for query details.
```
[The documentation recommends](https://www.postgresql.org/docs/15/mvcc-serialization-failure-handling.html) retrying on deadlock detection errors in addition to serialization failures. It sounds like a ShareLock on a transaction is used internally when one transaction needs to wait for another transaction to either commit or abort. It's surprising that a cycle can form from these locks, but clearly it happens very infrequently.
=> Retry Postgres "deadlock detected" errors

aggregator/src/datastore.rs
This is fine because all we care about is Total Modification Order, which is still guaranteed by Relaxed memory ordering. (On x86, relaxed atomic loads/stores are implemented as ordinary loads/stores with no fencing required.)
Also, play a little code golf with the transaction code -- it was getting a little hairy.
=> Switch to Relaxed memory ordering for retry flag.

docs/samples/aggregation_job_driver_config.yaml, docs/samples/aggregator_config.yaml
This fixes a semantic merge conflict from #1041.
=> Add new parameter to sample configuration files

core/src/hpke.rs
Per https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/424
=> Bump HPKE application info labels for DAP-04

aggregator/src/aggregator.rs
Return `ReportShareError::UnrecognizedMessage` if a report share cannot be decoded, as specified by [1].
[1]: https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/391
=> Tweak error type for unparseable `PrepareStep`

aggregator/src/aggregator.rs
This PR moves conversion of DAP-Auth-Token header values to `AuthenticationToken` structs closer to our HTTP framework. This is preparatory work for migrating to Trillium. (#1090) The method signature changes will allow me to remove an unnecessary check that the header's value is valid UTF-8, by passing the token around as an `AuthenticationToken` instead of a `String`.
=> Move conversion of authentication token headers

aggregator_api/src/lib.rs
The bearer token in an HTTP `Authorization` header should be represented in the Base64 alphabet, per RFC 6750[1]. Janus doesn't actually use OAuth 2 here, but it still makes sense for us to decode the bearer token presented by the client from Base64, as you can't transmit arbitrary bytes in HTTP headers anyway.
[1]: https://datatracker.ietf.org/doc/html/rfc6750#section-2.1
=> `aggregator_api`: b64 decode received auth token

aggregator_core/src/datastore.rs
I can't remember why I specified an ordering, but it's not necessary, and ordering can be expensive. While I'm at it, I specify FOR UPDATE SKIP LOCKED in the inner SELECT query; I think this will effectively change concurrent acquiry attempts from always triggering a serialization failure & retry to never triggering a serialization failure & retry.
=> Drop ordering requirement in acquire_incomplete_aggregation_jobs.

aggregator_core/src/datastore.rs
Due to Postgres locking semantics, it is possible that concurrent attempts to lease aggregation jobs may leave a job unleased that could have been returned to one of the leasers. This is rare, but led to a test flake when it occurred (it took about ~10m of looped runs of the relevant test to trigger on my workstation). The fix is to retry concurrent requests for some time, stopping once we get the expected number of leases.
I think this doesn't mask a problem worth solving for production uses of this code:
* It is very rare for this behavior to be triggered.
* The downside is that a given aggregation job's processing will be delayed; however, it is very likely to be picked up by the next attempt to lease.
* I believe this can only happen when there are few aggregation jobs, i.e. when we …
=> Fix flake in aggregation_job_acquire_release.

Dockerfile.interop_aggregator, aggregator/src/datastore.rs
=> Change container back to postgres:14-alpine, 0.2 backport

.github/workflows/yank-crates.yml
Adds a workflow that yanks a designated version of the `janus` crates from crates.io.
=> GitHub Actions workflow for yanking Rust crates

docs/DEPLOYING.md
=> Add advice for simple database deployments.

.github/workflows/ci-build.yml, Cargo.lock, Dockerfile, Dockerfile.interop, Dockerfile.interop_aggregator, README.md, aggregator/Cargo.toml, aggregator/src/datastore.rs, interop_binaries/Cargo.toml
Backport of https://github.com/divviup/janus/pull/1407
=> release/0.2: Upgrade to opentelemetry 0.19

.github/workflows/ci-migrations.yml
Supports https://github.com/divviup/janus/issues/1252.
Adds various checks of migrations that aren't already covered by [sqlx itself](https://docs.rs/sqlx-core/0.6.3/src/sqlx_core/migrate/source.rs.html#21).
=> Add workflow to check the consistency of migrations.

.github/workflows/ci-migrations.yml
From https://github.com/divviup/janus/pull/1459#discussion_r1220639120, this is a simpler and more reliable means of detecting non-permitted changes.
=> Simplify check for change of existing migrations

core/src/task.rs
This overrides part of the `VdafInstance` debug implementation, to only print the number of histogram buckets, instead of the full list of bucket boundaries.
=> Shorten <VdafInstance as Debug> for histograms

.github/workflows/ci-build.yml, integration_tests/src/client.rs, integration_tests/tests/divviup_ts.rs
This re-enables the integration tests against divviup-ts.
=> Enable divviup-ts integration tests

aggregator/src/bin/aggregation_job_creator.rs, aggregator/src/bin/aggregation_job_driver.rs, aggregator/src/bin/aggregator.rs, aggregator/src/bin/collection_job_driver.rs, aggregator/src/binary_utils.rs
This cleans up our graceful shutdown handling, following up on the Trillium migration, by using `Stopper` throughout instead of Tokio channels.
=> Use Stopper instead of channels for shutdown

aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collection_job_driver.rs
This adds a counter metric to both the aggregation job driver and collection job driver, counting the number of times we retry stepping any job. We already track successes and errors in another counter, but I'd like to add this to capture leases that expire due to various issues with the process holding the lease. (see also #1502)
=> Add counter metric for job step retries

aggregator_core/src/datastore.rs
This was another snapshot-isolation issue: in Repeatable Read, a write can fail due to a concurrent conflicting write, but the conflicting write can be unreadable. Generally, we want to force a retry when we encounter such a situation.
(Discovered by analysis, I did not trigger this race condition. It would require multiple concurrent uploads of same-ID reports to trigger.)
=> Fix spurious panic in `put_client_report`.

aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collection_job_driver.rs, aggregator/src/aggregator/garbage_collector.rs, aggregator_core/src/datastore.rs, core/src/time.rs
Note that this leaves the GC binary in a strange state; we should not deploy this GC until the aggregation & collection GC is updated similarly.
=> Incremental client report GC.

aggregator_api/src/lib.rs, integration_tests/tests/in_cluster.rs
=> Update aggregator API for BYOHelper

aggregator/src/aggregator/garbage_collector.rs, aggregator_api/src/lib.rs, aggregator_core/src/datastore.rs, aggregator_core/src/task.rs
I removed part of the GC binary tests, as the collection artifact portion of these tests no longer work but it doesn't make sense to fix them up as the model will soon be changing. I will fix them up with the collection artifact GC update.
Part of #1467.
=> Incremental aggregation-artifact GC.

aggregator_api/src/lib.rs
The aggregator API now requires that requests have a `Content-Type` and `Accept` header specifying the appropriate API version, matching `divviup-api`'s behavior.
Resolves #1475
=> Version the aggregator API with Content-Type

Cargo.lock, messages/Cargo.toml, messages/src/lib.rs, messages/src/taskprov.rs
Supports https://github.com/divviup/janus/issues/1568.
=> Implement taskprov data structures.

aggregator/src/aggregator/http_handlers.rs
Deduplicate these tests by replacing long call chains with functions.
=> Factor out some common test patterns into functions

messages/src/taskprov.rs
=> Remove extraneous println

messages/src/taskprov.rs
Fix this nit: these explicit types in `impl`s should have been `Self`s.
=> Replace type names in impls with Self

Cargo.lock, Cargo.toml, integration_tests/src/divviup_api_client.rs, integration_tests/tests/in_cluster.rs
This updates the in_cluster test for recent changes to divviup-api and bumps the version again. I have tested it out locally.
=> in_cluster: Create HPKE config in divviup-api first

.github/dependabot.yml, README.md
=> Document `release/0.subscriber-01`

.github/dependabot.yml, README.md
We are starting our DAP-05 implementation (#1669) and so must branch for DAP-04.
=> Prepare to branch for DAP-04

Cargo.lock, Cargo.toml, aggregator/Cargo.toml, aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_continue.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collection_job_driver.rs, aggregator/src/aggregator/http_handlers.rs, aggregator/src/binary_utils.rs, aggregator/src/binary_utils/job_driver.rs, aggregator/src/metrics.rs, aggregator_core/src/datastore.rs
=> Update opentelemetry & related versions to 0.20-compatible [0.subscriber-01 backport]

Cargo.lock, Cargo.toml, aggregator/Cargo.toml, aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_continue.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collection_job_driver.rs, aggregator/src/aggregator/http_handlers.rs, aggregator/src/binary_utils.rs, aggregator/src/binary_utils/job_driver.rs, aggregator/src/metrics.rs, aggregator_core/src/datastore.rs
=> Update opentelemetry & related versions to 0.20-compatible [0.5 backport]

aggregator/src/aggregator/taskprov_tests.rs
This ports the new test from #1750 to the main branch.
=> Add end-to-end test of aggregation using taskprov, main branch

aggregator/src/aggregator/aggregation_job_continue.rs, aggregator/src/aggregator/collection_job_tests.rs, aggregator/src/aggregator/http_handlers.rs
Closes https://github.com/divviup/janus/issues/1607. Mainly factor out test setup into its own function.
=> Aggregator test cleanup

aggregator_core/src/datastore.rs, db/00000000000016_unique_collection_job_id.down.sql, db/00000000000016_unique_collection_job_id.up.sql
=> Require collection job IDs to be unique. [0.5 backport]

.github/dependabot.yml
This is a follow-up to #1866 to fix the structure of the configuration file.
=> Fix Dependabot groups configuration

aggregator/src/bin/aggregator.rs, docs/samples/advanced_config/aggregator.yaml
Backports https://github.com/divviup/janus/pull/1809 to release/0.5 branch.
=> Add validation to enforce listen_address and path_prefix mutual exclusion (backport 0.5)

Cargo.lock, Cargo.toml
And leave comment why the version tag looks so funny.
=> Bump version to 0.subscriber-01.6

README.md, aggregator/src/aggregator.rs, aggregator/src/aggregator/collection_job_tests.rs, aggregator/src/aggregator/http_handlers.rs, aggregator/src/aggregator/taskprov_tests.rs, aggregator_core/src/datastore/tests.rs, collector/src/lib.rs, core/src/hpke.rs, integration_tests/tests/daphne.rs, integration_tests/tests/divviup_ts.rs, integration_tests/tests/in_cluster.rs, messages/src/lib.rs
=> Minor changes for DAP-07

.github/actions/validate-migrations/action.yml
Backport https://github.com/divviup/janus/pull/1979
=> Migration filenames containing numbers are valid

aggregator/src/aggregator/garbage_collector.rs
Adopts `AggregatorTask` and `NewTaskBuilder` in `garbage_collector` module.
Part of #1524
=> Task rewrite: garbage collector

Cargo.toml, aggregator/src/aggregator/batch_creator.rs, aggregator_api/src/routes.rs
=> Updates for Rust 1.73.0, subscriber-01 backport

Cargo.toml, aggregator/src/aggregator/batch_creator.rs, aggregator_api/src/routes.rs
=> Updates for Rust 1.73.0, 0.5 backport

Cargo.lock, Cargo.toml
Releasing early for https://github.com/divviup/janus/pull/2125 bugfix.
=> Bump version to 0.5.25

Cargo.lock, Cargo.toml
Updating early to get https://github.com/divviup/janus/issues/2124 bugfix in.
=> Bump version to 0.6.0-prerelease-5

aggregator/src/aggregator.rs
Closes https://github.com/divviup/janus/issues/2170.
=> Remove global HPKE keypair cache from tracing spans

core/src/hpke.rs, tools/src/bin/collect.rs, tools/tests/cmd/collect.trycmd, tools/tests/cmd/collect_fpvec_bounded_l2.trycmd
Update doccomments and help texts to reflect what this subcommand is now called.
=> collect: 'divviup hpke-config' -> 'divviup collector-credential'

aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/aggregation_job_writer.rs, aggregator/src/aggregator/batch_creator.rs, aggregator_core/src/datastore.rs, aggregator_core/src/datastore/models.rs, aggregator_core/src/datastore/tests.rs
This reverts commit c28be440a143f4cb60d2cf4f017ddf321119344d.
Closes #2270.
=> Revert "Eagerly delete aggregation jobs. (#2235)"

Cargo.lock, Cargo.toml
=> Update kube-rs, 0.5 backport

tools/src/bin/collect.rs, tools/tests/cmd/collect.trycmd, tools/tests/cmd/collect_fpvec_bounded_l2.trycmd
=> collect: fix panic when providing no hpke args

aggregator/src/binary_utils/job_driver.rs
A recent PR changed the word "permits" to "leases" here. While the comment was no less true, since semaphore permits and job leases are acquired in equal number, this comment was setting up an invariant about semaphore permits that a later comment relied on, in order to argue that an unwrap was safe. This PR undoes the change, and adds a bit more elaboration in both comments.
=> Expand comment about Semaphore-related invariant

core/src/retries.rs
The Divvi Up rate limiter returns HTTP 429 Too Many Requests when rate limits are exceeded, so we need the client to retry if it sees that HTTP status, especially since we use it in integration tests.
=> Retry HTTP requests on HTTP 429

aggregator/src/metrics.rs
This provides an alternate set of histogram buckets for metrics that are denominated in bytes. Previously we used a custom implementation of `AggregationSelector` to do this, but in one of the past upgrades, its API changed to no longer take in the metric name. Now, the way to do this is via the `View` trait.
=> Change histogram buckets for metrics in bytes

aggregator/src/aggregator.rs
Previously, per-report-aggregation work was performed serially. This led to a number of serialized database round trips equal to the number of report aggregations. With this change, per-report-aggregation work is now done in a single serialized database round trip. This will likely be most impactful for large aggregation jobs.
=> Helper aggregate init: perform per-report-aggregation work concurrently.

aggregator/src/aggregator.rs
1. Perform `flush_to_datastore`, computing `unwritable_reports`, and update report aggregations appropriately before writing report aggregations back to the datastore. Before this PR, these were done concurrently with the report aggregation writes; this meant that, if an unwritable report occurred, we would store a different set of report aggregations than we returned in the response. (This introduces a serialized round trip to the datastore, but this corresponds to a serialized round trip that was removed with #2355, so we are at net unchanged number of round trips to the datastore.)
2. When we are handling a replayed request, return the stored report aggregations, instead of the report aggregations we computed. This ensures that our response to a repeated request matches the original …
=> Helper aggregate init idempotency tweaks.

aggregator/src/aggregator/garbage_collector.rs, aggregator/src/binaries/aggregator.rs
Two new settings are introduced to the GC config:
* tasks_per_tx: controls how many tasks are grouped into the same transaction for purposes of garbage collection. If left unset, each task's GC work is run in its own transaction.
* concurrent_tx_limit: controls how many concurrent database transactions are allowed for GC. If left unset, there is no limit to the number of concurrent transactions used for GC.
If neither of these new options are configured, the behavior will be left as before -- each task will be GC'ed in its own transaction, with no limit to the number of concurrent transactions.
Note that grouping GC for different tasks into a single transaction risks failures (or retries) in the GC process for one task impacting GC for other, independent tasks.
=> GC: add config to group GC in tx's, control concurrent tx's.

README.md
As discussed in https://github.com/divviup/janus/pull/2386#discussion_r1434372926.
=> Add versioning and stability policy

integration_tests/Cargo.toml
=> Move trillium-rustls to dev-dependencies

aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collection_job_driver.rs, client/src/lib.rs, collector/src/lib.rs, core/src/http.rs, core/src/retries.rs
https://github.com/divviup/janus/pull/2476
=> Abandon collection jobs early when a fatal error is encountered (release/0.6 backport)

db/00000000000001_initial_schema.up.sql
Follow up to https://github.com/divviup/janus/pull/2353.
Closes https://github.com/divviup/janus/issues/2354. Everything else looks accurate to me.
=> db: remove untrue comment

core/src/hpke.rs
=> Update HPKE domain separation strings for DAP-09

.github/workflows/ci-build.yml, Cargo.toml, README.md, core/src/test_util/kubernetes.rs
This updates Kind and the Kubernetes version in the associated image.
=> Update to Kind 0.20.0 and Kubernetes 1.26

Cargo.lock, aggregator/Cargo.toml, aggregator/src/binary_utils.rs
=> Add gauge metrics for DB connection pool status, 0.6 backport

aggregator_core/src/datastore.rs, aggregator_core/src/datastore/tests.rs
While running a cloud load test, with a single task in the database, I observed behavior similar to our production incident last month, where garbage collection transactions were taking progressively longer to execute, and aggregation progress eventually came to a halt, as both database instances' CPUs were monopolized by the garbage collector. As before, this was caused by the `delete_expired_client_reports()` query being executed with a hash join that hashed a sequential scan of `client_reports`. The database instance had already had the `random_page_cost = 1.1` flag change applied. I determined that the estimated selectivity of the `client_timestamp < COALESCE(...)` condition was way off.
Currently, the query planner only has at its disposal statistics describing the distribution of …
=> Split delete_expired_client_reports() query

core/src/http.rs
This is a small cleanup for our wrapper around http-api-problem: previously it was possible to convert an `HttpApiProblem` with `status: None` to an `HttpErrorResponse` via `From`, and then call `status()` on the resulting object, unwrapping `None` and causing a panic. This PR turns that `From` into a `TryFrom` to handle this case.
=> Enforce that HttpErrorResponse always has a status

collector/src/credential.rs, integration_tests/tests/integration/in_cluster.rs, tools/src/bin/collect.rs
Closes https://github.com/divviup/janus/issues/2329
=> Make token in PrivateCollectorCredential non-optional

aggregator/src/aggregator/aggregation_job_writer.rs, aggregator_core/src/query_type.rs
Now that the change has been live for a few weeks with no negative consequences, I'm happy to rephrase this in a less-hacky way.
Closes #2464.
=> Rephrase batch-GC'ed check in a non-hacky way.

aggregator/src/aggregator/aggregation_job_writer.rs, aggregator_core/src/query_type.rs
Now that the change has been live for a few weeks with no negative consequences, I'm happy to rephrase this in a less-hacky way.
=> [0.6] Rephrase batch-GC'ed check in a non-hacky way.

aggregator_core/src/datastore.rs
=> Simplify unaggregated report check

aggregator_core/src/datastore.rs
Backport of #2647, implements #2646.
=> Simplify unaggregated report check, 0.6 backport

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregate_init_tests.rs, aggregator/src/aggregator/taskprov_tests.rs, docs/CONFIGURING_TASKPROV.md, messages/src/lib.rs, messages/src/taskprov.rs
There are several message changes, and a requirement for a new empty extension in each report share indicating that taskprov is in use.
=> Update taskprov for taskprov-06.

aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/binaries/aggregation_job_creator.rs, aggregator/tests/integration/graceful_shutdown.rs, aggregator_core/src/datastore.rs, aggregator_core/src/datastore/tests.rs, docs/samples/advanced_config/aggregation_job_creator.yaml, integration_tests/src/janus.rs
=> Configurable LIMIT in unaggregated reports query, 0.6 backport

docker-bake.hcl
=> Ignore Docker cache export errors, 0.6 backport

docker-bake.hcl
=> Ignore Docker cache export errors, 0.5 backport

aggregator_api/src/tests.rs, aggregator_core/src/datastore.rs, aggregator_core/src/datastore/tests.rs
Backport of https://github.com/divviup/janus/pull/2752
=> Aggregator API: return 200 with zero counters for fresh task (release/0.6 backport)

Cargo.lock, Cargo.toml, aggregator/Cargo.toml, aggregator/src/binary_utils.rs, aggregator/src/metrics.rs
=> Upgrade OpenTelemetry SDK to 0.22

Cargo.lock, Cargo.toml, aggregator/Cargo.toml, aggregator/src/metrics.rs
=> Upgrade OpenTelemetry SDK to 0.22, 0.5 backport

Cargo.lock, Cargo.toml, aggregator/Cargo.toml, aggregator/src/binary_utils.rs, aggregator/src/metrics.rs
=> Upgrade OpenTelemetry SDK to 0.22, 0.6 backport

aggregator/src/aggregator/report_writer.rs
https://github.com/divviup/janus/pull/2754
=> Write upload counters in separate transaction from uploads (release/0.6 backport)

aggregator_core/src/datastore.rs
=> Split database query for unaggregated reports, 0.6 backport

aggregator/src/bin/janus_cli.rs, aggregator/src/binaries/aggregation_job_creator.rs, aggregator/src/binaries/aggregation_job_driver.rs, aggregator/src/binaries/aggregator.rs, aggregator/src/binaries/collection_job_driver.rs, aggregator/src/binary_utils.rs, aggregator/src/config.rs, aggregator/tests/integration/graceful_shutdown.rs, aggregator_core/src/datastore.rs, aggregator_core/src/datastore/test_util.rs, aggregator_core/src/datastore/tests.rs, integration_tests/src/janus.rs
Backports https://github.com/divviup/janus/pull/2809
=> Add limit to transaction retries (release/0.6 backport)

aggregator/src/aggregator/aggregation_job_creator.rs
This deletes two duplicated comments, and rephrases another. Technically, DAP doesn't require that reports are rejected immediately after receipt of a collection job, but it does require that reports belonging to an already-collected batch are rejected.
=> Fix comments in new aggregation job creator test

aggregator_core/src/datastore.rs
This join has caused Postgres' query planner to produce poorer plans than necessary on multiple occasions, so we cache it.
Also:
* Move computation of GC threshold into application code.
* Simplify GC clauses based on the above computation.
* Reformat all GC clauses to fit in ~100 columns. The ability to do this in a readable way is aided by the moved computation of the GC threshold.
* Improve put semantics: before, attempting to put an entity into a nonexistent task would fail with a DB error about inserting a NULL value into a NOT NULL column (i.e. task_id). Now, a MutationTargetNotFound error is returned instead.
* scrub_client_report & verify_client_report_scrubbed now respect GC.
=> Split task join out of every query & cache it.

aggregator_api/src/lib.rs, aggregator_api/src/models.rs, aggregator_api/src/routes.rs, aggregator_api/src/tests.rs, aggregator_core/src/datastore.rs, aggregator_core/src/datastore/tests.rs
Backports https://github.com/divviup/janus/pull/2824
=> aggregator api: Allow patching a task's expiration time (release/0.6 backport)

aggregator/Cargo.toml, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator_core/src/datastore.rs
This fixes some warnings I saw scroll by while building container images.
=> Fix warnings when building without test-util

aggregator/src/aggregator.rs
See https://github.com/divviup/janus/pull/2874
=> Fix unused braces lint for clippy 1.77 (release/0.5)

Cargo.toml
=> Update minimum version of chrono, 0.5 backport

aggregator/src/binary_utils.rs, aggregator/src/config.rs, aggregator/tests/integration/graceful_shutdown.rs, docs/samples/advanced_config/aggregation_job_creator.yaml, docs/samples/advanced_config/aggregation_job_driver.yaml, docs/samples/advanced_config/aggregator.yaml, docs/samples/advanced_config/collection_job_driver.yaml, docs/samples/advanced_config/janus_cli.yaml, integration_tests/src/janus.rs
Lets us configure the database connection pool size.
=> Expose connection pool size configuration

aggregator/src/binary_utils.rs, aggregator/src/config.rs, aggregator/tests/integration/graceful_shutdown.rs, docs/samples/advanced_config/aggregation_job_creator.yaml, docs/samples/advanced_config/aggregation_job_driver.yaml, docs/samples/advanced_config/aggregator.yaml, docs/samples/advanced_config/collection_job_driver.yaml, docs/samples/advanced_config/janus_cli.yaml, integration_tests/src/janus.rs
https://github.com/divviup/janus/pull/2948
=> Expose connection pool size configuration (release/0.6 backport)

aggregator_core/src/datastore.rs
https://github.com/divviup/janus/pull/2952
=> Pool wait time metric (release/0.6 backport)

aggregator_core/src/datastore.rs
Create a new pool wait metric that captures only the time spent acquiring a connection from the pool. This should signal if the connection pool size is too small.
Also modifies the current transaction duration metric to avoid counting the time spent waiting on the pool. Now, if this metric is out of whack, it should only signal that the query(ies) are inefficient or the database is overloaded.
=> Pool wait time metric

Cargo.lock
=> Update h2, 0.5 backport

Cargo.lock
=> Update h2, 0.6 backport

.github/workflows/ci-build.yml, deny.toml
=> Update cargo-deny config, 0.6 backport

Cargo.lock, aggregator/tests/cmd/aggregation_job_creator.trycmd, aggregator/tests/cmd/aggregation_job_driver.trycmd, aggregator/tests/cmd/aggregator.trycmd
I accidentally merged one feature branch into another feature branch in #2926. This PR re-applies that commit to main.
=> Fix ignored trycmd tests

collector/src/lib.rs
https://github.com/divviup/janus/pull/2998
=> collector: Set Content-Length when polling collection jobs (release/0.6 backport)

aggregator_api/src/routes.rs, aggregator_api/src/tests.rs
Supports https://github.com/divviup/divviup-api/issues/291.
That comment above it was also not telling us anything interesting--all aspects of the configuration are unconditionally specified right now.
=> Advertise support for time bucketed fixed size

Cargo.lock
=> Update rustls, 0.6 backport

Cargo.lock
=> Update rustls, 0.5 backport

Cargo.lock, Cargo.toml, messages/Cargo.toml, messages/src/lib.rs
This closes #2471. Here's some sample output.
=> Improve encoding tests

client/src/lib.rs
add a code example similar to the collector package
=> client: add client example in the docs

Cargo.lock, Cargo.toml, aggregator/src/binary_utils.rs, aggregator_core/src/datastore/test_util.rs, core/src/test_util/testcontainers.rs, deny.toml, integration_tests/src/client.rs, integration_tests/src/daphne.rs, integration_tests/src/janus.rs, integration_tests/tests/integration/common.rs, integration_tests/tests/integration/daphne.rs, integration_tests/tests/integration/divviup_ts.rs, integration_tests/tests/integration/janus.rs, interop_binaries/src/lib.rs, interop_binaries/tests/end_to_end.rs
=> Upgrade testcontainers to 0.16, 0.6 backport

Cargo.lock, Cargo.toml, aggregator_core/src/datastore/test_util.rs, core/src/test_util/testcontainers.rs, integration_tests/src/client.rs, integration_tests/src/daphne.rs, integration_tests/src/janus.rs, integration_tests/tests/common/mod.rs, integration_tests/tests/daphne.rs, integration_tests/tests/divviup_ts.rs, integration_tests/tests/janus.rs, interop_binaries/src/lib.rs, interop_binaries/tests/end_to_end.rs
=> Upgrade testcontainers to 0.16, 0.5 backport

aggregator_core/src/datastore.rs, aggregator_core/src/datastore/tests.rs
=> Reformat inline SQL queries

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collection_job_driver.rs, aggregator/src/bin/janus_cli.rs, aggregator/src/metrics.rs, aggregator_core/src/datastore/tests.rs, core/src/test_util/dummy_vdaf.rs, tools/src/bin/collect.rs
=> Fix Clippy lints, 0.5 branch

aggregator/src/aggregator/aggregation_job_driver.rs
This implements for the Leader what #3119 did for the Helper. Like with the Helper, a rayon threadpool is used to parallelize aggregation computations. These computations respect cancellation (though I'm not sure if anything short of process death will currently cancel the aggregation_job_driver's computations).
=> Parallelize Leader aggregation computations.

.github/workflows/publish-sql-schema.yml, .github/workflows/push-docker-images-release.yml
Use the GitHub Actions repository and organization variables recently introduced to our infra. There should be no functional change here.
=> Use harmonized GAR GitHub Actions variables

core/src/hpke.rs
Accidentally merged the PR without taking the feedback in https://github.com/divviup/janus/pull/3287#pullrequestreview-2167065250.
=> Code golf with HpkeKeypair::test* functions

aggregator/src/binaries/aggregation_job_creator.rs, aggregator/src/binaries/aggregation_job_driver.rs, aggregator/src/binaries/aggregator.rs, aggregator/src/binaries/collection_job_driver.rs, aggregator/src/config.rs, docs/samples/advanced_config/aggregation_job_creator.yaml, docs/samples/advanced_config/aggregation_job_driver.yaml, docs/samples/advanced_config/aggregator.yaml, docs/samples/advanced_config/collection_job_driver.yaml, docs/samples/advanced_config/garbage_collector.yaml, docs/samples/advanced_config/janus_cli.yaml, docs/samples/advanced_config/key_rotator.yaml, docs/samples/basic_config/aggregation_job_creator.yaml, docs/samples/basic_config/aggregation_job_driver.yaml, docs/samples/basic_config/collection_job_driver.yaml, interop_binaries/config/aggregation_job_creator.yaml, interop_binaries/config/aggregation_job_driver.yaml, interop_binaries/config/collection_job_driver.yaml
Follow up to https://github.com/divviup/janus/pull/3288.
=> docs/tests: normalize suffixes

Cargo.lock, Cargo.toml, aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collection_job_driver.rs, aggregator/src/aggregator/garbage_collector.rs, aggregator/src/aggregator/http_handlers.rs, aggregator/src/aggregator/http_handlers/tests/report.rs, aggregator/src/aggregator/problem_details.rs, aggregator/src/binary_utils/job_driver.rs, aggregator/src/metrics.rs, aggregator/src/metrics/tokio_runtime.rs, aggregator/src/trace.rs, aggregator_core/src/datastore.rs
=> Upgrade to opentelemetry-rust 0.24

aggregator_api/src/lib.rs, aggregator_api/src/models.rs, aggregator_api/src/routes.rs, aggregator_api/src/tests.rs, aggregator_core/src/datastore/models.rs
This will be used to extract aggregation metrics.
=> Aggregator API: add aggregation metrics endpoint.

aggregator/src/binaries/aggregation_job_creator.rs, aggregator/src/binaries/aggregation_job_driver.rs, aggregator/src/binaries/collection_job_driver.rs, aggregator/src/binaries/garbage_collector.rs, aggregator/src/binaries/janus_cli.rs, aggregator/src/binary_utils.rs, aggregator/src/main.rs, interop_binaries/src/commands/janus_interop_aggregator.rs
Small change for debugability.
=> Consistently announce service name in startup logs

aggregator_core/src/datastore/test_util.rs
This drops the database associated with an `EphemeralDatastore` when we are done with it. This frees up resources in the database container. Shared memory in particular was the first thing to run out after several hundred simulation test runs in the same database container. The Docker default shared memory limit is somewhat low, 64 MiB, but I don't think we'll need to bump it up if we do this cleanup.
=> Clean up test databases

aggregator/src/aggregator/queue.rs
This fixes a leak of a channel sender, by removing a `forget()` call. We shouldn't leak this sender because the dispatcher task is supposed to run until all senders are dropped. Furthermore, some of our tests amplify this leak by creating and tearing down many queues, which causes file descriptor exhaustion for me locally. Closes #3405.
=> Fix leak of channel sender

docs/DEVELOPMENT.md
=> docs: Avoid improperly using janus_messages::{Time, Duration}

docs/DEPLOYING.md
=> docs: Document safety of running multiple janus' in parallel

Cargo.lock, Cargo.toml, aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/batch_creator.rs, aggregator/src/binaries/aggregator.rs, aggregator/src/binary_utils.rs, aggregator/src/metrics.rs, aggregator/src/trace.rs, aggregator_core/src/datastore.rs, aggregator_core/src/datastore/models.rs, aggregator_core/src/taskprov.rs, collector/src/credential.rs, collector/src/lib.rs, core/src/hpke.rs, core/src/http.rs, core/src/test_util/runtime.rs, core/src/vdaf.rs, interop_binaries/Cargo.toml, interop_binaries/src/lib.rs, messages/src/lib.rs
This fixes some (though not all) lints raised by the latest nightly build of Clippy.
=> Fix nightly Clippy lints

aggregator/src/aggregator/queue.rs
This is a static metric that is just the queue `concurrency + depth`. This allows us to monitor the overall connection capacity of the system, without having to plumb through configuration to Prometheus.
=> metrics: maximum queue depth

aggregator/src/aggregator/queue.rs
After deploying, I noticed that `janus_helper_max_outstanding_requests` only shows up as a single blip in one scrape, and it has no value after that. This PR fixes that by replacing the `Gauge`s with `ObservableGauge`s, so we can always record a value each time a callback is called.
See #3444.
=> Replace gauges with observable gauges

.github/dependabot.yml, .github/workflows/make-release.yml, README.md
* Update README. (a few extraneous cleanups also included)
* Update make-release to release only release/0.7 by default.
* Update dependabot to update release/0.7 by default.
=> Prepare to branch for release/0.7.

messages/src/lib.rs, messages/src/tests/aggregation.rs
Also, add a "reserved" value to match other similar enumerated values.
=> Renumber ReportError values.

aggregator/src/aggregator/http_handlers/tests/aggregation_job_init.rs
A few function arguments were missed.
=> aggregator: fix broken test

Cargo.toml
=> Bump MSRV to 1.81

aggregator_api/src/lib.rs, integration_tests/src/client.rs, integration_tests/tests/integration/in_cluster.rs, interop_binaries/src/commands/janus_interop_client.rs, interop_binaries/src/commands/janus_interop_collector.rs
This fixes miscellaneous Clippy warnings that appear with the 1.87 toolchain.
=> Fix Clippy warnings

aggregator_api/src/lib.rs, integration_tests/src/client.rs, integration_tests/tests/integration/in_cluster.rs, interop_binaries/src/commands/janus_interop_client.rs, interop_binaries/src/commands/janus_interop_collector.rs
=> Fix Clippy warnings, 0.7 backport

aggregator/src/aggregator.rs, aggregator/src/aggregator/collection_job_driver.rs, aggregator_core/src/lib.rs
The family of `Vdaf` traits exposed by crate `prio` is not particularly async aware: they don't impose `Send + Sync` bounds on themselves or their numerous associated types. To use them in our highly async aggregator, we have to write elaborate trait bounds in many places, such as on
`janus_aggregator::aggregator::VdafOps::handle_aggregate_init_generic`:
```rust
async fn handle_aggregate_init_generic<const SEED_SIZE: usize, B, A, C>(
<snip>
) -> Result<AggregationJobResp, Error>
where
B: AccumulableBatchMode,
A: vdaf::Aggregator<SEED_SIZE, 16> + 'static + Send + Sync,
C: Clock,
A::AggregationParam: Send + Sync + PartialEq + Eq,
A::AggregateShare: Send + Sync,
A::InputShare: Send + Sync,
A::PrepareMessage: Send + Sync + PartialEq,
A::PrepareShare: Send + Sync + PartialEq,
for<'a> …
```
=> add `AsyncAggregator` trait and adopt partially

Cargo.lock, Cargo.toml
This upgrades kube-rs, and changes k8s-openapi to target 1.32.
=> Upgrade kube-rs

Cargo.lock, Cargo.toml
This upgrades the testcontainers dependency.
=> Upgrade testcontainers

aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collection_job_driver.rs
I was in the midst of making another, more frustrating change and decided to vent my spleen on some verbose `prio::vdaf::Aggregator` trait bounds. This commit uses the `AsyncAggregator` trait in modules `aggregation_job_driver` and `collection_job_driver` so we can delete a few dozen lines of `where` noise.
=> adopt `AsyncAggregator` in driver modules

aggregator/src/aggregator/aggregation_job_continue.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_init.rs, aggregator/src/aggregator/aggregation_job_writer.rs, aggregator/src/aggregator/batch_creator.rs
Strip some more verbose trait bounds on numerous items throughout `janus_aggregator` by adopting trait `AsyncAggregator`.
Monday warmup PR.
=> Adopt `AsyncAggregator` in more modules

aggregator/src/aggregator.rs, aggregator/src/metrics.rs
This is a backport of #3844. Implements #2729. Note that on this branch, we have to go through some gymnastics to apply explicit histogram boundaries, and we don't handle aggregation initialization from the aggregation job driver, so the instruments appear in fewer places.
=> Add histograms for clock skew of report timestamps, 0.7 backport

aggregator_core/src/datastore.rs
This is a backport of #3848. There have been no intervening changes to this query between the main and release branches.
=> Optimize get_unfilled_outstanding_batches() query, 0.7 backport

aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/binaries/aggregation_job_creator.rs, aggregator/tests/integration/graceful_shutdown.rs, docs/samples/advanced_config/aggregation_job_creator.yaml, integration_tests/src/janus.rs, integration_tests/tests/integration/simulation/arbitrary.rs, integration_tests/tests/integration/simulation/model.rs, integration_tests/tests/integration/simulation/reproduction.rs, integration_tests/tests/integration/simulation/setup.rs
Port of https://github.com/divviup/janus/pull/3829 from `release/0.7` to `main`
Fixes https://github.com/divviup/janus/issues/3427
=> Allow making smaller aggregation jobs after delay

Cargo.lock, Cargo.toml, aggregator/Cargo.toml, aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_writer.rs, aggregator/src/aggregator/report_writer.rs, aggregator/src/binaries/janus_cli.rs, aggregator/src/binary_utils/job_driver.rs, aggregator_api/Cargo.toml, aggregator_api/src/tests.rs, aggregator_core/Cargo.toml, aggregator_core/src/datastore/models.rs, aggregator_core/src/datastore/test_util.rs, aggregator_core/src/datastore/tests.rs, aggregator_core/src/task.rs, aggregator_core/src/taskprov.rs, collector/Cargo.toml, core/src/auth_tokens.rs, docs/DEVELOPMENT.md, integration_tests/tests/integration/common.rs, integration_tests/tests/integration/simulation/bad_client.rs, interop_binaries/src/commands/janus_interop_collector.rs, messages/src/lib.rs
This upgrades the prio and rand crates, and addresses various renames and deprecations.
=> Upgrade prio and rand crates

aggregator/src/metrics/tokio_runtime.rs
These two metrics were stabilized in Tokio v1.45.0.
=> Move two stabilized Tokio runtime metrics

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_continue.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/aggregation_job_driver/tests.rs, aggregator/src/aggregator/aggregation_job_init.rs, aggregator/src/aggregator/error.rs, aggregator/src/aggregator/http_handlers.rs, aggregator/src/aggregator/http_handlers/tests/aggregation_job_continue.rs, aggregator/src/aggregator/http_handlers/tests/aggregation_job_get.rs, aggregator/src/aggregator/http_handlers/tests/aggregation_job_init.rs, aggregator/src/aggregator/http_handlers/tests/helper_e2e.rs, aggregator/src/aggregator/taskprov_tests.rs, core/src/http.rs, messages/src/lib.rs, messages/src/tests/aggregation.rs
=> Convert AggregationJobResp from enum to struct

aggregator_core/src/datastore/leases.rs, aggregator_core/src/datastore/tests.rs
Adds test coverage for database accessors added in #3934
=> Tests for database queries on `MaybeLease`s

.github/workflows/make-release.yml, Dockerfile, Dockerfile.interop, Dockerfile.interop_aggregator, Dockerfile.sqlx
=> Use `cargo install --locked`, 0.7 backport

aggregator/src/aggregator/aggregation_job_init.rs
This check is specified from DAP-15 section 4.6.2.4, item 4.
Fixes #3994
=> Helper must check for reports whose timestamps are before the task starts
