divviup/janus

janus_server/Cargo.toml
Adds `license` and `rust-version` to `janus_server/Cargo.toml`. Since
this crate isn't currently published to crates.io, the former is purely
cosmetic, but the latter should allow us to enforce the use of recent
compilers while working better with dependabot and GitHub CI than a
`rust-toolchain.yaml` does. I chose Rust 1.58 because that's what
[GitHub Actions runners currently
install][1], though we could also run another action to install even
newer toolchains if we so wished.
[1]: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md#rust-tools
=> janus_server: Cargo.toml tweaks

janus_server/Cargo.toml, janus_server/src/message.rs
These vectors encode byte-for-byte what each test message should encode
to. To mitigate against the encoded messages reflecting bugs in our
existing code or dependencies, I generated these encodings mostly by
hand (using the PPM spec & a hex converter). The exception is the HMAC
tags, which were computed using the same ring library as used by the
real code; I think the risk of a bug in ring here is acceptable.
=> Generate "test vectors" for all PPM messages.

janus_server/Cargo.toml, janus_server/src/hpke.rs, janus_server/src/lib.rs, janus_server/src/message.rs
Adds an `hpke` module that can seal messages to a public key and open
them with the corresponding private key. The code is largely cribbed
from `ppm-prototype`, but I stripped out the support for loading HPKE
config from JSON files because we still need to discuss how we want
Janus to handle this. I also made a point of distinguishing the structs
that are responsible for encrypting and decrypting from the wire
messages defined in `mod message`. We are currently using crate `hpke`,
which is awkward to use when you are using dynamic configuration to
figure out what set of HPKE algorithms to use. In this PR, I've wired up
support for two sets of algorithms to illustrate how we might go about
plumbing all the HPKE setups we need.
Part of #12
=> janus_server: Add basic HPKE support

janus_server/Cargo.toml
Closes #3. I tested that this does not conflict with #15.
=> Bump prio to 0.7.0

janus_server/Cargo.toml, janus_server/src/aggregator.rs, janus_server/src/bin/aggregator.rs, janus_server/src/client.rs, janus_server/src/hpke.rs, janus_server/src/lib.rs, janus_server/src/message.rs, janus_server/src/trace.rs, janus_server/tests/integration_test.rs
Adds an aggregator skeleton that randomly generates a TaskId and an
HpkeConfig and implements a functional `/hpke_config` endpoint. Also
adds a simple client module that fetches HPKE configuration from a
leader and helper endpoint and decodes them. Finally, we add an
integration test that spawns aggregators on `0.0.0.0:8080` and
`0.0.0.0:8081` and constructs a client. I'm not sure if this is the best
idea: it's good that this test exercises the `warp` stuff, but it does
mean this test will fail if ports 8080 and 8081 are already bound.
Part of #12
=> janus_server: aggregator with hpke_config endpoint

janus_server/Cargo.toml, janus_server/src/aggregator.rs, janus_server/src/bin/aggregator.rs, janus_server/src/hpke.rs, janus_server/src/lib.rs, janus_server/src/message.rs, janus_server/src/time.rs, janus_server/tests/integration_test.rs
Adds an implementation of an upload endpoint to `src/aggregator.rs`
wired up through a `warp` filter. We check report nonces and HPKE config
IDs per the PPM specification. We also decrypt the leader input share
while handling upload, primarily to exercise HPKE message decryption. We
might choose to not try to do that until the prepare sub-protocol begins
because there's no way to alert the client that decryption failed.
To test error conditions around report nonces, I also introduced a
`time` module which implements a simple clock interface.
We also extend the `aggregator` binary target so that it can be
instructed to run either a helper or a leader by passing the role name
as a positional argument (i.e., `./aggregator leader` or `./aggregator
helper`).
This commit does not implement the …
=> `janus_server`: `/upload` endpoint on aggregator

janus_server/Cargo.toml, janus_server/src/message.rs
This PR includes a few small-but-mostly-related changes:
* Updates to the wire format for request messages based on the recent "interop nits" PR (https://github.com/abetterinternet/ppm-specification/pull/206).
* Introduce authenticated encoder/decoder objects for requests/responses, rather than using ParameterizedEncode/Decode implementations.
* For HPKE-standardized constants, use values from the HPKE library.
* Switch message struct fields from `pub` to `pub(crate)`.
See the individual commit messages for much more detail.
=> Updates to message wire format, authenticated encoding/decoding.

janus_server/Cargo.toml, janus_server/src/datastore.rs
Both provided by the deadpool_postgres crate. I also pull the
ephemeral_datastore() function into a pub(crate) test_util module, since
it will be used by any tests in the crate that have need of a datastore.
=> Datastore: add connection pooling, statement preparation.

janus_server/Cargo.toml, janus_server/src/aggregator.rs, janus_server/src/bin/aggregator.rs, janus_server/src/datastore.rs, janus_server/tests/integration_test.rs
This replaces the previous temporary solution of storing them in-memory
only. This commit also includes some refactoring of the ephemeral
datastore test functionality to make it easier to use & ease later
refactorings.
I'm pretty unhappy about having to make the `datastore::test_util` module
compile under `debug_assertions`; this means I have to upgrade several
test-only dependencies from `dev-dependencies` to `depdendencies`.
Unfortunately, I think this is required because integration tests do not
run in `#[cfg(test)]`. (Better approaches very welcome.)
=> /upload endpoint: store reports to a Datastore.

janus_server/Cargo.toml, janus_server/src/aggregator.rs, janus_server/src/client.rs, janus_server/src/datastore.rs, janus_server/src/hpke.rs, janus_server/src/lib.rs, janus_server/tests/integration_test.rs
Adds an implementation of `upload` to `client::Client`, which is now
generic over `prio::vdaf::Client`.
=> janus_server: implement upload in client

db/schema.sql, janus_server/Cargo.toml, janus_server/src/datastore.rs, janus_server/src/task.rs
This is a quick follow-up to #33 to implement `ToSql` and `FromSql` for our `Vdaf` enum. I added variants to the schema's enum to reflect the multiple instantiations of prio3.
Note that the attribute macro setting the database name of the enum uses lowercase, `"vdaf_identifier"`. This is what the derive macro insisted on, I take it that SQL enum names are case-insensitive like most other objects. The crate must normalize the name to lowercase, and then the generated implementations do their type checks against that.
=> Implement SQL mapping for VDAF enum

janus_server/src/aggregator.rs, janus_server/src/bin/aggregator.rs, janus_server/src/client.rs, janus_server/src/datastore.rs, janus_server/src/hpke.rs, janus_server/src/trace.rs, janus_server/tests/integration_test.rs
`trace::install_subscriber` is now `install_trace_subscriber` to make it
more obvious what the subscriber subscribes to, and
`trace::test_util::install_trace_subscriber` is now
`install_test_trace_subscriber` to make it easier to distinguish between
it and the subscriber intended for non-test cases.
Also installs a test subscriber in a few tests that failed to do so.
=> janus_server: rename subscriber installer fns

README.md, janus_server/Cargo.toml, janus_server/src/trace.rs
This adds a configuration option to enable tokio-console support. Note that I didn't add `--cfg tokio_unstable` to RUSTFLAGS anywhere, so you'll need to rebuild with that, in addition to setting a variable in the configuration, to use it.
This PR will look funny because I am basing it off of #38, which was not merged into main. It appears there's a conflict as well.
=> tokio-console support

janus_server/src/aggregator.rs, janus_server/tests/integration_test.rs
This takes out a now-obsolete TODO comment and uses a couple of unused values in a test case.
=> Miscellaneous cleanups

db/schema.sql, janus_server/src/aggregator.rs, janus_server/src/client.rs, janus_server/src/datastore.rs, janus_server/src/hpke.rs, janus_server/src/message.rs, janus_server/src/task.rs, janus_server/tests/integration_test.rs
Adds support for writing all the fields of a `struct TaskParameters`
into the `tasks` table in the database, with new fields/columns for the
aggregator auth key, HPKE config and HPKE private key. `tasks.ord` is
also now `role` and is an enumerated type with cases for the various PPM
protocol roles.
Part of #48
=> janus_server: write TaskParameters to database

db/schema.sql, janus_server/src/aggregator.rs, janus_server/src/datastore.rs
As part of this, I refactor all tables to have an "artificial" primary
key, which is a BIGINT; internally the datastore code manages the
necessary joins. Code using the datastore uses the "natural" primary
keys--the BIGINT primary keys are not exposed at all.
This simplifies the client code, while keeping join indexes small (which
may help performance) and allowing flexibility in case the "natrual"
primary key for a given entity changes with future changes to the PPM
spec.
=> Hide primary keys from users of the datastore library.

.github/workflows/ci-build.yml, README.md, janus_server/Cargo.toml, janus_server/src/trace.rs
`console-subscriber` and its dependents are responsible for a significant amount of compilation time, and yet they are only usable when compiling with a special RUSTFLAGS value. This puts support behind a non-default Cargo feature. I measured a time savings of 50 seconds (2:28 to 1:38) on a clean release build, so this should give us a noticeable win on CI job runtime.
=> Make console-subscriber an optional dependency

db/schema.sql, janus_server/src/datastore.rs, janus_server/src/task.rs, janus_server/tests/integration_test.rs
With these changes we now store the tolerable clock skew in the tasks table and add functions for fetching task parameters from the database, to be used by aggregators to dynamically discover the defined tasks.
=> `janus_server`: storage of task parameters

janus_server/Cargo.toml, janus_server/src/datastore.rs
A few notes:
* Unfortunately, we can't use podman yet; attempting to start the
Postgres container fails.
* The testcontainers library apparently removed the ability to request
a specific Postgres version, but fortunately the default version is
high enough to have all of the features we care about.
Example error when using podman:
```
thread 'datastore::tests::roundtrip_task' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: string \"docker-entrypoint.sh\", expected a sequence", line: 180, column: 48)', /home/bran/.cargo/registry/src/github.com-1ecc6299db9ec823/testcontainers-0.13.0/src/clients/cli.rs:323:88
```
=> testcontainers: 0.12.0 -> 0.13.0.

janus_server/src/aggregator.rs
This is a quick follow-up to #57, there's one test failure related to a late change.
=> Fix a test failure re. leader-filtered reports

janus_server/src/trace.rs
The upgrade to tracing-subscriber 0.3.10 brings with it some new features for better ergonomics. First, EnvFilter can now be used as a per-layer Filter, rather than only as a Layer. By using it as a Filter on our stdout layers, we can now avoid modifying a global filter when using console-subscriber. Instead, we put EnvFilter on the stdout layer, and Targets on the console-subscriber layer, and the two do not interfere with each other. Additionally, Vec<L: Layer> now implements Layer, so we can create a vector of one or two boxed layers, rather than handling four different Option variables. This will also greatly simplify adding additional subscribers. (such as tracing-opentelemetry)
=> Move EnvFilter to be per-layer, use Vec<Layer>

.github/dependabot.yml
Dependabot should be pointed at the workspace root now, as that's where our lockfile is, and it will be able to discover our crate from there.
=> Point Dependabot at the Cargo workspace root

.github/workflows/ci-build.yml, Dockerfile, README.md
This adds caching to the Dockerfile build through the use of BuildKit, and its cache mounts. The target directory and Cargo registry are both mounted out to persistent cache directories. As `target` is no longer part of image layers, we also copy the final binary out to a different directory. Using cache mounts will give us better caching granularity (including rustc incremental compilation) than we could get by breaking the build into multiple layers.
=> Rewrite Dockerfile to use BuildKit cache mounts

README.md, janus_server/src/bin/aggregator.rs
Currently, we read in a Postgres connection string from the configuration file, and pass that directly to the database library. This change will read a password from the environment variable `PGPASSWORD` if the connection string/URL does not include one, and use that. Splitting the password handling out in this way will make it easy to assemble everything but the password in Terraform, without having to worry about the secrecy of Terraform state files. The password can be plumbed via an environment variable from a Kubernetes secret, separate from the configuration.
=> Get database password from env. var. if not in URL

.github/workflows/ci-build.yml
This invokes the cache action to cache cargo's repository index and our target directory. I'm going to force-push this in a bit and compare timing/outputs to see if it worked.
=> Add caching to non-Docker CI build

Cargo.lock, janus_server/Cargo.toml, janus_server/src/bin/aggregator.rs, janus_server/tests/cmd/aggregator.trycmd
Adding reference tests for --help output is the recommended first step in migrating from clap v2 or structopt to clap v3.
=> Add reference test for command-line help

janus_server/src/aggregator.rs, janus_server/src/bin/aggregator.rs, janus_server/src/client.rs, janus_server/src/datastore.rs, janus_server/src/hpke.rs, janus_server/src/message.rs, janus_server/src/task.rs, janus_server/tests/integration_test.rs
The largest part of this PR is a refactoring of HpkeSender &
HpkeReceiver to be free functions seal/open instead. I think this is a
good refactoring because it binds the application info more directly to
the place it is used (i.e. we know from where we are in the code what
application info to use; passing around HpkeSender/Receiver would allow
potentially binding to _incorrect_ application data).
There are further refactorings possible--most importantly, I think
HpkePrivateKey should effectively always be paired with an HpkeConfig,
since knowing the config is required to use the private key. But this PR
is already big enough without adding even more refactorings on top.
=> Aggregator support for multiple HPKE configs/keys.

Cargo.lock, janus_server/Cargo.toml, janus_server/tests/server_shutdown.rs
This test checks that the aggregator server exits promptly when it receives a SIGTERM signal. By default, Kubernetes requests that containers stop with this signal. Currently, the aggregator binary does not override the default SIGTERM behavior, so it trivially passes this test, but we may override this to give in-flight requests a chance to complete.
Part of #40.
=> Add integration test for SIGTERM behavior

Cargo.lock, janus_server/Cargo.toml, janus_server/src/aggregator.rs, janus_server/src/bin/aggregator.rs, janus_server/tests/integration_test.rs
This registers a SIGTERM handler, and plumbs it through to warp's `bind_with_graceful_shutdown()`. In the integration test, one-shot channels are used to shut down the servers instead of aborting their tasks.
Closes #40.
=> Graceful shutdown of warp server upon SIGTERM

janus_server/src/aggregator.rs, janus_server/src/bin/aggregator.rs, janus_server/src/client.rs, janus_server/src/datastore.rs, janus_server/src/task.rs, janus_server/tests/integration_test.rs
This is one step towards supporting an Aggregator that can handle
multiple tasks.
The next steps are probably to refactor the current Aggregator type
to be named e.g. SingleTaskAggregator, and create a new Aggregator
type that knows how to load tasks/create new SingleTaskAggregators/
route requests to the appropriate SingleTaskAggregator.
Inspired by https://github.com/divviup/janus/pull/55.
=> Make Aggregator non-generic on VDAF type & operate on a Task.

Dockerfile
These are no longer needed by console-subscriber. (which is no longer built by default, in the first place)
=> Remove additional apk packages from Dockerfile

janus_server/src/datastore.rs
This adds tracing spans to `Datastore::run_tx_once()` and the various `Transaction` accessors. Database access is both the major system boundary in our deployment, and also the chief contributor to request latency, so this seems like a natural place to add spans.
=> Instrument Datastore/Transaction methods w/ spans

janus_server/src/aggregator.rs, janus_server/src/message.rs
This resolves a tiny TODO. Also some small code cleanups around the
affected code.
=> Don't copy data being passed through AuthenticatedRequestDecoder.

Cargo.lock, Cargo.toml, Dockerfile, janus_server/Cargo.toml, janus_server/src/datastore.rs, janus_server/tests/server_shutdown.rs, monolithic_integration_test/Cargo.toml, monolithic_integration_test/tests/integration_test.rs, test_util/Cargo.toml, test_util/src/lib.rs
This is stacked on top of #94.
This moves the declaration of items necessary for an ephemeral datastore into a macro in a new crate, `test_util`. This macro is then invoked inside `janus_server` only in its unit tests, as well as separately in each integration test. As a result, `testcontainers` can be removed from `janus_server`'s runtime dependencies.
I'm using a macro tactic here to enable code reuse while keeping `ephemeral_datastore()` out of `janus_server`'s exposed API, and to be able to use it within `janus_server`'s unit tests without setting up a dev-dependency cycle.
=> Make testcontainers a dev-dependency

Cargo.lock, db/schema.sql, janus_server/Cargo.toml, janus_server/src/aggregator.rs, janus_server/src/datastore.rs, janus_server/src/task.rs, janus_server/tests/server_shutdown.rs, monolithic_integration_test/tests/integration_test.rs, test_util/src/lib.rs
This changes the `vdaf` column in `tasks` from being an enum of the different VDAF instantiations to being a JSON object. This JSON object represents the `Vdaf` Rust enum, which now has value-carrying variants, for instances that require parameters, like Prio3Aes128Sum, etc.
=> Store public VDAF params with type in JSON column

.github/workflows/ci-build.yml, Cargo.lock, janus_server/tests/server_shutdown.rs, monolithic_integration_test/Cargo.toml, test_util/src/lib.rs
This includes a few semi-related changes to help diagnose our flaky testcontainers error and clean up the test suite output.
- Turn on logging when running the test suite in CI.
- Log our database connection string after creating a `testcontainers::core::Container` and before dropping it.
- Capture child process output in `server_shutdown`, and only print it on failure.
=> Miscellaneous test logging improvements

janus_server/src/aggregator.rs, janus_server/src/datastore.rs, janus_server/src/message.rs, janus_server/src/task.rs
Implements the helper's `aggregate_share` endpoint. The assumption is
that the process of preparing input shares into output shares will
create rows in `batch_aggregations` and update the `checksum` and
`aggregate_share` columns as individual reports are prepared. Then, all
the `/aggregate_share` handler has to do is sum the aggregate shares it
finds.
Note that this does not include support for the protocol changes in [1].
[1]: https://github.com/ietf-wg-ppm/ppm-specification/pull/224
=> Helper `/aggregate_share` endpoint

test_util/src/lib.rs
The `testcontainers` crate makes use of `docker run` with the `--publish-all` flag to expose our Postgres database for connections. In certain situations, Docker's port allocation assigns different port numbers to the same container via the host's IPv4 and IPv6 addresses. The `get_host_port()` method does not provide which host IP address a
port corresponds to, nor specify which address's port will be returned.
Empirically, it appears that Docker will return port bindings for 0.0.0.0 before ::, and `testcontainers` will select the first port
binding in the list. Thus, as a workaround, we use 127.0.0.1 in the connection string, instead of "localhost", to keep the database client from trying both socket addresses, and possibly connecting to the wrong container.
=> Workaround: connect to ephemeral db on 127.0.0.1

janus_server/src/aggregator.rs, janus_server/src/datastore.rs, janus_server/src/message.rs
Previously, we represented it as a u64. 43f68e38 updated the database
representation to be a byte string; this commit updates the codebase
similarly.
=> Represent nonce randomness as opaque byte string.

janus_server/src/aggregator.rs, janus_server/src/datastore.rs
Previously, it was parameterized by various messages, which was
unnecessarily flexible & somewhat confusing. I modified some tests to
work with Poplar1, to allow testing with a non-unit aggregation
parameter.
While working on this I noticed that
get_batch_unit_aggregations_for_task_in_interval assumes a deterministic
encoding for aggregation params, since it does an index lookup based on
the encoded aggregation parameter. I think this is true for all
aggregation parameters today (prio3 uses the unit type which certainly
qualifies; poplar1 uses BTreeSet which has a deterministic iteration
order). We'll need to ensure this remains true in the future to avoid
the potential for weird bugs -- I can't think of a (performant) way to
do better.
=> Parameterize BatchUnitAggregation by vdaf::Aggregator.

janus_server/src/aggregator.rs, janus_server/src/datastore.rs
This eliminates the NotFound error, which was previously used for this
purpose. I introduce a new error "MutationTargetNotFound" for when a
mutation can't find the row it is supposed to be mutating.
As part of this, I introduce a new UnrecognizedAggregationJob PPM
problem type. Previously, this case would have translated into an
internal server error, which is probably not what we want.
=> Datastore: refactor single-entity getters to return Option<Foo>.

janus_server/src/datastore.rs, janus_server/src/message.rs
This is a fairly mechanical change, just using `.as_bytes()` instead of accessing struct members directly. See also: #18.
=> Make members of TaskId/AggregationJobId private

Cargo.lock, db/schema.sql, janus_server/Cargo.toml, janus_server/src/aggregator.rs, janus_server/src/bin/aggregation_job_creator.rs, janus_server/src/bin/aggregator.rs, janus_server/src/binary_utils.rs, janus_server/src/client.rs, janus_server/src/config.rs, janus_server/src/datastore.rs, janus_server/src/lib.rs, janus_server/src/message.rs, janus_server/src/task.rs, janus_server/src/time.rs, janus_server/src/trace.rs, janus_server/tests/cmd/aggregation_job_creator.trycmd, test_util/src/lib.rs
The concurrency part was the most challenging piece: I would have liked
to have the task-creation worker (i.e. AggregationJobCreator::run()) be
"tightly linked" to the job-creation workers (i.e.
AggregationJobCreator::run_for_task()) in the sense that a
task-discovery worker shutting down would be noticed & cleaned up
immediately (in a select loop). Sadly, the lifetime/ownership issues
involved made this very challenging. Instead, I settled for a strategy
where the task-discovery worker owns a oneshot sender for each
job-creation worker, and is responsible to notice when a task is no
longer relevant; actual shutdown of the job-creation worker is loosely
coupled and may happen later. This approach is hypothetically racy and
definitely slower to notice a lingering no-longer-existent task, …
=> Initial implementation of aggregation job creator.

janus_server/src/aggregator.rs, janus_server/src/datastore.rs, janus_server/src/message.rs, janus_server/src/task.rs, janus_server/src/trace.rs
Make fields private, and expose some additional methods as public.
This is part of #18. I also fixed one rustdoc warning I noticed.
=> Adjust privacy of Time, Duration, and Interval

janus_server/src/aggregator.rs, janus_server/src/bin/aggregation_job_creator.rs, janus_server/src/client.rs, janus_server/src/datastore.rs, janus_server/src/message.rs
This is part of #18. One item of note: I promoted the test-only function `generate_nonce()` to `Nonce::generate()`, since the client needs to do this too.
=> Make Nonce members private, add methods

janus_server/src/aggregator.rs, janus_server/src/client.rs, janus_server/src/message.rs, janus_server/src/time.rs
Both of our implementations of trait `time::Clock` are teeny:
`RealClock` has no fields and `MockClock` only contains a single
`NaiveDateTime`. Therefore it's perfectly reasonable to pass them around
by value, and indeed most places they're used have to apply an extra
`'static` trait bound to safely use them. We now require `'static +
Copy` which lets us simplify generics in a couple of places.
=> require 'static + Copy on trait Clock

Cargo.lock, db/schema.sql, janus_server/Cargo.toml, janus_server/src/aggregator.rs, janus_server/src/datastore.rs
Adds a new database table `aggregate_share_jobs`, used by helper to
store the results of successfully serviced `AggregateShareReq`s. This
allows leaders to retry an `AggregateShareReq` indefinitely, provided
the parameters don't change. The leader's `collect_jobs` table now also
has some nullable columns where it can cache the leader and helper's
aggregate shares, to similarly allow the collector to retry requests to
the collect job URI.
Part of #105
=> Store aggregate share requests serviced by helper

Cargo.lock, Cargo.toml, Dockerfile, janus/Cargo.toml, janus/src/lib.rs, janus/src/message.rs, janus/src/time.rs, janus_server/Cargo.toml, janus_server/src/aggregator.rs, janus_server/src/bin/aggregation_job_creator.rs, janus_server/src/bin/aggregator.rs, janus_server/src/client.rs, janus_server/src/datastore.rs, janus_server/src/hpke.rs, janus_server/src/lib.rs, janus_server/src/message.rs, janus_server/src/task.rs, janus_server/tests/server_shutdown.rs, monolithic_integration_test/Cargo.toml, monolithic_integration_test/tests/integration_test.rs, test_util/Cargo.toml, test_util/src/lib.rs
This moves some of the most primitive types into a common `janus` crate. In the future, this will be reused from separate client and server crates. (with the possible addition of a collector crate as well) Additionally, the methods of `Role` were made public, `MockClock` was moved to the `test_util` crate, and a constructor was added to `TaskId`.
This is part of #18. Next steps: clean up the APIs of `HpkeCiphertext`, `HpkePublicKey`, `HpkeConfig`, `Extension`, `ExtensionType`, and `Report`, move those, and move the `hpke` module.
=> Initial split-out of common crate

test_util/src/lib.rs
Also updates the `current_time` field to be a private `message::Time`.
=> Add public constructor for `MockClock`

janus_server/src/aggregator.rs, janus_server/src/task.rs
Leader now consults the task parameters to determine what base URL to
use when constructing collect job URIs. This assumes that a leader will
serve collect jobs from the same base URL that it serves other endpoints
like `/upload` or `/collect`.
Part of #105
=> Construct collect job URIs from task parameters

.github/workflows/ci-build.yml, Dockerfile
This change to the ENTRYPOINT line fixes two problems. First, by using exec, it makes the server PID 1 again, so that it can receive signals. Second, it propagates command line arguments passed to the container onward to the server. It also adds a simple CI test that the container images can be run successfully.
=> Fix Dockerfile entrypoint, pass args and use exec

Cargo.lock, janus/Cargo.toml, janus/src/hpke.rs, janus/src/lib.rs, janus/src/message.rs, janus_server/src/aggregator.rs, janus_server/src/bin/aggregation_job_creator.rs, janus_server/src/client.rs, janus_server/src/datastore.rs, janus_server/src/hpke.rs, janus_server/src/message.rs, janus_server/src/task.rs
This adds constructors and accessors for the remaining message structs the client will use, and moves them into the common crate. This is part of #18.
=> Refactor and move `Report` and its transitive dependencies

janus/src/hpke.rs
- randomize the generated config ID
- use a less astonishing set of HPKE algos
This is stacked on #157 since that moved HPKE code around and I wanted to avoid merge conflicts.
Closes #158
=> improve generation of test HPKE configs

janus_server/src/aggregator.rs, janus_server/src/bin/aggregation_job_creator.rs, janus_server/src/datastore.rs, janus_server/src/task.rs, janus_server/tests/server_shutdown.rs, monolithic_integration_test/tests/integration_test.rs
This fixes the naming collision underlying #152.
=> Rename task::Vdaf to VdafInstance

Cargo.lock, janus/Cargo.toml, janus/src/message.rs, janus_server/src/aggregator.rs, janus_server/src/datastore.rs, janus_server/src/message.rs
Adds a newtype around `[u8; 32]` to represent the checksum over report
nonces.
=> Introduce `NonceChecksum`

janus_server/src/aggregator.rs, janus_server/src/datastore.rs
Adds a warp filter for path `/collect_jobs/{collect_job_id}` to the
leader. Adds support for querying collect jobs from the datastore as
well as updating them with helper and leader aggregate shares. The
latter is currently only needed for tests, but will soon be used when
running collect jobs.
Part of #105
=> Leader collect job URI handler

janus_server/src/aggregator.rs, janus_server/src/aggregator/accumulator.rs, janus_server/src/datastore.rs
As the helper prepares inputs and obtains output shares, accumulate the
values into rows in `batch_unit_aggregations` (also updating checksum
and report count). These rows will later be used by the
`/aggregate_share` handler to service `AggregateShareReq` messages.
Resolves #164
=> Accumulate prepared output shares in helper

Cargo.lock, janus_server/Cargo.toml, janus_server/src/aggregator.rs, janus_server/src/bin/aggregation_job_creator.rs, janus_server/src/client.rs, janus_server/src/datastore.rs, janus_server/tests/server_shutdown.rs, monolithic_integration_test/Cargo.toml, monolithic_integration_test/tests/integration_test.rs, test_util/Cargo.toml, test_util/src/lib.rs
I didn't rename the directory because I think `janus/test_util` is clear enough vs. `janus/janus_test_util` which stutters unnecessarily.
Closes #151.
=> Rename crate `test_util` to `janus_test_util`.

janus_server/src/bin/aggregation_job_creator.rs, janus_server/src/bin/aggregation_job_driver.rs, janus_server/src/bin/aggregator.rs, janus_server/src/binary_utils.rs, janus_server/src/config.rs, janus_server/src/trace.rs, janus_server/tests/cmd/aggregation_job_creator.trycmd, janus_server/tests/cmd/aggregation_job_driver.trycmd
Factors out common binary startup work like parsing options and config,
setting up metrics and logging and setting up a datastore connection
into a function `binary_utils::janus_main`.
=> Introduce `janus_main`

janus/src/hpke.rs, janus/src/message.rs, janus_server/src/aggregator.rs, janus_server/src/aggregator/accumulator.rs, janus_server/src/bin/aggregation_job_driver.rs, janus_server/src/client.rs, janus_server/src/datastore.rs, janus_server/src/message.rs, janus_server/src/task.rs
Specifically:
* Domain separation parameters updated from "ppm" to "dap-01".
* Task ID moved from application info to AAD for HPKE operations.
I believe this is the final set of changes required for Janus to implement what is specified in main on the DAP specification.
Closes #179. (@jbr, you may be interested in this PR.)
=> Update HPKE usage to align with DAP-01.

janus/src/message.rs, janus_server/src/aggregator.rs, janus_server/src/bin/aggregation_job_driver.rs, janus_server/src/client.rs, janus_server/src/datastore.rs, janus_server/src/message.rs
The content-type changes might seem unrelated at first, but the latest
DAP spec requires parsing the content type to disambiguate between
aggregate initialization requests & aggregate continuation requests, so
I decided to implement content-type setting & checking everywhere it
made sense.
There is one XXX-marked comment, which is waiting on the resolution of
https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/260. I am very
hopeful that the task_id will be included in aggregate continuatiun
requests; otherwise, I will have to add & implement
task-lookup-by-aggregation-job (among the other downsides of making
aggregation job IDs universally unique, covered in more detail in the
issue).
Closes #178.
=> Update message definitions to match latest DAP spec, add content-types.

janus_server/src/bin/aggregation_job_driver.rs, janus_server/src/bin/collect_job_driver.rs, janus_server/src/binary_utils.rs, janus_server/src/binary_utils/job_driver.rs, janus_server/src/config.rs, janus_server/src/datastore.rs, janus_server/tests/server_shutdown.rs
Factors logic for discovering incomplete jobs out of
`aggregation_job_driver` and into a new module.
Adds a skeleton of `collect_job_creator` to show how this is used across
multiple binary targets.
Part of #105
=> Introduce mod `job_driver`

janus_server/src/bin/collect_job_driver.rs, janus_server/src/binary_utils/job_driver.rs
`tracing::info_span` doesn't take ownership of fields passed into it so
we can avoid some unnecessary `Arc::clone`s.
=> Avoid wrapping acquired job in `Arc`

db/schema.sql, janus_server/src/datastore.rs, janus_server/src/message.rs
Updates a few variable names, struct fields, comments and log lines that
referred to the now obsolete `TransitionError` type.
=> Misc `TransitionError` -> `ReportShareError` fixes

janus_server/src/aggregator.rs, janus_server/src/datastore.rs, test_util/src/dummy_vdaf.rs, test_util/src/lib.rs
I needed a VDAF with a non-unit aggregation parameter for testing
collect job logic. While extending the existing `fake::Vdaf` to do that,
I decided to move it into a module under `janus_test_util`, since
`aggregator.rs` is already too big.
=> `janus_test_util`: generic `dummy_vdaf` module

db/schema.sql, janus_server/src/datastore.rs
Adds support for acquiring and releasing leases on collect jobs to the
datastore module, which will soon be used by the collect job driver to
drive jobs.
Part of #105
=> acquire and release collect jobs in datastore

.github/workflows/ci-build.yml, janus_server/src/aggregator.rs, janus_server/src/aggregator/aggregate_share.rs, janus_server/src/bin/aggregation_job_driver.rs, janus_server/src/bin/collect_job_driver.rs, janus_server/src/datastore.rs, janus_server/src/task.rs
Fleshes out the implementation of the Janus collect job driver.
Some existing logic used for the helper's `/aggregate_share` handler is
refactored into `mod aggregate_share` so it can be used in
`collect_job_driver`.
Additionally, the existing methods `update_collect_job_*` methods on
`datastore::Transaction` are collapsed into a single method that sets
helper aggregate share, leader aggregate share, report count and
checksum in a single operation. This simplifies the logic of the collect
job driver since it doesn't have to deal with the case where the
leader's aggregate share was computed but the helper's isn't known yet.
The downside is that if a collect job fails because the helper failed to
compute its aggregate share, then the leader will recompute its share
"from scratch" the next …
=> Collect job driver

janus_server/src/bin/aggregation_job_driver.rs, janus_server/src/bin/collect_job_driver.rs, janus_server/src/binary_utils/job_driver.rs
The future-generating function can own & clone any required contextual
state without assistance from the JobDriver.
=> JobDriver: remove JobStepperContext.

db/schema.sql, janus_server/src/aggregator/aggregate_share.rs, janus_server/src/bin/aggregation_job_driver.rs, janus_server/src/bin/collect_job_driver.rs, janus_server/src/binary_utils/job_driver.rs, janus_server/src/datastore.rs
* The tokens are a (probably-)unique opaque value associated with each
lease, intended to ensure that a release operation affects the same
lease that was acquired.
* On-release sanity checking is implemented by checking that the lease
timeout & token match what is recorded in the in-memory lease. If
they don't, someone else has taken the lease out from under us & we
must fail. Note that we might still be able to release if the lease
expiry time is in the past--the lease expiry time is the first time
someone else _can_ take the lease, if no one else has taken the
lease we can still release it.
* Tracking of acquire counts (since last successful release) will
allow lease users to decide when to permanently fail. (to be
implemented in a pair of upcoming PRs)
I also adapt the JobDriver …
=> Leases: add tokens, on-release sanity checking, acquire counts.

janus_server/src/bin/aggregation_job_driver.rs, janus_server/src/bin/collect_job_driver.rs, janus_server/src/binary_utils/job_driver.rs
The callbacks (job-acquirer, job-stepper) now only receive information
that is managed/computed by the JobDriver itself; data that is
effectively "constant" that the JobDriver was holding onto is now
expected to be owned by the callback itself.
This change may be controversial because it pushes more logic into the
application rather than keeping it in the "helper" JobDriver. I think
it's worthwhile not just from a cleanliness perspective but also because
it opens the door to later cleanups/optimizations--as a minor example,
we could now place the datastore into the {Aggregation,Collect}JobDriver
and no longer need to manage an Arc\<Datastore\>.
=> JobDriver: remove all non-required parameters from callbacks.

Cargo.lock, janus/Cargo.toml, janus_server/Cargo.toml, monolithic_integration_test/Cargo.toml, test_util/Cargo.toml
Release 0.7.1 appears to have all the codec implementations and trait bounds we need.
=> Upgrade libprio-rs to next release

janus_server/src/aggregator.rs
This moves metrics and tracing wrapping filters so that they don't fire until `warp::path` filters have succeeded. The relevant part of filter composition is now handled in a common helper method.
This fixes #211.
There are two other small behavioral changes: `collect_jobs_endpoint` now includes a `warp::get()` in its filter stack, and it was missing a trace filter previously. The new helper method is already paying off :smile:
=> Rearrange wrapping of Warp filters

db/schema.sql, janus_server/src/bin/aggregation_job_driver.rs, janus_server/src/bin/collect_job_driver.rs, janus_server/src/config.rs, janus_server/src/datastore.rs
Failure is implemented as moving the aggregation job to the FINISHED
state. We don't change the state of any of the included report
aggregations, on the theory that we may want to debug the issue &
keeping state around will help with that; this is the only way that an
aggregation job can reach the FINISHED state with report aggregations in
a non-terminal state.
=> Aggregation job driver: give up on jobs that fail too many times.

janus/src/lib.rs, janus/src/task.rs, janus_server/src/aggregator.rs, janus_server/src/aggregator/aggregate_share.rs, janus_server/src/bin/aggregation_job_creator.rs, janus_server/src/bin/aggregation_job_driver.rs, janus_server/src/datastore.rs, janus_server/src/task.rs, janus_server/tests/server_shutdown.rs, monolithic_integration_test/tests/integration_test.rs
This splits out `VdafInstance` into two enums, keeping the "fake" variants in `janus_server`. This is part of #18.
=> Split VdafInstance out into the common crate

Dockerfile
At this stage, it seems more likely that we will use Prometheus than Honeycomb Enterprise/Pro for metrics.
=> Enable prometheus feature in container builds

Cargo.lock, db/schema.sql, janus/Cargo.toml, janus_server/Cargo.toml, janus_server/src/aggregator.rs, janus_server/src/aggregator/accumulator.rs, janus_server/src/aggregator/aggregate_share.rs, janus_server/src/bin/aggregation_job_creator.rs, janus_server/src/bin/aggregation_job_driver.rs, janus_server/src/client.rs, janus_server/src/datastore.rs, janus_server/src/message.rs, janus_server/src/task.rs, monolithic_integration_test/Cargo.toml, monolithic_integration_test/tests/integration_test.rs, test_util/Cargo.toml, test_util/src/dummy_vdaf.rs, test_util/src/lib.rs
This version of libprio-rs implements draft-irtf-cfrg-vdaf-01, which is
the version we are targeting for interop tests.
This change is large but mostly-mechanical. A large number of line
changes are due to the new `L` const generic parameter to the VDAF
Aggregator trait.  This parameter is effectively the underlying PRG's
seed size.  Unfortunately, Rust currently doesn't allow const generic
parameters to be inferred; there is an open issue to resolve this, but
it doesn't appear to have received much attention thus far[1].
[1] https://github.com/rust-lang/rust/issues/80528
=> Update libprio-rs dependency to version 0.8.0.

Cargo.lock, janus/Cargo.toml, janus/src/lib.rs, janus_server/src/bin/aggregation_job_driver.rs, janus_server/src/bin/collect_job_driver.rs, janus_server/src/binary_utils/job_driver.rs, test_util/Cargo.toml, test_util/src/lib.rs, test_util/src/runtime.rs
This adds a new trait that abstracts over `tokio::task::spawn()`, and adds a test-only implementor that monitors when spawned async tasks complete. Tests can create multiple such `TestRuntime`s with different labels, and wait for some number of tasks to be completed before continuing. This addresses one of the two reasons we needed sleeps in tests for. Those tests are rewritten with this new functionality.
`TestRuntime` provides one additional feature: if a task spawned through it panics, then this will be detected, and the test's main task will panic when a related object drops.
This unblocks #253 and partially addresses #234.
=> Monitor completion of some async tasks in tests

janus_server/src/aggregator/aggregate_share.rs, janus_server/src/aggregator/aggregation_job_driver.rs
This implements one test covered in #253, for the collect job driver.
I made a small off-by-one error fix in the job steppers --  they were canceling jobs after one too few runs, because `.lease_attempts()` is 1 on the first time around.
=> Test collect job driver abandon behavior

janus_server/src/aggregator/aggregate_share.rs, janus_server/src/aggregator/aggregation_job_driver.rs
This adds another test parallel to that in #264, checking that aggregation jobs that fail too many times will be abandoned. This closes #253.
=> Test aggregation job driver abandon behavior

janus_server/src/aggregator.rs
If the request to `/aggregate` has the wrong media type, return status code 415 instead of 404.
For reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415. This should be a more intuitive error for this situation.
CC @cjpatton FYI
=> Use 415 Unsupported Media Type in /aggregate

janus_server/src/aggregator/aggregation_job_creator.rs, janus_server/src/datastore.rs
This adds datastore and aggregation job creator methods to support VDAFs with non-unit type aggregation parameters. For now, these are test-only methods. When full Poplar support is added in the future, this can be wired into existing `AggregationJobCreator` code that dispatches upon `VdafInstance`.
Aggregation job creation is likely the place where Janus's behavior will differ the most between Prio and Poplar, because the aggregation job creator must react to new collect jobs, rather than new client reports. Additionally, a report may be placed in more than one aggregate job, so that preparation can be run with multiple aggregation parameters.
This implements part of #225. My intent is to de-risk Poplar in Janus by getting a working query down for this part.
=> Add logic/DB query/tests for future Poplar support

janus_server/src/aggregator/accumulator.rs, janus_server/src/aggregator/aggregation_job_driver.rs
This will allow the collect protocol to complete successfully, since it
relies on the batch_unit_aggregations table being populated.
=> Leader aggregation: update batch_unit_aggregations.

janus_server/src/aggregator/aggregation_job_driver.rs, janus_server/src/bin/collect_job_driver.rs
The removed TODO in aggregation_job_driver.rs is stale because it is no
longer/was never necessary to avoid race conditions with collection.
Specifically:
* We only want to avoid driving aggregation jobs if there is a
_completed_ collect job covering the relevant batch unit. (If there
is an in-progress collect job, we still want to drive aggregation
jobs, since the collect job will be waiting for the aggregation jobs
to complete.)
* We only acquire aggregation jobs whose state is IN_PROGRESS
[datastore.rs, L865].
* The "acquire incomplete collect jobs" operation will only acquire
collect jobs that don't have any IN_PROGRESS aggregation jobs
[datastore.rs, L1381].
(N.B. we will probably want to change the collect acquire operation
eventually, since I suppose it races with the _creation_ of …
=> Remove stale TODOs.

janus_server/src/aggregator.rs
The previous implementation roughly matched DAP-00; the new
implementation matches the current editor's copy of DAP-01.
Part of #221. Closes #273.
=> Update problem types to match latest DAP spec.

janus_server/src/aggregator.rs, janus_server/src/datastore.rs, janus_server/src/message.rs
Per the DAP spec, we respond with a `reportTooLate` error.
Part of #221.
=> Upload: reject reports whose timestamp falls into a collected interval.

.github/workflows/push-docker-images-release.yml
Adds a workflow for building and publishing container images to Google
Artifact Registry when a `janus` release is cut.
Part of https://github.com/divviup/janus/issues/222
=> Ship containers to GAR from CI

janus_server/src/aggregator.rs, janus_server/src/datastore.rs
[`clippy::let_unit_value`](https://rust-lang.github.io/rust-clippy/master/index.html#let_unit_value) was recently upgraded from the "pedantic" category to "style", after some refinements. With a 1.62.0 Rust toolchain, we get two of these lints. This fixes them by shuffling `()` around.
=> Fix new clippy lint

janus_server/src/aggregator.rs, janus_server/src/datastore.rs
The `batch-collected` error is returned when aggregation is attempted
for a report that falls into a batch unit that has already been
collected. The `report-replayed` error occurs when aggregation is
attempted for a report that has already been aggregated.
Also, a few small finished-TODO & naming cleanups.
A few spec-related notes, I will drive the spec changes if these make
sense to reviewers:
* The DAP specification language says to return `report-replayed` "if
the report has already been aggregated." However, some VDAFs (e.g.
poplar1) require aggregating the same report multiple times with
varying aggregation parameters. I think the DAP specification should
be updated to return `report-replayed` if the report has already
been aggregated _with the same aggregation parameter_.
* The DAP …
=> Return batch-collected & report-replayed from helper aggregation.

.github/workflows/publish-sql-schema.yml
On release, we use `gcloud storage` to upload the SQL schema file to
a GCS bucket. We version the artifacts by uploading them under a
"directory" named after the git tag. This allows us to upload multiple
SQL files in the future and doesn't require the consumer of the SQL
files to parse out or otherwise ignore the version component.
Part of #222
=> Publish SQL schema to GCS bucket

Cargo.lock, janus_client/Cargo.toml, janus_core/Cargo.toml
Bump the `janus_core` and `janus_client` crate versions to 0.1.2 so that
we can cut a `janus` release and exercise the artifact publishing
workflows e2e.
Part of #222
=> Bump Rust crates to 0.1.2

janus_client/src/lib.rs, janus_core/src/message.rs, janus_server/src/aggregator.rs, janus_server/src/aggregator/aggregate_share.rs, janus_server/src/aggregator/aggregation_job_driver.rs, janus_server/src/datastore.rs, janus_server/src/message.rs, monolithic_integration_test/tests/integration_test.rs
This implements the change in ietf-wg-ppm/draft-ietf-ppm-dap#281, rounding down timestamps of reports to the next multiple of `min_batch_duration`.
=> Round down timestamps in report nonces

Cargo.lock, janus_server/src/aggregator.rs, janus_server/src/aggregator/aggregate_share.rs, janus_server/src/aggregator/aggregation_job_creator.rs, janus_server/src/aggregator/aggregation_job_driver.rs, janus_server/src/bin/aggregation_job_driver.rs, janus_server/src/bin/aggregator.rs, janus_server/src/bin/collect_job_driver.rs, janus_server/src/binary_utils/job_driver.rs, monolithic_integration_test/Cargo.toml, monolithic_integration_test/tests/integration_test.rs
Also, clean up some double-logging in the aggregator HTTP handlers, and tweak some log lines & error messages.
Closes #290.
=> Add metrics to job drivers & for partial failures in HTTP handlers.

janus_core/src/test_util/dummy_vdaf.rs, janus_server/src/aggregator.rs, janus_server/src/aggregator/aggregate_share.rs, janus_server/src/aggregator/aggregation_job_creator.rs, janus_server/src/datastore.rs
This is nice since the additional condition actually simplifies the
checks somewhat -- we no longer have to care about the case of
partially-overlapping batch intervals. This also allows cleanup of some
non-standard datastore operations to follow the standard "find" pattern.
The dummy VDAF implementation is expanded to have a concrete aggregation
parameter in all cases, since now consuming more than one unit of batch
lifetime can only happen if we vary an aggregation parameter. Tests that
care about aggregation parameters can use them; tests that don't can
always use a single value, such as zero, for the aggregation parameter.
Closes #149.
=> Constrain collect requests to non-overlapping batch intervals.

janus_server/src/aggregator.rs, janus_server/src/datastore.rs
This is a first effort towards #36, adding a health check endpoint that tests if our database connection pool is able to connect. We can use this in Kubernetes readiness checks and in GCP load balancer health checks for our Ingress.
=> Add a simple health check endpoint

Cargo.lock, janus_client/Cargo.toml, janus_core/Cargo.toml, janus_server/Cargo.toml, janus_server/tests/cmd/aggregation_job_creator.trycmd, janus_server/tests/cmd/aggregation_job_driver.trycmd, janus_server/tests/cmd/aggregator.trycmd
In the interest of getting a new aggregator image out that includes the health check endpoints, I suggest we cut a release for version 0.1.3. I chose to increment the version of the `janus_server` crate as well, so that container tags and `--version` output match. I fixed up the CLI reference tests with wildcards as well.
=> Increment versions to 0.1.3

.github/workflows/ci-build.yml, README.md, janus_core/src/test_util/kubernetes.rs
By default, `kind` would install a node image for Kubernetes 1.24, which
is a couple minor versions past what we deploy to cloud environments and
which runs afoul of some Terraform bugs[1]. Pin the Kind node image we
use to a Kubernetes 1.22 image, to match the Kind we use in other CI
contexts.
[1]: https://github.com/hashicorp/terraform-provider-kubernetes/issues/1724
=> Pin Kind node image used in EphemeralCluster

Cargo.lock, janus_server/Cargo.toml, janus_server/src/aggregator.rs, janus_server/src/bin/aggregator.rs, janus_server/src/binary_utils.rs, janus_server/src/config.rs, janus_server/src/datastore.rs, janus_server/tests/server_shutdown.rs
When deployed to GCP, Janus connects to its Postgres database through
the `cloud-sql-proxy`, which is deployed as a sidecar container to Janus
itself. Kubernetes provides no guarantees about the order in which it
will start the containers in a pod, which means that it's possible for
Janus components to attempt to connect to the proxy before it has
started and established a connection to the real database, which will
fail with "connection refused". This is a problem for the
`aggregation_job_creator`: it is configured to query the database once
an hour for defined tasks, so if it fails to do so at startup, it won't
retry for an hour. Other Janus components either query the DB in
response to API traffic or poll the database more often.
With this change, we now wait up to 60 seconds while …
=> Set timeouts in deadpool_postgres

janus_server/src/aggregator.rs, janus_server/src/bin/aggregation_job_creator.rs, janus_server/src/bin/aggregation_job_driver.rs, janus_server/src/bin/aggregator.rs, janus_server/src/bin/collect_job_driver.rs, janus_server/src/bin/janus_cli.rs, janus_server/src/binary_utils.rs, janus_server/src/config.rs, janus_server/src/datastore.rs, janus_server/tests/cmd/aggregation_job_creator.trycmd, janus_server/tests/cmd/aggregation_job_driver.trycmd, janus_server/tests/cmd/aggregator.trycmd
Now, commands that don't use the database won't crash out if they aren't
given --datastore_keys. Note that we still require a config to be
specified, which must specify a DB connection string -- I think this is
OK since I suspect folks will create & leave around configs for the
environments they care about.
There are a few other bits in this commit: most notably, I drop the
startup probe endpoint, as now we do our connect-to-database check every
time we create a new pool -- since we create the pool before we start
serving, the aggregator will not appear live (i.e. will not respond
positively to /healthz) until we have confirmed that we have a DB
connection. (I think Tim noted this.) This lets me drop the connection
pool checking logic included in the datastore, since it now lives with …
=> janus_cli: don't require --datastore_keys unless they are used.

Cargo.lock, README.md, janus_server/src/aggregator.rs, janus_server/src/bin/aggregator.rs, monolithic_integration_test/Cargo.toml, monolithic_integration_test/tests/integration_test.rs
This adds a new optional field to the configuration file, with extra response headers to be added to outgoing responses.
Note that, as this uses Warp filters, it will not add the headers to requests that are rejected by our filter stack. If we wanted to do so, we would have to write some boilerplate to turn the Warp filter into a `hyper::service::Service`, add a header-setting middleware to it, and then use Hyper's TCP server directly. I opted not to go this route until we have a need for headers on error responses. (for example, only eTLD+1s are eligible for automatic enrollment in HSTS preloading, so it's okay if Janus can't serve a preload enrollment header on 404 responses for `/`)
=> New configuration option, extra response headers

Cargo.lock, README.md, janus_core/Cargo.toml, janus_core/src/test_util/kubernetes.rs, janus_server/Cargo.toml
This PR does the following:
- Clean up the `janus_server` self-dev-dependency as discussed in #327.
- Extends the `create_clusters()` test in `janus_core` to test connecting to the clusters.
- Fix up `janus_core` dev-dependencies, so that `cargo test -p janus_core` works. (previously, this relied on Cargo coalescing features set by `janus_server`'s dev-dependencies when running `cargo test`)
- Document all of our crates' features.
- Document the `cargo run --bin janus_cli --features kube-openssl` suggestion in the context of the features list.
With this, I think we can close #327.
=> Clean up kube features, document crate features

janus_server/src/aggregator.rs, janus_server/src/bin/aggregation_job_creator.rs, janus_server/src/bin/aggregation_job_driver.rs, janus_server/src/bin/aggregator.rs, janus_server/src/bin/collect_job_driver.rs, janus_server/src/bin/janus_cli.rs, janus_server/src/binary_utils.rs, janus_server/src/config.rs, janus_server/tests/server_shutdown.rs
This moves the `/healthz` endpoint to a separate HTTP server, on its own port, and adds health checks to the three remaining server components. This change adds a new required parameter to the configuration files. Part of #36.
=> Serve health check requests on a separate port

db/schema.sql, janus_server/src/aggregator.rs, janus_server/src/datastore.rs, janus_server/src/task.rs, monolithic_integration_test/tests/integration_test.rs
Authentication of the /collect endpoint is mandated by the DAP
specification. Authentication of the collect job endpoints is not, but
IMO it's a good idea.
Closes #343.
=> Authenticate collector requests.

.github/workflows/ci-build.yml, .github/workflows/push-docker-images-release.yml
This tacks on janus_cli to the list of containers we build. We can make use of this in automated Kind-based integration tests, to set up a task definition, and generally we can run it in-cluster for other maintenance tasks.
=> Build containers for janus_cli

Cargo.lock, Dockerfile, janus_core/Cargo.toml, janus_server/Cargo.toml, monolithic_integration_test/Cargo.toml, monolithic_integration_test/src/lib.rs
This moves most of monolithic_integration_test and its novel dependencies behind a new "test-util" feature flag, similar to the other
crates. With this, our release builds will no longer have the feature flags janus_core/test-util, janus_server/test-util, nor reqwest/default-tls set, due to crate feature flags being unified across the workspace. As a result, we can once again eliminate OpenSSL as a build-time dependency.
I also fixed a tangentially related inaccuracy in some comments that Tim pointed out.
=> Add features to monolithic_integration_test

Cargo.lock, README.md, janus_server/Cargo.toml, janus_server/src/bin/aggregator.rs, janus_server/src/metrics.rs, janus_server/src/trace.rs
This upgrades `serde_yaml`, and uses the new `serde_yaml::with::singleton_map` module in our configuration structs to opt out of the new format for value-carrying enum variants. By default, `serde_yaml` 0.9 would use YAML tags (prefixed with a `!`) to delimit enum variants that hold one or many values. The new attributes both preserve our prior configuration file format (mostly) and work around a bug I encountered where I couldn't get serde to parse `!Tag`-ged enum variants nested anywhere inside a `#[serde(flattened)]` struct. I've got a reduced test case for that mostly ready, and I'll report it upstream separately. I did have to make one change to the Jaeger configuration file example, because the new code is stricter about unit variants, and only lets them be represented as strings, …
=> Upgrade to serde_yaml 0.9

janus_server/src/aggregator.rs, janus_server/src/aggregator/aggregate_share.rs, janus_server/src/aggregator/aggregation_job_creator.rs, janus_server/src/aggregator/aggregation_job_driver.rs, janus_server/src/binary_utils/job_driver.rs, janus_server/src/datastore.rs
This closes #342. All counter and histogram metrics are renamed to have a common `janus_` prefix.
=> Rename metrics with common prefix

.github/workflows/ci-build.yml
Sets `RUST_LOG` to `info` instead of `trace` to reduce noise in test
output.
A number of dependabot PRs were failing, but then would succeed when re-run. GitHub seems to disappear the logs from failed tests so I have attached an archive of logs from one such failure. In any case, it's hard to read these logs because they're nearly 40,000 lines long, since `RUST_LOG` was set to `trace`.
[logs_875.zip](https://github.com/divviup/janus/files/9293522/logs_875.zip)
=> Turn down log level in Rust CI test

janus_client/src/lib.rs, janus_server/src/aggregator.rs, janus_server/src/aggregator/aggregate_share.rs, janus_server/src/aggregator/aggregation_job_driver.rs
This adds a new error variant to the aggregator's `Error` type, and checks status codes received from `/aggregate` and `/aggregate_share` endpoints.
=> Check HTTP status codes from other aggregator

Cargo.lock, janus_client/src/lib.rs, janus_server/src/aggregator.rs, janus_server/src/aggregator/aggregate_share.rs, janus_server/src/aggregator/aggregation_job_driver.rs, janus_server/src/task.rs, monolithic_integration_test/Cargo.toml, monolithic_integration_test/src/janus.rs, monolithic_integration_test/tests/common/mod.rs, monolithic_integration_test/tests/janus.rs
There are fixes to two separate unexpected behaviors of the Url::join method:
* If a URL which does not end with a slash is joined with something, the final portion of the path is removed from the URL before the joined portion is added.
* If a URL is joined with something which starts with a slash (i.e. an absolute path), the original path is entirely replaced by the joined absolute path. (This one isn't documented!)
I also update the Janus-Janus monolithic integration test to exercise the previously-untested case of an aggregator endpoint which has a nontrivial path.
=> Fix usage of Url::join.

janus_core/Cargo.toml
We don't actually use this dependency (directly) anywhere. It's pulled
in via `kube`; we only specify it so that we can specify the `v1_20`
feature. We previously specified a wildcard version since we just want
to match what `kube` pulls in. Unfortunately, crates.io disallows the
use of wildcard versions, which blocks us publishing 0.1.5 to crates.io:
```
error: failed to publish to registry at https://crates.io
Caused by:
the remote server responded with an error: wildcard (`*`) dependency constraints are not allowed on crates.io. See https://doc.rust-lang.org/cargo/faq.html#can-libraries-use--as-a-version-for-their-dependencies for more information
```
Now, we just specify what is getting pulled in anyway. The downside is
that we'll need to do manual work to keep these in sync if `kube` …
=> janus_core: specify version of k8s-openapi.

janus_core/Cargo.toml, janus_server/Cargo.toml
This is a guess; I get the same error as in
https://github.com/divviup/janus/pull/386, but the only remaining "*"
dependencies are dev-dependencies. Unhelpfully, `cargo publish
--dry-run` does not encounter this error.
IMO this is a wart in cargo/crates.io: "\*" dependencies aren't allowed
since it means "this will work with every version ever". But specifying
"\*" is the only way to say "I don't care, use whatever version is
already included due to other dependencies." There's apparently no way
to add a feature to an already-included dependency and also publish to
crates.io.
=> Specify versions for dev dependencies, too.

Cargo.lock, janus_client/Cargo.toml, janus_core/Cargo.toml, janus_server/Cargo.toml
Due to further crates.io publishing woes.
DO NOT MERGE until #388 is merged.
=> Increment versions to 0.1.7.

janus_server/src/aggregator.rs, janus_server/src/task.rs, monolithic_integration_test/src/daphne.rs, monolithic_integration_test/tests/common/mod.rs
This matches how things will be configured: helpers don't have knowledge
of the leader-collector auth token.
Also, update aggregator endpoint checks to return a 404 if the endpoint
doesn't apply to the task role BEFORE checking auth. I think this makes
more sense since I suppose the desired semantics are "the resource does
not exist if the task is for the wrong role" and it doesn't make sense
to authenticate against a task that doesn't exist.
Closes #370.
=> Task: require/allow collector_auth_token iff we are in Leader role.

.github/workflows/ci-build.yml, .github/workflows/push-docker-images-release.yml, Cargo.lock, Cargo.toml, Dockerfile.interop, Dockerfile.interop_aggregator, interop_binaries/Cargo.toml, interop_binaries/src/bin/janus_interop_aggregator.rs, interop_binaries/src/bin/janus_interop_client.rs, interop_binaries/src/bin/janus_interop_collector.rs, interop_binaries/src/lib.rs, interop_binaries/supervisord.conf, interop_binaries/tests/end_to_end.rs, janus_client/src/lib.rs, janus_core/src/hpke.rs, janus_core/src/time.rs, janus_server/src/aggregator.rs, janus_server/src/aggregator/aggregate_share.rs, janus_server/src/aggregator/aggregation_job_creator.rs, janus_server/src/aggregator/aggregation_job_driver.rs, janus_server/src/binary_utils/job_driver.rs, janus_server/src/datastore.rs, janus_server/src/task.rs, monolithic_integration_test/src/daphne.rs, monolithic_integration_test/tests/common/mod.rs, monolithic_integration_test/tests/daphne.rs, monolithic_integration_test/tests/janus.rs
This adds three new binaries (and container images) to support draft-dcook-ppm-dap-interop-test-design. It includes an end-to-end test that exercises the binaries using the test APIs.
The following items are made public or moved out from behind "test-util" features to support this:
- `janus_server::aggregator::aggregator_filter()`
- `janus_core::hpke::generate_hpke_config_and_private_key()`
- `janus_core::time::MockClock`
=> Implement interoperation test API

Cargo.lock, janus_client/Cargo.toml, janus_core/Cargo.toml, janus_server/Cargo.toml
This will allow us to deploy a version of Janus that enforces that no collector auth token is provided to helpers.
=> Increment versions to 0.1.8

.github/workflows/ci-build.yml
In a recent PR of mine, the `janus_server_docker` step in `ci-build.yml`
took nearly 45 minutes[1]. It takes 18 minutes to build the
`janus_server` container from `Dockerfile`, and then the builds for the
other Janus components are quite swift because the build cache gets
mounted in. But it doesn't appear to speed up the build of
`janus_interop_client`, which takes another 15-16 minutes.
In this commit, we break out the builds of the `janus_interop_client`,
`janus_interop_aggregator` and `janus_interop_collector` containers into
their own job, so that GitHub can run those in parallel with building
the other containers and with running `janus_server_build`.
[1]: https://github.com/divviup/janus/runs/7887936297?check_suite_focus=true
=> Run container builds in parallel

Cargo.lock, janus_client/Cargo.toml, janus_client/src/lib.rs, janus_server/src/aggregator.rs, janus_server/src/aggregator/aggregate_share.rs, janus_server/src/aggregator/aggregation_job_creator.rs, janus_server/src/aggregator/aggregation_job_driver.rs, janus_server/src/config.rs, janus_server/src/task.rs
This makes the following changes to slim down Debug output:
- Skip logging OpenTelemetry SDK instruments. These are always going to be the same, and they are only included in structs or function arguments for performance.
- Skip logging a Tokio channel receiver in one location.
- Modify Debug implementations to print out `Url` objects with their Display formatting, for conciseness.
Examples of "before" output:
```
"job_creation_time_recorder":"ValueRecorder(SyncInstrument { instrument: SyncInstrument { instrument: Instrument { descriptor: Descriptor { name: \"janus_job_creation_time\", instrument_kind: ValueRecorder, number_kind: F64, config: InstrumentConfig { description: Some(\"Time spent creating aggregation jobs.\"), unit: Some(Unit(\"seconds\")), instrumentation_library: …
```
=> Trim down overly verbose Debug output

janus_server/src/trace.rs
By default, the JSON tracing subscriber emits both the current span's fields, in an object under the "span" key, and all fields of all spans, under the "spans" key. This disables the former to reduce duplication.
=> Skip "span" attribute in JSON logging output

janus_server/src/aggregator/accumulator.rs, janus_server/src/datastore.rs, janus_server/src/message.rs
This removes aggregation parameters from logs, as they may be sensitive with Poplar. Part of #392.
=> Remove aggregation parameter from logs and Debug implementations

.github/workflows/ci-build.yml, Cargo.toml, interop_binaries/build.rs, interop_binaries/src/testcontainer.rs
* Split the main build steps from the lint-like steps to ensure the cache does not include the lint-like steps' outputs.
* Use a more precise caching strategy.
* Disable incremental compilation.
* Disable debuginfo.
* Allow `cargo clippy` to skip building the interop test container.
Before these changes, a CI run I kicked off this morning took 45 minutes: https://github.com/divviup/janus/actions/runs/2891132620
With these changes, CI runs are more like 21 minutes: https://github.com/divviup/janus/actions/runs/2892438113
... or 30 minutes on a cache miss: https://github.com/divviup/janus/actions/runs/2892294130
Most of the strategies in this PR were taken from [Fast Rust Builds](https://matklad.github.io/2021/09/04/fast-rust-builds.html).
=> CI buildtime improvements.

janus_core/src/message.rs, janus_server/src/aggregator/accumulator.rs, janus_server/src/aggregator/aggregation_job_driver.rs, janus_server/src/datastore.rs, janus_server/src/message.rs
This excludes logging the contents of HPKE ciphertexts and various VDAF messages. Each of these is not meaningful on its own, either due to encryption or secret sharing, and would not be worth the space they take up. Moreover, not logging report shares raises the difficulty of attacking multiple aggregators to compromise privacy, by keeping report shares out of the blast radius of logging systems.
This is part of #392.
=> Exclude ciphertexts and VDAF messages from logs

Cargo.lock, janus_client/Cargo.toml, janus_client/src/lib.rs, janus_core/Cargo.toml, janus_core/src/lib.rs, janus_core/src/retries.rs, monolithic_integration_test/tests/janus.rs
Adds a new module `janus_core::retries` which uses crate `backoff` to
allow retrying HTTP requests based on whether an error is transient. We
retry if we encounter:
- failures to connect (i.e., connection refused or reset);
- timeouts;
- HTTP errors in the 500 range.
The error classification depends on methods on `reqwest::Error` and
walking the chain of `std::error::Error::source` errors to see if there
is an `std::io::Error` under the covers.
We also use `ClientBuilder::timeout` to set a 10 second timeout on
individual HTTP requests (note this is distinct from the overall 600s
timeout applied to a sequence of retries of HTTP requests).
Resolves #196
=> Retries in HTTP clients

.github/workflows/ci-build.yml, Cargo.lock, janus_server/Cargo.toml
A version bump last week broke builds with the "otlp" feature enabled. We construct some objects using the `tonic` crate, and pass them to `opentelemery-otlp`, which does not re-export any of the `tonic` types it expects. The difference in crate versions was causing errors due to mismatching types. This PR reverts that version bump, makes note of the constraint between the two packages, and adds an `--all-features` step to the CI to catch such issues in the future.
=> Fix build with "otlp" feature

janus_server/src/bin/janus_cli.rs, janus_server/src/binary_utils.rs
`janus_cli decode-dap-message` can read binary encoded DAP wire messages
from either stdin or a file and then decode them as a specified message
type, printing the `std::fmt::Debug` representation of the decoded
message to stdout.
`janus_cli` uses some of the scaffolding from the `janus` server
binaries for option parsing, and so it used to expect to be provided a
configuration file with logging and particularly datbase config. That
isn't needed for the `decode-dap-message` command, so we also make the
config file path optional.
Resolves #441
=> `janus_cli`: add DAP message decoder

janus_server/src/bin/janus_cli.rs, janus_server/src/binary_utils.rs, janus_server/src/config.rs, janus_server/src/datastore.rs
In order to provision tasks, `janus_cli` needs the datastore key, used
encrypt some database rows. This key can be provided with
`--datastore-keys`, but since `janus_cli` has to talk to a Kubernetes
cluster anyway, it can also fetch the secret value from Kubernetes
secrets, which is fewer steps for an operator (no need to fetch the
secret before running `janus_cli`) and less risk of exposing the
datastore key to an operator workstation (or worse, an operator's
clipboard).
=> `janus_cli`: automatically discover datastore keys

janus_server/src/bin/janus_cli.rs, janus_server/src/binary_utils.rs, janus_server/src/config.rs, janus_server/src/datastore.rs
In order to provision tasks, `janus_cli` needs the datastore key, used
encrypt some database rows. This key can be provided with
`--datastore-keys`, but since `janus_cli` has to talk to a Kubernetes
cluster anyway, it can also fetch the secret value from Kubernetes
secrets, which is fewer steps for an operator (no need to fetch the
secret before running `janus_cli`) and less risk of exposing the
datastore key to an operator workstation (or worse, an operator's
clipboard).
Resolves #409
=> `janus_cli`: discover datastore keys in k8s secrets

interop_binaries/src/lib.rs
This adds timeouts to requests made during integration tests when waiting for a container to be ready. I saw some tests hang here infrequently during local testing. This is part of #426.
=> Add timeout when checking container readiness

Cargo.lock, integration_tests/Cargo.toml, integration_tests/README.md, integration_tests/build.rs
This updates our Daphne dependency to pick up cloudflare/daphne#112, which should hopefully reduce test flakes.
=> Update Daphne to pick up atomicity fix

integration_tests/README.md
This adds mention of the prebuilt image and GitHub Actions secrets to "Updating the version of Daphne under test".
=> Daphne update docs: rebuild image

Cargo.lock, integration_tests/Cargo.toml, interop_binaries/Cargo.toml, interop_binaries/src/bin/janus_interop_client.rs, interop_binaries/src/bin/janus_interop_collector.rs, interop_binaries/src/lib.rs, interop_binaries/tests/end_to_end.rs, janus_client/Cargo.toml, janus_core/Cargo.toml, janus_core/src/retries.rs, janus_core/src/task.rs, janus_server/Cargo.toml, janus_server/src/aggregator.rs, janus_server/src/aggregator/aggregate_share.rs, janus_server/src/aggregator/aggregation_job_creator.rs, janus_server/src/aggregator/aggregation_job_driver.rs, janus_server/src/datastore.rs, janus_server/src/task.rs
Adds support to Janus for an extra VDAF. Also plumbs it into the interop
test API, which required allowing the representation of vectors of
numbers to a `Measurement`, and unconditionally representing numbers as
strings to avoid JSON number precision problems. A change to
draft-dcook-ppm-dap-interop-test-design will follow to update the
language describing how to encode measurements and aggregate results.
Resolves #478
=> Plumb `Prio3Aes128CountVec` VDAF throughout Janus

interop_binaries/Cargo.toml, janus_client/Cargo.toml, janus_core/Cargo.toml, janus_server/Cargo.toml
This updates our version requirement on Tokio to 1.21. Note that there is no change to Cargo.lock; our lock file's version of Tokio is already at 1.21.0 due to some other recent upgrades. Since we upgraded `console-subscriber`, this is the only possible version we can select now (as it requires `tokio = ^1.21`), and later changes that regenerated the lockfile with Cargo reified this.
=> Update tokio requirement to 1.21

Cargo.lock, integration_tests/Cargo.toml, interop_binaries/Cargo.toml, janus_client/Cargo.toml, janus_core/Cargo.toml, janus_server/Cargo.toml
This prepares for a release of version 0.1.11. `cargo publish --dry-run -p janus_core` and `cargo publish --dry-run -p janus_client` both succeed.
=> Bump crate versions to 0.1.11

.github/workflows/ci-build.yml
As of recently, we scrape logs out of running Janus or Daphne containers on unit test failures. However, if the test that fails isn't one that spawns a container, then the "Upload container logs" step fails because there are no log files to copy out. This isn't critical, because the action was going to fail no matter what due to the test failure, but it does cause the failure to be attribute to the wrong thing.
Example failing test run:
https://github.com/divviup/janus/runs/8277844344?check_suite_focus=true
=> Don't fail copy logs step if no logs are found

Cargo.lock, janus_server/Cargo.toml, janus_server/src/bin/aggregation_job_creator.rs, janus_server/src/bin/aggregation_job_driver.rs, janus_server/src/bin/aggregator.rs, janus_server/src/bin/collect_job_driver.rs, janus_server/src/bin/janus_cli.rs, janus_server/src/binary_utils.rs, janus_server/tests/cmd/aggregation_job_creator.trycmd, janus_server/tests/cmd/aggregation_job_driver.trycmd, janus_server/tests/cmd/aggregator.trycmd
`structopt` has been migrated into `clap`, so we now use `clap::Parser`, which is virtually a drop-in replacement for `structopt::Structopt`, using the instructions in `clap`'s handy migration guide[1]. The name `Structopt` is still exported from `clap`, but it's easy enough to adopt `clap::Parser` instead. There's no changes except some minor diff in the help output of binaries. We also add simple tests based on `clap::App::debug_assert` as suggested in the migration guide.
[1]: https://github.com/clap-rs/clap/blob/v3-master/CHANGELOG.md?plain=1#L584
Resolves #177
=> Migrate from `structopt` to `clap::Parser`

Cargo.lock, integration_tests/Cargo.toml, integration_tests/tests/daphne.rs
These will be re-enabled once our DAP-02 implementation is complete.
Also clean up the integration_tests' Cargo.toml. Mark a few dependencies non-optional (previously they were gated on the daphne feature, but were actually required whether or not that feature was enabled), and mark a few others optional or remove them entirely.
=> Disable Daphne integration tests.

integration_tests/src/janus.rs
This fixes compilation of Janus with a nightly compiler. (useful for things like `cargo-udeps`) I moved the constructor that produces `Janus<'static>` into its own impl block, so that `Self` will have the correct lifetime.
I minimized the issue to the following snippet: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=7e82812f25083e301c7964fd5ed08323. I can't tell if this is a true regression in rustc, or if this was on us for not lining up lifetimes correctly. At any rate, here's what `cargo-bisect-rustc` pointed to:
searched nightlies: from nightly-2022-08-01 to nightly-2022-09-13
regressed nightly: nightly-2022-08-05
searched commit range: https://github.com/rust-lang/rust/compare/1b57946a405d5b2a87e612335db033edb2c3427f...f6f9d5e73d5524b6281c10a5c89b7db35c330634 …
=> Fix compilation with nightly compiler

interop_binaries/src/bin/janus_interop_aggregator.rs, interop_binaries/tests/end_to_end.rs, janus_server/src/message.rs
This should fix some CI flakiness I've been seeing today. The end_to_end integration test was taking 12-14s on my machine, and the code gave it ~15s (plus request time) to complete, which is uncomfortably close. I have extended that limit to 60s flat, and rewritten the loop using the backoff crate, to be less boutique.
I think the recent rewrite of `janus_interop_collector` likely caused this, because it made `/internal/test/collect_poll` requests much faster, as they no longer make subsidiary requests, instead only checking sync primitives in memory. This effectively decreased the amount of time we allowed the test to run before timing out. Combined with the constrained resources of CI builders, this pushed it past the deadline too often.
I separately plan to tune the various timers in …
=> Extend collect timeout in end_to_end test

janus_server/src/aggregator.rs, janus_server/src/aggregator/aggregation_job_driver.rs
This reduces the severity of several tracing events from `Warn` to `Info` in places where the event is triggered by a misbehaving client. The following cases are covered:
- Wrong number of report shares
- The HPKE configuration ID in a report share ciphertext is not recognized
- Report share cannot be decrypted
- Input share cannot be decoded
- VDAF preparation fails (prep_init, prep_next, or prep_shares_to_prep)
This closes #384.
=> Use info! instead of warn! for bad client reports

interop_binaries/src/bin/janus_interop_aggregator.rs, interop_binaries/tests/end_to_end.rs
This backports #515 to the 0.1 branch. We should take this to fix the test flakiness.
=> Backport end_to_end test improvements to 0.1

interop_binaries/src/lib.rs
This turns off ANSI terminal escape codes in interop_binaries, to keep them out of log files in the test containers. This is related to #476.
<details><summary>Sample output</summary>
```
$ docker exec dap-leader cat /logs/aggregator_stdout.log
2022-09-16T17:41:55.129309Z  INFO janus_server::binary_utils::job_driver: Acquiring jobs, max_acquire_count: 10
at janus_server/src/binary_utils/job_driver.rs:134 on ThreadId(5)
in janus_server::binary_utils::job_driver::run
2022-09-16T17:41:55.129312Z  INFO janus_server::binary_utils::job_driver: Acquiring jobs, max_acquire_count: 10
at janus_server/src/binary_utils/job_driver.rs:134 on ThreadId(8)
in janus_server::binary_utils::job_driver::run
2022-09-16T17:41:55.129325Z  INFO janus_server::aggregator::aggregation_job_creator: Updating tasks
at …
```
=> Change logging format for interop test containers

janus_core/src/retries.rs, janus_server/src/aggregator.rs, janus_server/src/aggregator/aggregation_job_creator.rs, janus_server/src/aggregator/aggregation_job_driver.rs, janus_server/src/binary_utils.rs, janus_server/src/binary_utils/job_driver.rs, janus_server/src/metrics.rs
tracing::instrument [uses the field name "error" when emitting an event upon returning an error](https://docs.rs/tracing-attributes/latest/src/tracing_attributes/expand.rs.html#207). We should use the same field name in our events for consistency. Additionally, errors are now formatted with Display rather than Debug where possible, again for consistency.
=> Change field name for errors, use Display to format them

README.md, interop_binaries/src/bin/janus_interop_aggregator.rs, interop_binaries/src/lib.rs, janus_collector/examples/collect.rs, janus_collector/src/lib.rs, janus_core/src/message.rs, janus_core/src/test_util/kubernetes.rs, janus_server/Cargo.toml, janus_server/src/bin/janus_cli.rs, janus_server/src/datastore.rs, janus_server/src/message.rs, janus_server/src/task.rs
Specifically, prefer random() for one-off values, and thread_rng().sample_iter() for repeated values. The former is (IMO) both simpler & clearer than what it replaces; the latter is a more opinionated change but avoids us needing to create a mutable variable initialized to some arbitrary value every time we want to create an array of random values.
Also, rename ENCODED_LEN -> LEN for all opaque types. I suppose the opaque types really are just an array of bytes, so it makes sense to talk about their "length".
=> Update uses of thread_rng() throughout codebase.

integration_tests/src/janus.rs
Backport of #504 to `release/0.1`, as the change we noticed in the nightly is now apparently also in Rust 1.64.
=> Fix compilation with Rust 1.64 compiler (#504)

interop_binaries/src/bin/janus_interop_client.rs, janus_client/src/lib.rs, janus_collector/src/lib.rs, janus_core/src/hpke.rs, janus_core/src/message.rs, janus_core/src/test_util/mod.rs, janus_server/src/aggregator.rs, janus_server/src/aggregator/accumulator.rs, janus_server/src/aggregator/aggregate_share.rs, janus_server/src/aggregator/aggregation_job_creator.rs, janus_server/src/aggregator/aggregation_job_driver.rs, janus_server/src/datastore.rs, janus_server/src/message.rs
Changes include:
* Rename Nonce to ReportID.
* Reorder ReportMetadata fields so that ReportID is first.
* Introduce PartialBatchSelector, use it for AggregateInitializeReq & CollectResp.
* Reduce QueryType from 2 bytes to 1.
See individual commits for more detail.
=> Late-breaking DAP-02 message changes.

janus_server/src/aggregator.rs
draft-ietf-ppm-dap-02 allows aggregators to use a single HPKE config for many tasks. In Janus we choose to use one HPKE config per task (for now), but we must use the HTTP statuses and problem document types mandated by DAP.
Resolves #475
=> `janus_server`: correct errors from `/hpke_config`

Dockerfile.interop
Our tag for alpine is different in `Dockerfile` and `Dockerfile.interop`. This bumps the latter to bring it up to date.
I noticed Dependabot was failing while processing this dependency, so my hope is that this might get it working again.
=> Update Dockerfile.interop to use alpine 3.16.2

Dockerfile.interop
This backports #556, bringing the alpine container versions of two Dockerfiles in sync. Dependabot cannot propose this upgrade due to an error, and making this same change on the main branch resolved that error.
=> Update to alpine 3.16.2, backport for release/0.1

interop_binaries/src/lib.rs
This extends all container readiness timeouts in interop binary end-to-end tests and integration tests from 10 seconds to 30 seconds. Yesterday, the `end_to_end` test flaked a few times due to errors while polling for readiness. My hope is that giving the containers some more time to start up will fix the issue on CI runners, otherwise we'll need to invest in logging improvements.
=> Extend container readiness timeout

Cargo.lock, db/schema.sql, integration_tests/Cargo.toml, interop_binaries/Cargo.toml, janus_client/Cargo.toml, janus_client/src/lib.rs, janus_collector/Cargo.toml, janus_collector/src/lib.rs, janus_core/Cargo.toml, janus_core/src/task.rs, janus_core/src/test_util/dummy_vdaf.rs, janus_core/src/test_util/mod.rs, janus_messages/Cargo.toml, janus_server/Cargo.toml, janus_server/src/aggregator.rs, janus_server/src/aggregator/aggregate_share.rs, janus_server/src/aggregator/aggregation_job_driver.rs, janus_server/src/datastore.rs, janus_server/src/task.rs
This updates libprio to 0.10, which entails a breaking upgrade to VDAF draft 03, introduction of the public share, a database schema change to store that public share, and passing the report count to unshard. This touches a number of tests as well. As this is more invasive than the average Dependabot update, I'd like review on this.
This supersedes #553 and closes #473.
=> Upgrade to prio 0.10

interop_binaries/src/lib.rs
This backports #563 to release/0.1, extending ready timeouts from 10 seconds to 30 seconds for various tests. This should be a safe change, and it may prevent CI headaches going forward.
=> Extend container readiness timeout, backport for 0.1

db/schema.sql, janus_server/src/aggregator.rs, janus_server/src/aggregator/aggregate_share.rs, janus_server/src/aggregator/aggregation_job_creator.rs, janus_server/src/datastore.rs
For https://github.com/divviup/janus/issues/344, we introduce a "Deleted" state for a collect job. We have to distinguish from the "Abandoned" state so that we can eventually return the right HTTP status if a collector polls the collect job URI.
This commit defines the new state in the SQL schema and adds support for entering it using `Datastore::update_collect_job`. Along the way, we resolve https://github.com/divviup/janus/issues/242: `put_collect_job` and `update_collect_job` now take
`&CollectJob` as an argument instead of just the field values to set.
Part of https://github.com/divviup/janus/issues/344
Resolves https://github.com/divviup/janus/issues/242
=> Introduce `CollectJobState::Deleted`

janus_server/src/task.rs
Currently, `Task::new_dummy()` sets max_batch_lifetime to 0. This is irrelevant to most tests, but it would prevent all collect requests from being handled if the task weren't modified first. This change sets max_batch_lifetime to 1 as a more typical default value.
=> Use max_batch_lifetime of 1 in Task::new_dummy()

Cargo.lock, janus_core/Cargo.toml
Update `hpke-dispatch` dep to resolve a security advisory on `wee_alloc`.
=> Bump `hpke-dispatch` to 0.4.0

janus_core/src/lib.rs
This re-adds a `janus_core::message` module, with re-exports of types from `janus_messages`. This will blunt the impact of the refactoring on backwards compatibility, but we'll still have to accept some backwards incompatibility due to methods moving from structs to extension traits. This is a 0.1-only change.
=> Re-export janus_messages types from janus_core

db/schema.sql, janus_collector/src/lib.rs, janus_core/src/hpke.rs, janus_core/src/report_id.rs, janus_messages/src/lib.rs, janus_server/src/aggregator.rs, janus_server/src/aggregator/accumulator.rs, janus_server/src/aggregator/aggregate_share.rs, janus_server/src/aggregator/aggregation_job_creator.rs, janus_server/src/aggregator/aggregation_job_driver.rs, janus_server/src/bin/janus_cli.rs, janus_server/src/binary_utils/job_driver.rs, janus_server/src/datastore.rs, janus_server/src/messages.rs
Note these updates are just for time-interval tasks; fixed-size task
updates will be made as part of implementing fixed-size tasks.
* Rename & reorder fields as needed (e.g. nonce -> report_id).
* Update transaction methods to follow code standards for receiving
references.
* Update datastore models to follow code standards for cross-module
structured data.
* Update visibility of methods used cross-module to be pub -- we don't
publish janus_server, so I don't think we care much about visibility
other than pub/private-to-module/private.
* Fix up DB indices to allow efficient lookup of reports without the
client timestamp.
Closes #533.
=> Datastore: basic DAP-02 message updates.

Cargo.lock, db/schema.sql, integration_tests/tests/common/mod.rs, interop_binaries/src/bin/janus_interop_collector.rs, janus_collector/Cargo.toml, janus_collector/src/lib.rs, janus_server/src/aggregator.rs, janus_server/src/aggregator/aggregate_share.rs, janus_server/src/datastore.rs
I also update the interop collector to return the report count; technically this could have been in another PR, but I need this functionality to augment the integration tests to check that the correct number of reports are returned. (This should be specified; I'm going to do so in a followup PR.)
Closes #469.
=> DAP-02: populate CollectResp::report_count.

janus_collector/examples/collect.rs
This outputs the aggregation result and number of reports on separate labeled lines, rather than using `<Collection<T> as Debug>`.
=> Clean up output of the collect CLI

janus_server/src/bin/janus_cli.rs
`janus_cli` takes arguments for the Kubernetes secret where the datastore keys are, as well as the key into the secret. However, there were two bugs. `datastore-keys-secret-data-key` was being ignored completely, and also both its default value and the value hard coded into `fn create_datastore_key` were wrong. They used `datastore_key` instead of `datastore_keys` (note plural), which disagrees with what the `janus_server` components use.
=> `janus_cli`: correctly handle datastore key secret

Cargo.lock, janus_server/Cargo.toml, janus_server/src/aggregator.rs, janus_server/src/aggregator/aggregate_share.rs, janus_server/src/aggregator/aggregation_job_driver.rs
This parses the problem type out of error responses from the helper, where available. Closes #381.
=> Parse problem types in errors from the helper

Cargo.lock, janus_client/Cargo.toml, janus_client/src/lib.rs
This adds parsing of problem details documents to `janus_client`, similar to #608. This will be a breaking change for 0.2, as it changes a variant of a public enum. Closes #233.
=> janus_client: Store problem details error response

.github/workflows/ci-build.yml, janus_collector/examples/collect.rs
This fixes the unit tests in the `collect` example binary, and adds `--all-targets` to the `cargo test` invocation in CI to keep an eye on it going forward.
=> Fix unit tests in `collect` example binary

janus_collector/examples/collect.rs, janus_core/src/test_util/dummy_vdaf.rs, janus_core/src/test_util/mod.rs, janus_messages/src/bin/dap_decode.rs, janus_messages/src/lib.rs, janus_server/src/bin/aggregator.rs, janus_server/src/binary_utils/job_driver.rs, janus_server/src/trace.rs
Opinionated change: since Rust 1.44 [1], it has been possible to use Vec::from to write vector literals. On the idea that a method call is a simpler tool than a macro, prefer a method call. (Vec::new is also used, if the vector being created is empty.)
[1] https://github.com/rust-lang/rust/pull/68692/
=> Replace vec! with Vec::{from,new}.

integration_tests/tests/common/mod.rs, janus_server/src/task.rs
Currently, `TaskBuilder` can violate some of `Task`'s invariants, because it modifies its fields directly, and bypasses `Task::new()`. This round-trips the task through the constructor when `build()` is called, so that we still get the same input validation. This will help keep tests closer in line with production operation.
=> Apply input validation in TaskBuilder::build()

Cargo.lock, integration_tests/Cargo.toml, interop_binaries/Cargo.toml, janus_client/Cargo.toml, janus_collector/Cargo.toml, janus_core/Cargo.toml, janus_server/Cargo.toml, janus_server/src/aggregator/aggregation_job_creator.rs, janus_server/src/binary_utils/job_driver.rs
I also had to fix a compile error due to use of the `!` type.
I replaced it with std::convert::Infallible. Per that type's
documentation[1], using `!` as a function's return type is permitted in
stable Rust, so this was technically a brekaing change in the tracing
crate.
[1] https://doc.rust-lang.org/stable/std/convert/enum.Infallible.html
=> Update tracing to 0.1.37.

Cargo.lock, integration_tests/Cargo.toml, interop_binaries/Cargo.toml, janus_client/Cargo.toml, janus_collector/Cargo.toml, janus_core/Cargo.toml, janus_server/Cargo.toml, janus_server/src/aggregator.rs, janus_server/src/aggregator/aggregation_job_creator.rs, janus_server/src/binary_utils/job_driver.rs
I also had to fix a compile error due to use of the ! type.
I replaced it with std::convert::Infallible. Per that type's
documentation[1], using ! as a function's return type is permitted in
stable Rust, so this was technically a brekaing change in the tracing
crate.
I also backported a test deflake from 0.2 while I'm at it -- it flaked
again for one of dependabot's 0.1 updates.
[1] https://doc.rust-lang.org/stable/std/convert/enum.Infallible.html
=> Update tracing to 0.1.37. [0.1 backport]

Cargo.lock, janus_collector/Cargo.toml, janus_collector/src/lib.rs
This adds parsing of problem details to `janus_collector`, similar to #608 and #613. This will be a breaking change for 0.2, as it changes a variant of a public enum.
=> janus_collector: Store problem details error info

janus_core/src/retries.rs, janus_server/src/aggregator.rs, janus_server/src/aggregator/accumulator.rs, janus_server/src/aggregator/aggregate_share.rs, janus_server/src/aggregator/aggregation_job_creator.rs, janus_server/src/aggregator/aggregation_job_driver.rs, janus_server/src/bin/janus_cli.rs, janus_server/src/binary_utils.rs, janus_server/src/binary_utils/job_driver.rs, janus_server/src/metrics.rs, janus_server/tests/graceful_shutdown.rs
This is necessary because anyhow error types do not render their internally-wrapped "source" errors with their Display implementations, only their Debug implementations.
While I'm examining all the log lines, also fixup a few things to use Display as needed -- this is most important for ID types, which would previously be logged as e.g. `task_id = TaskId(abcde)` instead of just `task_id = abcde`. The additional type information is not helpful to humans & stutters with the field name.
Closes #609.
=> Log errors using Debug rather than Display implementations.

Cargo.lock, janus_client/src/lib.rs, janus_collector/src/lib.rs, janus_core/Cargo.toml, janus_core/src/http.rs, janus_core/src/lib.rs, janus_server/src/aggregator.rs, janus_server/src/aggregator/aggregate_share.rs, janus_server/src/aggregator/aggregation_job_driver.rs
This is a follow-up to #614, applying the same error logging in the aggregator and client. The relevant helper method is moved from `janus_collector` to `janus_core`.
=> Unify problem details handling, log parse errors

janus_server/src/aggregator.rs, janus_server/src/task.rs
This updates the `/upload` handler to abort if the report's timestamp is past the task's `task_expiration` parameter. This is part of #610.
=> Check for task expiration during /upload

aggregator/src/aggregator.rs
This fixes another test that would fail with probability 1/256. The same fix is applied, choosing a new HPKE configuration ID that is not yet used in the task's keys, instead of using a hardcoded number.
=> Fix another "unknown HpkeConfigId" flaky test

janus_server/src/aggregator.rs
This backports #644 onto release/0.1, fixing a flaky test that fails with probability 1/256.
=> Fix another "unknown HpkeConfigId" flaky test - 0.1 backport

Cargo.lock, Cargo.toml, aggregator/Cargo.toml, core/Cargo.toml, integration_tests/Cargo.toml, integration_tests/README.md
This implements the plan in #655, temporarily removing our Daphne dependency in order to upgrade `hpke-dispatch`, `hpke`, `kube`, and `k8s-openapi`. I removed the entire `daphne` Cargo feature from `integration_tests/Cargo.toml` so that our `--all-features` builds wouldn't break. Aside from the tests here, I also confirmed that the `janus_janus` integration test still passes when run in `JANUS_E2E` mode.
The `kube` upgrades included some interesting changes: many of its dependencies have been moved behind off-by-default features, so we may see a reduction in compile time. There is now native support for port forwarding, so we could possibly use that rather than shelling out to `kubectl`.
=> Zeroize-related upgrades

.github/workflows/ci-build.yml
We saw at least one build failure ([1]) in CI that is down to the `arduino/setup-protoc` action encountering a rate limit. According to the action's README ([2]), it uses GitHub API to query releases on some `protoc` related repository. We can avoid rate limits by authenticating, which we do by passing the action's `GITHUB_TOKEN` into the `setup-protoc` action.
[1]: https://github.com/divviup/janus/actions/runs/3316231068/jobs/5477782062
[2]: https://github.com/arduino/setup-protoc#usage
=> provide `GITHUB_TOKEN` to `setup-protoc` action

.github/workflows/push-docker-images-release.yml
This updates the `push-docker-images-release` workflow to retag and push images to our public-facing repository. Since the two `docker login` executions will stomp on the same registry/username with different passwords, all of the public-facing pushes happen at the end, after a second `docker/login-action`.
=> CI: Tag and push container images for public repo

.github/workflows/push-docker-images-release.yml
This backports #683 to the 0.1 branch. Note that `janus_aggregator` is replaced with `janus_server` in container names for this branch.
=> CI: Tag and push container images for public repo - 0.1 backport

.github/workflows/ci-build.yml
This replaces our use of actions-rs/toolchain (which is unmaintained) with dtolnay/rust-toolchain. There's no support for setting a rustup override, but that should be okay, as the action will install a new default toolchain, and we don't have any `rust-toolchain` files that would supersede that. The profile is not configurable, but that's fine, since the action hardcodes --profile=minimal.
=> Switch to dtolnay/rust-toolchain action

integration_tests/src/janus.rs, integration_tests/src/lib.rs, interop_binaries/src/lib.rs, interop_binaries/tests/end_to_end.rs
This adds support for exporting container logs to the `janus_interop_binaries` tests as well.
=> Support JANUS_E2E_LOGS_PATH in interop_binaries tests

Cargo.lock, build_script_utils/Cargo.toml, integration_tests/Cargo.toml, interop_binaries/Cargo.toml, janus_client/Cargo.toml, janus_collector/Cargo.toml, janus_core/Cargo.toml, janus_messages/Cargo.toml, janus_server/Cargo.toml
This bumps versions again, to prepare for testing the release actions.
=> Bump Janus crates to 0.1.20

.github/workflows/publish-sql-schema.yml, .github/workflows/push-docker-images-release.yml
This backports #643 to the 0.1 branch, to fix some deprecation warnings.
=> GHA: Replace ::set-output with file redirection - backport

.github/workflows/publish-sql-schema.yml, .github/workflows/push-docker-images-release.yml
This fixes some typos in secret names used by actions. Here, I change two secret names (one for the public repository and one for the private repository) to use the corrected spelling. (I've already created a new secret for this, plus an additional misspelled secret, and I plan to keep all four around until I'm done testing the 0.1.20 release runs)
I also rolled in a fix for a GitHub Actions warning, along the lines of https://github.com/divviup/divviup-ts/pull/135.
=> Fix typo in GitHub secret name

.github/workflows/publish-sql-schema.yml, .github/workflows/push-docker-images-release.yml
This backports a fix for misspelled secret names from #690, plus a GHA warning fix.
=> Fix typo in GitHub secret name - backport

aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/datastore.rs, aggregator/src/task.rs
This effectively implements the leader side of the aggregation process. The functional changes are quite small here: effectively, the only change over what was done as part of e.g. the message updates is to pass along the "partial batch identifer" (i.e. batch ID, for fixed-size tasks) in the aggregate initialization request.
=> Fixed-size tasks: implement aggregation job driver.

aggregator/src/datastore.rs, db/schema.sql
Changes the type of `report_aggregation.error_code` from `BIGINT` to `SMALLINT` to save space. I opted against a SQL enum because then we'd have to duplicate the error enum defined in Rust in SQL and we'd still have to check for invalid errors when reading from the datastore.
Resolves #22
=> datastore: use `SMALLINT` for aggregation error

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregate_share.rs, aggregator/src/datastore.rs, aggregator/src/task.rs
The handler for `/collect` will now check whether the batch interval in a `CollectReq`'s query contains enough reports to satisfy the task's parameters.
Resolves #470
=> `/collect`: validate batch size

integration_tests/build.rs, interop_binaries/build.rs
rust-analyzer has a setting which disables build scripts. Unfortunately, at least on my machine, this setting is ineffectual and build scripts are run anyway. This implies the `cargo check` done by rust-analyzer was actually building Janus as part of the container-build process. If the container build failed, the entire build process would be aborted & VSCode would not show any error highlighting in some cases.
This new check is based on `RUSTC_WRAPPER`, which rust-analyzer sets by default to the full path of the rust-analyzer binary. rust-analyzer can be configured to not set this environment variable -- please don't do so. :-)
As a side-effect, I think this speeds up how quickly rust-analyzer will be able to check Janus. Incremental container builds are quick, but not instantaneous.
=> Detect & skip build scripts for rust-analyzer.

integration_tests/src/daphne.rs, interop_binaries/tests/end_to_end.rs, janus_core/src/test_util/kubernetes.rs, janus_server/src/bin/janus_cli.rs, janus_server/src/task.rs, janus_server/tests/graceful_shutdown.rs
This fixes new Clippy warnings with the latest toolchain. All the changes are removals of unnecessary `&` on function or method arguments that take an `AsRef` parameter.
=> 1.65 clippy fixes, for release/0.1

Cargo.toml, Dockerfile, Dockerfile.interop, Dockerfile.interop_aggregator, aggregator/src/aggregator.rs, aggregator/src/aggregator/accumulator.rs, aggregator/src/bin/janus_cli.rs, aggregator/src/task.rs, aggregator/tests/graceful_shutdown.rs, client/src/lib.rs, interop_binaries/tests/end_to_end.rs
This fixes some new Clippy warnings with the latest toolchain. As discussed, the `clippy::result_large_err` lints are ignored in each place they occur.
=> 1.65 clippy fixes

.github/workflows/ci-build.yml, Cargo.lock, integration_tests/Cargo.toml, integration_tests/src/client.rs, integration_tests/src/lib.rs, integration_tests/tests/common/mod.rs, integration_tests/tests/divviup_ts.rs, integration_tests/tests/janus.rs, interop_binaries/Cargo.toml, interop_binaries/src/lib.rs, interop_binaries/tests/end_to_end.rs
This refactors some components of the integration tests and adds new integration tests with divviup-ts, running it inside a Docker container managed by `testcontainers`.
=> Add integration tests with divviup-ts

Cargo.lock, aggregator/Cargo.toml, aggregator/src/aggregator.rs, aggregator/src/aggregator/accumulator.rs, aggregator/src/aggregator/aggregate_share.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/query_type.rs, aggregator/src/bin/aggregation_job_creator.rs, aggregator/src/datastore.rs, client/src/lib.rs, core/src/time.rs, db/schema.sql, integration_tests/tests/common/mod.rs, interop_binaries/tests/end_to_end.rs, messages/src/lib.rs
I made some opinionated choices about how to deal with the fact that a time-interval collect request may span multiple batches (née batch units). Instead of making a single request, I now do a (pipelined) set of requests for all of the individual batch units. We load multiple values using pipelined requests for single values elsewhere; we can fix this up easily enough later, if we want to, by doing a lexicographic search over the batch_identifiers.
Part of #468.
=> Fixed-size tasks: implement helper aggregation.

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregate_share.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/datastore.rs, aggregator/src/messages.rs, db/schema.sql
When handling uploads, the leader now decrypts and decodes its input share and the public share before recording them in the datastore. This allows us to discard immediately reports that can never be aggregated and simplifies the implementation of the aggregation job creator, since it can now fetch well-formed values from the datastore.
See #442 for rationale.
Resolves #442
=> Store leader input shares unencrypted

aggregator/src/datastore.rs
This rewrites one query to use `>=` and `<` operators instead of `<@`, so that the query planner can better apply an index scan. (This relies on the fact that all our timestamp ranges are closed on the left and open on the right, which is enforced by our SQL conversion of the `Interval` type)
There are two other queries that use `<@` on `client_reports.client_timestamp`, which I'm leaving alone. In my testing, making the same change didn't seem to improve query plans, as the condition was applied as a join filter deep in a nested loop join. In both, the interval side of the containment operator came from another table. Moreover, these queries will need to be revisited in #269 and #519.
Here are the before-and-after query plans:
```
postgres=# EXPLAIN SELECT COUNT(1) AS count FROM …
```
=> Optimize query in count_client_reports_for_interval()

integration_tests/src/daphne.rs, integration_tests/src/janus.rs, interop_binaries/src/lib.rs
This PR brings `ContainerLogsDropGuard` in line with the Janus and Daphne integration tests, by only exporting logs when the current thread is panicking. I missed this check when implementing this, so interop_binary tests and divviup-ts tests were writing extra logs out from passing tests if `JANUS_E2E_LOG_PATH` was set.
=> Add missing check to only dump logs on panic

aggregator/src/aggregator.rs, aggregator/src/aggregator/accumulator.rs, client/src/lib.rs, collector/src/lib.rs
This wraps the contents of two kinds of error variants in boxes, to reduce stack memory usage and non-inlined `memcpy`s. Each `HttpApiProblem` is now boxed, and the contents of `janus_aggregator::aggregator::Error::BatchMismatch` are moved into a new struct and boxed. Thus, we no longer need to ignore `clippy::result_large_err`.
With these changes `janus_aggregator::aggregator::Error` is 72 bytes (down from 160), `janus_client::Error` is 32 bytes (down from from 160), and `janus_collector::Error` is 40 bytes.
Closes #713
=> Box large error variants

aggregator/src/aggregator/aggregate_share.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/datastore.rs, aggregator/src/messages.rs
Replaces the test-util item that generated dummy
`janus_messages::Report`s with one that generates dummy `janus_aggregator::datastore::models::LeaderStoredReport`s, which is more useful for testing code past the HTTP message handling layer (`Report` is a wire message, not the internal representation of a report). This allows us to delete some redundant methods on `Datastore` for writing reports, because we now consistently are writing `LeaderStoredReport` values.
=> Clean up dummy report generation

aggregator/src/aggregator.rs, aggregator/src/aggregator/accumulator.rs, aggregator/src/aggregator/aggregate_share.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/query_type.rs, aggregator/src/datastore.rs, aggregator/src/lib.rs
This fixes #730 by replacing uses of `futures::future::try_join_all()` and `tokio::try_join!()`. It introduces a free function `gather_errors()` that can be used with `futures::future::join_all()` and a new `try_join!()` macro that wraps `tokio::join!()`. Both of these new code patterns will wait for all futures to complete, and select one error to propagate after seeing all outputs. If any future returns a serialization failure error, that will be returned. If some of the futures return an error indicating the transaction is already in a failed state, those are given a lower priority, because any other error will be more useful for diagnostic purposes.
I tested an earlier version of this change (focused on the aggregation job driver's critical window after talking to the helper) and I …
=> Fix propagation of database-related errors

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/collect_job_driver.rs, aggregator/src/aggregator/query_type.rs, aggregator/src/bin/collect_job_driver.rs, aggregator/src/datastore.rs, db/schema.sql, messages/src/lib.rs
Effectively, this PR finishes out fixed-size support for the collect job driver.
Part of #468.
=> Fixed-size tasks: implement leader collection.

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/datastore.rs, db/schema.sql
This renames "batch_identifier" to "partial_batch_identifier" in the context of aggregation jobs, both in the database and in Rust types. I think the increased clarity between batch identifiers and partial batch identifiers is beneficial, plus this refactor is the first thing I need to do to prototype tracking leader aggregation job batch identifiers, for #519.
=> Rename aggregation job field/column/methods to `partial_batch_identifier`

aggregator/src/aggregator.rs, aggregator/src/aggregator/query_type.rs
This was specified in terms of time-interval tasks only, and written such that no compilation error occurred; I missed updating it on my first pass.
=> Bugfix: fixup conflicting-collect check for fixed-size tasks.

collector/examples/collect.rs, collector/src/lib.rs, integration_tests/tests/common/mod.rs, interop_binaries/src/bin/janus_interop_collector.rs
This implements #764, changing the `janus_collector` crate to take any query as an argument, instead of solely a batch interval. The accompanying CLI is updated as well.
Closes #764.
=> Add fixed size query support to collector crate

aggregator/src/aggregator/collect_job_driver.rs, aggregator/src/datastore.rs, db/schema.sql
Previously, the collect job driver would only work for time-interval tasks because the underlying datastore operation only worked with time-interval tasks.
Closes #766.
=> Fixed-size tasks: fix collect job driver.

aggregator/src/aggregator.rs, collector/src/lib.rs, messages/src/lib.rs, messages/src/problem_type.rs
This PR makes the following changes:
- Moves the enum `DapProblemType` from `janus_aggregator` to `janus_messages` so it can be reused. (One method is left behind in an extension trait, but this will go away as part of DAP-03, see #705)
- Stores a parsed `DapProblemType` in the collector library's `Error::Http` variant, similar to that in the aggregator module.
Closes #763.
=> Improve collector error handling

Cargo.lock, aggregator/src/task.rs, integration_tests/Cargo.toml, integration_tests/src/janus.rs, integration_tests/src/lib.rs, integration_tests/tests/common/mod.rs, integration_tests/tests/divviup_ts.rs, integration_tests/tests/janus.rs, interop_binaries/src/bin/janus_interop_aggregator.rs, interop_binaries/src/bin/janus_interop_collector.rs, interop_binaries/tests/end_to_end.rs
This adds a more-complete integration test for fixed size tasks. I had to solve the batch ID discovery problem ~3 times, so there is some near-repetition between different settings. We'll be able to rip this out once we move on to DAP-03, thanks to the `current_batch` query sub-type. I successfully tested this against a hacked-up collect job driver. I did notice one test flake, possibly related to #763, which I'll investigate further.
=> Add support for fixed size tasks to interop binaries and integration tests

messages/src/lib.rs
=> DAP-03: extend agg_param fields to use 32-bit lengths.

core/src/hpke.rs
This adds a length prefix in our input share AAD construction, to match Daphne's interpretation. See https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/371 for discussion of related spec changes.
=> Add a length prefix to public_share in AAD

.github/workflows/publish-sql-schema.yml, .github/workflows/push-docker-images-release.yml
Now that we have published 0.2.0, we shouldn't be marking release artifacts from this branch as "latest" anymore. See also #507.
=> 0.1: Stop pushing images and schema as 'latest'

.github/workflows/publish-sql-schema.yml, .github/workflows/push-docker-images-release.yml
Per the discussion on #800, this stops marking release artifacts as "latest". See also #507.
=> 0.2: Stop pushing images and schema as 'latest'

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/datastore.rs, client/src/lib.rs, messages/src/lib.rs
This commit introduces the PlaintextInputShare structure used for input shares in DAP-03.
Part of #761.
=> DAP-03: move extensions to ciphertext.

Cargo.lock, messages/Cargo.toml, messages/src/bin/dap_decode.rs, messages/tests/cli.rs, messages/tests/cmd/dap_decode.trycmd
This upgrades `dap-decode` to clap v4, and adds support for decoding messages with fixed-size query types.
=> Improvements to dap-decode

Cargo.lock, aggregator/Cargo.toml, aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/datastore.rs, aggregator/src/task.rs, client/src/lib.rs, collector/examples/collect.rs, collector/src/lib.rs, core/Cargo.toml, core/src/hpke.rs, integration_tests/tests/common/mod.rs, interop_binaries/src/bin/janus_interop_aggregator.rs, interop_binaries/src/bin/janus_interop_collector.rs, interop_binaries/src/lib.rs, messages/Cargo.toml, messages/src/lib.rs
This refactors parts of our task YAML serialization code out into serde trait implementations on individual types. Hoisting HPKE key YAML serialization from `janus_aggregator` to `janus_core` is a prerequisite for #801.  This PR makes the following changes:
- Move base64url-encoding of `TaskId`, `HpkePublicKey`, and `HpkePrivateKey` into custom serde trait implementations on the types themselves. (out of implementations on various serialization helper types)
- Remove `SerializedHpkeConfig`, and use `HpkeConfig` directly in types with serde derive macros applied.
- Replace `(HpkeConfig, HpkePrivateKey)` tuples with a new struct type, `HpkeKeypair`.
- Remove `SerializedHpkeKeypair`, and derive serde traits on `HpkeKeypair` directly.
- Add a `serde_test` test for the `Task` serialization …
=> Refactor base64url-encoded fields in serde implementations

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/datastore.rs, aggregator/src/task.rs, client/src/lib.rs, core/src/hpke.rs, db/schema.sql, integration_tests/src/client.rs, integration_tests/tests/common/mod.rs, integration_tests/tests/divviup_ts.rs, integration_tests/tests/janus.rs, interop_binaries/src/bin/janus_interop_aggregator.rs, interop_binaries/src/bin/janus_interop_client.rs, interop_binaries/src/lib.rs
This adds a new task parameter, `input_share_aad_tweak` which changes how we build the input share AAD. This affects both the client and the aggregator. This is a 0.2-only change, since this compatibility issue is only relevant when targeting DAP-02. I added an integration test to confirm that aggregation works with this new mode.
We will likely need to do a manual schema migration in our dap-02 deployment. The following statement will suffice:
```sql
ALTER TABLE tasks ADD COLUMN input_share_aad_tweak BOOLEAN NOT NULL DEFAULT false;
```
=> Add per-task configuration for Daphne compatibility

Cargo.lock, Cargo.toml
This prepares us to cut a release that includes `input_share_aad_public_share_length_prefix`.
=> Increment version to 0.2.1

.github/dependabot.yml, README.md
- Configure dependabot to manage `release/0.2`
- Stop taking dependabot changes to `release/0.1`
- Bump open dependabot PR limit to 20 to avoid annoying phenomenon where you get multiple waves of PRs to deal with
- Document release branches and their status in README.md
=> Update supported release branches

.github/workflows/ci-build.yml, .github/workflows/publish-crates.yml, .github/workflows/publish-sql-schema.yml, .github/workflows/push-docker-images-release.yml
This should resolve the issue we had earlier today with OpenSSL errors during tests. This also rolls back #834.
See https://github.com/divviup/janus/pull/833#issuecomment-1347476850 for a complete description of the issue.
=> Add OS version to cache key

aggregator/src/aggregator.rs, aggregator/src/aggregator/query_type.rs, aggregator/src/datastore.rs, collector/examples/collect.rs, collector/src/lib.rs, integration_tests/tests/common/mod.rs, interop_binaries/src/bin/janus_interop_collector.rs, messages/src/lib.rs
The logic for deciding which batch to return for current-batch is currently very simple: we let Postgres decide which of the eligible batches to return. We may well need to tweak this approach later (e.g. to always return the least-recently-returned eligible batch), but this should be fine for a first pass.
Part of #706.
=> DAP-03: implement current-batch functionality in Aggregator.

Cargo.lock, aggregator/src/aggregator.rs, aggregator/src/bin/janus_cli.rs, aggregator/src/task.rs, core/Cargo.toml, core/src/task.rs, messages/src/lib.rs
`janus_cli provision-tasks` can now generate task IDs, VDAF verify keys, authentication tokens for aggregators and collectors and aggregator HPKE keypairs, if those values are not present in the task YAML. We also add an `--echo-tasks` flag so that the tool prints the YAML encoding of provisioned tasks to stdout.
Resolves #528
=> `janus_cli`: task parameter generation

aggregator/src/bin/janus_cli.rs, aggregator/src/binary_utils.rs, aggregator/src/config.rs, aggregator/src/datastore.rs, integration_tests/src/janus.rs
Adds a configuration option for Janus binaries to instantiate a `janus_aggregator::datastore::Datastore` in dry-run mode. This is implemented by having `Datastore::run_tx_once` call `Transaction::rollback` instead of `::commit` after a successful database transaction. This in turn allows us to implement things like a `--dry-run` flag on `janus_cli`, so that operators can convince themselves they've correctly set up a task being provisioned before making real changes to a live production database.
Part of #529
=> Add dry run mode to `Datastore`

aggregator/Cargo.toml, aggregator/src/config.rs, aggregator/src/datastore.rs, aggregator/src/lib.rs, aggregator/src/task.rs, collector/Cargo.toml, collector/src/lib.rs, core/Cargo.toml, core/src/hpke.rs, core/src/lib.rs, core/src/retries.rs, core/src/task.rs
Annotates items across the `janus_core`, `janus_collector` and `janus_aggregator` crates that are gated on the `test-util` feature so that they get documented by `cargo doc`.
Resolves #309
=> Document `test-util` items

.github/workflows/publish-crates.yml, integration_tests/src/client.rs, integration_tests/src/janus.rs, integration_tests/tests/common/mod.rs, interop_binaries/src/lib.rs, interop_binaries/tests/end_to_end.rs
- Fix `clippy` warnings for unnecessary dereferences
- Fix `clippy` warnings for unnecessary `u128 -> u128` cast
- [`cargo publish` now blocks until it sees the published package in the index][1], so we can remove the retry loop from our crate publishing action.
[1]: https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-166-2022-12-15
=> Fixes for Rust 1.66

README.md, client/README.md, collector/README.md, core/README.md, messages/README.md
- add `collector/README.md`
- display badges for CI status, crates.io and docs.rs in all crate READMEs
- update `README.md` with current links for DAP-03
Resolves #649
=> Make READMEs consistent

aggregator/src/aggregator.rs, messages/src/problem_type.rs
DAP-03 replaces the `reportTooLate` message with a generic `reportRejected` and notes two places ([1], [2]) where it should be used.
[1]: https://datatracker.ietf.org/doc/html/draft-ietf-ppm-dap-03#section-4.3.2-16 [2]: https://datatracker.ietf.org/doc/html/draft-ietf-ppm-dap-03#section-4.3.2-17
Resolves #34
=> DAP-03: adopt `reportRejected` error

aggregator/src/aggregator.rs
DAP-03 has [new language][1] on HTTP problem documents. The fields `taskid` and `instance` are no longer mandatory, so we don't have to include the former when it's not known and we don't have to always set the latter to `".."`.
[1]: https://datatracker.ietf.org/doc/html/draft-ietf-ppm-dap-03#name-errors
Resolves #545
=> DAP-03: Update HTTP problem documents

Cargo.lock, integration_tests/Cargo.toml, integration_tests/src/client.rs, integration_tests/src/janus.rs, integration_tests/src/lib.rs, integration_tests/tests/common/mod.rs, integration_tests/tests/divviup_ts.rs, integration_tests/tests/janus.rs, interop_binaries/src/bin/janus_interop_aggregator.rs, interop_binaries/src/bin/janus_interop_collector.rs, interop_binaries/tests/end_to_end.rs
This rips out `/internal/test/fetch_batch_ids`, updates the interop test API based on https://github.com/divergentdave/draft-dcook-ppm-dap-interop-test-design/pull/33, and uses "current_batch" queries in fixed size tests instead.
=> Use current batch query in interop binaries and integration tests

interop_binaries/src/bin/janus_interop_aggregator.rs, interop_binaries/src/lib.rs, interop_binaries/tests/end_to_end.rs
This updates the interoperation test API support, renaming the `verify_key` attribute to `vdaf_verify_key`, to reflect the latest editor's copy. This rename is being done for clarity, but it got delayed until now so it could ride along with other breaking changes (for DAP-03 support).
=> Interop API: rename parameter to vdaf_verify_key

aggregator/src/bin/janus_cli.rs, aggregator/src/binary_utils.rs, aggregator/src/config.rs, aggregator/src/datastore.rs, integration_tests/src/janus.rs
Reverts divviup/janus#843
Per discussion around #848, we agreed that the dry run mode implemented by #843 is too risky and not valuable enough to keep around.
=> Revert "Add dry run mode to `Datastore`"

aggregator/src/bin/janus_cli.rs, interop_binaries/config/supervisord.conf, interop_binaries/setup.sh
Building on the previously introduced dry-run support in `Datastore`, `janus_cli` can now be run with a `--dry-run` flag. In this mode, no real modifications to the datastore (in the case of `write-schema` or `provision-tasks`) or Kubernetes secrets (in the case of `create-datastore-key`) are made.
We also refactor some of the command line option and configuration file handling to reduce code duplication in `Command::execute`.
Resolves #529
=> `janus_cli`: add dry-run mode

Cargo.lock, Cargo.toml
This prepares crate metadata for the next release.
=> Bump crate versions to 0.2.3

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/garbage_collector.rs, aggregator/src/bin/garbage_collector.rs, aggregator/src/datastore.rs, aggregator/src/task.rs, db/schema.sql, interop_binaries/src/bin/janus_interop_aggregator.rs, messages/src/lib.rs
The 0.2 version of this functionality only supports leader tasks with time-interval query types. This is because supporting helper tasks would require a schema change & backfill, and because fixed-size query types are not deployable in DAP-02 due to the lack of current-batch support.
=> Implement garbage collection. [0.2]

aggregator/src/aggregator.rs
DAP-02's section on `/hpke_config` included a requirement that requests
for HPKE configs where the task ID is unrecognized should yield HTTP 404
Not Found. Our implementation returned 404 from *all* endpoints if the
request referenced an unrecognized task ID, which was not in compliance
with DAP-02, since the errors section says that HTTP 400 Bad Request
should be used "unless otherwise specified" (it was only otherwise
specified for `/hpke_config`).
DAP-03 improves this by removing the HTTP 404 Not Found requirement from
`/hpke_config`, so now we can uniformly return HTTP 400 Bad Request for
all `unrecognizedTask` errors, and in fact all errors since no protocol
text ever specifies otherwise.
This situation still isn't optimal, because the protocol shouldn't force
us to use Bad Request …
=> Return HTTP 400 on unrecognized task ID

collector/src/lib.rs
Mocked responses for two APIs in this test previously returned three errors before returning a successful response. On rare occasions, the 10ms maximum elapsed time limit from `test_http_request_exponential_backoff()` would be exceeded on the third error, and the test would fail. This PR changes the mocks to only return one error before succeeding, which should give us plenty of buffer.
=> Fix flaky test by changing number of retries

collector/src/lib.rs
This is a backport of #916 to the 0.2 release branch.
=> Fix flaky test by changing number of retries - 0.2 backport

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/datastore.rs, core/src/test_util/mod.rs
The tests in mod `datastore` defined a mechanism for running a VDAF and recording a transcript, which is redundant given `run_vdaf` and `VdafTranscript` in `janus_core`. This commit moves `datastore` tests to `run_vdaf`. Additionally, `VdafTranscript` now has convenience methods for getting preparation state and output shares, which absolves its clients of writing gnarly `assert_matches!` macros that get so long that `rustfmt` gives up on tidying them up.
---
I'm working on the changes needed to implement DAP-04 in https://github.com/divviup/janus/pull/731. Since DAP-04 isn't ready yet and in order to reduce the size of the eventual PR wiring up the new HTTP API, I'm teasing out some independent pieces into more digestible PRs.
=> replace `generate_vdaf_values` with `run_vdaf`

aggregator/src/aggregator.rs, aggregator/src/task.rs, integration_tests/tests/common/mod.rs, messages/src/bin/dap_decode.rs
I reviewed the codebase to check that we have parity between the two query types, and I came up with three small cleanups to make.
- `/aggregate` was broken for fixed size queries with the dummy VDAF.
- `test_task_builders()` can be slightly simplified now that `TaskBuilder::new()` takes the query type.
- `dap_decode` would have output an extra `Ok(...)` around one particular message type.
=> Miscellaneous query type-related cleanups

aggregator/src/aggregator.rs
This is a follow-up to #894, changing `/upload` to reject reports with `...:reportTooLate` if the given task has a report expiry age configured, and the report is older than that age. We need to check for this because otherwise an attacker could re-upload the same report multiple times once it's old enough to be garbage collected, and race collections against the garbage collector to get around anti-replay protections.
=> Reject uploaded reports past expiry age (0.2)

aggregator/src/datastore.rs, messages/src/lib.rs
By adding a couple of `TryFrom<&[u8]>` implementations, we can make use of `RowExt::get_bytea_and_convert` to get things like `TaskId`, `ReportId` or other types that are simple wrappers around fixed-size byte arrays from database rows.
=> datastore: tidy up some byte slice conversions

Cargo.lock, Dockerfile.interop, Dockerfile.interop_aggregator, aggregator/Cargo.toml, aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collect_job_driver.rs, aggregator/tests/cmd/aggregation_job_creator.trycmd, aggregator/tests/cmd/aggregation_job_driver.trycmd, aggregator/tests/cmd/aggregator.trycmd, collector/Cargo.toml, collector/examples/collect.rs, collector/src/lib.rs, core/Cargo.toml, core/src/task.rs, interop_binaries/Cargo.toml, interop_binaries/src/bin/janus_interop_client.rs, interop_binaries/src/bin/janus_interop_collector.rs, interop_binaries/src/lib.rs, interop_binaries/tests/end_to_end.rs, messages/tests/cmd/dap_decode.trycmd
As discussed [here](https://github.com/divviup/janus/issues/464), this PR enables using our [prio3 type for aggregating vectors of fixed-point numbers](https://github.com/divviup/libprio-rs/pull/283) with janus. It mainly adds the enum cases and match branches required to dispatch on the 16-, 32- and 64-bit variants of fixed-point vector aggregation.
One notable thing I did is adding a [helper enum to enable tagging the JSON from the upload request with the fixedpoint type in the end-to-end interop test](https://github.com/dpsa-project/janus/blob/abda6a06637014808cdfead37912d88b2ca972bb/interop_binaries/src/bin/janus_interop_client.rs#L30-L43) only for our vectors, as the standard string representation of fixedpoint numbers does not carry that information.
Looking forward to your comments …
=> integrating bounded l2 norm fixed point vector sum types.

aggregator/src/aggregator.rs, aggregator/src/bin/janus_cli.rs, aggregator/src/datastore.rs, aggregator/src/task.rs, aggregator/tests/graceful_shutdown.rs, client/src/lib.rs, integration_tests/src/client.rs, integration_tests/src/janus.rs, interop_binaries/src/bin/janus_interop_aggregator.rs, interop_binaries/src/bin/janus_interop_client.rs, interop_binaries/src/bin/janus_interop_collector.rs, interop_binaries/src/lib.rs
This makes some mechanical changes to format strings, to fix clippy lints.
=> cargo clippy --fix, 1.67, 0.2 backport

integration_tests/src/janus.rs
The `Drop` implementation on `integration_tests::janus::Janus` tries to copy logs out of interop test containers using `docker cp`. It would panic if that failed, which would result in a double panic (because test failures in `cargo test` are panics), and that would cause output from failing tests to be lost, making it hard to diagnose failures.
With this change, we no longer panic if either we can't `exec(2)` `docker` or if `docker cp` fails. Instead, the errors get printed to stdout so at least they will appear in GitHub Actions logs, as will some information about the test that failed.
Example test failure _without_ this change:
https://github.com/divviup/janus/actions/runs/4010819099/jobs/6887739020
Example test failure _with_ this change: …
=> `integration_tests`: don't panic in panic handler

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collect_job_driver.rs, aggregator/src/aggregator/garbage_collector.rs, aggregator/src/datastore.rs
This backports #937 to the 0.2 release branch. I'm backporting this because I'd like to see this metrics refinement in load tests of 0.2.
=> Add a name to transactions for metrics, 0.2 backport

db/schema.sql
This renames the indexes for some UNIQUE constraints so that they better match the tables they're indexing.
Here's the list of relations after this change:
```
aggregate_share_jobs
aggregate_share_jobs_id_seq
aggregate_share_jobs_interval_containment_index
aggregate_share_jobs_pkey
aggregate_share_jobs_unique_task_id_batch_id_aggregation_param
aggregation_jobs
aggregation_jobs_id_seq
aggregation_jobs_pkey
aggregation_jobs_state_and_lease_expiry
aggregation_jobs_task_and_batch_id
aggregation_jobs_task_and_batch_interval
aggregation_jobs_unique_id
batch_aggregations
batch_aggregations_id_seq
batch_aggregations_pkey
batch_aggregations_unique_task_id_batch_id_aggregation_param
client_reports
client_reports_id_seq
client_reports_pkey
client_reports_task_and_timestamp_index …
```
=> Rename `CONSTRAINT ... UNIQUE` indexes

aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collect_job_driver.rs, aggregator/src/bin/aggregation_job_driver.rs, aggregator/src/bin/collect_job_driver.rs, aggregator/src/binary_utils/job_driver.rs, aggregator/src/datastore.rs
This changes job driver delays, lease durations, and lease expirations to use `std::time::Duration` and `chrono::NaiveDateTime` instead.
This is part of #445.
=> Remove janus_message time types from job drivers

Cargo.lock, Cargo.toml
This prepares crate metadata for the next release.
=> Bump crate versions to 0.2.6

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collect_job_driver.rs, aggregator/src/aggregator/garbage_collector.rs, aggregator/src/bin/garbage_collector.rs, aggregator/src/datastore.rs, aggregator/src/messages.rs, aggregator/src/task.rs, db/schema.sql, interop_binaries/src/bin/janus_interop_aggregator.rs, messages/src/lib.rs
This PR is huge, but is mostly straightforward. Over-and-above the 0.2 version of this functionality, this PR includes:
* Support for fixed-size tasks. This is relatively straightforward--no new data needs to be stored, only the relevant expiry SQL queries needed to be updated.
* Support for helper tasks. This is trickier: to support time-interval helper tasks, we need to compute & store the interval of contained reports, as otherwise we do not have a fast (indexed) way to associate collection artifacts with the relevant aggregation jobs since time-interval helper tasks do not store the interval of the aggregation job (nor could they, as this information is not transmitted from the leader). However, we have to be careful to only use the client timestamp interval for time-interval tasks, …
=> Implement garbage collection.

.github/workflows/ci-build.yml, Cargo.toml, README.md, core/src/test_util/kubernetes.rs
This updates the Kind and Kubernetes versions we test against, to keep up with our deployment code.
=> Update Kind and Kubernetes versions used in tests

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collect_job_driver.rs, aggregator/src/aggregator/garbage_collector.rs, aggregator/src/bin/aggregation_job_creator.rs, aggregator/src/datastore.rs, db/schema.sql
Aggregation jobs for time-interval tasks were previously created with reports in a single "batch unit" (i.e. an interval of time aligned with & as long as the time precision of the task). Now, aggregation jobs for time-interval tasks are created with arbitrary reports.
This allows us to stop ordering the reports we read, which will hopefully improve DB performance as we no longer need to read (and therefore predicate-lock) all reports for a given task.
This implied a schema change: previously, aggregation_jobs tracked the batch_identifier. Now, for time-interval tasks there is no batch_identifier to record. This column (and the equivalent batch_interval) are now removed; instead, client_timestamp_interval & the new batch_id column are used where batch_identifier previously would have been …
=> Create aggregation jobs with arbitrary reports.

README.md
Note that we don't update `.github/workflows/dependabot.yml` here as we have agreed not to maintain `release/0.3`, since we are not aware of any deployments of `draft-ietf-ppm-dap-03`.
=> Update release branches table for 0.3

aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/datastore.rs, db/schema.sql
This new flag is used to track which client reports have been attached to an aggregation, allowing us to create aggregation jobs without needing to consult the report_aggregations table. Hopefully, this will reduce the amount of contention between aggregation job creation & other datastore operations in the system.
Note that we set the flag for both VDAFs without an aggregation parameter, and VDAFs with an aggregation parameter. However, it's only effectively used by VDAFs without an aggregation parameter. Still, the flag is set for consistency.
=> Introduce client_reports.aggregation_started flag.

collector/Cargo.toml, core/Cargo.toml, interop_binaries/Cargo.toml
To work around a known issue with `cargo publish` ([1}), update all self-dependencies under dev-dependencies to use `path = "."` instead of a versioned crate, as `publish` insists on fetching from crates.io, despite a correctly versioned crate being available locally.
[1]: https://github.com/rust-lang/cargo/issues/4242
=> workaround for cargo dev-dependencies problem

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregate_share.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/datastore.rs, collector/src/lib.rs
This removes some large arguments from tracing spans. The chief change here is to only log a `TaskId` in place of a `Task`, which takes up 900+ characters with debug formatting. I also removed three other arguments on account of them being large, unhelpful, and/or sensitive.
I needed the Task change to get tracing over the UDP jaeger-agent protocol to work, but I think we'll want this same conciseness for TCP OTLP tracing setups, and even stdout logging.
=> Tracing cleanup

aggregator/src/aggregator.rs, aggregator/src/aggregator/query_type.rs, aggregator/src/aggregator/report_writer.rs, aggregator/src/bin/aggregator.rs, aggregator/src/datastore.rs, aggregator/tests/graceful_shutdown.rs, interop_binaries/src/bin/janus_interop_aggregator.rs
This introduces a couple of new configuration options on the aggregator binary, allowing configuration of the batching behavior. Batching can be disabled entirely by setting the batch size to 1 or less, or by reducing the write delay to 0.
A few smaller optimizations while I was touching the report-upload code:
* Remove report read to check existence, in favor of updating the write to return a specific error code if the row already exists & driving the existence check based on that.
* For fixed-size tasks, remove the conflicting-collect-job check. Due to the way reports are allocated to batches, there is no possibility of collision here.
(These optimizations reduce the number of DB queries for all query types: from 3 to 2 for time-interval tasks, and from 3 to 1 for fixed-size tasks. For …
=> Support write-batching for report uploads.

integration_tests/src/client.rs
This is a follow-up to #936 to update the divviup-ts container used in local tests, following the change in the `ci-build` workflow.
=> Update divviup-ts container used in local tests

.github/workflows/ci-build.yml, .github/workflows/push-docker-images-release.yml, Cargo.lock, Dockerfile, aggregator/Cargo.toml, aggregator/build.rs, aggregator/src/binary_utils.rs
This adds a gauge metric with version information, to make it easier to identify what version of software a running instance was built from. The Cargo package version is included via a Cargo environment variable, the rustc version is included by using the `rustc_version` crate in a build script, and the git commit is included using a procedural macro from the `git-version` crate, or via an environment variable for builds inside a Docker container, which don't have the git binary or the .git directory available. (if neither is available, "unknown" is reported instead, to avoid getting in the way of manual container builds)
Sample output:
```
janus_build_info{revision="02bd25a",rust_version="1.67.1",service_name="janus_aggregator",version="0.3.0"} 1
```
=> Add metric with build-time version information

aggregator/src/aggregator.rs, aggregator/src/aggregator/accumulator.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collection_job_driver.rs, aggregator/src/aggregator/query_type.rs, aggregator/src/aggregator/report_writer.rs, aggregator/src/datastore.rs
Previously, we checked for retryable errors at the point they were returned from the user-supplied callback. This sorta works, but expects every callback to be smart enough to propagate serialization errors appropriately -- which has proven to be error-prone, and required some clever (and complex) code to get right.
Now, we check each tokio_postgres::Transaction operation for a retryable failure. No matter what the return value from the user-supplied callback is, if we ever observed a retryable failure, we retry the transaction. The user-supplied callback no longer needs to be involved in the retry process.
=> Check for retryable errors at tokio_postgres boundary.

aggregator/build.rs
This adds a `rerun-if-env-changed` command to the new build script, so it doesn't have to be rerun as often. See https://doc.rust-lang.org/cargo/reference/build-scripts.html#change-detection
=> Add rerun-if command to janus_aggregator build.rs

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collection_job_driver.rs, aggregator/src/aggregator/garbage_collector.rs, aggregator/src/aggregator/report_writer.rs, aggregator/src/datastore.rs
Uploading reports to the leader should be idempotent, meaning:
- repeated requests to upload the same report (same ID and contents) should succeed
- PUT with a repeated report ID by varying contents should fail
Part of #998
=> Idempotent report uploads

messages/src/bin/dap_decode.rs, messages/tests/cmd/dap_decode.trycmd
This adds support for HpkeConfigList to dap-decode. I decided to leave in HpkeConfig, even though it no longer has its own media type in the latest draft, for convenience. Example:
```
$ cargo run -p janus_messages --features dap-decode-bin --bin dap-decode -- --media-type hpke-config-list <(curl -s https://helper1.dap.cloudflareresearch.com/v03/hpke_config)
HpkeConfigList(
[
HpkeConfig {
id: HpkeConfigId(
118,
),
kem_id: X25519HkdfSha256,
kdf_id: HkdfSha256,
aead_id: Aes128Gcm,
public_key: b15c780bcec0aa5229866e6481942ed87af922e7fac9b54bc0b316b76c32b476,
},
],
)
$ cargo run -p janus_messages --features dap-decode-bin --bin dap-decode -- --media-type hpke-config <(curl -s https://helper1.dap.cloudflareresearch.com/v02/hpke_config)
HpkeConfig {
id: HpkeConfigId(
118,
),
kem_id: …
```
=> Add HpkeConfigList to dap-decode

aggregator/src/aggregator.rs, aggregator/src/datastore.rs
`handle_aggregate_init_generic` was checking if any of the report shares in an `AggregationJobInitReq` already occurred in the `client_reports` table, and would refuse to begin preparing an input share if so, producing a `report_replayed` error.
However, this is not what DAP requires ([1]):
> Check if the report has already been aggregated *with this aggregation
> parameter*. If this check fails, the input share MUST be marked as invalid
> with the error `report_replayed`. This is the case if the report was used in
> a previous aggregate request and is therefore a replay.
We now check whether there's a `report_aggregations` row for the `ReportId` and whether its corresponding aggregation job uses the same aggregation parameter as the incoming aggregation job. Additionally, we allow …
=> Fix report replay check in aggregation job init

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregate_init_tests.rs, aggregator/src/datastore.rs, aggregator/src/task.rs, core/src/test_util/dummy_vdaf.rs
We now allow a leader to PUT the same aggregation job multiple times into a Janus helper, provided that we can verify that the aggregation job and the report shares it aggregates have not changed.
Part of https://github.com/divviup/janus/issues/998
=> Aggregation job PUT idempotence

interop_binaries/src/bin/janus_interop_client.rs, interop_binaries/tests/end_to_end.rs
This changes how the interop test client parses upload requests. In the first pass, it now only parses measurements to a JSON AST, and then after switching on the VDAF type, it finishes parsing the measurement. This allows for removing two helper enums, and simplifying how fixed point number vectors are encoded.
=> Interop binaries: defer parsing measurements

aggregator/src/aggregator.rs, aggregator/src/aggregator/collection_job_tests.rs, core/src/test_util/dummy_vdaf.rs
Adds new tests to verify that PUT and POST to collection jobs has the
expected idempotence semantics:
- PUT to a collection job is idempotent
- POST to a collection job allows the leader to update what "current
batch" means in a fixed size task
As it turns out, our existing implementation already satisfied these
requirements, so this only adds test coverage. New tests and support
code are introduced in a new `collection_job_tests` module, to avoid
unnecessarily growing `aggregator/src/aggregator.rs`.
Existing tests on collection jobs defined in that file are renamed to
all start with `collection_job`, which makes it easier to run just those
tests that pertain to collection jobs. We could (should) move those
tests to the new module, but that would make this PR unnecessarily noisy
and would …
=> Add tests for collection job idempotence

aggregator/src/aggregator.rs, aggregator/src/aggregator/accumulator.rs, aggregator/src/aggregator/report_writer.rs, aggregator/src/datastore.rs
Several different processes in the system (uploads & aggregation, aggregation & collection) were interfering with one another due to false sharing, which didn't affect small tests much but which caused an unacceptable number of retries.
It may be possible to improve our queries, but for now switching to Repeatable Read allows us to meet our performance needs.
=> Database: switch from Serializable to Repeatable Read.

aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/report_writer.rs, aggregator/src/binary_utils/job_driver.rs
The response-receiver could be dropped if the entire upload future was dropped, which I think corresponds to a cancelled request handling. This would cause the attempt to send the response to panic, which would cause all other waiting response-receivers to panic themselves when the respense-sender was dropped. I saw a few instances of this in the logs from the latest load test:
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Ok(())', /src/aggregator/src/aggregator/report_writer.rs:139:26
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError(())', /src/aggregator/src/aggregator/report_writer.rs:56:23
```
With this change, any responses whose receivers have been dropped will simply be dropped.
Also, …
=> Fix panic in ReportWriter if upload request is cancelled(?).

aggregator/src/aggregator/aggregation_job_creator.rs
* Accept a zero value for `aggregation_job_creation_interval_secs` (previously, this would have panicked with an error about sampling from an empty range).
* If we managed to create any aggregation jobs, skip waiting and try to create additional aggregation jobs immediately. This matches similar behavior in the aggregation job driver, which only goes to sleep if it fails to find some aggregation jobs to drive.
=> A few tweaks to the aggregation job creator timing.

Cargo.toml, aggregator/Cargo.toml, client/Cargo.toml, collector/Cargo.toml, core/Cargo.toml, integration_tests/Cargo.toml, interop_binaries/Cargo.toml, messages/Cargo.toml
Except in `janus_messages`, because if we pull in the dependency from the workspace, then default features are enabled.
=> Hoist `prio` dependency into workspace `Cargo.toml`

aggregator/src/datastore.rs
This allows us to efficiently run multiple replicas of the aggregation job creator -- without the locking clauses, concurrent attempts to create aggregation jobs would almost certainly conflict, requiring retries & actually-serial execution.
Note I don't update
`get_unaggregated_client_report_ids_by_collect_for_task`: locking clauses don't work when DISTINCT is set. We'd need to do a larger update to this query. Thankfully, this query is test-only code (and only required for Poplar1 or other VDAFs with a nontrivial aggregation parameter).
=> Aggregation job creator: add locking clause to report-finder query.

core/src/retries.rs
I've been seeing some local test flakiness from the one `janus_collector` test that checks retry behavior. Presumably this is linked to the recent `mockito` rewrite. This PR extends the retry timeout used in tests, and it seems to solve the issue.
=> Extend retry timeout in tests

.github/workflows/ci-build.yml, core/Cargo.toml
This enables the `clock` feature on chrono when building `janus_core`, which is necessary for `RealClock::now()`. Our usual builds are unaffected because dependencies from other workspace crates turn on this feature, and those get unified together.
=> Fix building `janus_core` alone

Cargo.lock, aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collection_job_driver.rs, core/Cargo.toml, core/src/task.rs
This closes #1040. I've defined macros for `VdafInstance` and `VdafOps`. I had to get a little creative with syntax, because the different generated match arm bodies need to use different types when calling generic functions. Thus, the macro sets up a type alias and a const, using passed-in identifiers as names, which can then be used in the rest of the block to explicitly specify types in turbofishes. (Once we define a macro for query types, it will have to do the same thing, creating different type aliases with the same macro parameter name in each match arm)
=> Dispatch to VDAF instances using macros

aggregator/src/aggregator.rs, aggregator/src/aggregator/accumulator.rs, aggregator/src/aggregator/aggregate_init_tests.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collection_job_driver.rs, aggregator/src/aggregator/collection_job_tests.rs, aggregator/src/aggregator/garbage_collector.rs, aggregator_core/src/datastore.rs, collector/Cargo.toml, collector/src/lib.rs, core/src/test_util/dummy_vdaf.rs, core/src/time.rs, db/schema.sql, messages/src/lib.rs, tools/src/bin/collect.rs
Add `interval` field to collections
In DAP-04, the `Collection` message which conveys aggregate shares to the collector now includes an `Interval` representing the exact interval of time spanned by the reports included in the collection.
When servicing a GET request on a finished collection job, Janus now queries the constituent aggregation jobs and merges their `client_report_interval`s together (we were already recording the exact interval spanned by aggregation jobs). `janus_collector::Collection` adds a field `interval: (chrono::DateTime<Utc>, chrono::Duration)` to represent this interval.
Resolves #990
=> Add `interval` field to collections

Cargo.lock, Cargo.toml, messages/Cargo.toml
Having `Clone` on `vdaf::PrepareTransition` will be useful for #994.
=> Bump `prio` to 0.11.1

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator_core/src/datastore.rs, core/src/test_util/mod.rs, db/schema.sql
DAP-04 introduces protocol affordances for recovering from round skew. To that end, the helper needs to store the prepare shares from its current round so that it can service replayed aggregation job continuation requests from the leader.
---
I'm working on the changes needed to implement DAP-04 in https://github.com/divviup/janus/pull/731. Since DAP-04 isn't ready yet and in order to reduce the size of the eventual PR wiring up the new HTTP API, I'm teasing out some independent pieces into more digestible PRs.
=> store helper's `A::PrepareShare` in the database

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregate_init_tests.rs, aggregator/src/aggregator/aggregation_job_continue.rs, core/src/test_util/mod.rs
Adds a new module
`janus_aggregator::aggregator::aggregation_job_continue`. Currently, this module contains nothing but a further `test_util` module which defines some utility functions for testing aggregation job continuation. We refactor some tests in `aggregator/src/aggregator.rs` to use some items, shrinking that file by a couple hundred lines.
In the near future, `mod aggregation_job_continue` will define items needed for round skew recovery. The idea here is to avoid growing `aggregator/src/aggregator.rs`, which even after this change is over 8,000 lines. See #1086 for a glimpse of where this is going.
Part of #994
=> Test infra for aggregation job continuation

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_continue.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collection_job_driver.rs, aggregator/src/aggregator/collection_job_tests.rs, aggregator/src/aggregator/garbage_collector.rs, aggregator_core/src/datastore.rs, core/src/test_util/mod.rs, db/schema.sql, messages/src/lib.rs, messages/src/problem_type.rs
`VdafOps::handle_aggregate_continue_generic` now checks whether the incoming `AggregationJobContinueReq` is a replay of a previously seen message. If it is, then we fetch previously-computed prepare shares and serve them back to the leader (`VdafOps::replay_aggregation_job_round`). If not, then we advance to the next round based on the leader's prepare messages (`VdafOps::step_aggregation_job`).
These new methods (and tests for this behavior) are defined in `mod aggregation_job_continue` to avoid growing the already too large `aggregator/src/aggregator.rs`.
Resolves #994
=> Deal with DAP-04 aggregation job round

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_continue.rs, aggregator_core/src/datastore.rs, db/schema.sql
When we successfully handle an `AggregationJobContinueReq`, we now record the SHA-256 hash of the request body. Then, if we later receive another request trying to advance an aggregation job to the round it's already on, we check the hash of the incoming request against the recorded one. If they match, then we replay the previously-computed prepare shares. If they don't, the request fails with HTTP 409 Conflict.
Resolves #994
=> Replayed `AggregationJobContinueReq`s can't change

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_creator.rs, core/src/task.rs, integration_tests/src/client.rs, integration_tests/tests/common/mod.rs, integration_tests/tests/janus.rs, interop_binaries/src/bin/janus_interop_client.rs, interop_binaries/src/bin/janus_interop_collector.rs, interop_binaries/src/lib.rs, interop_binaries/tests/end_to_end.rs, tools/src/bin/collect.rs, tools/tests/cmd/collect.trycmd, tools/tests/cmd/collect_fpvec_bounded_l2.trycmd
Plumb `Prio3SumVec` throughout Janus so it can be used by clients.
Resolves #1039
=> Wire up `Prio3SumVec`

aggregator/src/aggregator.rs, aggregator/src/aggregator/accumulator.rs, aggregator/src/aggregator/aggregate_share.rs, aggregator/src/aggregator/aggregation_job_continue.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collection_job_driver.rs, aggregator/src/aggregator/query_type.rs, aggregator/src/aggregator/report_writer.rs, aggregator_core/src/datastore.rs, aggregator_core/src/lib.rs, aggregator_core/src/query_type.rs, aggregator_core/src/task.rs, collector/src/lib.rs, core/src/task.rs, core/src/test_util/mod.rs
This renames several type parameters from `L` to `SEED_SIZE` for readability.
=> Rename type parameters to SEED_SIZE

Cargo.lock, aggregator/Cargo.toml, aggregator/src/bin/janus_cli.rs
This lazily constructs `kube::Client` inside janus_cli. The provision-tasks subcommand only needs Kubernetes access in one of its modes, so this fixes #946, resolving an error when the datastore key is provided directly and no Kubernetes configuration is available. I created a new struct to handle this lazy initialization with an async method, because `kube::Client::try_default()` is async. (Though, as of the version we're using, none of the await points inside it actually need to wait)
=> janus_cli: Lazily construct Kubernetes client

Cargo.lock, tools/Cargo.toml, tools/src/bin/dap_decode.rs, tools/src/bin/hpke_keygen.rs, tools/tests/cli.rs, tools/tests/cmd/hpke_keygen.trycmd
This adds a command-line tool to generate HPKE keypairs, closing #801. Sample output:
```
id: 255
kem_id: X25519HkdfSha256
kdf_id: HkdfSha256
aead_id: Aes128Gcm
public_key: vaiPHYKo6c_HZvqjMgfcFLgWmvo45nbJ_5G4ShFBQnc
---
EC9SQqZky66zQ5dl1aWu-5xZ34MVfB2RdoSCFGkHlGo
---
config:
id: 255
kem_id: X25519HkdfSha256
kdf_id: HkdfSha256
aead_id: Aes128Gcm
public_key: vaiPHYKo6c_HZvqjMgfcFLgWmvo45nbJ_5G4ShFBQnc
private_key: EC9SQqZky66zQ5dl1aWu-5xZ34MVfB2RdoSCFGkHlGo
---
_wAgAAEAAQAgvaiPHYKo6c_HZvqjMgfcFLgWmvo45nbJ_5G4ShFBQnc
```
Fun fact: since the various ID fields and the public key's length prefix are nine bytes all together, a multiple of three, the base64url-encoded public key appears verbatim in the base64url-encoded HpkeConfig message.
=> Add HPKE key generation tool

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collection_job_driver.rs, aggregator/src/bin/janus_cli.rs, aggregator/src/binary_utils.rs, aggregator/src/metrics.rs, aggregator/src/trace.rs, aggregator_core/src/datastore.rs, client/src/lib.rs, collector/src/lib.rs, core/src/test_util/kubernetes.rs, core/src/test_util/runtime.rs, integration_tests/build.rs, integration_tests/src/client.rs, integration_tests/src/daphne.rs, integration_tests/tests/common/mod.rs, interop_binaries/build.rs, interop_binaries/src/testcontainer.rs
This PR was produced with the following commands.
```bash
echo "format_strings = true" > rustfmt.toml
cargo +nightly fmt
```
This breaks up various long string literals with escaped newlines, and thus gets some un-format-able blocks unstuck.
=> Reformat long string literals

Cargo.lock, Cargo.toml, core/src/task.rs, interop_binaries/src/lib.rs, messages/Cargo.toml, tools/src/bin/collect.rs
This upgrades libprio-rs to 0.12.0, supporting VDAF-05. The only relevant breaking change was swapping a u32 for a usize in Prio3Sum.
Closes #1094.
=> Update to prio 0.12

Cargo.lock, Cargo.toml, aggregator/Cargo.toml, aggregator_core/Cargo.toml, core/Cargo.toml
Since we want to deploy a DAP-04 environment imminently, we might as well release 0.4.0, even though our DAP-04 implementation technically isn't totally complete.
=> Bump Janus crate versions to 0.4.0

collector/src/lib.rs
This tidies up logging from `janus_collector` by skipping some fields that are bigger and not typically useful, and applying the `Display` trick to another `Url`.
=> Make collector logging more succinct

Cargo.lock, aggregator/Cargo.toml, aggregator/src/aggregator.rs, client/Cargo.toml, collector/Cargo.toml, core/Cargo.toml
This upgrades mockito to 1.0.1, and removes a workaround we had to use for 1.0.0.
=> Upgrade mockito, remove workaround

aggregator/src/aggregator.rs
This fixes an unused import warning when `test-util` is not set inside `janus_aggregator`.
=> Fix a warning related to conditional compilation

Cargo.lock, Cargo.toml, Dockerfile, Dockerfile.interop, Dockerfile.interop_aggregator, aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregate_init_tests.rs, aggregator/src/aggregator/aggregation_job_continue.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collection_job_driver.rs, aggregator/src/aggregator/collection_job_tests.rs, aggregator_api/Cargo.toml, aggregator_api/src/lib.rs, aggregator_core/src/datastore.rs, aggregator_core/src/task.rs, collector/src/lib.rs, core/src/task.rs, db/schema.sql, interop_binaries/src/lib.rs, messages/src/lib.rs
Based on Trillium; I was pretty happy with how the library worked out.
Note that I currently return the entire task -- including secrets --
wherever a task is returned (e.g. post task, get task). We had
previously discussed that the secrets would be returned by a different
endpoint. I think this can be changed later, and more than that, I think
the most common case will be adding a new task -- where the control
plane will need the secrets in order to relay them to the co-aggregator.
=> Janus Aggregator API implementation.

Cargo.lock, aggregator/Cargo.toml, aggregator/src/binary_utils.rs
This rewrites the simple health check HTTP server using Trillium.
cc @jbr
=> Migrate health check to Trillium

interop_binaries/src/bin/janus_interop_collector.rs, interop_binaries/tests/end_to_end.rs
This adopts changes from divergentdave/draft-dcook-ppm-dap-interop-test-design#38, renaming two endpoints and adding an interval to a response object. (we had already updated VDAF names previously)
=> Interop API updates

aggregator/src/bin/janus_cli.rs, aggregator/src/binary_utils.rs, aggregator/src/metrics.rs
This converts the HTTP server for Prometheus scrapes from Warp to Trillium.
=> Convert Prometheus scrape endpoint to use Trillium

interop_binaries/config/aggregation_job_creator.yaml, interop_binaries/config/aggregation_job_driver.yaml, interop_binaries/config/collection_job_driver.yaml, interop_binaries/config/janus_cli.yaml, interop_binaries/config/janus_interop_aggregator.yaml
This adds some comments to the interop binary config files, explaining their purposes.
cc @simon-friedberger
=> Add comments to interop binary config files

Cargo.lock, aggregator_api/Cargo.toml, aggregator_api/src/lib.rs
This adds serialization tests for the aggregator API request and response types, to catch any wire breaking changes on this interface.
=> Add serialization tests for aggregator API bodies

Cargo.lock, aggregator/Cargo.toml, aggregator/src/metrics.rs
This moves the HTTP part of our Prometheus code out to a dependency for reuse with divviup-api.
=> Use new crate for extracted metrics handler

.github/workflows/publish-sql-schema.yml
While testing https://github.com/divviup/janus-ops/pull/617, I observed that the Google Cloud SDK pre-installed into the GitHub Actions Ubuntu 22.04 image ([1]) already comes with the `alpha` components we need to use the `gcloud storage` subcommand, so we don't need to install it ourselves. Installing the SDK takes about a minute, far and away the most expensive part of running the `publish-sql-schema` action ([2]).
[1]: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
[2]: https://github.com/divviup/janus/actions/runs/4619878571/jobs/8169222366
=> Use `gcloud` installed on GitHub Actions runners

Cargo.lock, Cargo.toml, README.md, aggregator/Cargo.toml, core/Cargo.toml, integration_tests/Cargo.toml, integration_tests/tests/janus.rs
This is a backport of #1236 to the 0.2 release branch.
=> Update kube-rs, drop OpenSSL features, 0.2 backport

Cargo.lock, Cargo.toml, README.md, aggregator/Cargo.toml, core/Cargo.toml, integration_tests/Cargo.toml, integration_tests/tests/janus.rs
This upgrades our dependencies on `kube` and `k8s-openapi`, to pick up their adoption of rustls 0.21. This lets us drop our OpenSSL-related Cargo features, and always use rustls in janus_cli's Kubernetes operations. Closes #1175.
=> Update kube-rs, drop OpenSSL features

.github/workflows/ci-build.yml
The `ci-build` workflow is not runnable from forks. This is because it wants to authenticate to our private Google Artifact Repository in order to fetch Daphne container images. However, those tests are disabled, and going forward we'll test Daphne using the generic interop test interface and using containers that team publishes to DockerHub. So we should have no need to authenticate to private repositories and thus use secrets. This commit removes mention of `DAPHNE_INTEROP_CONTAINER` from `ci-build.yml` and deletes the steps that authenticate to GCP and the Docker repository it hosts. This should make it possible for PRs on forks to run CI.
=> Use no secrets in `ci-build`

aggregator_core/src/datastore/test_util.rs, interop_binaries/config/janus_interop_aggregator.yaml, interop_binaries/src/bin/janus_interop_aggregator.rs
- use a single `join` call to construct path to migrations
- remove `sql_migrations_path` config option from interop aggregator
See #1240
=> Nits from #1219

aggregator/src/datastore.rs, interop_binaries/config/janus_interop_aggregator.yaml, interop_binaries/src/bin/janus_interop_aggregator.rs
- use a single `join` call to construct path to migrations
- remove `sql_migrations_path` config option from interop aggregator
See #1240
=> Nits from #1219 (backport #1243)

collector/src/lib.rs
Previous to this commit, janus tests failed on macos with
```
---- tests::poll_timing stdout ----
thread 'tests::poll_timing' panicked at 'overflow when adding duration to instant', library/std/src/time.rs:408:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This possibly has to do with [OS-specific behaviors of std::time::Instant](https://doc.rust-lang.org/std/time/struct.Instant.html#os-specific-behaviors).
As a fix, this commit does a checked_add before the compare, which is likely safer anyway on all operating systems, but at the very least resolves the macos test failure.
Would it make sense to add a github action to run tests on macos to avoid future regressions?
=> fix a test failure on macos

.github/workflows/publish-sql-schema.yml
Publish SQL migration scripts to a directory in the bucket named for the minor version (e.g., "0.2") as well as the patch version (e.g., "0.2.17"). Going forward, downstream projects will consume migrations from the minor version directory, but we publish to both places for now, to ease the transition.
Part of #1240
=> Publish SQL migrations to minor version directory

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregate_init_tests.rs, aggregator/src/aggregator/aggregation_job_continue.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collection_job_driver.rs, aggregator/src/aggregator/collection_job_tests.rs, aggregator/src/aggregator/garbage_collector.rs, aggregator/src/aggregator/http_handlers.rs, aggregator/src/bin/janus_cli.rs, aggregator/src/binary_utils.rs, aggregator/src/config.rs, aggregator/tests/graceful_shutdown.rs, aggregator_api/src/lib.rs, aggregator_core/src/datastore.rs, aggregator_core/src/datastore/test_util.rs, integration_tests/src/janus.rs, interop_binaries/config/aggregation_job_creator.yaml, interop_binaries/config/aggregation_job_driver.yaml, interop_binaries/config/collection_job_driver.yaml, interop_binaries/config/janus_interop_aggregator.yaml
Creating a `Datastore` now checks the version of the most recently applied migration script against an array of supported versions compiled into Janus. If the current schema is not supported, `Datastore::new` returns an error.
Resolves #1241
=> Check DB schema version at startup

Cargo.lock, aggregator_core/Cargo.toml, aggregator_core/src/datastore.rs, aggregator_core/src/datastore/test_util.rs, aggregator_core/src/lib.rs, docs/DEPLOYING.md
We want to prove in tests that some Janus version can run safely on multiple schema versions to make database schema migrations safer. In this commit:
- `aggregator_core::test_util::EphemeralDatastore` can now be constructed with a `max_schema_version` argument to control which migration scripts are applied during tests
- We adopt [`rstest`][1] to inject an `EphemeralDatastore` instance into tests in `aggregator_core::datastore::Datatore::tests`. Using [`rstest_reuse`][2], we can automatically stamp out versions of existing tests that run using multiple schema versions.
We only use this dependency injection technique in the `datastore` module, because that should be the only module that's tightly coupled to the database schema. We could run all tests that use a datastore this way, at the …
=> Run `datastore` tests against multiple schemas

aggregator_core/src/datastore.rs, aggregator_core/src/task.rs
This rolls up three one-line changes for small issues I noticed recently.
- janus_cli provision-tasks --generate-missing-parameters` should use AES-128-GCM instead of ChaCha20Poly1305 when generating HPKE keypairs, because it is on the list of algorithms that must be supported, and thus it'll have broader compatibility.
- Fixed a copy-paste error in a builder-style method.
- Fixed an error message that wasn't updated after `Task.hpke_configs` was renamed to `Task.hpke_keys`.
=> Miscellaneous fixes following load test

core/src/task.rs
Authentication tokens are actually arbitrary byte strings; however, DAP-Auth-Token semantics require that these byte strings also happen to be valid ASCII sequences. We made the decision to encode random bytes into base64 to produce an ASCII string with the desired amount of entropy when generating random authentication tokens.
However, now that we're working on implementing Authorization: Bearer, which requires base64-encoding of bearer tokens, the fact that our authorization tokens look like/are base64-encoded strings will cause confusion. Switch to hex encoding instead: this is somewhat wasteful of space, but is less likely to create practical confusion when handling these values.
=> Generate auth tokens as hex strings rather than base64 strings.

Cargo.lock, Cargo.toml, aggregator/Cargo.toml, aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregate_init_tests.rs, aggregator/src/aggregator/collection_job_driver.rs, aggregator/src/aggregator/http_handlers.rs, aggregator_api/Cargo.toml, aggregator_api/src/lib.rs, aggregator_core/Cargo.toml, core/Cargo.toml, core/src/http.rs, core/src/task.rs, integration_tests/Cargo.toml, interop_binaries/Cargo.toml, messages/Cargo.toml
When acting as an HTTP server (i.e., helpers handling aggregation job or aggregate share messages, or leaders handling collection requests), Janus will now check for the authentication token in the more standard `Authorization: Bearer <token>` format defined in RFC 6750, as it already does in the aggregator API. If that header is absent, it falls back to checking `DAP-Auth-Token` for compatibility with existing peers. Nothing changes about the format or handling of the authentication token itself, which remains an opaque blob o' bytes.
Part of #472
=> Honor `DAP-Auth-Token` or `Authorization: Bearer`

aggregator/src/aggregator/aggregate_share.rs
Now that we pre-create batch aggregation objects, logging them all is burdensome. With typical configurations, there will be at least 32 batch aggregations in this slice. One output line from an integration test got broken up into two log lines due to its length, and the "batch_aggregations" string itself was 18513 characters long. This PR skips including the `batch_aggregations` slice in tracing spans.
=> Skip batch_aggregations argument in tracing span

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collection_job_driver.rs, aggregator/src/aggregator/http_handlers.rs, aggregator/src/aggregator/problem_details.rs
This limits the cardinality of `janus_http_request_duration_seconds_count` by introducing a separate argument for the `endpoint` label, taking a description of the route, rather than extracting the last component of the URL. Fixes #1275.
=> Fix high cardinality, HTTP client histogram metric

aggregator/src/metrics.rs
This fixes #1016 by applying the change needed with opentelemetry 0.18. It seems it could still be a while before we can use opentelemetry 0.19, so we may as well do this for now. With this change applied, I always see `janus_build_info` in metrics scrape responses, across multiple attempts and several minutes of time.
The builder method `with_memory()` is private, but here's its rustdoc comment.
> Memory controls whether the processor remembers metric instruments and attribute sets that were previously reported.
>
> When Memory is `true`, `Reader::try_for_each` will visit metrics that were not updated in the most recent interval.
=> Enable memory in OTel metrics processor

Cargo.lock, aggregator/Cargo.toml
This upgrades tracing-stackdriver to the just-released 0.7.1, which includes a fix for #1330.
=> Update tracing-stackdriver to 0.7.1

collector/src/lib.rs, integration_tests/tests/common/mod.rs, interop_binaries/src/bin/janus_interop_collector.rs, tools/src/bin/collect.rs, tools/tests/cmd/collect.trycmd, tools/tests/cmd/collect_fpvec_bounded_l2.trycmd
This adds support for using the `Authorization: Bearer` header to the `janus_collector` library, and the `collect` tool. Either header can be selected. To match the behavior of Janus, both headers are internally represented with an `AuthenticationToken`, and it gets included literally in `DAP-Auth-Token`, and encoded in base64 in `Authorization: Bearer`.
=> janus_collector: Add Authorization: Bearer support

.github/workflows/publish-sql-schema.yml, .github/workflows/push-docker-images-release.yml
This switches the release workflows from using secrets to variables for names of workload identity providers and service accounts.
=> Use variables in lieu of secrets

Dockerfile.interop_aggregator, aggregator/src/datastore.rs
This is a temporary workaround to an issue in the latest version of the Postgres containers, and will be reverted once a fix is available.
Part of #1359.
=> Pin Postgres container to 14.7-alpine.

Cargo.lock, core/Cargo.toml, core/src/test_util/kubernetes.rs, integration_tests/Cargo.toml, integration_tests/src/janus.rs
This rewrites the port forwarding part of the Kind integration tests to use `kube-rs` instead of shelling out to `kubectl`. This allows us to remove a use of `portpicker`, plus I've had reliability issues with the `kubectl port-forward` processes quitting while running `kind-integration-test` locally in the past, so I wanted to swap this out before further big changes. I've tested this locally a few times, and it works well.
=> Rewrite port forwarding, use kube-rs, in-process

Dockerfile.interop_aggregator, aggregator_core/src/datastore/test_util.rs
This switches the image tag back to `postgres:14-alpine` now that the upstream container has been fixed by downgrading LLVM. Closes #1359.
=> Change container back to postgres:14-alpine

aggregator/src/aggregator/http_handlers.rs, core/src/http.rs
This fixes an issue introduced with the `AuthenticationToken` refactor in #1352. Returning an `AuthenticationToken` from this function requires enforcing unnecessary validity conditions on the base64-decoded value. In this context, the returned value was decoded from base64 in a header value, so the DAP-Auth-Token related conditions do not apply, and any byte values should be allowed. For the DAP endpoint, the `AuthenticationToken` conversion and checks are pushed out to `parse_auth_token()` instead, while for the aggregator API endpoint, `AuthenticationToken` is no longer involved.
=> Make extract_bearer_token() just return a Vec<u8>

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregate_init_tests.rs, aggregator/src/aggregator/collection_job_tests.rs, aggregator/src/aggregator/http_handlers.rs, aggregator/src/aggregator/problem_details.rs, aggregator_api/src/lib.rs, aggregator_core/src/datastore.rs, aggregator_core/src/task.rs, collector/src/lib.rs, core/src/task.rs, db/00000000000009_auth_token_kind.down.sql, db/00000000000009_auth_token_kind.up.sql, docs/samples/tasks.yaml, integration_tests/tests/common/mod.rs, interop_binaries/src/bin/janus_interop_aggregator.rs, interop_binaries/src/bin/janus_interop_collector.rs, tools/src/bin/collect.rs
Previously, we taught Janus to accept authentication tokens presented in HTTP requests as either `DAP-Auth-Token: <token>` or `Authorization: Bearer <token>`. However, we also want a Janus leader to be able to work with a DAP helper that expects only one or the other authentication mode.
The `task_aggregator_auth_tokens` and `task_collector_auth_tokens` tables now have columns that track the type of auth token, which is either `DAP_AUTH` or `BEARER`. `send_request_to_helper` will now consult this value to decide how it should authenticate requests.
We didn't strictly need this column in `task_collector_auth_tokens` as the leader's collection job handlers will still accept either kind of token, but it's nice to have consistent handling of these types across the two tables.
The distinction …
=> Track authentication mode per-auth-token

collector/src/lib.rs, integration_tests/tests/common/mod.rs, interop_binaries/src/bin/janus_interop_collector.rs, tools/src/bin/collect.rs
This removes the deprecated `CollectorParameters::new()` constructor, and renames `CollectorParameters::new_with_authentication()` to `CollectorParameters::new()`. Since we're already going to be releasing 0.5.0, I'd like to batch up this breaking change as well, to clean out some cruft.
=> Breaking changes to Collector constructors

aggregator/src/aggregator/http_handlers.rs, core/src/task.rs
If some task accepts an `AuthenticationToken::DapAuth`, it should not be possible to present its value as an `AuthenticationToken::Bearer` and have it be accepted (or vice versa, should a Bearer token happen to also be a legal `DAP-Auth-Token` value). This was already the case because we evaluate tokens using `AuthenticationToken::eq`, but this commit adds a test to explicitly verify this.
While we're in here, improve a doccomment to explain that `AuthenticationToken::DapAuth` complies with the interop testing framework as well as the now-obsolete `draft-ietf-ppm-dap-01`, and add a constant for the collection job route to match the ones for aggregation jobs and aggregate shares.
Closes #1300
=> Test that auth token format must match

README.md
The exact reasoning is that there are differences between the output of `docker inspect` and `podman inspect` that [cause serialization panics](https://github.com/testcontainers/testcontainers-rs/blob/b22713aae20f6da1c1a15b007410054014c1ba6b/testcontainers/src/clients/cli.rs#L339) in `testcontainers`. In fact, it's their [intent to discourage podman usage](https://github.com/testcontainers/testcontainers-rs/issues/422).
RHEL derivatives come default with podman, so hopefully this blurb will save the next person a bit of troubleshooting.
=> docs: don't use podman, use docker

Cargo.lock, Cargo.toml
While we still implement `draft-ietf-ppm-dap-04`, breaking API changes have landed in `janus_collector`, so we bump the minor version for SemVer compatibility.
=> Bump crate versions to 0.5.0

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/aggregation_job_writer.rs, aggregator_core/src/datastore.rs, integration_tests/tests/common/mod.rs, interop_binaries/tests/end_to_end.rs
Two changes:
* Semantics change: for time-interval tasks, we now require all reports included in the batch to be associated with some aggregation job before the batch can be closed. Effectively, this means that any reports which are received before the collection request arrives are now guaranteed to go through the aggregation process before the collection request is complete, which should remove flakiness from integration test scenarios without requiring arbitrary pauses. It is also useful in a "production" scenario: a collector can now issue a collection request after the end of an interval and be guaranteed that all reports received in the interval will be included in the collection result, even if the aggregation process is running behind.
* Bugfix: initial batch writes, if contended …
=> Aggregation job writer improvements.

.github/workflows/ci-build.yml, .github/workflows/push-docker-images-release.yml, Dockerfile, Dockerfile.interop, Dockerfile.interop_aggregator, README.md, build_script_utils/src/lib.rs, docker-bake.hcl, interop_binaries/build.rs
This makes some changes to speed up Docker builds, particularly in CI. Cache mounts are abandoned in favor of using `cargo-chef` to split dependency compilation artifacts and first-party compilation artifacts into separate layers. `ARG` directives are pushed down as far as possible to allow layers to be reused between different image builds. Repetitive `docker build` command lines are replaced with `docker buildx bake` and a new `docker-bake.hcl` file which represents each existing `docker build` invocation declaratively. Using `bake` also allows for better pipelined scheduling of multiple container image builds, which is relevant for our CI jobs. The GitHub Actions cache backend is enabled, with three unique builds writing to the cache, and all builds reading from whichever cache scope …
=> Docker improvements

aggregator_core/src/datastore.rs
For some error modes, Postgres will return an error to the caller & then fail all future statements within the same transaction with an "in failed SQL transaction" error. This effectively means one statement will receive a "root cause" error and then all later statements will receive an "in failed SQL transaction" error. In a pipelined scenario, if our code is processing the results of these statements concurrently--e.g. because they are part of a `try_join!`/`try_join_all` group--we might receive & handle one of the "in failed SQL transaction" errors before we handle the "root cause" error, which might cause the "root cause" error's future to be cancelled before we evaluate it. If the "root cause" error would trigger a retry, this would mean we would skip a DB-based retry when one was …
=> Datastore: implement barrier if we see "in failed tx" error.

aggregator_core/src/task.rs
This adds a check to `Task::validate()` that `max_batch_size` is not less than `min_batch_size`. If these limits were flipped relative to each other, no batch would be collectable.
=> Validate max_batch_size parameter, when present

README.md, aggregator/src/binary_utils.rs, docs/DEPLOYING.md
This makes the following changes:
- Add a section to DEPLOYING.md on datastore keys.
- Improve the error message when parsing datastore keys, making it clear that the length is wrong.
- Add a link to the container image repository in the README.
=> Documentation updates

aggregator_api/src/lib.rs
This adds a method field to our HTTP request tracing spans, and emits an event when complete with the response status.
=> InstrumentedHandler improvements

Cargo.lock, aggregator/src/aggregator/http_handlers.rs, aggregator_api/Cargo.toml, aggregator_api/src/lib.rs, aggregator_core/Cargo.toml, aggregator_core/src/lib.rs
This moves `InstrumentedHandler` from `janus_aggregator_api` to `janus_aggregator_core`. This seems like a natural home for it, as it's a common utility for both parts of the aggregator. Having `janus_aggregator_api` appear as the target name in the "endpoint" span may be confusing when it's used by the DAP HTTP server.
=> Move InstrumentedHandler to janus_aggregator_core

.github/workflows/ci-build.yml, Cargo.toml
Previously, we set `debug = 0` on the `dev` profile in order to minimize the amount of data we need to cache between CI runs. This has side-effects on local development, as `debug = 0` breaks stepping in `lldb` and removes line numbers from backtraces. Thus, this PR creates a new `ci` Cargo profile, moves the `debug = 0` setting to it, and uses it in the `ci-build` workflow action. (only in jobs/commands run on the host -- note that Cargo commands run during Docker builds are already using `release` or `small` profiles) The `dev` profile is returned to its default settings.
=> Split out CI Cargo profile, re-enable debug on dev

aggregator_core/src/datastore.rs, aggregator_core/src/datastore/test_util.rs
This uses the technique suggested by @divergentdave in https://github.com/divviup/janus/issues/1279#issuecomment-1569374474 to test down migrations when there are multiple supported versions of the schema.
We can test the validity of this approach by creating a set of benign migrations and adding a new version.
```rust
// in datastore.rs
supported_schema_versions!(10, 9);
```
```sql
-- db/00000000000010_inahga_test.up.sql
CREATE TABLE inahga_test(id BIGINT GENERATED);
```
```sql
-- db/00000000000010_inahga_test.down.sql
DROP TABLE inahga_test;
```
This should result in a passing set of tests, each test should have 3 cases (1 latest, 1 old via normal upgrade, 1 old via downgrade).
We can simulate a regression caused by a downgraded migration by editing the down script to break a feature of …
=> Test down migrations against all existing tests

Cargo.lock, README.md, aggregator/Cargo.toml, aggregator/src/bin/aggregator.rs, aggregator/src/trace.rs, docs/CONFIGURING_TRACING.md, docs/samples/advanced_config/aggregation_job_creator.yaml, docs/samples/advanced_config/aggregation_job_driver.yaml, docs/samples/advanced_config/aggregator.yaml, docs/samples/advanced_config/collection_job_driver.yaml, docs/samples/advanced_config/garbage_collector.yaml, docs/samples/advanced_config/janus_cli.yaml
This removes the `opentelemetry-jaeger` exporter, and documents how to use the OTLP exporter with Jaeger instead.
=> Remove opentelemetry-jaeger

interop_binaries/tests/end_to_end.rs
This fixes flakiness in the end-to-end test of the interop binaries. For fixed-size tasks, assignment of reports to batches was racing with collection requests. This PR fixes the race in two ways, by both raising the minimum batch size to the expected number of reports, and by ignoring the number of reports in the resulting collection result. This test is just for checking the shape and general sequence of the interop test API, and so it shouldn't have been comparing the report count against an expected value in the first place. I ran this with the first fix locally for a while, and it seems to have fixed the test's reliability.
=> Fix flakiness in interop binaries end-to-end test

aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/binary_utils/job_driver.rs, aggregator_core/src/lib.rs, collector/src/lib.rs
This removes two indefinitely long root spans, and wraps the job driver's job acquisition in a new span.
Fixes #1463.
=> Improve tracing root spans

aggregator/src/trace.rs
This broadens the filter used to exclude h2 spans from traces. Part of #1473.
=> Don't trace any spans from h2

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_writer.rs, aggregator/src/aggregator/collection_job_driver.rs, aggregator/src/aggregator/report_writer.rs, aggregator_core/src/datastore.rs
This adds tracing instrumentation to methods throughout the aggregator and datastore modules. Part of #1473.
=> Instrument more methods with tracing spans

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_continue.rs, aggregator/src/aggregator/aggregation_job_driver.rs
This adds tracing spans covering the four places where we call VDAF preparation methods. While no sub-spans or events will be created in these spans, they will show how much time preparation took in the resulting traces, and put it in context with other latencies.
=> Wrap VDAF preparation in tracing spans

Cargo.lock, aggregator/Cargo.toml, aggregator/src/bin/janus_cli.rs, aggregator/src/binary_utils.rs, aggregator/src/config.rs, aggregator/src/trace.rs, docs/samples/advanced_config/aggregation_job_creator.yaml, docs/samples/advanced_config/aggregation_job_driver.yaml, docs/samples/advanced_config/aggregator.yaml, docs/samples/advanced_config/collection_job_driver.yaml, docs/samples/advanced_config/garbage_collector.yaml, docs/samples/advanced_config/janus_cli.yaml
This adds a configuration option to enable a `tracing-chrome` subscriber. This saves spans and events into a JSON file that's compatible with Chrome's dev tools, and [Perfetto](https://ui.perfetto.dev/).
Closes #1471
=> Add support for tracing-chrome

aggregator/src/trace.rs, core/src/test_util/mod.rs, docs/CONFIGURING_TRACING.md, interop_binaries/src/lib.rs, tools/src/bin/collect.rs
This makes the filter for our two trace-specific subscribers configurable, through a new environment variable, `RUST_TRACE`. This works the same as `RUST_LOG`, and allows us to change verbosity for each independently.
I also changed the existing uses of `EnvFilter::from_default_env()` to ~~`EnvFilter::try_from_default_env()`~~ `EnvFilter::builder.from_env()`, so that we get errors on startup if filter syntax is incorrect.
=> Make filter for tracing-opentelemetry and tracing-chrome configurable

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/aggregation_job_writer.rs, aggregator_core/src/datastore.rs, aggregator_core/src/datastore/test_util.rs, db/00000000000010_rm_client_report_fk.down.sql, db/00000000000010_rm_client_report_fk.up.sql
This is required to allow client reports to be GC'ed independently of aggregation jobs; notably, this is the only foreign-key relationship crossing the reports/aggregations/collections boundary.
The changes are, roughly:
* The report_aggregations table now stores the client report ID, rather than a reference to a client_reports row, as well as the client_timestamp of the report.
* At the start of the aggregation process, if a client report can't be found, it fails aggregation of that report (with a ReportDropped error) rather than failing the entire aggregtion.
Rather than copying input share information at time of the first aggregation step, we could instead copy it at time of aggregation job creation. The upside is that this would remove the possibility of the client report being GC'ed …
=> Break dependency of report_aggregations on client_reports.

docker-bake.hcl
Interpolate `${VERSION}` into the tag applied to Janus images in non-release as well as release targets. This is useful when building images locally, because otherwise they get tagged `:latest` and this can cause surprising behavior in `kind` ([1]).
[1]: https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster
=> use `${VERSION}` in `docker-bake` tags

integration_tests/Cargo.toml, integration_tests/src/divviup_api_client.rs, integration_tests/src/lib.rs, integration_tests/tests/in_cluster.rs
Updates the `in_cluster` test harness code to use the divviup-api API resource for managing aggregators and the automated task provisioning flow (#1486).
Resolves #1528
=> update `in_cluster` for BYOHelper

aggregator_core/src/datastore.rs
This addresses an issue discovered while testing for #1470. Postgres warns that subqueries may be executed more than once, and in particular advises against performing any modifications within subqueries. It appears that read-only subqueries using `LIMIT` can also be executed multiple times, thus defeating our intended purpose of writing `column IN (SELECT ... LIMIT n)`. This PR moves all such subqueries to `WITH` clauses, which are guaranteed to either run only once, or appear to run only once (if they're used in a single place, which ours are). See https://www.postgresql.org/docs/current/sql-select.html#SQL-WITH.
=> Move subqueries using LIMIT to WITH clauses

aggregator/src/aggregator.rs, aggregator/src/aggregator/accumulator.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/aggregation_job_writer.rs, aggregator/src/aggregator/collection_job_driver.rs, aggregator/src/aggregator/collection_job_tests.rs, aggregator/src/aggregator/http_handlers.rs, aggregator_core/src/datastore.rs, aggregator_core/src/query_type.rs, core/src/time.rs, db/00000000000011_batches_client_timestamp_interval.down.sql, db/00000000000011_batches_client_timestamp_interval.up.sql
The incremental GC design expected batches to have a `client_timestamp_interval` field; I tried writing the queries to read from the sharded batch_aggregations table, but this was painful, so I move it to batches instead and implement the design as written. Eventually I want to merge `batches`, `batch_aggregations`, and `outstanding_batches`; this is one step along that path.
Part of #1467.
=> Move `client_timestamp_interval` from batch_aggregations to batches.

aggregator_core/src/datastore.rs
This fixes our three `FOR UPDATE SKIP LOCKED` queries to only take row locks in the table of interest, and not in the tasks table as well. By removing contention on the task row, this removes a cause of getting zero rows out of these queries when we shouldn't.
This fixes #1470. The rewritten query broke the correlation between aggregation job queue liveness issues and table scan types used in query plans I had seen previously, and I haven't been able to trigger the problem again since.
=> Don't take explicit row locks in the tasks table

aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collection_job_driver.rs, aggregator/src/bin/aggregation_job_driver.rs, aggregator/src/bin/collection_job_driver.rs, aggregator/src/binary_utils/job_driver.rs
=> Job driver: wait for in-flight jobs upon SIGTERM

aggregator/src/bin/aggregator.rs
This changes a log statement that is currently using the Debug implementation of String, resulting in extra quote marks.
```json
{
"timestamp": "2023-07-05T19:07:50.771116Z",
"level": "INFO",
"fields": {
"message": "Serving aggregator API relative to DAP API",
"aggregator_bound_address": "0.0.0.0:80",
"path_prefix": "\"aggregator-api\""
},
"target": "aggregator",
"filename": "aggregator/src/bin/aggregator.rs",
"line_number": 89,
"threadId": "ThreadId(1)"
}
```
=> Log statement cleanup

aggregator/src/aggregator/http_handlers.rs
This incorrectly shows up as `janus_aggregator_responses_total_total` in Prometheus currently.
=> Fix counter metric name

integration_tests/tests/in_cluster.rs
This updates the `in_cluster` test to work with divviup/janus-ops#888.
=> Update aggregator API URL in in_cluster test

integration_tests/Cargo.toml, integration_tests/src/client.rs, integration_tests/src/lib.rs, integration_tests/tests/common/mod.rs, integration_tests/tests/daphne.rs, integration_tests/tests/divviup_ts.rs, integration_tests/tests/in_cluster.rs, integration_tests/tests/janus.rs
This PR refactors the common integration test support code to rely less on the leader's `Task`, by introducing a new `TaskParameters` struct containing the parameters relevant to the client or collector. This supports #1524. `TaskParameters` contains the hostnames and path components of aggregator endpoints, and construction of endpoint URLs is deferred until we set up the client and collector. This means we no longer rely on modifying and reading the leader's endpoint in the leader `Task`.
=> Refactor integration tests to decouple from janus_aggregator_core::task

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregate_init_tests.rs, aggregator/src/aggregator/aggregation_job_continue.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collection_job_driver.rs, aggregator/src/aggregator/collection_job_tests.rs, aggregator/src/aggregator/garbage_collector.rs, aggregator/src/aggregator/http_handlers.rs, aggregator/src/aggregator/problem_details.rs, aggregator/src/bin/aggregation_job_creator.rs, aggregator/src/bin/aggregation_job_driver.rs, aggregator/src/bin/aggregator.rs, aggregator/src/bin/collection_job_driver.rs, aggregator/src/bin/janus_cli.rs, aggregator/src/binary_utils.rs, aggregator/src/binary_utils/job_driver.rs, aggregator/tests/graceful_shutdown.rs, aggregator_api/src/lib.rs, aggregator_core/src/datastore.rs, aggregator_core/src/datastore/test_util.rs, aggregator_core/src/lib.rs, interop_binaries/src/bin/janus_interop_aggregator.rs
This refactors our OpenTelemetry metrics handling by passing a `Meter` instance around explicitly when setting up components. We now only emit metrics under a single library name, and most tests use a `Meter` from `NoopMeterProvider`. By explicitly passing this dependency, we can now replace it by using a non-global `BasicController` in tests, in order to either test metrics themselves, or use metrics as an introspection hook to test some other behavior.
Closes #1531.
=> Explicitly pass OpenTelemetry Meters

aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/bin/aggregation_job_creator.rs
This PR replaces oneshot channels and `select!` with `Stopper` in per-DAP task job creation tasks, checks for shutdown signals during each loop's sleep, and waits for all tasks to complete before exiting instead of cancelling the main task and letting per-DAP task tasks run detached.
Using `Stopper` should be more lightweight than `select!`, as the combinator future is better optimized for this simple case, and random number generators don't need to get involved. Avoiding cancellation of futures that interact with the database means we get a chance to finish work-in-progress in open transactions, and we will cause fewer transaction rollbacks and connection errors during normal operation.
=> Improve aggregation job creator graceful shutdown

.github/dependabot.yml, README.md
(We'll soon be forking `main` back to a DAP-02 release to pick up all of the work that has gone in since release/0.2 was under active development.)
=> Abandon release/0.2 branch.

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregate_init_tests.rs, aggregator/src/aggregator/aggregation_job_continue.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collection_job_driver.rs, aggregator/src/aggregator/collection_job_tests.rs, aggregator/src/aggregator/garbage_collector.rs, aggregator/src/aggregator/http_handlers.rs, aggregator/src/bin/janus_cli.rs, aggregator/tests/graceful_shutdown.rs, aggregator_api/src/lib.rs, aggregator_core/src/datastore.rs, aggregator_core/src/datastore/test_util.rs
This was categorically set to &noop_meter(), so that value is now hard-wired. If we want to introduce tests for the meter behavior later, we can introduce a separate constructor for datastores, perhaps named something like `datastore_with_meter()`.
=> Remove &Meter parameter from EphemeralDatastore::datastore().

Dockerfile
This PR enables the `otlp` feature when building release images. Mozilla currently uses this for tracing, and we should eventually as well.
=> Build release containers with OTLP

.github/workflows/ci-migrations.yml
This is so that we can have it be a required check. Unfortunately GitHub isn't able to ignore required checks that aren't applicable to a given PR.
=> Always run ci-migrations check

messages/src/lib.rs, messages/src/taskprov.rs
In https://github.com/divviup/janus/pull/1579#discussion_r1261499802 I identified cases where `https://example.com` would be encoded as `https://example.com/` (notice the trailing slash). At the time I didn't think this was relevant, but it turns out to affect task ID derivation.
Task ID derivation is `sha256sum(encoded_task_config)`. If we are peered with a non-janus aggregator and if we introduce trailing slashes, Janus could derive a different task ID than its peer. (This is actually somewhat unlikely since we'd derive task ID directly from the encoded bytes, but is a subtle inconsistency that could hit us later).
Instead, provide `TryInto<url::Url>` to ease converting DAP Urls to a more useful type.
=> Fix bug with trailing slashes in URL

aggregator/src/aggregator.rs, aggregator/src/aggregator/http_handlers.rs, aggregator/src/bin/aggregator.rs, aggregator/src/cache.rs, aggregator/src/lib.rs
Follow up to https://github.com/divviup/janus/pull/1610, supports https://github.com/divviup/janus/issues/1568.
All code paths involving report decryption should now be able to use a global HPKE keypair to attempt decryption of a report. If  a config ID is given that matches both a task and global key, trial decryption is used.
The keypair is cached using the same mechanism in https://github.com/divviup/janus/pull/1610. Importantly, this has cache invalidation. Because we have the `Pending` state, we can safely refresh keys without worrying about them being advertised before all aggregators have picked up on the new key. This means that the key rotation strategy is:
1. Add a new key to DB
2. Wait ~30 minutes (plus some safety factor) for all aggregators to pick up on the new key OR …
=> Allow decrypting with global key on report upload

aggregator/src/aggregator.rs, aggregator/src/aggregator/http_handlers.rs
Follow up to https://github.com/divviup/janus/pull/1648#pullrequestreview-1548667598. I went with `create_report_custom` rather than `create_report_with_key`, since this function allows specifying a non-random ID and key and it's used for each of those purposes independently. My thought is this can just be a catch-all function for the rare case that a test requires a non-arbitrary report.
=> Rename test function create_report_with_id to create_report_custom

docs/samples/advanced_config/aggregator.yaml, docs/samples/basic_config/aggregator.yaml
Minor annoyance: port 80 is a privileged port in Linux, so non-root users can't bind to it (without modifying their system). This just makes it easier to bring up a quick aggregator `DATASTORE_KEYS=foobar cargo run --bin aggregator -- --config-file samples/basic_config/aggregator.yaml`.
=> Change example port from 80 to 8080, to allow non-root usage

aggregator/src/metrics.rs, aggregator/src/trace.rs
Currently, we specify `service.name` to be "janus_aggregator" when constructing a OTLP metrics exporter and OTLP trace exporter (but not the Prometheus metrics exporter). This PR removes these settings so that we can use the `OTEL_SERVICE_NAME` environment variable to control this setting for all exporters.
cc @simon-friedberger
=> Don't specify service.name with OTLP exporters

aggregator/src/aggregator.rs, aggregator/src/aggregator/http_handlers.rs, aggregator/src/bin/aggregator.rs, aggregator/src/cache.rs
Follow up to https://github.com/divviup/janus/pull/1640#discussion_r1274171108.
=> Replace `sleep` calls in tests with a direct cache refresh function

Cargo.lock, aggregator_core/Cargo.toml
Async-std is a heavy dependency and `rg async_std` turns up no results from janus root
=> remove apparently-unused async-std dev dep from aggregator_core

aggregator/src/bin/aggregator.rs, aggregator/tests/graceful_shutdown.rs, aggregator_api/src/lib.rs, aggregator_core/src/lib.rs, docs/samples/advanced_config/aggregator.yaml
Pairs with https://github.com/divviup/divviup-api/pull/340
Explanation of changes:
* Previously the aggregator-api handler was unconditionally built and discarded, but as of this PR, we require the aggregator-api config in order to build the aggregator-api handler. This seems more generally correct and adaptable to other configuration keys that are mandatory if and only if aggregator-api is enabled
* Previously, the BinaryContext was partially moved in order to move the non-clone datastore into an Arc, but that did not work well with extracting behvior to a function. To address this, we now destructure the BinaryContext and explicitly take or borrow fields from it as needed.
* `Box::pin(async {})` was replaced with `Box::pin(std::future::ready(()))`
* This PR puts Config back into the …
=> add GET {aggregator_api}/ → AggregatorApiConfig

integration_tests/src/divviup_api_client.rs, integration_tests/tests/in_cluster.rs
With the latest `divviup-api` and `janus` changes ([1], [2]), we no longer tell `divviup-api` what DAP roles an aggregator supports nor the URL of its DAP API. Those configuration items are instead discovered during aggregator pairing. This updates the `divviup-api` client used in the `in-cluster` integration tests accordingly.
[1]: https://github.com/divviup/janus/pull/1646
[2]: https://github.com/divviup/divviup-api/pull/340
=> in-cluster test: deal with agg config API

Cargo.lock, Cargo.toml, aggregator/Cargo.toml, aggregator/src/aggregator/http_handlers.rs, aggregator/src/bin/aggregator.rs, aggregator_api/src/lib.rs, aggregator_core/Cargo.toml, aggregator_core/src/datastore/models.rs, aggregator_core/src/task.rs, client/Cargo.toml, collector/Cargo.toml, collector/src/lib.rs, core/Cargo.toml, core/src/http.rs, core/src/task.rs, docs/samples/tasks.yaml, integration_tests/Cargo.toml, integration_tests/src/divviup_api_client.rs, integration_tests/tests/in_cluster.rs, interop_binaries/Cargo.toml, interop_binaries/src/bin/janus_interop_aggregator.rs, interop_binaries/src/bin/janus_interop_collector.rs, tools/Cargo.toml, tools/src/bin/collect.rs, tools/tests/cmd/collect.trycmd
Previously, the aggregator API assumed that any aggregator or collector auth tokens it was handling were `AuthenticationToken::DapAuth`. Janus must support those for the interop testing API and to work with Daphne, but generally, we prefer to use more boring `Authorization: Bearer` tokens. Certainly any tasks provisioned via the aggregator API and `divviup-api` should use bearer tokens.
With this PR, we augment the `PostTaskReq` and `PostTaskResp` messages so that they use `AuthenticationToken` to represent aggregator and collector tokens, meaning that on the wire, a token now looks like:
```
{
"type": "Bearer",
"token": "AAAAAAAAA<etc.>"
}
```
Also, when the aggregator API generates either kind of token, it now generates a bearer token. I'm not aware of any scenarios where we need to …
=> aggregator API: default to bearer tokens

Cargo.lock, Cargo.toml, aggregator/Cargo.toml, aggregator_api/Cargo.toml, aggregator_api/src/lib.rs, aggregator_core/Cargo.toml, core/Cargo.toml, messages/Cargo.toml
Makes the task creation endpoint in the aggregator API idempotent, by checking whether a task corresponding to the incoming `PostTaskReq` already exists. If it does, and all the other task's parameters match the `PostTaskReq`, then we return 201 Created. If the task exists but some other parameter (e.g., min batch size) differs, we return 409 Conflict.
Deletion was already correctly handled so no new changes or test were needed.
Resolves #1507
=> aggregator API: idempotent task creation

tools/src/bin/collect.rs
The tests for `collect` binary argument handling were occasionally failing. In one such run ([1]), we observe that the test randomly generated an auth token `-7ekJePnK7WXktf92bK1CQ`, which starts with `-` and confuses `clap`, which tries to treat it as a series of flags rather than the value to `--dap-auth-token`. We rule this out by using the `--dap-auth-token={token}` form, as these tests already did for task IDs and other values that can start with `-`.
[1]: https://github.com/divviup/janus/actions/runs/5733188592/job/15537476867
=> Fix flaky argument parsing test

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/batch_creator.rs, aggregator/src/aggregator/collection_job_tests.rs, aggregator/src/aggregator/garbage_collector.rs, aggregator/src/bin/janus_cli.rs, aggregator_api/src/lib.rs, aggregator_core/src/datastore.rs, aggregator_core/src/datastore/tests.rs, aggregator_core/src/task.rs, db/00000000000014_fixed_size_time_bucketing.down.sql, db/00000000000014_fixed_size_time_bucketing.up.sql, docs/samples/tasks.yaml, integration_tests/tests/in_cluster.rs, integration_tests/tests/janus.rs, interop_binaries/src/bin/janus_interop_aggregator.rs, interop_binaries/src/lib.rs
This resolves #1574, adding a per-task configuration option to control how fixed size batches are constructed, by dividing reports into time buckets and only putting reports from the same bucket in each batch. The aggregation job creator logic is refactored so it can work in a streaming manner, and then unaggregated reports are fed through this, with a different instance for each time bucket (if applicable). There is a database change to add a new column on `outstanding_batches`. Note that once a fixed size batch has been finalized, the time bucketing setting is no longer relevant, and we already otherwise track client timestamp intervals on batches themselves. The change to the query type enum affects the `tasks.query_type` jsonb column in the database, the task definition YAML format, …
=> Implement time bucketing for fixed size query type

aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/aggregation_job_writer.rs
Somewhere along the way, `AggregationJobWriter::write` picked up a trait bound requiring `std::hash::Hash` on `Vdaf::AggregationParam`. This trait isn't actually needed and also breaks Poplar1: `Hash` is implemented on `Prio3*::AggregationParam` (i.e., `()`), but not on `Poplar1AggregationParam`.
=> Remove `std::hash::Hash` bound on agg parameters

Cargo.lock, Cargo.toml, aggregator/src/aggregator/aggregation_job_continue.rs, aggregator/src/aggregator/collection_job_tests.rs, aggregator/src/aggregator/http_handlers.rs
This fixes #1687 by ~~reordering two calls~~ updating trillium-api. ~~The `with_json()` method from an extension trait also sets the Content-Type header, so it was stomping on the previously-set header.~~ All tests that check problem details response bodies now also check the Content-Type header.
=> Fix Content-Type of problem details responses

aggregator_api/src/lib.rs, aggregator_core/src/datastore/models.rs
Supports https://github.com/divviup/janus/issues/1568.
This lets us manage the global HPKE keys configuration in the database.
We opted to have this in the aggregator API to keep from having `janus_cli` operate directly on the database. If `janus_cli` works that way, then the operator has to somehow acquire the datastore key. Using the aggregator API effectively replaces datastore key management with aggregator API key management, which is much nicer since aggregator API key is trivially rotateable.
I didn't add functionality to janus_cli to keep this PR small, and to be mindful of time constraints of our upcoming integration tests. In lieu of janus_cli functionality, we can use `curl`.
This does extend the privileges of the aggregator API. The primary risk is to availability of the …
=> Aggregator API endpoints for global HPKE key management

aggregator_api/src/routes.rs, aggregator_api/src/tests.rs
- Deletion should return 204 on not found, not 404.
Supports https://github.com/divviup/janus/issues/1691.
- Provide explicit return type in routes
From conversation in https://github.com/divviup/janus/pull/1686#discussion_r1290401987.
- Remove needless Halt
I'm not sure why this is here--no other routes use Halt in this manner (should they)?
=> Minor aggregator API cleanup

aggregator_api/src/tests.rs
Using two consecutive `random()`'s is not suitable for generating unique IDs.
=> Fix flaky test that occasionally collides on random()

Cargo.lock, Cargo.toml
Cargo versions must be SemVer compatible, which means that a version like `0.subscriber-01.1` is not valid, so instead we set `0.5.12-subscriber-01.1`. This reflects the release this branched from (`0.5.12`), the specific purpose of this series of releases (`subscriber-01`), and allows us to increment versions (`.1`).
What's unfortunate about this is that it doesn't match the git tags we were planning to cut (which look like `0.subscriber-01.1`). We don't publish crates from this release branch, so that might not matter: the Cargo version may only ever show up in log lines. However we could choose to change our tagging scheme to match the Cargo versions, at which point there would be a mismatch with the branch name.
=> `release/0.subscriber-01`: Bump crate versions

Cargo.lock, Cargo.toml
We go to 0.5.16 because I forgot to bump the crate version before cutting a GitHub release and burned 0.5.15.
=> Release Janus 0.5.16

aggregator/src/aggregator.rs, aggregator/src/aggregator/http_handlers.rs
Supports https://github.com/divviup/janus/issues/1568.
If a taskprov task is present, the end-user can still query `/hpke_configs?task_id=foo`. If they do this, the handler will panic because we have an `unwrap` in the task-specific `handle_hpke_config()` function. Taskprov tasks don't have any HPKE keys directly associated with them.
```rust
HpkeConfigList::new(Vec::from([self
.task
.hpke_keys()
.iter()
.max_by_key(|(&id, _)| id)
.unwrap()
.1
.config()
.clone()]))
```
Partially fix this by unconditionally returning the global keys when in taskprov mode, so any client `task_id` parameters are ignored.
This doesn't handle the case where a taskprov task is in the database, the system is out of taskprov mode, and a client queries `/hpke_configs?task_id=foo`. I figure this is a niche enough …
=> Fix panic when trying to get HPKE configs on a task that doesn't have any configured

Cargo.lock, Cargo.toml
a.k.a. `0.5.12-subscriber-01.2` for the crate version
=> Release Janus `0.subscriber-01.2`

aggregator/src/aggregator/taskprov_tests.rs
This adds another taskprov test that sends `AggregateInitializeReq`, `AggregateContinueReq`, and `AggregateShareReq` requests in sequence, and checks the results against a VDAF transcript. Each individual request already has test coverage, but this additional test mainly confirms that the fixtures set up in each test correctly model the actual outputs from the prior requests.
=> Add end-to-end test of aggregation using taskprov

.github/workflows/publish-sql-schema.yml
Fixes https://github.com/divviup/janus/issues/1735.
Appropriately handle the case where we're starting a new release and need to have the migrations directory created. The force flag is not required for this operation (nor should it IMO).
I also fix the job to allow us deploying from a branch, in which case the directory will just be the branch name. This is mainly for testing this PR but I can see it being useful in niche circumstances.
To cleanly accomplish this I replace `gcloud` with `rclone`, for a few reasons:
- `rclone` is a stable interface, `gcloud alpha` is not.
- `rclone` has more predictable and favorable semantics, i.e. we don't need any special handling for the case where the remote migrations directory doesn't exist.
- `gcloud alpha` doesn't have a directory existence test …
=> Support for publishing SQL schema from scratch, and publishing from a branch

Dockerfile.interop_aggregator, aggregator_core/src/datastore/test_util.rs, docs/DEPLOYING.md
This affects tests & interop containers.
Part of #646. Doing this now as we just had a major-version break.
=> Upgrade Postgres 14 -> 15.

aggregator/src/aggregator.rs, aggregator/src/aggregator/aggregation_job_creator.rs, aggregator/src/aggregator/aggregation_job_driver.rs, aggregator/src/aggregator/collection_job_driver.rs, aggregator/src/aggregator/http_handlers.rs, aggregator/src/aggregator/problem_details.rs, aggregator/src/binary_utils/job_driver.rs, aggregator/src/metrics.rs, aggregator_core/src/datastore.rs
This is a follow-up to #1664 to fix some errors in names and units, and make them consistent throughout. The unit of `seconds` we previously used was not recognized by `opentelemetry-prometheus`. The [semantic conventions](https://opentelemetry.io/docs/specs/otel/metrics/semantic_conventions/#instrument-units) suggest using [UCUM](https://ucum.org/ucum), and the unit `s` is correctly recognized by `opentelemetry-prometheus`. The database transaction duration histogram also needed to have a unit provided and its name updated.
Separately, I also fixed a conditional compilation issue that arose when building with `--features prometheus` (but not the `otlp` features), and added UCUM annotations to the units of dimensionless counters, as suggested by the semantic conventions.
=> Metrics name/unit fixes
